# Language Debug Notebook (I18N)

This notebook is for **diagnosing non-English scoring behavior** end-to-end.

It will:
1. Pull up to 50 jobs from **We Work Remotely RSS**
2. Detect language for each job post
3. Attempt translation to English (when confident non-English)
4. Display **all fields** in original and translated versions
5. Surface translation errors for quick triage

In [5]:
from pathlib import Path
import importlib
import importlib.util
import subprocess
import sys
import pandas as pd
from IPython.display import display, Markdown

ROOT = Path.cwd().resolve()
if not (ROOT / 'src').exists() and (ROOT.parent / 'src').exists():
    ROOT = ROOT.parent

if str(ROOT / 'src') not in sys.path:
    sys.path.insert(0, str(ROOT / 'src'))

if importlib.util.find_spec('deep_translator') is None:
    print('Installing deep-translator in the active notebook kernel...')
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'deep-translator==1.11.4'])
else:
    print('deep-translator is already available in this kernel.')

import job_fraud_detector.i18n as i18n_module
importlib.reload(i18n_module)
normalize_posting_language = i18n_module.normalize_posting_language
TRANSLATABLE_FIELDS = i18n_module.TRANSLATABLE_FIELDS

from job_fraud_detector.live_sources import fetch_jobs_from_sources

print('i18n module loaded from:', i18n_module.__file__)

pd.set_option('display.max_colwidth', 180)
pd.set_option('display.width', 240)

ROOT

deep-translator is already available in this kernel.
i18n module loaded from: /Users/shahan/Documents/Remote Job Scam-NotScam/src/job_fraud_detector/i18n.py

PosixPath('/Users/shahan/Documents/Remote Job Scam-NotScam')

In [18]:
import sys, importlib.util
import job_fraud_detector.i18n as i18n_module
print(sys.executable)
print(i18n_module.__file__)
print("deep_translator:", bool(importlib.util.find_spec("deep_translator")))

/Users/shahan/Documents/Remote Job Scam-NotScam/.venv/bin/python
/Users/shahan/Documents/Remote Job Scam-NotScam/src/job_fraud_detector/i18n.py
deep_translator: True

In [20]:
SOURCES = {
    'we_work_remotely_rss': 'https://weworkremotely.com/remote-jobs.rss',
}
PER_SOURCE = 50
ENABLE_TRANSLATION = True
SHOW_FULL_TEXT = True
FIELDS_TO_COMPARE = [
    'title',
    'company_profile',
    'location',
    'department',
    'description',
    'requirements',
    'benefits',
    'employment_type',
    'required_experience',
    'required_education',
    'industry',
    'function',
    'salary_range',
]

print('Configured source:', SOURCES)
print('PER_SOURCE =', PER_SOURCE)
print('ENABLE_TRANSLATION =', ENABLE_TRANSLATION)

Configured source: {'we_work_remotely_rss': 'https://weworkremotely.com/remote-jobs.rss'}
PER_SOURCE = 50
ENABLE_TRANSLATION = True

In [9]:
jobs = fetch_jobs_from_sources(
    sources=SOURCES,
    per_source=PER_SOURCE,
    fail_fast=False,
)

print(f'Fetched {len(jobs)} jobs from We Work Remotely RSS.')

if not jobs:
    print('No jobs fetched. Check network and rerun.')

Fetched 50 jobs from We Work Remotely RSS.

In [21]:
language_rows = []
detailed_posts = []

# Safety: reload i18n each run so notebook does not hold stale function objects.
import importlib
import job_fraud_detector.i18n as i18n_module
importlib.reload(i18n_module)
normalize_posting_language = i18n_module.normalize_posting_language

for idx, job in enumerate(jobs, start=1):
    i18n = normalize_posting_language(job, enable_translation=ENABLE_TRANSLATION)
    translated_posting = i18n.posting

    language_rows.append({
        'row_id': idx,
        'source': job.get('source', ''),
        'title': job.get('title', ''),
        'detected_language': i18n.language,
        'language_confidence': round(i18n.language_confidence, 4),
        'language_detector': i18n.language_detector,
        'translation_applied': i18n.translation_applied,
        'translation_provider': i18n.translation_provider,
        'translation_error': i18n.translation_error,
        'job_url': job.get('job_url', ''),
        'apply_url': job.get('apply_url', ''),
    })

    original = {field: str(job.get(field, '') or '') for field in FIELDS_TO_COMPARE}
    translated = {field: str(translated_posting.get(field, '') or '') for field in FIELDS_TO_COMPARE}

    detailed_posts.append({
        'row_id': idx,
        'source': job.get('source', ''),
        'job_url': job.get('job_url', ''),
        'apply_url': job.get('apply_url', ''),
        'detected_language': i18n.language,
        'language_confidence': round(i18n.language_confidence, 4),
        'language_detector': i18n.language_detector,
        'translation_applied': i18n.translation_applied,
        'translation_provider': i18n.translation_provider,
        'translation_error': i18n.translation_error,
        'original': original,
        'translated': translated,
    })


debug_summary_df = pd.DataFrame(language_rows)
debug_detail_df = pd.DataFrame(detailed_posts)

print('Rows processed:', len(debug_summary_df))

Rows processed: 50

In [22]:
display(debug_summary_df)

display(
    debug_summary_df
    .groupby(['detected_language', 'translation_applied'], dropna=False)
    .size()
    .reset_index(name='count')
    .sort_values('count', ascending=False)
)

translation_failures = debug_summary_df[debug_summary_df['translation_error'].notna()]
if not translation_failures.empty:
    print('Translation failures:')
    display(translation_failures[['row_id', 'title', 'detected_language', 'translation_error', 'job_url']])
else:
    print('No translation failures detected.')

,row_id,source,title,detected_language,language_confidence,language_detector,translation_applied,translation_provider,translation_error,job_url,apply_url
0,1,we_work_remotely_rss,"Senior Software Engineer, Platform",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-platform-1,https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-platform-1
1,2,we_work_remotely_rss,"Senior Software Engineer, Web",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-web-1,https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-web-1
2,3,we_work_remotely_rss,Junior Full-Stack Developer (Laravel and VueJS),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/appetiser-junior-full-stack-developer-laravel-and-vuejs,https://weworkremotely.com/remote-jobs/appetiser-junior-full-stack-developer-laravel-and-vuejs
3,4,we_work_remotely_rss,Product Marketing Manager (B2B for life sciences/pharma/biotech),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/viseven-product-marketing-manager-b2b-for-life-sciences-pharma-biotech,https://weworkremotely.com/remote-jobs/viseven-product-marketing-manager-b2b-for-life-sciences-pharma-biotech
4,5,we_work_remotely_rss,"Director, AI Product Development",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/centralreach-director-ai-product-development,https://weworkremotely.com/remote-jobs/centralreach-director-ai-product-development
5,6,we_work_remotely_rss,Senior DevOps Engineer - Migraciones CI/CD (Remoto 100%),es,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/knowmad-mood-senior-devops-engineer-migraciones-ci-cd-remoto-100,https://weworkremotely.com/remote-jobs/knowmad-mood-senior-devops-engineer-migraciones-ci-cd-remoto-100
6,7,we_work_remotely_rss,Product Owner (m/f),it,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/iungo-spa-product-owner-m-f,https://weworkremotely.com/remote-jobs/iungo-spa-product-owner-m-f
7,8,we_work_remotely_rss,Product Owner Zendesk Customer Service (m/w/d) // remote möglich,de,0.85,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/e-breuninger-co-product-owner-zendesk-customer-service-m-w-d-remote-moglich,https://weworkremotely.com/remote-jobs/e-breuninger-co-product-owner-zendesk-customer-service-m-w-d-remote-moglich
8,9,we_work_remotely_rss,"Senior Product Analyst, Remote",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/aledade-senior-product-analyst-remote,https://weworkremotely.com/remote-jobs/aledade-senior-product-analyst-remote
9,10,we_work_remotely_rss,Product Manager,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/welocalize-product-manager,https://weworkremotely.com/remote-jobs/welocalize-product-manager
10,11,we_work_remotely_rss,AI Engineer/Python Develope,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/toptal-ai-engineer-python-develope,https://weworkremotely.com/remote-jobs/toptal-ai-engineer-python-develope
11,12,we_work_remotely_rss,[Banco de Talentos] Pessoas com deficiência,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/conta-azul-banco-de-talentos-pessoas-com-deficiencia,https://weworkremotely.com/remote-jobs/conta-azul-banco-de-talentos-pessoas-com-deficiencia
12,13,we_work_remotely_rss,"Product Manager, Fraud Solutions",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/fis-capital-markets-product-manager-fraud-solutions,https://weworkremotely.com/remote-jobs/fis-capital-markets-product-manager-fraud-solutions
13,14,we_work_remotely_rss,Desenvolvedor Dynamics 365 CE [100% Remota],pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/cashme-desenvolvedor-dynamics-365-ce-100-remota,https://weworkremotely.com/remote-jobs/cashme-desenvolvedor-dynamics-365-ce-100-remota
14,15,we_work_remotely_rss,Operations Manager (Germany),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/ey-operations-manager-germany,https://weworkremotely.com/remote-jobs/ey-operations-manager-germany
15,16,we_work_remotely_rss,"Senior Manager, Finance Strategy & Planning",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/cohesity-senior-manager-finance-strategy-planning,https://weworkremotely.com/remote-jobs/cohesity-senior-manager-finance-strategy-planning
16,17,we_work_remotely_rss,Senior Fullstack Engineer — Produtos Financeiros (Miniapps),pt,0.85,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/rock-encantech-senior-fullstack-engineer-produtos-financeiros-miniapps,https://weworkremotely.com/remote-jobs/rock-encantech-senior-fullstack-engineer-produtos-financeiros-miniapps
17,18,we_work_remotely_rss,Pessoa Desenvolvedora Backend Sênior,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/cora-pessoa-desenvolvedora-backend-senior,https://weworkremotely.com/remote-jobs/cora-pessoa-desenvolvedora-backend-senior
18,19,we_work_remotely_rss,Data Labeling Specialist — Remote Contract Work ($18-$22 per hour),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/workada-data-labeling-specialist-remote-contract-work-18-22-per-hour,https://weworkremotely.com/remote-jobs/workada-data-labeling-specialist-remote-contract-work-18-22-per-hour
19,20,we_work_remotely_rss,Profissional Web Designer Sênior,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1,https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1
20,21,we_work_remotely_rss,Profissional Web Designer Sênior,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1,https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1
21,22,we_work_remotely_rss,Senior Product Manager - Remote - 13.5-18.3k CLT,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/vinta-senior-product-manager-remote-13-5-18-3k-clt,https://weworkremotely.com/remote-jobs/vinta-senior-product-manager-remote-13-5-18-3k-clt
22,23,we_work_remotely_rss,Staff Software Engineer - AI Website Builder - US (Remote),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/luxury-presence-staff-software-engineer-ai-website-builder-us-remote,https://weworkremotely.com/remote-jobs/luxury-presence-staff-software-engineer-ai-website-builder-us-remote
23,24,we_work_remotely_rss,[Cubos DevOps] Pessoa Engenheira de DevOps Pleno,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/cubos-tecnologia-cubos-devops-pessoa-engenheira-de-devops-pleno,https://weworkremotely.com/remote-jobs/cubos-tecnologia-cubos-devops-pessoa-engenheira-de-devops-pleno
24,25,we_work_remotely_rss,Profissional IaC| DevOps,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/radix-profissional-iac-devops,https://weworkremotely.com/remote-jobs/radix-profissional-iac-devops
25,26,we_work_remotely_rss,[Banco de Talentos] Product Manager Pleno,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-pleno,https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-pleno
26,27,we_work_remotely_rss,[BANCO DE TALENTOS] Product Manager Jr.,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-jr,https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-jr
27,28,we_work_remotely_rss,DevOps Engineer,pt,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/alice-devops-engineer,https://weworkremotely.com/remote-jobs/alice-devops-engineer
28,29,we_work_remotely_rss,Creative Performance Designer,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/nabu-global-fze-creative-performance-designer,https://weworkremotely.com/remote-jobs/nabu-global-fze-creative-performance-designer
29,30,we_work_remotely_rss,Lead Manager for Real Estate Investment Company,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/campos-property-solutions-lead-manager-for-real-estate-investment-company,https://weworkremotely.com/remote-jobs/campos-property-solutions-lead-manager-for-real-estate-investment-company
30,31,we_work_remotely_rss,Staff Product Engineer,pt,0.75,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/lawnstarter-staff-product-engineer,https://weworkremotely.com/remote-jobs/lawnstarter-staff-product-engineer
31,32,we_work_remotely_rss,Senior Webflow Designer,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/lawnstarter-senior-webflow-designer,https://weworkremotely.com/remote-jobs/lawnstarter-senior-webflow-designer
32,33,we_work_remotely_rss,Full-Stack Developer — .NET + React + Azure — Remote (US),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/shiftforce-llc-full-stack-developer-net-react-azure-remote-us,https://weworkremotely.com/remote-jobs/shiftforce-llc-full-stack-developer-net-react-azure-remote-us
33,34,we_work_remotely_rss,Jr Appointment Setter,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/orchard-brokerage-jr-appointment-setter,https://weworkremotely.com/remote-jobs/orchard-brokerage-jr-appointment-setter
34,35,we_work_remotely_rss,Entry-Level Account Manager,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/nogigiddy-entry-level-account-manager-4,https://weworkremotely.com/remote-jobs/nogigiddy-entry-level-account-manager-4
35,36,we_work_remotely_rss,Cold Caller / VertriebsmitarbeiterIn (Freelance Basis),de,0.95,latin-keyword-heuristic,True,deep-translator-google,None,https://weworkremotely.com/remote-jobs/lotaro-cold-caller-vertriebsmitarbeiterin-freelance-basis,https://weworkremotely.com/remote-jobs/lotaro-cold-caller-vertriebsmitarbeiterin-freelance-basis
36,37,we_work_remotely_rss,Senior Software Engineer II,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/nomad-senior-software-engineer-ii,https://weworkremotely.com/remote-jobs/nomad-senior-software-engineer-ii
37,38,we_work_remotely_rss,Senior Ruby on Rails Developer,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/onthegosystems-senior-ruby-on-rails-developer-2,https://weworkremotely.com/remote-jobs/onthegosystems-senior-ruby-on-rails-developer-2
38,39,we_work_remotely_rss,Lead Product Designer,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/blink-health-lead-product-designer,https://weworkremotely.com/remote-jobs/blink-health-lead-product-designer
39,40,we_work_remotely_rss,Senior Product Marketing Manager,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/nivoda-senior-product-marketing-manager,https://weworkremotely.com/remote-jobs/nivoda-senior-product-marketing-manager
40,41,we_work_remotely_rss,DevOps Engineer,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/createit-s-c-borkowski-bartosz-fredrych-aleksander-devops-engineer,https://weworkremotely.com/remote-jobs/createit-s-c-borkowski-bartosz-fredrych-aleksander-devops-engineer
41,42,we_work_remotely_rss,Product Marketing Manager,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/bazaarvoice-product-marketing-manager,https://weworkremotely.com/remote-jobs/bazaarvoice-product-marketing-manager
42,43,we_work_remotely_rss,Senior QLab Support Specialist (half time),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time-1,https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time-1
43,44,we_work_remotely_rss,Senior QLab Support Specialist (half time),en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time,https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time
44,45,we_work_remotely_rss,Casino Management & Operations,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/fairgambling-casino-management-operations,https://weworkremotely.com/remote-jobs/fairgambling-casino-management-operations
45,46,we_work_remotely_rss,Blockchain Engineer & Researcher,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/fairgambling-blockchain-engineer-researcher,https://weworkremotely.com/remote-jobs/fairgambling-blockchain-engineer-researcher
46,47,we_work_remotely_rss,Senior Product Manager,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/hint-health-senior-product-manager,https://weworkremotely.com/remote-jobs/hint-health-senior-product-manager
47,48,we_work_remotely_rss,Turfgrass Horticulturalist Agronomist - Product Innovation & Support - REMOTE,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/custom-simple-solutions-turfgrass-horticulturalist-agronomist-product-innovation-support-remote,https://weworkremotely.com/remote-jobs/custom-simple-solutions-turfgrass-horticulturalist-agronomist-product-innovation-support-remote
48,49,we_work_remotely_rss,"Director, Graphic Design",en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/olive-june-director-graphic-design,https://weworkremotely.com/remote-jobs/olive-june-director-graphic-design
49,50,we_work_remotely_rss,Senior Product Manager,en,0.55,latin-keyword-heuristic,False,none,None,https://weworkremotely.com/remote-jobs/biggerpockets-senior-product-manager,https://weworkremotely.com/remote-jobs/biggerpockets-senior-product-manager

  detected_language  translation_applied  count
1                en                False     33
4                pt                 True     13
0                de                 True      2
2                es                 True      1
3                it                 True      1

No translation failures detected.

In [23]:
def _combined_text(payload: dict[str, str]) -> str:
    parts = []
    for field in FIELDS_TO_COMPARE:
        value = str(payload.get(field, '') or '').strip()
        if value:
            parts.append(f'[{field}]\n{value}')
    return '\n\n'.join(parts)


def render_language_debug(row_id: int) -> None:
    detail = detailed_posts[row_id - 1]

    header = (
        f"### #{detail['row_id']} | {detail['original'].get('title', '')}\n"
        f"- source: {detail['source']}\n"
        f"- detected_language: {detail['detected_language']} (confidence={detail['language_confidence']})\n"
        f"- detector: {detail['language_detector']}\n"
        f"- translation_applied: {detail['translation_applied']}\n"
        f"- translation_provider: {detail['translation_provider']}\n"
        f"- translation_error: {detail['translation_error']}\n"
        f"- job_url: {detail['job_url']}\n"
        f"- apply_url: {detail['apply_url']}"
    )
    display(Markdown(header))

    compare_rows = []
    for field in FIELDS_TO_COMPARE:
        original = str(detail['original'].get(field, '') or '')
        translated = str(detail['translated'].get(field, '') or '')
        compare_rows.append({
            'field': field,
            'original': original,
            'translated': translated,
            'changed': original.strip() != translated.strip(),
        })

    compare_df = pd.DataFrame(compare_rows)
    display(compare_df)

    if SHOW_FULL_TEXT:
        original_combined = _combined_text(detail['original'])
        translated_combined = _combined_text(detail['translated'])

        display(Markdown('**Original Full Posting Text**'))
        print(original_combined if original_combined else '[empty]')

        display(Markdown('**Translated Full Posting Text**'))
        print(translated_combined if translated_combined else '[empty]')

    display(Markdown('---'))

In [24]:
# Run this cell to render all fetched jobs with full original/translated details.
START_INDEX = 1
END_INDEX = len(detailed_posts)

print(f'Rendering jobs {START_INDEX} to {END_INDEX} (inclusive).')

for row_id in range(START_INDEX, END_INDEX + 1):
    render_language_debug(row_id)

Rendering jobs 1 to 50 (inclusive).

### #1 | Senior Software Engineer, Platform
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-platform-1
- apply_url: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-platform-1

,field,original,translated,changed
0,title,"Senior Software Engineer, Platform","Senior Software Engineer, Platform",False
1,company_profile,Speechify Inc,Speechify Inc,False
2,location,"Anywhere in the World, Florida","Anywhere in the World, Florida",False
3,department,,,False
4,description,"Headquarters: Florida URL: http://www.speechify.com Overview As Speechify expands, our Platform team seeks a Senior Software Engineer. This role is central to ensuring our succ...","Headquarters: Florida URL: http://www.speechify.com Overview As Speechify expands, our Platform team seeks a Senior Software Engineer. This role is central to ensuring our succ...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,All Other Remote,All Other Remote,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Software Engineer, Platform

[company_profile]
Speechify Inc

[location]
Anywhere in the World, Florida

[description]
Headquarters: Florida URL: http://www.speechify.com Overview As Speechify expands, our Platform team seeks a Senior Software Engineer. This role is central to ensuring our success at Speechify by working on key features like: Payments, Analytics, Subscriptions and our API. If you are passionate about strategizing, enjoy high-paced environments, and are eager to take ownership of product decisions, we’d love to hear from you. What You’ll Do Design, develop, and maintain robust APIs including Public TTS API, Internal APIs like Payment, Subscription, Auth and Consumption Tracking, ensuring they meet business and scalability requirements. Oversee the full backend API landscape, enhancing and optimizing for performance and maintainability. Collaborate on B2B solutions, focusing on customization and integration needs for enterprise clients. Work closely with cross-functional teams to align backend architecture with overall product strategy and user experience. An Ideal Candidate Should Have Proven experience in backend development: TS/Node (required), Go (nice to have) Direct experience with GCP and knowledge of AWS, Azure, or other cloud providers. Efficiency in ideation and implementation, prioritizing tasks based on urgency and impact. Preferred: Experience with Docker and containerized deployments. Preferred: Proficiency in deploying high availability applications on Kubernetes What We Offer A dynamic environment where your contributions shape the company and its products. A team that values innovation, intuition, and drive. Autonomy, fostering focus and creativity. The opportunity to have a significant impact in a revolutionary industry. Competitive compensation, a welcoming atmosphere, and a commitment to an exceptional asynchronous work culture. The privilege of working on a product that changes lives, particularly for those with learning differences like dyslexia, ADD, and more. An active role at the intersection of artificial intelligence and audio – a rapidly evolving tech domain. Think you’re a good fit for this job? Tell us more about yourself and why you're interested in the role when you apply. And don’t forget to include links to your portfolio and LinkedIn. Not looking but know someone who would make a great fit? Refer them! Speechify is committed to a diverse and inclusive workplace. Speechify does not discriminate on the basis of race, national origin, gender, gender identity, sexual orientation, protected veteran status, disability, age, or other legally protected status. To apply: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-platform-1

[employment_type]
Full-Time

[industry]
All Other Remote

**Translated Full Posting Text**

[title]
Senior Software Engineer, Platform

[company_profile]
Speechify Inc

[location]
Anywhere in the World, Florida

[description]
Headquarters: Florida URL: http://www.speechify.com Overview As Speechify expands, our Platform team seeks a Senior Software Engineer. This role is central to ensuring our success at Speechify by working on key features like: Payments, Analytics, Subscriptions and our API. If you are passionate about strategizing, enjoy high-paced environments, and are eager to take ownership of product decisions, we’d love to hear from you. What You’ll Do Design, develop, and maintain robust APIs including Public TTS API, Internal APIs like Payment, Subscription, Auth and Consumption Tracking, ensuring they meet business and scalability requirements. Oversee the full backend API landscape, enhancing and optimizing for performance and maintainability. Collaborate on B2B solutions, focusing on customization and integration needs for enterprise clients. Work closely with cross-functional teams to align backend architecture with overall product strategy and user experience. An Ideal Candidate Should Have Proven experience in backend development: TS/Node (required), Go (nice to have) Direct experience with GCP and knowledge of AWS, Azure, or other cloud providers. Efficiency in ideation and implementation, prioritizing tasks based on urgency and impact. Preferred: Experience with Docker and containerized deployments. Preferred: Proficiency in deploying high availability applications on Kubernetes What We Offer A dynamic environment where your contributions shape the company and its products. A team that values innovation, intuition, and drive. Autonomy, fostering focus and creativity. The opportunity to have a significant impact in a revolutionary industry. Competitive compensation, a welcoming atmosphere, and a commitment to an exceptional asynchronous work culture. The privilege of working on a product that changes lives, particularly for those with learning differences like dyslexia, ADD, and more. An active role at the intersection of artificial intelligence and audio – a rapidly evolving tech domain. Think you’re a good fit for this job? Tell us more about yourself and why you're interested in the role when you apply. And don’t forget to include links to your portfolio and LinkedIn. Not looking but know someone who would make a great fit? Refer them! Speechify is committed to a diverse and inclusive workplace. Speechify does not discriminate on the basis of race, national origin, gender, gender identity, sexual orientation, protected veteran status, disability, age, or other legally protected status. To apply: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-platform-1

[employment_type]
Full-Time

[industry]
All Other Remote

---

### #2 | Senior Software Engineer, Web
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-web-1
- apply_url: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-web-1

,field,original,translated,changed
0,title,"Senior Software Engineer, Web","Senior Software Engineer, Web",False
1,company_profile,Speechify Inc,Speechify Inc,False
2,location,"Anywhere in the World, Florida","Anywhere in the World, Florida",False
3,department,,,False
4,description,Headquarters: Florida URL: http://www.speechify.com Overview With that growth comes the need for a Javascript Engineer to join the existing Web team and continue supporting the...,Headquarters: Florida URL: http://www.speechify.com Overview With that growth comes the need for a Javascript Engineer to join the existing Web team and continue supporting the...,False
5,requirements,JavaScript and React,JavaScript and React,False
6,benefits,,,False
7,employment_type,Contract,Contract,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Front-End Programming,Front-End Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Software Engineer, Web

[company_profile]
Speechify Inc

[location]
Anywhere in the World, Florida

[description]
Headquarters: Florida URL: http://www.speechify.com Overview With that growth comes the need for a Javascript Engineer to join the existing Web team and continue supporting the growing user base as well as building new and exciting features. This is a key role and ideal for someone who thinks strategically, enjoys high-pace environments, passionate about owning product decisions and has experience building and scaling complex engineering systems. What You’ll Do Actively ship production code to the web products Work closely with your dedicated product team Participate in product discussions to shape the product roadmap Have the opportunity to work on new and exciting features that will impact millions of lives An Ideal Candidate Should Have Experience. You've built and ship products that have scaled to thousands or millions of users Customer obsession. You are passionate about the field and have the desire to build high quality product that serves customer needs Speed. You work quickly to generate ideas and know how to decide which things can ship now and what things need time Focus. We’re a high-growth startup with a busy, remote team. You know how and when to engage or be heads down Collaboration. You know how to inspire, play, and negotiate with opinionated designers, marketers, and PMs Tech Stack: Vanilla JS, ReactJS, Redux, Firebase, Typescript What We Offer A fast-growing environment where you can help shape the culture An entrepreneurial crew that supports risk, intuition, and hustle A hands-off approach so you can focus and do your best work The opportunity to make an impact in a transformative industry A competitive salary, a collegiate atmosphere, and a commitment to building a great asynchronous culture To apply: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-web-1

[requirements]
JavaScript and React

[employment_type]
Contract

[industry]
Front-End Programming

**Translated Full Posting Text**

[title]
Senior Software Engineer, Web

[company_profile]
Speechify Inc

[location]
Anywhere in the World, Florida

[description]
Headquarters: Florida URL: http://www.speechify.com Overview With that growth comes the need for a Javascript Engineer to join the existing Web team and continue supporting the growing user base as well as building new and exciting features. This is a key role and ideal for someone who thinks strategically, enjoys high-pace environments, passionate about owning product decisions and has experience building and scaling complex engineering systems. What You’ll Do Actively ship production code to the web products Work closely with your dedicated product team Participate in product discussions to shape the product roadmap Have the opportunity to work on new and exciting features that will impact millions of lives An Ideal Candidate Should Have Experience. You've built and ship products that have scaled to thousands or millions of users Customer obsession. You are passionate about the field and have the desire to build high quality product that serves customer needs Speed. You work quickly to generate ideas and know how to decide which things can ship now and what things need time Focus. We’re a high-growth startup with a busy, remote team. You know how and when to engage or be heads down Collaboration. You know how to inspire, play, and negotiate with opinionated designers, marketers, and PMs Tech Stack: Vanilla JS, ReactJS, Redux, Firebase, Typescript What We Offer A fast-growing environment where you can help shape the culture An entrepreneurial crew that supports risk, intuition, and hustle A hands-off approach so you can focus and do your best work The opportunity to make an impact in a transformative industry A competitive salary, a collegiate atmosphere, and a commitment to building a great asynchronous culture To apply: https://weworkremotely.com/remote-jobs/speechify-inc-senior-software-engineer-web-1

[requirements]
JavaScript and React

[employment_type]
Contract

[industry]
Front-End Programming

---

### #3 | Junior Full-Stack Developer (Laravel and VueJS)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/appetiser-junior-full-stack-developer-laravel-and-vuejs
- apply_url: https://weworkremotely.com/remote-jobs/appetiser-junior-full-stack-developer-laravel-and-vuejs

,field,original,translated,changed
0,title,Junior Full-Stack Developer (Laravel and VueJS),Junior Full-Stack Developer (Laravel and VueJS),False
1,company_profile,Appetiser,Appetiser,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Colombo, 1, Sri Lanka Job description "" Appetiser challenges me to give the best version of myself. I like how the company is transparent about its business model...","Headquarters: Colombo, 1, Sri Lanka Job description "" Appetiser challenges me to give the best version of myself. I like how the company is transparent about its business model...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Junior Full-Stack Developer (Laravel and VueJS)

[company_profile]
Appetiser

[location]
Anywhere in the World

[description]
Headquarters: Colombo, 1, Sri Lanka Job description " Appetiser challenges me to give the best version of myself. I like how the company is transparent about its business model and anyone can contribute with an idea for its improvement. The culture within the team is unique and everyone is talented and skillful in their profession. We set goals guided by virtues created by the team rather than the traditional core values. ” - Jeff Miralles / iOS Developer Are you someone who is DRIVING themselves to peak performance? Are you excited by HELPING PEOPLE create technology that impacts millions every day? If you answered YES to these questions, you may be a fit for Appetiser Apps . Join a high-performance team who are striving to go from an Australian market leader to a worldwide phenomenon. Our competitors cannot keep up with our technology, pace, and track record of successful clients. We need ambitious people like YOU to help us grow by 10X over the next 5 years. YOU WILL: BUILD beautiful websites using HTML and CSS to bring creative ideas to life. COLLABORATE with designers and developers to create web apps and backend mobile solutions. COORDINATE with teams to launch content, setting clear timelines and expectations. PLAN for the unexpected by preparing backup solutions to ensure site reliability. GROW and maintain the website by expanding its features and keeping content fresh. LEAD projects and, when needed, take charge of a team from start to finish. ADAPT quickly and take on new tasks as they arise. Job requirements ​​The right fit for this role is DETERMINED, CURIOUS and EAGER TO GROW with : Has a strong work ethic and takes ownership of their learning Is hungry to improve every day and open to feedback Understands core programming fundamentals and is excited to build real-world applications Has some hands-on experience (school projects, internships, freelance, or personal projects) in web or mobile development Frontend/Backend Basic understanding of Git for version control Writing clean, readable, and maintainable code Basic knowledge of unit testing Understanding how APIs work (REST basics) Familiarity with Agile practices (Scrum or Kanban) Stable internet connection (minimum 30 Mbps download / 10 Mbps upload) Own laptop/desktop capable of handling development work Backend: Experience building projects using Laravel (v10 or later is a plus) Understanding of databases and basic SQL schema design Knowledge of clean coding principles (e.g., SOLID fundamentals) Basic understanding of RESTful APIs and how to test them (Postman, Insomnia, etc.) Exposure to deployment or cloud platforms like AWS is a plus Frontend: Comfortable with HTML5, CSS3, and JavaScript Experience working with a modern framework ( Nuxt.js is a plus) Understanding of responsive design and reusable components Exposure to testing tools (Vitest, Cypress, Playwright) or TypeScript is a bonus Join our team! Flexible Work Arrangements: The ability to work from anywhere in the world as long as you perform. Accelerate Your Career: After probation, you get performance reviews every 6 months. Progress based on merit faster than ever before. Become Your Best: Set personal & professional goals every quarter with your talent coach. Get optional counselling along the way. Global Impact: Build products that reach users worldwide and truly make a difference in the world! Public Recognition: Track your achievements as you build a personal portfolio & track record. Join a Culture of Drivers : Become part of a team that’s striving to be their very best. If this resonates with you, please apply today. P.S. We're hiring multiple individuals. If you want to recommend someone, please email us; an attractive referral bonus awaits! P.P.S. If you have any questions, email us at talent.acquisition@appetiserapps.com All done! Your application has been successfully submitted! Other jobs To apply: https://weworkremotely.com/remote-jobs/appetiser-junior-full-stack-developer-laravel-and-vuejs

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Junior Full-Stack Developer (Laravel and VueJS)

[company_profile]
Appetiser

[location]
Anywhere in the World

[description]
Headquarters: Colombo, 1, Sri Lanka Job description " Appetiser challenges me to give the best version of myself. I like how the company is transparent about its business model and anyone can contribute with an idea for its improvement. The culture within the team is unique and everyone is talented and skillful in their profession. We set goals guided by virtues created by the team rather than the traditional core values. ” - Jeff Miralles / iOS Developer Are you someone who is DRIVING themselves to peak performance? Are you excited by HELPING PEOPLE create technology that impacts millions every day? If you answered YES to these questions, you may be a fit for Appetiser Apps . Join a high-performance team who are striving to go from an Australian market leader to a worldwide phenomenon. Our competitors cannot keep up with our technology, pace, and track record of successful clients. We need ambitious people like YOU to help us grow by 10X over the next 5 years. YOU WILL: BUILD beautiful websites using HTML and CSS to bring creative ideas to life. COLLABORATE with designers and developers to create web apps and backend mobile solutions. COORDINATE with teams to launch content, setting clear timelines and expectations. PLAN for the unexpected by preparing backup solutions to ensure site reliability. GROW and maintain the website by expanding its features and keeping content fresh. LEAD projects and, when needed, take charge of a team from start to finish. ADAPT quickly and take on new tasks as they arise. Job requirements ​​The right fit for this role is DETERMINED, CURIOUS and EAGER TO GROW with : Has a strong work ethic and takes ownership of their learning Is hungry to improve every day and open to feedback Understands core programming fundamentals and is excited to build real-world applications Has some hands-on experience (school projects, internships, freelance, or personal projects) in web or mobile development Frontend/Backend Basic understanding of Git for version control Writing clean, readable, and maintainable code Basic knowledge of unit testing Understanding how APIs work (REST basics) Familiarity with Agile practices (Scrum or Kanban) Stable internet connection (minimum 30 Mbps download / 10 Mbps upload) Own laptop/desktop capable of handling development work Backend: Experience building projects using Laravel (v10 or later is a plus) Understanding of databases and basic SQL schema design Knowledge of clean coding principles (e.g., SOLID fundamentals) Basic understanding of RESTful APIs and how to test them (Postman, Insomnia, etc.) Exposure to deployment or cloud platforms like AWS is a plus Frontend: Comfortable with HTML5, CSS3, and JavaScript Experience working with a modern framework ( Nuxt.js is a plus) Understanding of responsive design and reusable components Exposure to testing tools (Vitest, Cypress, Playwright) or TypeScript is a bonus Join our team! Flexible Work Arrangements: The ability to work from anywhere in the world as long as you perform. Accelerate Your Career: After probation, you get performance reviews every 6 months. Progress based on merit faster than ever before. Become Your Best: Set personal & professional goals every quarter with your talent coach. Get optional counselling along the way. Global Impact: Build products that reach users worldwide and truly make a difference in the world! Public Recognition: Track your achievements as you build a personal portfolio & track record. Join a Culture of Drivers : Become part of a team that’s striving to be their very best. If this resonates with you, please apply today. P.S. We're hiring multiple individuals. If you want to recommend someone, please email us; an attractive referral bonus awaits! P.P.S. If you have any questions, email us at talent.acquisition@appetiserapps.com All done! Your application has been successfully submitted! Other jobs To apply: https://weworkremotely.com/remote-jobs/appetiser-junior-full-stack-developer-laravel-and-vuejs

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #4 | Product Marketing Manager (B2B for life sciences/pharma/biotech)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/viseven-product-marketing-manager-b2b-for-life-sciences-pharma-biotech
- apply_url: https://weworkremotely.com/remote-jobs/viseven-product-marketing-manager-b2b-for-life-sciences-pharma-biotech

,field,original,translated,changed
0,title,Product Marketing Manager (B2B for life sciences/pharma/biotech),Product Marketing Manager (B2B for life sciences/pharma/biotech),False
1,company_profile,Viseven,Viseven,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Warszawa Viseven Group is a leading global B2B MarTech service provider, empowering Pharma and LifeScience companies since 2009. Our mission is to drive digital t...","Headquarters: Warszawa Viseven Group is a leading global B2B MarTech service provider, empowering Pharma and LifeScience companies since 2009. Our mission is to drive digital t...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Sales and Marketing,Sales and Marketing,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Product Marketing Manager (B2B for life sciences/pharma/biotech)

[company_profile]
Viseven

[location]
Anywhere in the World

[description]
Headquarters: Warszawa Viseven Group is a leading global B2B MarTech service provider, empowering Pharma and LifeScience companies since 2009. Our mission is to drive digital transformation and excellence, offering comprehensive end-to-end software and digital marketing services tailored to the pharmaceutical industry. The company's solutions, products, and services are actively used by the top 100 Pharma and Life Science companies. At Viseven, our rapidly growing team boasts over 700 highly skilled professionals, including experts in development, design, business analysis, project management, delivery, sales, marketing, and customer success. With a global footprint in more than 30 countries across the US, LATAM, Europe, and APAC, and physical offices in Ukraine, Poland, Estonia, India, and the US, we are well-positioned to serve our diverse clientele. Join us and become part of a pioneering team dedicated to shaping the future of digital transformation in Pharma and Life Sciences across more than 50 countries around the globe. Responsibilities: Translating industry trends into Viseven's strategic positioning and product roadmap influence. Translating product capabilities into business outcomes our clients care about. Collaborate with cross-functional teams, including product, sales, delivery, and digital, to develop and execute effective marketing campaigns. Building and maintaining business decks, competitive battle cards, objection handling frameworks, and differentiation narratives. Positioning product bundles and pricing tiers for different buyer segments. Developing buyer persona frameworks for multi-stakeholder pharma decisions. Defining GTM strategy for new product launches, platform expansions, and market entry (geographic or vertical). Building relationships with key opinion leaders, industry analysts, and pharma marketing executives. Supporting RFP/tender responses with strategic positioning. Analyze marketing campaign results and make recommendations for future marketing strategies. Requirements: Proven experience as a Product Marketing Manager in B2B (life sciences/pharma/biotech). Strong understanding of ICP definition, customer segmentation, and Jobs-to-Be-Done frameworks. Competitive positioning experience with measurable impact on win rates or deal velocity Ability to translate customer, market, and competitive insights into clear product positioning and value propositions. Product launch or GTM execution in B2B enterprise or mid-market segments Experience working with brand, content, and demand teams to ensure consistent messaging across all touchpoints. Hands-on experience leading go-to-market strategies for new products, features, or market expansions. Strong understanding of the full B2B funnel (MQL, SQL, pipeline, revenue) and PMM’s role in revenue growth. Experience coordinating cross-functional launch efforts with Product, Sales, Marketing, and Customer Success teams. Data-driven mindset with the ability to turn insights into clear recommendations and actions. What we provide: We know our team members are key to achieving our goals, so we value and empower them to share their vision. We reward this passion with exceptional benefits, including: Competitive Compensation : Regular performance-based salary and career development reviews. Experienced Team : Join a passionate, experienced team in a friendly atmosphere. Career Growth : Opportunities for professional and career advancement. Paid Time Off : 18 business days per year (20 business days after 2 years of service). Sick Leave : Non-documented: 4 business days per year. Documented: 20 business days per year. Family Leave : 3 paid business days for marriage, childbirth, or bereavement. Medical Insurance : Comprehensive coverage. English Courses : Learning opportunities to improve your language skills. Professional Development : Participation in forums and conferences. Corporate Events : Regular team-building activities and events. Work Environment : Enjoy a comfortable, fully equipped office and the possibility to work from home. To apply: https://weworkremotely.com/remote-jobs/viseven-product-marketing-manager-b2b-for-life-sciences-pharma-biotech

[employment_type]
Full-Time

[industry]
Sales and Marketing

**Translated Full Posting Text**

[title]
Product Marketing Manager (B2B for life sciences/pharma/biotech)

[company_profile]
Viseven

[location]
Anywhere in the World

[description]
Headquarters: Warszawa Viseven Group is a leading global B2B MarTech service provider, empowering Pharma and LifeScience companies since 2009. Our mission is to drive digital transformation and excellence, offering comprehensive end-to-end software and digital marketing services tailored to the pharmaceutical industry. The company's solutions, products, and services are actively used by the top 100 Pharma and Life Science companies. At Viseven, our rapidly growing team boasts over 700 highly skilled professionals, including experts in development, design, business analysis, project management, delivery, sales, marketing, and customer success. With a global footprint in more than 30 countries across the US, LATAM, Europe, and APAC, and physical offices in Ukraine, Poland, Estonia, India, and the US, we are well-positioned to serve our diverse clientele. Join us and become part of a pioneering team dedicated to shaping the future of digital transformation in Pharma and Life Sciences across more than 50 countries around the globe. Responsibilities: Translating industry trends into Viseven's strategic positioning and product roadmap influence. Translating product capabilities into business outcomes our clients care about. Collaborate with cross-functional teams, including product, sales, delivery, and digital, to develop and execute effective marketing campaigns. Building and maintaining business decks, competitive battle cards, objection handling frameworks, and differentiation narratives. Positioning product bundles and pricing tiers for different buyer segments. Developing buyer persona frameworks for multi-stakeholder pharma decisions. Defining GTM strategy for new product launches, platform expansions, and market entry (geographic or vertical). Building relationships with key opinion leaders, industry analysts, and pharma marketing executives. Supporting RFP/tender responses with strategic positioning. Analyze marketing campaign results and make recommendations for future marketing strategies. Requirements: Proven experience as a Product Marketing Manager in B2B (life sciences/pharma/biotech). Strong understanding of ICP definition, customer segmentation, and Jobs-to-Be-Done frameworks. Competitive positioning experience with measurable impact on win rates or deal velocity Ability to translate customer, market, and competitive insights into clear product positioning and value propositions. Product launch or GTM execution in B2B enterprise or mid-market segments Experience working with brand, content, and demand teams to ensure consistent messaging across all touchpoints. Hands-on experience leading go-to-market strategies for new products, features, or market expansions. Strong understanding of the full B2B funnel (MQL, SQL, pipeline, revenue) and PMM’s role in revenue growth. Experience coordinating cross-functional launch efforts with Product, Sales, Marketing, and Customer Success teams. Data-driven mindset with the ability to turn insights into clear recommendations and actions. What we provide: We know our team members are key to achieving our goals, so we value and empower them to share their vision. We reward this passion with exceptional benefits, including: Competitive Compensation : Regular performance-based salary and career development reviews. Experienced Team : Join a passionate, experienced team in a friendly atmosphere. Career Growth : Opportunities for professional and career advancement. Paid Time Off : 18 business days per year (20 business days after 2 years of service). Sick Leave : Non-documented: 4 business days per year. Documented: 20 business days per year. Family Leave : 3 paid business days for marriage, childbirth, or bereavement. Medical Insurance : Comprehensive coverage. English Courses : Learning opportunities to improve your language skills. Professional Development : Participation in forums and conferences. Corporate Events : Regular team-building activities and events. Work Environment : Enjoy a comfortable, fully equipped office and the possibility to work from home. To apply: https://weworkremotely.com/remote-jobs/viseven-product-marketing-manager-b2b-for-life-sciences-pharma-biotech

[employment_type]
Full-Time

[industry]
Sales and Marketing

---

### #5 | Director, AI Product Development
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/centralreach-director-ai-product-development
- apply_url: https://weworkremotely.com/remote-jobs/centralreach-director-ai-product-development

,field,original,translated,changed
0,title,"Director, AI Product Development","Director, AI Product Development",False
1,company_profile,Centralreach,Centralreach,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Remote - US CentralReach is a leading provider of autism and IDD care software for Applied Behavior Analysis (ABA), multidisciplinary therapy, and special educati...","Headquarters: Remote - US CentralReach is a leading provider of autism and IDD care software for Applied Behavior Analysis (ABA), multidisciplinary therapy, and special educati...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,DevOps and Sysadmin,DevOps and Sysadmin,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Director, AI Product Development

[company_profile]
Centralreach

[location]
Anywhere in the World

[description]
Headquarters: Remote - US CentralReach is a leading provider of autism and IDD care software for Applied Behavior Analysis (ABA), multidisciplinary therapy, and special education. Trusted by more than 200,000 users, we enable therapy providers, educators, and employers to scale the way they deliver ABA and related therapies with innovative technology, market-leading industry expertise, and world-class customer satisfaction. CentralReach’s AI team operates as an AI Foundry: a cross-functional group that rapidly builds, validates, and scales AI-enabled product capabilities. The Principal Software Engineer, AI Applications is the senior-most engineer on the AI team and sets the technical bar for how AI-powered product experiences are designed, built, evaluated, and operated. This role is hands-on and deeply engaged across the early stages of development of AI applications , from early prototypes and pilots through production hardening and scale. They partner closely with AI p roduct b uilders, Product organization leaders and DevOps to translate customer problems into reliable AI features that integrate seamlessly with CentralReach’s core workflows. They also establish engineering standards for AI application development: evaluation and quality thresholds, observability, guardrails and performance management. Key Accountabilities: Technical Leadership & Engineering Excellence Serve as the technical lead for AI application development within the AI Foundry, setting standards for code quality, architecture, and delivery Lead by doing: design and implement core AI application components, critical services, and integration layers Mentor AI engineers; raise the bar on engineering rigor and AI-specific best practices Establish quality thresholds and release criteria (accuracy, latency, reliability, cost, and user trust) Design safeguards and “safe failure modes”: fallback behaviors, confidence thresholds, user controls, content filtering, and transparency patterns AI Application Development (Hands-On) Build AI-powered product capabilities end-to-end (service + workflow integration + instrumentation), including LLM-enabled workflows, RAG, summarization, classification, and automation patterns Build and maintain shared libraries/components for AI application development (prompt/tooling patterns, service templates, evaluation utilities, safety layers) Own technical readiness for production: reliability, observability, performance tuning, and incident response preparedness Collaborate with platform Engineering and DevOps to ensure CI/CD and environment consistency , s caling strategies , cost controls for inference and s ecrets management and secure data handling Cross-Functional Delivery & Integration Partner tightly with AI p roduct b uilders and workflow Product owners to translate validated prototypes into production implementations Collaborate with core engineering teams to integrate AI capabilities into CentralReach’s main platforms Strategic Direction & Innovation Identify and prioritize foundational investments that increase delivery velocity and reduce long-term maintenance: reusable components, platform primitives, and standardized patterns Evaluate build vs. buy decisions for AI tooling and recommend approaches aligned to CR constraints Stay current with AI application engineering practices and help translate emerging techniques into safe, valuable product capabilities Desired Skills and Experience: Bachelor's degree or equivalent work experience 10+ years of professional software engineering experience, with principal-level scope and demonstrated technical leadership Strong experience building and operating production distributed systems and backend services Demonstrated hands-on experience delivering AI/ML-powered product features (LLMs and/or traditional ML), including evaluation and monitoring Experience with retrieval systems and search relevance (RAG, embeddings, indexing, ranking, evaluation) Strong system design skills: APIs, data flows, integration patterns, performance and reliability tradeoffs Experience with observability and operational excellence (logging, metrics, tracing, alerting, incident response) Ability to communicate technical concepts clearly to product, design, and executive stakeholders Experience in a healthcare SaaS environment Familiarity with multi-tenant architectures and enterprise access control models Experience building internal platforms/tooling that improve developer experience and standardize best practices #LI-Remote Base Salary Range $180,000 - $200,000 USD Backed by Roper Technologies, Inc. (Nasdaq: ROP), and led by award-winning CEO Chris Sullens, CentralReach is entering an exciting phase of growth, innovation, and scale. Recognized as one of the best places to work over 10 times by organizations such as Inc, Built In, and NJBIZ, our culture is centered around impact, inclusion, and flexibility. As a hybrid company with collaborative offices in Ft. Lauderdale, FL; Holmdel, NJ; and Verona, Italy, we foster a workplace where top talent can thrive and make a real difference in the lives of those we serve. We offer competitive compensation, comprehensive health benefits, generous PTO, 401(k) matching, and paid parental leave. Our team members also enjoy hybrid work schedules, career development support, wellness programs, and opportunities to give back through CR Cares™, our community engagement initiative. Be part of a market leader driving the future of care. Explore opportunities at centralreach.com/careers . To apply: https://weworkremotely.com/remote-jobs/centralreach-director-ai-product-development

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

**Translated Full Posting Text**

[title]
Director, AI Product Development

[company_profile]
Centralreach

[location]
Anywhere in the World

[description]
Headquarters: Remote - US CentralReach is a leading provider of autism and IDD care software for Applied Behavior Analysis (ABA), multidisciplinary therapy, and special education. Trusted by more than 200,000 users, we enable therapy providers, educators, and employers to scale the way they deliver ABA and related therapies with innovative technology, market-leading industry expertise, and world-class customer satisfaction. CentralReach’s AI team operates as an AI Foundry: a cross-functional group that rapidly builds, validates, and scales AI-enabled product capabilities. The Principal Software Engineer, AI Applications is the senior-most engineer on the AI team and sets the technical bar for how AI-powered product experiences are designed, built, evaluated, and operated. This role is hands-on and deeply engaged across the early stages of development of AI applications , from early prototypes and pilots through production hardening and scale. They partner closely with AI p roduct b uilders, Product organization leaders and DevOps to translate customer problems into reliable AI features that integrate seamlessly with CentralReach’s core workflows. They also establish engineering standards for AI application development: evaluation and quality thresholds, observability, guardrails and performance management. Key Accountabilities: Technical Leadership & Engineering Excellence Serve as the technical lead for AI application development within the AI Foundry, setting standards for code quality, architecture, and delivery Lead by doing: design and implement core AI application components, critical services, and integration layers Mentor AI engineers; raise the bar on engineering rigor and AI-specific best practices Establish quality thresholds and release criteria (accuracy, latency, reliability, cost, and user trust) Design safeguards and “safe failure modes”: fallback behaviors, confidence thresholds, user controls, content filtering, and transparency patterns AI Application Development (Hands-On) Build AI-powered product capabilities end-to-end (service + workflow integration + instrumentation), including LLM-enabled workflows, RAG, summarization, classification, and automation patterns Build and maintain shared libraries/components for AI application development (prompt/tooling patterns, service templates, evaluation utilities, safety layers) Own technical readiness for production: reliability, observability, performance tuning, and incident response preparedness Collaborate with platform Engineering and DevOps to ensure CI/CD and environment consistency , s caling strategies , cost controls for inference and s ecrets management and secure data handling Cross-Functional Delivery & Integration Partner tightly with AI p roduct b uilders and workflow Product owners to translate validated prototypes into production implementations Collaborate with core engineering teams to integrate AI capabilities into CentralReach’s main platforms Strategic Direction & Innovation Identify and prioritize foundational investments that increase delivery velocity and reduce long-term maintenance: reusable components, platform primitives, and standardized patterns Evaluate build vs. buy decisions for AI tooling and recommend approaches aligned to CR constraints Stay current with AI application engineering practices and help translate emerging techniques into safe, valuable product capabilities Desired Skills and Experience: Bachelor's degree or equivalent work experience 10+ years of professional software engineering experience, with principal-level scope and demonstrated technical leadership Strong experience building and operating production distributed systems and backend services Demonstrated hands-on experience delivering AI/ML-powered product features (LLMs and/or traditional ML), including evaluation and monitoring Experience with retrieval systems and search relevance (RAG, embeddings, indexing, ranking, evaluation) Strong system design skills: APIs, data flows, integration patterns, performance and reliability tradeoffs Experience with observability and operational excellence (logging, metrics, tracing, alerting, incident response) Ability to communicate technical concepts clearly to product, design, and executive stakeholders Experience in a healthcare SaaS environment Familiarity with multi-tenant architectures and enterprise access control models Experience building internal platforms/tooling that improve developer experience and standardize best practices #LI-Remote Base Salary Range $180,000 - $200,000 USD Backed by Roper Technologies, Inc. (Nasdaq: ROP), and led by award-winning CEO Chris Sullens, CentralReach is entering an exciting phase of growth, innovation, and scale. Recognized as one of the best places to work over 10 times by organizations such as Inc, Built In, and NJBIZ, our culture is centered around impact, inclusion, and flexibility. As a hybrid company with collaborative offices in Ft. Lauderdale, FL; Holmdel, NJ; and Verona, Italy, we foster a workplace where top talent can thrive and make a real difference in the lives of those we serve. We offer competitive compensation, comprehensive health benefits, generous PTO, 401(k) matching, and paid parental leave. Our team members also enjoy hybrid work schedules, career development support, wellness programs, and opportunities to give back through CR Cares™, our community engagement initiative. Be part of a market leader driving the future of care. Explore opportunities at centralreach.com/careers . To apply: https://weworkremotely.com/remote-jobs/centralreach-director-ai-product-development

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

---

### #6 | Senior DevOps Engineer - Migraciones CI/CD (Remoto 100%)
- source: we_work_remotely_rss
- detected_language: es (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/knowmad-mood-senior-devops-engineer-migraciones-ci-cd-remoto-100
- apply_url: https://weworkremotely.com/remote-jobs/knowmad-mood-senior-devops-engineer-migraciones-ci-cd-remoto-100

,field,original,translated,changed
0,title,Senior DevOps Engineer - Migraciones CI/CD (Remoto 100%),Senior DevOps Engineer - CI/CD Migrations (100% Remote),True
1,company_profile,Knowmad Mood,Knowmad Mood,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Calle Jacinto Benavente, 2 Las Rozas de Madrid, España, 28232 Spain ¡Hola! Sabemos que , sí, no lo niegues, estás explorando nuevos proyectos ofertas y empresas, ...","Headquarters: Calle Jacinto Benavente, 2 Las Rozas de Madrid, Spain, 28232 Spain Hello! We know that, yes, don't deny it, you are exploring new projects, offers and companies, ...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior DevOps Engineer - Migraciones CI/CD (Remoto 100%)

[company_profile]
Knowmad Mood

[location]
Anywhere in the World

[description]
Headquarters: Calle Jacinto Benavente, 2 Las Rozas de Madrid, España, 28232 Spain ¡Hola! Sabemos que , sí, no lo niegues, estás explorando nuevos proyectos ofertas y empresas, algo te gustaría cambiar. Nos gustaría que, en esta oferta de empleo pares, directamente a las responsabilidades, conocimientos, y todas esas cosas que buscamos de ti. Porque primero queremos presentarnos… Lo primero de todo , lo segundo que í , somos tekkies, nos gusta, aunque no tenga que ver con nuestro puesto de trabajo, esas novedades frikies que se comen nuestras horas mirando en youtube, en twich, en tik tok, gitlab o dónde sea. Por las mañanas nos levantamos, nos tomamos un café, y no iniciamos el ordenador con palpitaciones, sino alegres , con ganas de comenzar el día, de trabajar con las personas de tu equipo y todas aquellas con las que estamos en contacto día a día. Esa es nuestra primera promesa, á . Se te pasarán las horas volando, haciendo lo que te apasiona hacer. ¿é í ? En primer lugar, somos Microsoft Gold Partner con 5 competencias: - Gold Application Development - Gold Cloud Platform - Gold Application Integration - Silver DevOps - Silver Data Analytics A parte de ello contamos con acuerdos con Google Cloud a nivel PartnertShip Advantage y AWS como Partner Estratégico... ´ ! ️ Como una imagen vale más que mil palabras, te compartimos este vídeo para que veas cómo es vivir en knowmad mood: https://www.youtube.com/watch?v=PHn3vImdA7I&feature=youtu.be Además, trabajamos para 14 de las empresas del IBEX-35 y desarrollamos proyectos internos de innovación, pero ¡ ! ️ Además, te ofrecemos grandes posibilidades en plan de carrera, formación y certificación para crecer profesionalmente. Horario Flexible ¿Trabajar viernes por la tarde? De eso nada, en knowmad mood la siesta se respeta Julio y Agosto jornada intensiva, ¡el verano está para disfrutarlo! Formación y Plan de Carrera Formaciones: Red Hat Academy, Docker, Ansible, Udemy For Business & Cloud Gurú / Bootcamps: K8S, ELK for Kubernetes, Openshift… Certificaciones TOP: AWS DevOps/Architect, CKA/CKS, AZ104, AZ400, GCP Architect/DevOps… ¿é í ? Que tengas al menos 4 añitos de experiencia como DevOps Engineer y conocimientos en migración de CI/CD de GitLabCI a GitHubActions (Ojo, que si no llegas a los 4 años y es algo menos, te escucharemos igual ) Lo que queremos es ver tus ganas de aportar, aprender, crecer y de entrar a formar parte de proyectos estables, dinámicos y que sean un reto para ti: • Liderar el diseño y la ejecución del proyecto de migración de GitLab a GitHub, definiendo arquitectura objetivo, estrategia, fases, riesgos y plan de adopción. • Responsabilizarse de la migración de pipelines CI/CD y operativa, asegurando continuidad, seguridad y calidad (GitLab CI → GitHub Actions). • Diseñar y mantener pipelines CI/CD y prácticas DevOps/DevSecOps en entornos cloud, automatizando builds, tests, despliegues e infraestructura (IaC). • Coordinarse con equipos de desarrollo, cloud y seguridad, estableciendo estándares, documentación y buenas prácticas para la operación en GitHub. • También debe tener capacidad de análisis y benchmarking para toma de decisiones de herramientas. Es un PLUS si cuentas con experiencia en: • Migraciones con otras tecnologías de CI/CD a GitHubActions En knowmad mood utilizamos la tecnología para estar cerca, nos profesionalizamos, investigamos, creamos y vendemos nuestras propias creaciones, nos certificamos, realizamos eventos, nos y por supuesto, para ayudar a impulsar y hacer realidad los proyectos de nuestros clientes. ¿Qué más puedes hacer con nosotros? « Si aún no te ves capaz de tener una conversación con el rey Carlos III puedes llegar hasta ese nivel con é. « Sabemos que te gusta comer en restaurantes y que a veces no vas para no gastar tanto dinero. Con la ó en tickets restaurante podrás ahorrarte unos eurillos. También en cheques guardería, tarjeta de transporte y seguro médico. « El ir a trabajar no es solo mirar correos y atender peticiones. ¿Te imaginas hacer un scape room virtual con tus compañeros o unirte a un club de ajedrez? Durante todo el año hacemos actividades de para todos los gustos. « Si tienes un amigo del que no puedes despegarte, ¡haz que se una a la knowmad mood family !. Si crees que encaja en alguno de nuestros perfiles y se une a nosotros tendrás un premio « ¡Los eventos son lo nuestro! Tenemos dos grandes congresos además de webinars, formaciones internas hechas por técnicos de knowmad mood o meetups. « ¡Ah! Se nos olvidaba decirte que Los Reyes Magos también se pasan por knowmad mood... En knowmad mood nos comprometemos con la igualdad de oportunidades y el respeto a la diversidad. Aplicamos nuestro Plan de Igualdad y el principio de no discriminación en todos nuestros procesos de selección. To apply: https://weworkremotely.com/remote-jobs/knowmad-mood-senior-devops-engineer-migraciones-ci-cd-remoto-100

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Senior DevOps Engineer - CI/CD Migrations (100% Remote)

[company_profile]
Knowmad Mood

[location]
Anywhere in the World

[description]
Headquarters: Calle Jacinto Benavente, 2 Las Rozas de Madrid, Spain, 28232 Spain Hello! We know that, yes, don't deny it, you are exploring new projects, offers and companies, something you would like to change. We would like you, in this job offer, to address directly the responsibilities, knowledge, and all those things that we are looking for from you. Because first we want to introduce ourselves... First of all, second of all, we are tekkies, we like, even if it has nothing to do with our job, those geeky news that eat up our hours watching on YouTube, on Twitch, on Tik Tok, Gitlab or wherever. In the mornings we get up, we have a coffee, and we don't start the computer with palpitations, but rather happy, eager to start the day, to work with the people on your team and all those with whom we are in contact every day. That is our first promise, á. The hours will fly by, doing what you are passionate about doing. hey? First of all, we are a Microsoft Gold Partner with 5 competencies: - Gold Application Development - Gold Cloud Platform - Gold Application Integration - Silver DevOps - Silver Data Analytics Apart from this we have agreements with Google Cloud at the PartnertShip Advantage level and AWS as a Strategic Partner... ´ ! ️ As a picture is worth a thousand words, we share this video so you can see what it is like to live in knowmad mood: https://www.youtube.com/watch?v=PHn3vImdA7I&feature=youtu.be In addition, we work for 14 of the IBEX-35 companies and develop internal innovation projects, but ! ️ In addition, we offer you great possibilities in career plans, training and certification to grow professionally. Flexible Hours Work Friday afternoons? Nothing of that, in knowmad mood the nap is respected

July and August intensive day, summer is here to enjoy! Training and Career Plan Trainings: Red Hat Academy, Docker, Ansible, Udemy For Business & Cloud Guru / Bootcamps: K8S, ELK for Kubernetes, Openshift… TOP Certifications: AWS DevOps/Architect, CKA/CKS, AZ104, AZ400, GCP Architect/DevOps… is it? That you have at least 4 years of experience as a DevOps Engineer and knowledge in CI/CD migration from GitLabCI to GitHubActions (Be careful, if you don't reach 4 years and it's a little less, we'll listen to you anyway). What we want is to see your desire to contribute, learn, grow and become part of stable, dynamic projects that are a challenge for you: • Lead the design and execution of the migration project from GitLab to GitHubActions. GitHub, defining target architecture, strategy, phases, risks and adoption plan. • Be responsible for the migration of CI/CD and operational pipelines, ensuring continuity, security and quality (GitLab CI → GitHub Actions). • Design and maintain CI/CD pipelines and DevOps/DevSecOps practices in cloud environments, automating builds, tests, deployments and infrastructure (IaC). • Coordinate with development, cloud and security teams, establishing standards, documentation and good practices for operation on GitHub. • It must also have analysis and benchmarking capacity for tool decision making. It is a PLUS if you have experience in: • Migrations with other CI/CD technologies to GitHubActions At knowmad mood we use technology to be close, we professionalize, we research, we create and sell our own creations, we get certified, we hold events, and of course, to help promote and make our clients' projects a reality. What else can you do with us? «

If you still don't feel capable of having a conversation with King Charles III, you can reach that level with him. « We know that you like to eat in restaurants and that sometimes you don't go to avoid spending so much money. With the or on restaurant tickets you can save a few euros. Also in daycare checks, transportation card and medical insurance. «Going to work is not just checking emails and responding to requests. Can you imagine doing a virtual escape room with your classmates or joining a chess club? Throughout the year we do activities for all tastes. «If you have a friend you can't let go of, make him join the knowmad mood family! If you think you fit one of our profiles and join us you will have a prize «Events are our thing! We have two large conferences in addition to webinars, internal training done by knowmad mood technicians or meetups. «Ah! We forgot to tell you that The Three Wise Men also go through knowmad mood... At knowmad mood we are committed to equal opportunities and respect for diversity. We apply our Equality Plan and the principle of non-discrimination in all our selection processes. To apply: https://weworkremotely.com/remote-jobs/knowmad-mood-senior-devops-engineer-migraciones-ci-cd-remoto-100

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #7 | Product Owner (m/f)
- source: we_work_remotely_rss
- detected_language: it (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/iungo-spa-product-owner-m-f
- apply_url: https://weworkremotely.com/remote-jobs/iungo-spa-product-owner-m-f

,field,original,translated,changed
0,title,Product Owner (m/f),Product Owner (m/f),False
1,company_profile,Iungo Spa,Iungo Spa,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Via Tacito, 7, 41123 Modena MO, Italia Descrizione dell'azienda Contratto: Tempo indeterminato full-time Modalità di lavoro: Remote First RAL: 40.000€ - 45.000€ P...","Headquarters: Via Tacito, 7, 41123 Modena MO, Italy Company description Contract: Full-time permanent Work method: Remote First RAL: €40,000 - €45,000 Benefit package: Welfare ...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full Time,True
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Product Owner (m/f)

[company_profile]
Iungo Spa

[location]
Anywhere in the World

[description]
Headquarters: Via Tacito, 7, 41123 Modena MO, Italia Descrizione dell'azienda Contratto: Tempo indeterminato full-time Modalità di lavoro: Remote First RAL: 40.000€ - 45.000€ Pacchetto Benefit: Portafoglio welfare su piattaforma Coverflex con min. 1.355€, max 2.355 € Buoni pasto da € 8,00 per giornata lavorata (anche in remote) Assicurazione sanitaria Accesso illimitato a piattaforme di formazione Corso di inglese in orario di lavoro La nostra azienda è leader di mercato nell’offrire soluzioni per migliorare la Supply Chain Collaboration, grazie all’eccellenza delle innovative soluzioni software IUNGO. Nata da uno spin-off della Facoltà di Ingegneria dell’Università di Modena e Reggio Emilia, IUNGO possiede 2 brevetti internazionali, 415 clienti e 75.000 fornitori attivati in 44 Paesi del mondo. Il prodotto IUNGO permette di automatizzare processi di acquisto ed integrare fornitori differenti, garantendo efficiente modalità di comunicazione tra cliente e fornitore. Questo potenzia l’intero processo di supply chain, che diventa collaborativo attraverso l’integrazione di sistemi di clienti e fornitori. Descrizione del lavoro In ottica di evoluzione della piattaforma IUNGO e di rafforzamento metodologico dell’area Solutions, cerchiamo un Product Owner , che possa far parte di un team di Product Management ed R&D in crescita con il proprio entusiasmo e motivazione. Si avrà l’opportunità di lavorare all’intero ciclo di ideazione, creazione e lancio, di una nuova suite di prodotti contribuendo anche a favorire la transizione dal sistema legacy a sistemi tecnologici innovativi, per rispondere alle esigenze in continua evoluzione del mercato di riferimento, della tecnologia e delle normative di settore. Qualifiche Responsabilità Principali Definizione della Product Vision : Collaborare con il management per allineare gli obiettivi di business con le necessità degli utenti. Market & Customer Research : Analizzare il mercato, i competitor e i trend di settore. Condurre interviste con gli utenti per identificare problemi reali da risolvere. Gestione del Backlog : Creare, ordinare e dare priorità alle User Story, assicurandosi che il team di sviluppo abbia sempre chiaro il lavoro da svolgere. Massimizzazione del Valore : Prendere decisioni critiche su quali funzionalità sviluppare per garantire il massimo ROI (Return on Investment). Analisi dei Dati e KPI: Definire e monitorare le metriche di successo per guidare le decisioni basate sui dati. Interfaccia con gli Stakeholder: Raccogliere feedback, gestire le aspettative e comunicare lo stato di avanzamento del prodotto a clienti o reparti interni (marketing, vendite, etc.), affiancamento alla vendita e pre-vendita o alla messa a terra del progetto su cliente acquisito. Gestione progetti pilota: Coordinare i primi progetti sui clienti per validare il prodotto/servizio e definire la modalità migliore per raggiungere gli obiettivi del cliente. Qualifiche Esperienza Pregressa nel ruolo di Product Owner o Product Manager, preferibilmente in contesti software/SaaS. Capacità Analitiche e di sintesi: Abilità nel tradurre requisiti di business complessi in specifiche tecniche semplici e attuabili. Soft Skills: Eccellenti doti comunicative, attitudine al problem solving, capacità di interfacciarsi con interlocutori diversi sia interni che esterni all’azienda Conoscenza Strumenti e Processi: Utilizzo di tool di gestione progetto come Jira, Confluence o similari e familiarità con la metodologia Agile. Nice-to-Have Public Speaking: Capacità di rappresentare il prodotto in conferenze, webinar o presentazioni ai grandi clienti. Esperienza in ambito Supply-Chain Esperienza in Growth Hacking : Conoscenza di tecniche per l'acquisizione e l'attivazione rapida degli utenti. Conoscenza delle metodologie di Problem-solving , come ad esempio Design Thinking Esperienza in t eam di lavoro cross-funzionali (es: User Experience designer, Data engineer, Developer, Architect, Sales & Marketing) Ulteriori informazioni Cosa non ci interessa sapere: • Tutto ciò che non riguarda strettamente le tue competenze come stato famigliare o coniugale, religione, orientamento sessuale, genere, aspetto fisico etc Le differenze in IUNGO sono accolte e preservate per la creazione di opportunità e crescita comune IUNGO: WELCOME, SHARE, ENJOY! “Porta le tue idee: sono le benvenute. Condividi il tuo talento: lo nutriremo assieme. Goditi il viaggio con noi.” Nella nostra azienda potrai vivere e lavorare in una squadra accogliente, all’interno della quale il tuo talento può esplodere e le tue idee possono brillare. Una cultura basata su feedback trasparente (Appraisal 360°), piani formativi personalizzati per la tua carriera e attenzione al benessere personale (survey periodiche, eventi di team building, gite e momenti di relax insieme). To apply: https://weworkremotely.com/remote-jobs/iungo-spa-product-owner-m-f

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Product Owner (m/f)

[company_profile]
Iungo Spa

[location]
Anywhere in the World

[description]
Headquarters: Via Tacito, 7, 41123 Modena MO, Italy Company description Contract: Full-time permanent Work method: Remote First RAL: €40,000 - €45,000 Benefit package: Welfare portfolio on Coverflex platform with min. €1,355, max €2,355 Meal vouchers from €8.00 per day worked (even remotely) Health insurance Unlimited access to training platforms English course during working hours Our company is a market leader in offering solutions to improve Supply Chain Collaboration, thanks to the excellence of the innovative IUNGO software solutions. Born from a spin-off of the Faculty of Engineering of the University of Modena and Reggio Emilia, IUNGO owns 2 international patents, 415 customers and 75,000 suppliers activated in 44 countries around the world. The IUNGO product allows you to automate purchasing processes and integrate different suppliers, ensuring efficient communication between customer and supplier. This enhances the entire supply chain process, which becomes collaborative through the integration of customer and supplier systems. Job description With a view to evolving the IUNGO platform and methodologically strengthening the Solutions area, we are looking for a Product Owner who can be part of a growing Product Management and R&D team with his own enthusiasm and motivation. You will have the opportunity to work on the entire cycle of conception, creation and launch of a new suite of products, also helping to facilitate the transition from the legacy system to innovative technological systems, to respond to the constantly evolving needs of the reference market, technology and sector regulations. Qualifications Main Responsibilities Definition of the Product Vision:

Collaborate with management to align business objectives with user needs. Market & Customer Research: Analyze the market, competitors and sector trends. Conduct user interviews to identify real problems to solve. Backlog Management: Create, order and prioritize User Stories, ensuring that the development team is always clear on the work to be done. Value Maximization: Make critical decisions on which features to develop to ensure maximum ROI (Return on Investment). Data Analytics and KPIs: Define and monitor success metrics to drive data-driven decisions. Interface with Stakeholders: Collect feedback, manage expectations and communicate the progress of the product to customers or internal departments (marketing, sales, etc.), support in sales and pre-sales or in the implementation of the project on an acquired customer. Pilot project management: Coordinate the first customer projects to validate the product/service and define the best way to achieve the customer's objectives. Qualifications Previous experience in the role of Product Owner or Product Manager, preferably in software/SaaS contexts. Analytical and Synthesis Skills: Ability to translate complex business requirements into simple, actionable technical specifications. Soft Skills: Excellent communication skills, aptitude for problem solving, ability to interface with different interlocutors both internal and external to the company Knowledge of Tools and Processes: Use of project management tools such as Jira, Confluence or similar and familiarity with the Agile methodology. Nice-to-Have Public Speaking: Ability to represent the product at conferences, webinars or

presentations to major clients. Experience in Supply-Chain Experience in Growth Hacking: Knowledge of techniques for rapid user acquisition and activation. Knowledge of Problem-solving methodologies, such as Design Thinking Experience in cross-functional work teams (e.g. User Experience designer, Data engineer, Developer, Architect, Sales & Marketing) Further information What we are not interested in knowing: • Everything that does not strictly concern your skills such as family or marital status, religion, sexual orientation, gender, physical appearance etc. Differences in IUNGO are welcomed and preserved for the creation of opportunities and common growth IUNGO: WELCOME, SHARE, ENJOY! "Bring your ideas: they are welcome. Share your talent: we will nurture it together. Enjoy the journey with us." In our company you will be able to live and work in a welcoming team, within which your talent can explode and your ideas can shine. A culture based on transparent feedback (Appraisal 360°), personalized training plans for your career and attention to personal well-being (periodic surveys, team building events, trips and moments of relaxation together). To apply: https://weworkremotely.com/remote-jobs/iungo-spa-product-owner-m-f

[employment_type]
Full Time

[industry]
Full-Stack Programming

---

### #8 | Product Owner Zendesk Customer Service (m/w/d) // remote möglich
- source: we_work_remotely_rss
- detected_language: de (confidence=0.85)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/e-breuninger-co-product-owner-zendesk-customer-service-m-w-d-remote-moglich
- apply_url: https://weworkremotely.com/remote-jobs/e-breuninger-co-product-owner-zendesk-customer-service-m-w-d-remote-moglich

,field,original,translated,changed
0,title,Product Owner Zendesk Customer Service (m/w/d) // remote möglich,Product Owner Zendesk Customer Service (m/f/d) // possible remotely,True
1,company_profile,E. Breuninger& Co.,E. Breuninger & Co.,True
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Stuttgart, Deutschland Unternehmensbeschreibung Fashion und Lifestyle, 6.500 Mitarbeiter:innen, 13 Department Stores, Online-Shops in Deutschland, Polen, Österrei...","Headquarters: Stuttgart, Germany Company description Fashion and lifestyle, 6,500 employees, 13 department stores, online shops in Germany, Poland, Austria, Belgium, Luxembourg...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full time,True
8,required_experience,,,False
9,required_education,,,False
10,industry,Product,Product,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Product Owner Zendesk Customer Service (m/w/d) // remote möglich

[company_profile]
E. Breuninger& Co.

[location]
Anywhere in the World

[description]
Headquarters: Stuttgart, Deutschland Unternehmensbeschreibung Fashion und Lifestyle, 6.500 Mitarbeiter:innen, 13 Department Stores, Online-Shops in Deutschland, Polen, Österreich, Belgien, Luxemburg, Spanien, Italien, Tschechien, den Niederlanden und der Schweiz, über 2.000 Marken, 25 Restaurants & Confiserien, 15 erstklassige Services, drei Friseur-Salons und stets ein besonderes Einkaufserlebnis – das ist Breuninger. Ein Traditionsunternehmen, das internationale Wege geht, seine Ziele klar definiert und innovative Möglichkeiten schafft. Stellenbeschreibung Wer wir sind: Technologischer Taktgeber für exzellenten Service In unserer Abteilung Customer Service Services (CSS) sind wir der technologische Taktgeber für den Kundenservice bei Breuninger. Unser Ziel: Wir bauen die technische Infrastruktur, die unsere Kolleg:innen befähigt, Kundenbegeisterung auf Breuninger-Niveau zu erzeugen. Wir administrieren, konfigurieren und orchestrieren die Tools von morgen – von der Telefonie bis zur KI – und schaffen damit einzigartige Kundenerlebnisse. Deine Mission: Bauen, Steuern und Begeistern Du bist weit mehr als ein:e Administrator:in – Du bist der:die Botschafter:in Deiner Produkte. Du nimmst strategische Leitplanken, sowie operative Problemstellungen auf und übersetzt sie eigenständig in exzellente technologische Lösungen. Du liebst es, tief in die Konfiguration einzutauchen, hältst aber gleichzeitig die Fahne für Deine Produkte hoch und steckst andere mit Deiner Begeisterung für neue Features an. Damit bist Du ein wesentlicher Teil der digitalen Transformation des Customer Service. End-to-End Konfiguration : Du verantwortest die Administration und Weiterentwicklung unserer Low-Code-Produkte (z. B. Zendesk, Babelforce). Du hast Freude daran, „unter die Haube“ zu schauen und Prozesse technisch perfekt abzubilden. Product Evangelism : Du machst Lust auf das Produkt! Du vermarktest neue Funktionen intern, begeisterst die User:innen für Deine Lösungen und sorgst für eine hohe Akzeptanz und Freude an der Nutzung. Demand- & Stakeholder-Management : Du nimmst Anforderungen aus den Operations auf, priorisierst diese und orchestrierst IT-Schnittstellen und externe Partner bei Bedarf. KI-Pionierarbeit : Du spielst eine zentrale Rolle bei der Auswahl und Implementierung von KI-Komponenten. Du beherrschst Prompting und optimierst unsere Systeme für maximale Effizienz. Projektsteuerung : Du leitest (Teil-)Projekte von der Marktanalyse bis zum Go-Live und sorgst dafür, dass das "perfekte Produkt" für den Kundenservice entsteht. Das „Breuninger-Plus“ für Dich: Gestaltungsspielraum: Wir bieten Dir eine zentrale Rolle bei der technologischen Transformation – inklusive der Freiheit, Deine Rolle nach Deinen Stärken (Strategie vs. Technik) mitzugestalten. Qualifikationen Erfahrung und Background : Du verfügst über mehrjährige Erfahrung als Product/Business Owner:in oder eine vergleichbare Tätigkeit und bist es gewohnt, in einem sich schnell wandelnden E-Commerce Umfeld agil und innovativ zu arbeiten. Qualifikation : Ein abgeschlossenes Studium im Bereich Betriebswirtschaft oder Wirtschaftsinformatik ist von Vorteil. Tool-Expertise & Leidenschaft : Du hast fundierte Erfahrung in der Konfiguration und Administration von Ticket- oder Telefonie-Systemen im Customer Service (z. B. Zendesk, Babelforce) und brennst darauf, diese technologisch auf das nächste Level zu heben. Steuerung : Du hast Erfahrung in der eigenverantwortlichen Steuerung von Produktweiterentwicklungen oder vergleichbarer Projekte und bist in der Lage externe Partner und Stakeholder zu orchestrieren. Technisches Mindset : Du liebst Low-Code/No-Code-Tools und hast eine hohe Affinität für KI-Lösungen und modernes Prompting. Mindset eines digitalen Gastgeber:in: Du trägst die Verantwortung, dass Dein Produkt nicht nur reibungslos funktioniert, sondern interne und externe Kunden an jedem Kontaktpunkt begeistert werden. Zusätzliche Informationen Bei Breuninger geht es um mehr als einen Job. Wir leben Wertschätzung und Verantwortung – und genau das spiegeln unsere Benefits wieder. Sie sind ein Zeichen dafür, wie wir Dich begleiten und unterstützen. Und das Beste: Dies ist nur ein Teil dessen, was Dich bei uns erwartet. Wertschätzung, die spürbar ist Freiwilliges Urlaubs- und Weihnachtsgeld sowie Zuschüsse zur Altersvorsorge. Dein Stil, Dein Vorteil 30 % Mitarbeitendenrabatt, auch für Deine:n Partner:in, inklusive Gastronomie und Friseur. Deine Treue zählt Ab dem 5. Jahr erhältst Du zusätzliche Urlaubstage. Sport-Life-Balance Zuschuss zu Deiner Urban Sports Mitgliedschaft. Wachse mit uns Von Trainings bis zu Führungsprogrammen. Workation available Bis zu 30 Kalendertage im Jahr in ausgewählten europäischen Ländern. Urlaub à la carte Über Gehaltsumwandlung kannst Du Dir zusätzliche Urlaubstage sichern, ergänzt durch Sabbatical-Option. Mobil im Alltag Mit Company Bike Dein Wunschrad oder E-Bike unkompliziert leasen. Haben wir Dein Interesse geweckt? Dann sollten wir uns schnell kennenlernen. Bei Fragen steht Dir Sabrina Rösch gerne jederzeit zur Verfügung. Wir freuen uns auf Deine aussagekräftige Online Bewerbung mit Angabe Deiner Verfügbarkeit sowie Gehaltsvorstellung. Bewerbungen per E-Mail können aus Datenschutzgründen nicht verarbeitet werden. Nutze daher bitte ausschließlich unser Online-Bewerbungssystem . Impressum To apply: https://weworkremotely.com/remote-jobs/e-breuninger-co-product-owner-zendesk-customer-service-m-w-d-remote-moglich

[employment_type]
Full-Time

[industry]
Product

**Translated Full Posting Text**

[title]
Product Owner Zendesk Customer Service (m/f/d) // possible remotely

[company_profile]
E. Breuninger & Co.

[location]
Anywhere in the World

[description]
Headquarters: Stuttgart, Germany Company description Fashion and lifestyle, 6,500 employees, 13 department stores, online shops in Germany, Poland, Austria, Belgium, Luxembourg, Spain, Italy, the Czech Republic, the Netherlands and Switzerland, over 2,000 brands, 25 restaurants & confectioneries, 15 first-class services, three hairdressing salons and always a special shopping experience - that is Breuninger. A traditional company that follows international paths, clearly defines its goals and creates innovative opportunities. Job description Who we are: Technological pacesetter for excellent service In our Customer Service Services (CSS) department, we are the technological pacesetter for customer service at Breuninger. Our goal: We build the technical infrastructure that enables our colleagues to generate customer enthusiasm at Breuninger levels. We administer, configure and orchestrate the tools of tomorrow - from telephony to AI - and thereby create unique customer experiences. Your mission: Build, control and inspire You are much more than an administrator – you are the ambassador of your products. You take strategic guidelines and operational problems and independently translate them into excellent technological solutions. You love diving deep into the configuration, but at the same time you keep the flag high for your products and infect others with your enthusiasm for new features. This makes you an essential part of the digital transformation of customer service. End-to-end configuration: You are responsible for the administration and further development of our low-code products (e.g. Zendesk, Babelforce). You enjoy looking “under the hood” and

To represent processes technically perfectly. Product Evangelism: You make people want the product! You market new functions internally, get users excited about your solutions and ensure a high level of acceptance and enjoyment of use. Demand & stakeholder management: You record requirements from operations, prioritize them and orchestrate IT interfaces and external partners if necessary. AI pioneering work: You play a central role in the selection and implementation of AI components. You master prompting and optimize our systems for maximum efficiency. Project management: You manage (sub-)projects from market analysis to go-live and ensure that the “perfect product” is created for customer service. The “Breuninger Plus” for you: Freedom of design: We offer you a central role in technological transformation - including the freedom to help shape your role according to your strengths (strategy vs. technology). Qualifications Experience and background: You have several years of experience as a product/business owner or a comparable position and are used to working agile and innovatively in a rapidly changing e-commerce environment. Qualifications: A completed degree in business administration or business information technology is an advantage. Tool expertise & passion: You have in-depth experience in the configuration and administration of ticket or telephony systems in customer service (e.g. Zendesk, Babelforce) and are eager to take them to the next level technologically. Control: You have experience in independently managing product developments or comparable projects and are able to manage external partners and stakeholders

orchestrate. Technical Mindset: You love low-code/no-code tools and have a high affinity for AI solutions and modern prompting. Mindset of a digital host: You are responsible for ensuring that your product not only functions smoothly, but that internal and external customers are impressed at every point of contact. Additional information At Breuninger it is about more than a job. We live by appreciation and responsibility – and that’s exactly what our benefits reflect. They are a sign of how we accompany and support you. And best of all: This is only part of what awaits you with us. Appreciation that can be felt Voluntary vacation and Christmas bonuses as well as subsidies for retirement provision. Your style, your advantage 30% employee discount, also for your partner, including restaurants and hairdressers. Your loyalty counts From the 5th year you will receive additional vacation days. Sport-Life-Balance subsidy for your Urban Sports membership. Grow with us From training to leadership programs. Workation available Up to 30 calendar days per year in selected European countries. Vacation à la carte You can secure additional vacation days via salary conversion, supplemented by a sabbatical option. Mobile in everyday life Easily lease your dream bike or e-bike with Company Bike. Have we piqued your interest? Then we should get to know each other quickly. If you have any questions, Sabrina Rösch will be happy to help you at any time. We look forward to receiving your detailed online application stating your availability and salary expectations. Applications via email cannot be processed for data protection reasons. Please only use our online application system. Imprint To apply:

https://weworkremotely.com/remote-jobs/e-breuninger-co-product-owner-zendesk-customer-service-m-w-d-remote-possible

[employment_type]
Full time

[industry]
Product

---

### #9 | Senior Product Analyst, Remote
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/aledade-senior-product-analyst-remote
- apply_url: https://weworkremotely.com/remote-jobs/aledade-senior-product-analyst-remote

,field,original,translated,changed
0,title,"Senior Product Analyst, Remote","Senior Product Analyst, Remote",False
1,company_profile,Aledade,Aledade,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Bethesda, MD As a Product Analyst you will be a key supporting member of the teams responsible for ingesting data from our payer partners; specifically, medical a...","Headquarters: Bethesda, MD As a Product Analyst you will be a key supporting member of the teams responsible for ingesting data from our payer partners; specifically, medical a...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Product,Product,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Product Analyst, Remote

[company_profile]
Aledade

[location]
Anywhere in the World

[description]
Headquarters: Bethesda, MD As a Product Analyst you will be a key supporting member of the teams responsible for ingesting data from our payer partners; specifically, medical and pharmacy claims, patient eligibility, and care gaps data. The Analyst will work alongside the product team members and engineers to triage and investigate issues, provide operational support for data exchange, assist in data analysis and requirements gathering to support new integrations. Product Analysts participate in sprint planning and ceremonies alongside the product and engineering team members. This role will serve as a key interface between the product and engineering teams and internal teams that work directly with practices to ensure data accuracy and timeliness. As a Product Analyst, you will report to and be mentored by a Senior Product Manager at Aledade. You’ll be hands-on with our payer ingestion data while developing tangential skills. If you’re a data expert with a healthcare background and are interested in working directly with the teams building data ingestion pipelines, this is the role for you. Primary Duties: First line of defense on data quality and accuracy issues with existing payer data ingestion feeds. This includes triage, prioritization, and communication of issues. Provide operational support needed to ensure continuity of data exchange between Aledade and payer partners. Assist in data analysis requests to support net new integrations and investigate investments for new data-based projects. Assist in the product team in gathering requirements and creating specifications for new payer data feeds. Minimum Qualifications: Bachelor’s degree in related field or 4+ years of healthcare data experience, preferably with claims data. Proficient in SQL, able to write complex queries making use of sub-queries, unions and CTEs. Preferred Qualifications: Experience in triaging and prioritizing operations related data issues and developing processes to support resolution and tracking. Preferably in healthcare data. Experience using data and primary research to inform business decision making. Excellent organizational and communication skills, with an emphasis on problem-solving, prioritization, and building subject matter expertise. Experience participating in Agile / Scrum teams or using Agile methodology/concepts in product development Experience with data, data structures (e.g. relational databases), relevant or similar analytics platforms and tech stacks (e.g. Tableau, Snowflake, ETL, healthcare data sets, etc). Experience with and understanding of the software development lifecycle and software development methodologies. Experience with project management tools like JIRA or Trello. Knowledge of alternative payment models related to primary care such as MSSP ACOs, Pioneer ACOs, commercial insurance shared savings programs, PCMH. Experience with basic quality assurance testing processes. Who We Are: Aledade, a public benefit corporation, exists to empower the most transformational part of our health care landscape - independent primary care. We were founded in 2014, and since then, we've become the largest network of independent primary care in the country - helping practices, health centers and clinics deliver better care to their patients and thrive in value-based care. Additionally, by creating value-based contracts across a wide variety of health plans, we aim to flip the script on the traditional fee-for-service model. Our work strengthens continuity of care, aligns incentives and ensures primary care physicians are paid for what they do best - keeping patients healthy. If you want to help create a health care system that is good for patients, good for practices and good for society - and if you're eager to join a collaborative, inclusive and remote-first culture - you've come to the right place. What Does This Mean for You? At Aledade, you will be part of a creative culture that is driven by a passion for tackling complex issues with respect, open-mindedness and a desire to learn. You will collaborate with team members who bring a wide range of experiences, interests, backgrounds, beliefs and achievements to their work - and who are all united by a shared passion for public health and a commitment to the Aledade mission. In addition to time off to support work-life balance and enjoyment, we offer the following comprehensive benefits package designed for the overall well-being of our team members: Flexible work schedules and the ability to work remotely are available for many roles Health, dental and vision insurance paid up to 80% for employees, dependents and domestic partners Robust time-off plan (21 days of PTO in your first year) Two paid volunteer days and 11 paid holidays 12 weeks paid parental leave for all new parents Six weeks paid sabbatical after six years of service Educational Assistant Program and Clinical Employee Reimbursement Program 401(k) with up to 4% match Stock options And much more! At Aledade, we don’t just accept differences, we celebrate them! We strive to attract, develop and retain highly qualified individuals representing the diverse communities where we live and work. Aledade is committed to creating a diverse environment and is proud to be an equal opportunity employer. Employment policies and decisions at Aledade are based on merit, qualifications, performance and business needs. All qualified candidates will receive consideration for employment without regard to age, race, color, national origin, gender (including pregnancy, childbirth or medical conditions related to pregnancy or childbirth), gender identity or expression, religion, physical or mental disability, medical condition, legally protected genetic information, marital status, veteran status, or sexual orientation. Privacy Policy: By applying for this job, you agree to Aledade's Applicant Privacy Policy available at https://www.aledade.com/privacy-policy-applicants We may use automated tools, including artificial intelligence (AI), to help organize and evaluate application materials. These tools support our recruiters and hiring managers by helping manage large applicant pools. Human judgment plays an essential role in our hiring process, including in the oversight and use of any automated tools. If you would like more information about our screening and hiring process, please contact us. To apply: https://weworkremotely.com/remote-jobs/aledade-senior-product-analyst-remote

[employment_type]
Full-Time

[industry]
Product

**Translated Full Posting Text**

[title]
Senior Product Analyst, Remote

[company_profile]
Aledade

[location]
Anywhere in the World

[description]
Headquarters: Bethesda, MD As a Product Analyst you will be a key supporting member of the teams responsible for ingesting data from our payer partners; specifically, medical and pharmacy claims, patient eligibility, and care gaps data. The Analyst will work alongside the product team members and engineers to triage and investigate issues, provide operational support for data exchange, assist in data analysis and requirements gathering to support new integrations. Product Analysts participate in sprint planning and ceremonies alongside the product and engineering team members. This role will serve as a key interface between the product and engineering teams and internal teams that work directly with practices to ensure data accuracy and timeliness. As a Product Analyst, you will report to and be mentored by a Senior Product Manager at Aledade. You’ll be hands-on with our payer ingestion data while developing tangential skills. If you’re a data expert with a healthcare background and are interested in working directly with the teams building data ingestion pipelines, this is the role for you. Primary Duties: First line of defense on data quality and accuracy issues with existing payer data ingestion feeds. This includes triage, prioritization, and communication of issues. Provide operational support needed to ensure continuity of data exchange between Aledade and payer partners. Assist in data analysis requests to support net new integrations and investigate investments for new data-based projects. Assist in the product team in gathering requirements and creating specifications for new payer data feeds. Minimum Qualifications: Bachelor’s degree in related field or 4+ years of healthcare data experience, preferably with claims data. Proficient in SQL, able to write complex queries making use of sub-queries, unions and CTEs. Preferred Qualifications: Experience in triaging and prioritizing operations related data issues and developing processes to support resolution and tracking. Preferably in healthcare data. Experience using data and primary research to inform business decision making. Excellent organizational and communication skills, with an emphasis on problem-solving, prioritization, and building subject matter expertise. Experience participating in Agile / Scrum teams or using Agile methodology/concepts in product development Experience with data, data structures (e.g. relational databases), relevant or similar analytics platforms and tech stacks (e.g. Tableau, Snowflake, ETL, healthcare data sets, etc). Experience with and understanding of the software development lifecycle and software development methodologies. Experience with project management tools like JIRA or Trello. Knowledge of alternative payment models related to primary care such as MSSP ACOs, Pioneer ACOs, commercial insurance shared savings programs, PCMH. Experience with basic quality assurance testing processes. Who We Are: Aledade, a public benefit corporation, exists to empower the most transformational part of our health care landscape - independent primary care. We were founded in 2014, and since then, we've become the largest network of independent primary care in the country - helping practices, health centers and clinics deliver better care to their patients and thrive in value-based care. Additionally, by creating value-based contracts across a wide variety of health plans, we aim to flip the script on the traditional fee-for-service model. Our work strengthens continuity of care, aligns incentives and ensures primary care physicians are paid for what they do best - keeping patients healthy. If you want to help create a health care system that is good for patients, good for practices and good for society - and if you're eager to join a collaborative, inclusive and remote-first culture - you've come to the right place. What Does This Mean for You? At Aledade, you will be part of a creative culture that is driven by a passion for tackling complex issues with respect, open-mindedness and a desire to learn. You will collaborate with team members who bring a wide range of experiences, interests, backgrounds, beliefs and achievements to their work - and who are all united by a shared passion for public health and a commitment to the Aledade mission. In addition to time off to support work-life balance and enjoyment, we offer the following comprehensive benefits package designed for the overall well-being of our team members: Flexible work schedules and the ability to work remotely are available for many roles Health, dental and vision insurance paid up to 80% for employees, dependents and domestic partners Robust time-off plan (21 days of PTO in your first year) Two paid volunteer days and 11 paid holidays 12 weeks paid parental leave for all new parents Six weeks paid sabbatical after six years of service Educational Assistant Program and Clinical Employee Reimbursement Program 401(k) with up to 4% match Stock options And much more! At Aledade, we don’t just accept differences, we celebrate them! We strive to attract, develop and retain highly qualified individuals representing the diverse communities where we live and work. Aledade is committed to creating a diverse environment and is proud to be an equal opportunity employer. Employment policies and decisions at Aledade are based on merit, qualifications, performance and business needs. All qualified candidates will receive consideration for employment without regard to age, race, color, national origin, gender (including pregnancy, childbirth or medical conditions related to pregnancy or childbirth), gender identity or expression, religion, physical or mental disability, medical condition, legally protected genetic information, marital status, veteran status, or sexual orientation. Privacy Policy: By applying for this job, you agree to Aledade's Applicant Privacy Policy available at https://www.aledade.com/privacy-policy-applicants We may use automated tools, including artificial intelligence (AI), to help organize and evaluate application materials. These tools support our recruiters and hiring managers by helping manage large applicant pools. Human judgment plays an essential role in our hiring process, including in the oversight and use of any automated tools. If you would like more information about our screening and hiring process, please contact us. To apply: https://weworkremotely.com/remote-jobs/aledade-senior-product-analyst-remote

[employment_type]
Full-Time

[industry]
Product

---

### #10 | Product Manager
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/welocalize-product-manager
- apply_url: https://weworkremotely.com/remote-jobs/welocalize-product-manager

,field,original,translated,changed
0,title,Product Manager,Product Manager,False
1,company_profile,Welocalize,Welocalize,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Mexico / United States Welo Data works with technology companies to provide datasets that are high-quality, ethically sourced, relevant, diverse, and scalable to ...","Headquarters: Mexico / United States Welo Data works with technology companies to provide datasets that are high-quality, ethically sourced, relevant, diverse, and scalable to ...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Product Manager

[company_profile]
Welocalize

[location]
Anywhere in the World

[description]
Headquarters: Mexico / United States Welo Data works with technology companies to provide datasets that are high-quality, ethically sourced, relevant, diverse, and scalable to supercharge their AI models. As a Welocalize brand, WeloData leverages over 25 years of experience in partnering with the world’s most innovative companies and brings together a curated global community of over 500,000 AI training and domain experts to offer services that span: ANNOTATION & LABELLING: Transcription, summarization, image and video classification and labeling. ENHANCING LLMs: Prompt engineering, SFT, RLHF, red teaming and adversarial model training, model output ranking. DATA COLLECTION & GENERATION: From institutional languages to remote field audio collection. RELEVANCE & INTENT: Culturally nuanced and aware, ranking, relevance, and evaluation to train models for search, ads, and LLM output. Want to join our Welo Data team? We bring practical, applied AI expertise to projects. We have both strong academic experience and a deep working knowledge of state-of-the-art AI tools, frameworks, and best practices. Help us elevate our clients' Data at Welo Data. About Welo Works Welo Works is Welo Data's workforce management platform powering our data annotation services, spanning from sourcing and recruiting workers through to managing their full lifecycle after onboarding. We're building technology that enables our Delivery Services teams to deliver faster without compromising quality, scale sustainably, and serve both clients and raters exceptionally well. About the Role We're seeking a Product Manager to drive the worker and operations experience after workers are qualified and onboarded to projects. As our Delivery Services team scales during a transitionary period in the AI and data annotation space, this role will build the platform foundation that supports sustainable growth. You'll work across Delivery Services (Operations, Quality, Assessments, L&D, Community Experience), Development and QA, and Finance teams to deliver exceptional client outcomes while creating an engaging platform that respects workers' time. We're looking for someone with initiative and ownership who isn't afraid to push back constructively, question the status quo, and drive toward their vision of what "good" looks like—not settling for "good enough." What You Will Do Own product strategy for post-onboarding worker operations: project lifecycle management, task assignment, payment automation, quality dashboards, roster management, and self-service capabilities. Align roadmap with Delivery Services North Stars: deliver faster without compromising quality, scale sustainably, and serve clients and raters exceptionally well. Lead discovery sessions and user research with Project Managers, Quality Managers, L&D/Assessments specialists, Finance teams, and workers/raters; collaborate with Design to create intuitive experiences that engage workers and respect their time. Partner with Development (Tech Leads, Engineering Managers, developers) and QA on solution design, involving technical teams early. Create clear epics, user stories, and documentation for engineering with defined success metrics; maintain visibility into priorities and progress in Jira and Confluence. Navigate distributed teams effectively—Development and QA are in India and Spain; Delivery Services are in Mexico and the US. Strong async communication and creative time zone management are essential . Own end-to-end product development from discovery through UAT, release, and iteration; gather feedback and make informed ship decisions. Monitor usage and adoption, gathering feedback to drive continuous improvements. What You Bring Required 3-5 years in operations management, program management, technical program management, or business operations—driving process improvements and working with product/technology teams. Examples: Technical Program Managers who owned roadmaps and wrote user stories, or Operations Managers who partnered with engineering to build internal tools. Strong analytical skills and comfort with data-driven decisions in ambiguous environments. Excellent communication across technical and business audiences. Cross-functional experience with engineering, operations, and business teams, ideally across distributed time zones. Proficiency with Jira, Confluence, and modern collaboration tools. Initiative and ownership—proactively identify problems, propose solutions, and drive completion. Willingness to push back constructively while maintaining strong relationships. High standards and clear perspective on what "good" looks like. Preferred Product management experience in operations platforms, workforce management systems, or related domains. Background in data annotation, ML operations, gig economy platforms, or services businesses with distributed workforces. Experience with payments/invoicing, quality management, or project/task management systems. Track record of process improvements driving measurable efficiency gains. Strong async communication practices with globally distributed teams. Why Join Us Direct Impact : Enable operations teams to scale efficiently while affecting client delivery quality and worker satisfaction. Shape the Future : Influence processes and have genuine ownership during a transformation period in the AI/data annotation industry. Small, Empowered Team : Work with Head of Product and two other PMs where your voice matters. Growth Trajectory : Expand your scope as the platform evolves. We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/welocalize-product-manager

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Product Manager

[company_profile]
Welocalize

[location]
Anywhere in the World

[description]
Headquarters: Mexico / United States Welo Data works with technology companies to provide datasets that are high-quality, ethically sourced, relevant, diverse, and scalable to supercharge their AI models. As a Welocalize brand, WeloData leverages over 25 years of experience in partnering with the world’s most innovative companies and brings together a curated global community of over 500,000 AI training and domain experts to offer services that span: ANNOTATION & LABELLING: Transcription, summarization, image and video classification and labeling. ENHANCING LLMs: Prompt engineering, SFT, RLHF, red teaming and adversarial model training, model output ranking. DATA COLLECTION & GENERATION: From institutional languages to remote field audio collection. RELEVANCE & INTENT: Culturally nuanced and aware, ranking, relevance, and evaluation to train models for search, ads, and LLM output. Want to join our Welo Data team? We bring practical, applied AI expertise to projects. We have both strong academic experience and a deep working knowledge of state-of-the-art AI tools, frameworks, and best practices. Help us elevate our clients' Data at Welo Data. About Welo Works Welo Works is Welo Data's workforce management platform powering our data annotation services, spanning from sourcing and recruiting workers through to managing their full lifecycle after onboarding. We're building technology that enables our Delivery Services teams to deliver faster without compromising quality, scale sustainably, and serve both clients and raters exceptionally well. About the Role We're seeking a Product Manager to drive the worker and operations experience after workers are qualified and onboarded to projects. As our Delivery Services team scales during a transitionary period in the AI and data annotation space, this role will build the platform foundation that supports sustainable growth. You'll work across Delivery Services (Operations, Quality, Assessments, L&D, Community Experience), Development and QA, and Finance teams to deliver exceptional client outcomes while creating an engaging platform that respects workers' time. We're looking for someone with initiative and ownership who isn't afraid to push back constructively, question the status quo, and drive toward their vision of what "good" looks like—not settling for "good enough." What You Will Do Own product strategy for post-onboarding worker operations: project lifecycle management, task assignment, payment automation, quality dashboards, roster management, and self-service capabilities. Align roadmap with Delivery Services North Stars: deliver faster without compromising quality, scale sustainably, and serve clients and raters exceptionally well. Lead discovery sessions and user research with Project Managers, Quality Managers, L&D/Assessments specialists, Finance teams, and workers/raters; collaborate with Design to create intuitive experiences that engage workers and respect their time. Partner with Development (Tech Leads, Engineering Managers, developers) and QA on solution design, involving technical teams early. Create clear epics, user stories, and documentation for engineering with defined success metrics; maintain visibility into priorities and progress in Jira and Confluence. Navigate distributed teams effectively—Development and QA are in India and Spain; Delivery Services are in Mexico and the US. Strong async communication and creative time zone management are essential . Own end-to-end product development from discovery through UAT, release, and iteration; gather feedback and make informed ship decisions. Monitor usage and adoption, gathering feedback to drive continuous improvements. What You Bring Required 3-5 years in operations management, program management, technical program management, or business operations—driving process improvements and working with product/technology teams. Examples: Technical Program Managers who owned roadmaps and wrote user stories, or Operations Managers who partnered with engineering to build internal tools. Strong analytical skills and comfort with data-driven decisions in ambiguous environments. Excellent communication across technical and business audiences. Cross-functional experience with engineering, operations, and business teams, ideally across distributed time zones. Proficiency with Jira, Confluence, and modern collaboration tools. Initiative and ownership—proactively identify problems, propose solutions, and drive completion. Willingness to push back constructively while maintaining strong relationships. High standards and clear perspective on what "good" looks like. Preferred Product management experience in operations platforms, workforce management systems, or related domains. Background in data annotation, ML operations, gig economy platforms, or services businesses with distributed workforces. Experience with payments/invoicing, quality management, or project/task management systems. Track record of process improvements driving measurable efficiency gains. Strong async communication practices with globally distributed teams. Why Join Us Direct Impact : Enable operations teams to scale efficiently while affecting client delivery quality and worker satisfaction. Shape the Future : Influence processes and have genuine ownership during a transformation period in the AI/data annotation industry. Small, Empowered Team : Work with Head of Product and two other PMs where your voice matters. Growth Trajectory : Expand your scope as the platform evolves. We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/welocalize-product-manager

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #11 | AI Engineer/Python Develope
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/toptal-ai-engineer-python-develope
- apply_url: https://weworkremotely.com/remote-jobs/toptal-ai-engineer-python-develope

,field,original,translated,changed
0,title,AI Engineer/Python Develope,AI Engineer/Python Develope,False
1,company_profile,Toptal,Toptal,False
2,location,"Anywhere in the World, California, 🇮🇳 India","Anywhere in the World, California, 🇮🇳 India",False
3,department,,,False
4,description,"Headquarters: Remote URL: https://www.toptal.com/ About the Client A leading global agriculture company empowering millions of farmers to make smarter, data-driven decisions — ...","Headquarters: Remote URL: https://www.toptal.com/ About the Client A leading global agriculture company empowering millions of farmers to make smarter, data-driven decisions — ...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Contract,Contract,False
8,required_experience,,,False
9,required_education,,,False
10,industry,All Other Remote,All Other Remote,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
AI Engineer/Python Develope

[company_profile]
Toptal

[location]
Anywhere in the World, California, 🇮🇳 India

[description]
Headquarters: Remote URL: https://www.toptal.com/ About the Client A leading global agriculture company empowering millions of farmers to make smarter, data-driven decisions — building technology with real-world impact at scale. The Role We're looking for an experienced AI/Python Engineer to design, build, and optimize intelligent systems using Python and Azure — from prototyping new ideas to maintaining production-grade pipelines. What You'll Do Design and implement Python and Azure-based solutions for complex business problems Build and maintain RAG pipelines, multi-agent systems, and LLM-powered workflows Optimize existing systems for performance and scalability Ensure compliance with data privacy regulations Why This Role High-impact global projects at enterprise scale Collaborate with top-tier engineers via the Toptal network Requirements What We're Looking For Strong Python skills + data science libraries (NumPy, Pandas, Scikit-learn) Solid Azure services and cloud architecture experience Hands-on experience with LangChain, LangGraph, RAG pipelines, and multi-agent orchestration Familiarity with MCP (Model Context Protocol) To apply: https://weworkremotely.com/remote-jobs/toptal-ai-engineer-python-develope

[employment_type]
Contract

[industry]
All Other Remote

**Translated Full Posting Text**

[title]
AI Engineer/Python Develope

[company_profile]
Toptal

[location]
Anywhere in the World, California, 🇮🇳 India

[description]
Headquarters: Remote URL: https://www.toptal.com/ About the Client A leading global agriculture company empowering millions of farmers to make smarter, data-driven decisions — building technology with real-world impact at scale. The Role We're looking for an experienced AI/Python Engineer to design, build, and optimize intelligent systems using Python and Azure — from prototyping new ideas to maintaining production-grade pipelines. What You'll Do Design and implement Python and Azure-based solutions for complex business problems Build and maintain RAG pipelines, multi-agent systems, and LLM-powered workflows Optimize existing systems for performance and scalability Ensure compliance with data privacy regulations Why This Role High-impact global projects at enterprise scale Collaborate with top-tier engineers via the Toptal network Requirements What We're Looking For Strong Python skills + data science libraries (NumPy, Pandas, Scikit-learn) Solid Azure services and cloud architecture experience Hands-on experience with LangChain, LangGraph, RAG pipelines, and multi-agent orchestration Familiarity with MCP (Model Context Protocol) To apply: https://weworkremotely.com/remote-jobs/toptal-ai-engineer-python-develope

[employment_type]
Contract

[industry]
All Other Remote

---

### #12 | [Banco de Talentos] Pessoas com deficiência
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/conta-azul-banco-de-talentos-pessoas-com-deficiencia
- apply_url: https://weworkremotely.com/remote-jobs/conta-azul-banco-de-talentos-pessoas-com-deficiencia

,field,original,translated,changed
0,title,[Banco de Talentos] Pessoas com deficiência,[Talent Bank] People with disabilities,True
1,company_profile,Conta Azul,Blue Account,True
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://contaazul.com SOBRE A CONTA AZUL A Conta Azul é movida pela crença que todo empreendedor merece ter sucesso. Apesar do dia a dia cheio de responsab...,Headquarters: BR URL: http://contaazul.com ABOUT ACCOUNT AZUL Conta Azul is driven by the belief that every entrepreneur deserves to be successful. Despite the daily life full ...,True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
[Banco de Talentos] Pessoas com deficiência

[company_profile]
Conta Azul

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://contaazul.com SOBRE A CONTA AZUL A Conta Azul é movida pela crença que todo empreendedor merece ter sucesso. Apesar do dia a dia cheio de responsabilidades, queremos que todo dono de um pequeno negócio consiga tempo para se dedicar ao que sempre sonhou quando decidiu abrir uma empresa. Por isso, usamos a tecnologia para criar uma plataforma em nuvem, onde o empreendedor juntamente com o seu contador, de forma simples e fácil, podem encontrar tudo o que precisam em tempo real. Buscamos pessoas motivadas neste propósito. Se você é esta pessoa, junte-se a nós! INCLUSÃO E DIVERSIDADE Queremos construir um ambiente cada vez mais diverso e inclusivo. Por isso, incentivamos a candidatura de pessoas com deficiência em todas as nossas oportunidades. Caso você não encontre uma vaga aderente ao seu perfil neste momento, você pode se cadastrar em nosso banco de talentos para futuras oportunidades. Nosso time de Talent Acquisition revisa continuamente os currículos recebidos e, quando identificamos uma oportunidade compatível, entraremos em contato para dar continuidade ao processo. Aqui, você encontrará um ambiente de troca, aprendizado contínuo e colaboração, onde diferentes perspectivas são valorizadas e contribuem para a construção de soluções cada vez melhores. Se fizer sentido para você, será um prazer contar com a sua trajetória por aqui. #VemPraContaAzul Algumas características que valorizamos por aqui: Vontade de aprender e se desenvolver continuamente Colaboração e trabalho em equipe Comunicação clara, respeitosa e aberta Proatividade e senso de protagonismo Capacidade de se adaptar a mudanças e novos desafios Interesse em gerar impacto positivo para clientes e para o time Informações adicionais: BENEFÍCIOS Plano de saúde : cobertura nacional sem custo de mensalidade ou coparticipação. Pode ser estendido a dependentes (cônjuge e filhos), conforme política interna. Plano odontológico : cobertura nacional sem custo de mensalidade. Pode se estender aos dependentes (filhos e cônjuges) conforme política interna. Benefício flexível : R$ 1.000,00 por mês para investir em educação (70% de reembolso em mensalidades), idiomas (70%), atividades físicas e atendimento com psicólogos(as), nutricionistas, massoterapeutas e fisioterapeutas (50%). Auxílio creche para Papais e Mamães com filhos entre 0 e 24 meses. Auxílio Home Office mensal apoio mensal a partir de R$ 150,00 (de acordo com a localidade) Auxílio Home Office - parcela única de R$ 1.500,00 para custear a estação de trabalho. Vale Refeição e Alimentação : cartão Flash sem desconto em folha. Zenklub : acesso ilimitado a psicólogos, terapeutas, coaches e psicanalistas. As duas primeiras sessões do mês são gratuitas, e as demais têm custo de apenas R$ 20,00. Programa de bônus conforme atingimento de metas. Benefício Farmácia : App Vidalink com subsídio de 75% para medicamentos com receita. Podendo se estender aos dependentes (filhos e cônjuges) conforme política interna. Licença maternidade e paternidade estendidas . Filiação gratuita ao Sesc : podendo estender os benefícios aos dependentes. A filiação garante acesso a diversas atividades e serviços com preços especiais, como educação, esportes, lazer, excursões, hotéis, programação cultural, assistência odontológica e nutrição. Você paga apenas pelas atividades que utilizar. Transporte e Estacionamento : vale-transporte (com desconto de até 6%) e estacionamento gratuito na sede (Joinville). GoGood : Acesso a diversas academias em todo o Brasil com subsídio de 50% para Azuis. Dependentes podem aderir ao plano integral. Auxílio Mudança : Para todos os Azuis que têm o desejo de estar mais próximo da sede, oferecemos uma ajuda de custo para apoiar neste processo. Pacote de Experiências : Baby Blue Time : jornada menor de trabalho com flexibilidade extra de horário nos retornos das licenças Maternidade e Paternidade; Days Off Experience : Todos os Azuis com mais de 1 ano de casa poderão ter 4 folgas no ano; Sabático Parcialmente Remunerado : período em que os Azuis elegíveis podem ficar off e ainda recebem uma graninha antecipadamente; Seguro de vida : sem desconto; Licença gratuita na plataforma Conta Azul. E mais: Ambiente inovador que proporciona crescimento, com profissionais incríveis e de aprendizado constante; Escritório com acessibilidade, que estimula a criatividade e produtividade, com comida e bebida à vontade; Horário flexível (trabalhamos de segunda a sexta). Diversidade & Inclusão na Conta Azul Na Conta Azul, prezamos por um ambiente inclusivo, onde todas as pessoas se sintam respeitadas, valorizando as diferentes vivências e as particularidades de cada Azul. Por isso, promovemos a diversidade em nossos processos seletivos, como um reflexo da nossa crença na integração e na valorização de cada pessoa. Fique à vontade para declarar as informações no formulário de inscrição. Esses dados são essenciais para promover um processo seletivo inclusivo, e serão utilizados exclusivamente para essa finalidade, sem qualquer impacto durante ou após o processo. Por dentro da Conta Azul Nossos times adoram compartilhar conhecimento. Veja o que estamos fazendo por aqui. Acesse: https://medium.com/cultura-contaazul https://medium.com/design-contaazul https://engineering.contaazul.com To apply: https://weworkremotely.com/remote-jobs/conta-azul-banco-de-talentos-pessoas-com-deficiencia

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
[Talent Bank] People with disabilities

[company_profile]
Blue Account

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://contaazul.com ABOUT ACCOUNT AZUL Conta Azul is driven by the belief that every entrepreneur deserves to be successful. Despite the daily life full of responsibilities, we want every small business owner to have time to dedicate themselves to what they always dreamed of when they decided to open a company. Therefore, we use technology to create a cloud platform, where the entrepreneur, together with their accountant, can simply and easily find everything they need in real time. We are looking for people motivated by this purpose. If you are this person, join us! INCLUSION AND DIVERSITY We want to build an increasingly diverse and inclusive environment. Therefore, we encourage applications from people with disabilities at all our opportunities. If you do not find a vacancy that fits your profile at this time, you can register in our talent pool for future opportunities. Our Talent Acquisition team continually reviews the CVs received and, when we identify a compatible opportunity, we will contact you to continue the process. Here, you will find an environment of exchange, continuous learning and collaboration, where different perspectives are valued and contribute to the construction of increasingly better solutions. If it makes sense to you, it will be a pleasure to talk about your journey here. #VemPraContaAzul Some characteristics that we value here: Willingness to learn and continually develop Collaboration and teamwork Clear, respectful and open communication Proactivity and sense of protagonism Ability to adapt to changes and new challenges Interest in generating a positive impact for clients and the team Additional information: BENEFITS Health plan: national coverage

no monthly fee or co-participation. It can be extended to dependents (spouse and children), according to internal policy. Dental plan: national coverage with no monthly fee. It can be extended to dependents (children and spouses) according to internal policy. Flexible benefit: R$ 1,000.00 per month to invest in education (70% reimbursement in monthly fees), languages ​​(70%), physical activities and services with psychologists, nutritionists, massage therapists and physiotherapists (50%). Daycare assistance for Moms and Dads with children between 0 and 24 months. Monthly Home Office Allowance monthly support from R$150.00 (according to location) Home Office Allowance - single installment of R$1,500.00 to cover the cost of the workstation. Meal and Food Voucher: Flash card without payroll discount. Zenklub: unlimited access to psychologists, therapists, coaches and psychoanalysts. The first two sessions of the month are free, and the rest cost just R$20.00. Bonus program based on achievement of goals. Pharmacy Benefit: Vidalink app with 75% subsidy for prescription medicines. It may be extended to dependents (children and spouses) according to internal policy. Extended maternity and paternity leave. Free membership to Sesc: the benefits can be extended to dependents. Membership guarantees access to various activities and services at special prices, such as education, sports, leisure, excursions, hotels, cultural programming, dental care and nutrition. You only pay for the activities you use. Transport and Parking: transport voucher (with a discount of up to 6%) and free parking at the headquarters (Joinville). GoGood: Access to several gyms throughout Brazil with a 50% subsidy for Azuis. Dependents can join the plan

integral. Moving Assistance: For all Blues who wish to be closer to headquarters, we offer a stipend to support this process. Experience Package: Baby Blue Time: shorter working hours with extra flexibility when returning from Maternity and Paternity leave; Days Off Experience: All Blues with more than 1 year of service can have 4 days off per year; Partially Paid Sabbatical: period in which eligible Blues can take time off and still receive a little money in advance; Life insurance: no discount; Free license on the Conta Azul platform. And more: Innovative environment that provides growth, with incredible professionals and constant learning; Accessible office, which stimulates creativity and productivity, with unlimited food and drink; Flexible hours (we work Monday to Friday). Diversity & Inclusion at Conta Azul At Conta Azul, we value an inclusive environment, where all people feel respected, valuing the different experiences and particularities of each Azul. Therefore, we promote diversity in our selection processes, as a reflection of our belief in the integration and appreciation of each person. Please feel free to declare the information on the application form. This data is essential to promote an inclusive selection process, and will be used exclusively for this purpose, without any impact during or after the process. Inside Conta Azul Our teams love to share knowledge. See what we're doing here. Visit: https://medium.com/cultura-contaazul https://medium.com/design-contaazul https://engineering.contaazul.com To apply:

https://weworkremotely.com/remote-jobs/conta-azul-banco-de-talentos-pessoas-com-deficiencia

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #13 | Product Manager, Fraud Solutions
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/fis-capital-markets-product-manager-fraud-solutions
- apply_url: https://weworkremotely.com/remote-jobs/fis-capital-markets-product-manager-fraud-solutions

,field,original,translated,changed
0,title,"Product Manager, Fraud Solutions","Product Manager, Fraud Solutions",False
1,company_profile,FIS Capital Markets,FIS Capital Markets,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: US NE OMA 4501 Virtual URL: http://fisglobal.com Job Description About the role: We are seeking an experienced Product Manager, Fraud Solutions to lead strategy, ...","Headquarters: US NE OMA 4501 Virtual URL: http://fisglobal.com Job Description About the role: We are seeking an experienced Product Manager, Fraud Solutions to lead strategy, ...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Product Manager, Fraud Solutions

[company_profile]
FIS Capital Markets

[location]
Anywhere in the World

[description]
Headquarters: US NE OMA 4501 Virtual URL: http://fisglobal.com Job Description About the role: We are seeking an experienced Product Manager, Fraud Solutions to lead strategy, execution, and growth for our non-card fraud and risk products across payments. This role is ideal for a product leader with deep financial crimes and fraud domain expertise who can own existing product lines, lead client migrations and integrations, and bring new solutions to market in close partnership with Sales, Technology, and Operations. The focus is on non-card payment fraud (ACH, Wires, Deposits, RTP), with opportunities to expand into adjacent payment and fraud capabilities over time. What you will be doing: Own the end‑to‑end product strategy, roadmap, and lifecycle for non‑card fraud and risk solutions across payment channels including ACH, Wire, and Deposits. Lead go‑to‑market planning and execution , including positioning, pricing, sales enablement, and market entry for new and enhanced fraud solutions. Serve as the product and domain expert for Sales and clients, supporting prospecting, deal execution, and complex solution discussions. Drive client migrations, integrations, and implementations , partnering closely with Technology, Operations, and vendors. Monitor and manage product profitability , financial performance, forecasting, and value realization. Define and track KPIs related to solution health, fraud outcomes, adoption, and customer satisfaction. Identify and prioritize product enhancements and expansion opportunities , including adjacent payment and fraud capabilities (e.g., RTP, P2P, card fraud). Partner cross‑functionally to deliver new products and enhancements, including requirements definition, UAT support, and release readiness . Maintain strong vendor and partner relationships to support product delivery and innovation. What you will need: Proven experience in fraud, risk, or financial crimes within financial services or payments. Strong understanding of non-card payment fraud (e.g., ACH, wires, account takeover, check and deposit fraud, etc.). Experience owning products or solutions that involve integrations, client migrations, or complex implementations. Demonstrated ability to define and execute go-to-market strategies and support sales efforts. Strong business acumen, including profitability analysis, forecasting, and KPI definition. Excellent communication and stakeholder management skills, with the ability to influence across functions. Ability to manage multiple initiatives in a fast-paced environment with a strong sense of ownership and accountability. Added bonus if you have: Experience with payments ecosystems, including money movement, RTP, P2P, or card fraud solutions. Familiarity with fraud platforms, identity verification tools, or vendor-managed solutions (e.g., Verafin or similar). Experience working directly with financial institutions. Exposure to vendor management and third-party partnerships. Prior experience with product expansion into adjacent markets or capabilities. What we offer you: At FIS, you can learn, grow and make an impact in your career. Our benefits include: Flexible and creative work environment Diverse and collaborative atmosphere Professional and personal development resources Opportunities to volunteer and support charities Competitive salary and benefits Privacy Statement FIS is committed to protecting the privacy and security of all personal information that we process in order to provide services to our clients. For specific information on how FIS protects personal information online, please see the Online Privacy Notice . EEOC Statement FIS is an equal opportunity employer. We evaluate qualified applicants without regard to race, color, religion, sex, sexual orientation, gender identity, marital status, genetic information, national origin, disability, veteran status, and other protected characteristics. The EEO is the Law poster is available here supplement document available here For positions located in the US, the following conditions apply. If you are made a conditional offer of employment, you will be required to undergo a drug test. ADA Disclaimer: In developing this job description care was taken to include all competencies needed to successfully perform in this position. However, for Americans with Disabilities Act (ADA) purposes, the essential functions of the job may or may not have been described for purposes of ADA reasonable accommodation. All reasonable accommodation requests will be reviewed and evaluated on a case-by-case basis. Sourcing Model Recruitment at FIS works primarily on a direct sourcing model; a relatively small portion of our hiring is through recruitment agencies. FIS does not accept resumes from recruitment agencies which are not on the preferred supplier list and is not responsible for any related fees for resumes submitted to job postings, our employees, or any other part of our company. #pridepass To apply: https://weworkremotely.com/remote-jobs/fis-capital-markets-product-manager-fraud-solutions

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
Product Manager, Fraud Solutions

[company_profile]
FIS Capital Markets

[location]
Anywhere in the World

[description]
Headquarters: US NE OMA 4501 Virtual URL: http://fisglobal.com Job Description About the role: We are seeking an experienced Product Manager, Fraud Solutions to lead strategy, execution, and growth for our non-card fraud and risk products across payments. This role is ideal for a product leader with deep financial crimes and fraud domain expertise who can own existing product lines, lead client migrations and integrations, and bring new solutions to market in close partnership with Sales, Technology, and Operations. The focus is on non-card payment fraud (ACH, Wires, Deposits, RTP), with opportunities to expand into adjacent payment and fraud capabilities over time. What you will be doing: Own the end‑to‑end product strategy, roadmap, and lifecycle for non‑card fraud and risk solutions across payment channels including ACH, Wire, and Deposits. Lead go‑to‑market planning and execution , including positioning, pricing, sales enablement, and market entry for new and enhanced fraud solutions. Serve as the product and domain expert for Sales and clients, supporting prospecting, deal execution, and complex solution discussions. Drive client migrations, integrations, and implementations , partnering closely with Technology, Operations, and vendors. Monitor and manage product profitability , financial performance, forecasting, and value realization. Define and track KPIs related to solution health, fraud outcomes, adoption, and customer satisfaction. Identify and prioritize product enhancements and expansion opportunities , including adjacent payment and fraud capabilities (e.g., RTP, P2P, card fraud). Partner cross‑functionally to deliver new products and enhancements, including requirements definition, UAT support, and release readiness . Maintain strong vendor and partner relationships to support product delivery and innovation. What you will need: Proven experience in fraud, risk, or financial crimes within financial services or payments. Strong understanding of non-card payment fraud (e.g., ACH, wires, account takeover, check and deposit fraud, etc.). Experience owning products or solutions that involve integrations, client migrations, or complex implementations. Demonstrated ability to define and execute go-to-market strategies and support sales efforts. Strong business acumen, including profitability analysis, forecasting, and KPI definition. Excellent communication and stakeholder management skills, with the ability to influence across functions. Ability to manage multiple initiatives in a fast-paced environment with a strong sense of ownership and accountability. Added bonus if you have: Experience with payments ecosystems, including money movement, RTP, P2P, or card fraud solutions. Familiarity with fraud platforms, identity verification tools, or vendor-managed solutions (e.g., Verafin or similar). Experience working directly with financial institutions. Exposure to vendor management and third-party partnerships. Prior experience with product expansion into adjacent markets or capabilities. What we offer you: At FIS, you can learn, grow and make an impact in your career. Our benefits include: Flexible and creative work environment Diverse and collaborative atmosphere Professional and personal development resources Opportunities to volunteer and support charities Competitive salary and benefits Privacy Statement FIS is committed to protecting the privacy and security of all personal information that we process in order to provide services to our clients. For specific information on how FIS protects personal information online, please see the Online Privacy Notice . EEOC Statement FIS is an equal opportunity employer. We evaluate qualified applicants without regard to race, color, religion, sex, sexual orientation, gender identity, marital status, genetic information, national origin, disability, veteran status, and other protected characteristics. The EEO is the Law poster is available here supplement document available here For positions located in the US, the following conditions apply. If you are made a conditional offer of employment, you will be required to undergo a drug test. ADA Disclaimer: In developing this job description care was taken to include all competencies needed to successfully perform in this position. However, for Americans with Disabilities Act (ADA) purposes, the essential functions of the job may or may not have been described for purposes of ADA reasonable accommodation. All reasonable accommodation requests will be reviewed and evaluated on a case-by-case basis. Sourcing Model Recruitment at FIS works primarily on a direct sourcing model; a relatively small portion of our hiring is through recruitment agencies. FIS does not accept resumes from recruitment agencies which are not on the preferred supplier list and is not responsible for any related fees for resumes submitted to job postings, our employees, or any other part of our company. #pridepass To apply: https://weworkremotely.com/remote-jobs/fis-capital-markets-product-manager-fraud-solutions

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #14 | Desenvolvedor Dynamics 365 CE [100% Remota]
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/cashme-desenvolvedor-dynamics-365-ce-100-remota
- apply_url: https://weworkremotely.com/remote-jobs/cashme-desenvolvedor-dynamics-365-ce-100-remota

,field,original,translated,changed
0,title,Desenvolvedor Dynamics 365 CE [100% Remota],Dynamics 365 CE Developer [100% Remote],True
1,company_profile,CashMe,CashMe,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://cashme.com.br Desenvolvedor(a) Dynamics 365 CRM - 100% remota! Estamos buscando um(a) Desenvolvedor(a) Dynamics 365 CRM para atuar em modelo 100% r...,Headquarters: BR URL: http://cashme.com.br Dynamics 365 CRM Developer - 100% remote! We are looking for a Dynamics 365 CRM Developer to work in a 100% remote model. The objecti...,True
5,requirements,"CRM, Cross-Browser Development, MySQL, Computer Vision, NoSQL, PostgreeSQL, CRM Systems, Cross-Selling, CRM Integration, and APIs","CRM, Cross-Browser Development, MySQL, Computer Vision, NoSQL, PostgreeSQL, CRM Systems, Cross-Selling, CRM Integration, and APIs",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Desenvolvedor Dynamics 365 CE [100% Remota]

[company_profile]
CashMe

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cashme.com.br Desenvolvedor(a) Dynamics 365 CRM - 100% remota! Estamos buscando um(a) Desenvolvedor(a) Dynamics 365 CRM para atuar em modelo 100% remoto . O objetivo é projetar e implementar soluções escaláveis e de alta performance no ecossistema Microsoft, sustentando a expansão dos produtos financeiros da CashMe. Buscamos um perfil técnico sólido e proativo, com domínio em C# e APIs, capaz de propor arquiteturas eficientes e garantir a qualidade das entregas em um ambiente de colaboração à distância. Como Desenvolvedor Dynamics 365 CRM, você focará em: • Desenvolver soluções de tecnologia para viabilizar o crescimento exponencial da CashMe, com múltiplos produtos de negócio, da simulação de empréstimo até a assinatura do contrato; • Atuar com Dynamics 365 CRM (Sales, Marketing, Customer Service com Omnichannel), Power Platform (Power Apps Model Driven e Canvas, Dataverse, Power Automate), realizando as atividades de desenvolvimento, administração, configuração, customização e teste unitário; • Propor padrões de solução e compartilhar conhecimento técnico; • Avaliar impactos, mapeando riscos e oportunidades de melhoria do produto; • Trabalhar com metodologia ágil SCRUM, participando dos refinamentos, plannings, dailies, e retro/reviews. Você contará com SM, PO,PM, QA, UX e os demais devs. É importante que você tenha: • Ensino superior completo em áreas de tecnologia; • Experiência com Microsoft Dynamics CRM, Power Apps Model Driven, plug-ins, workflows, customizações, Actions e Custom APIs, Power Automate e SDK; • Experiência com decisões de modelagem de dados em Dataverse; • Experiência com desenvolvimento de sistemas utilizando C# (.NET), JavaScript/TypeScript e integrações via REST/SOAP e OData (Web API); • Experiência com ferramentas de suporte: XrmToolBox, Power Pane, Level Up e ferramentas CLI (PAC CLI); • Experiência com gestão de código fonte utilizando GIT; • Habilidade para criação de documentação técnica. • Perfil Proativo e Autônomo: Postura orientada a resultados, com iniciativa para identificar débitos técnicos, propor refatorações e antecipar impactos de integração. Você se destaca ainda mais se tiver: • Experiência em Power Apps Canvas, Power Fx; • Experiência em PCF (PowerApps Component Framework); • Conhecimento em Cloud Aws,Azure; • Conhecimento em SQL Server; • Experiência com os módulos de Marketing, Customer Service com Omnichannel e Copilot Studio; • Inglês avançado para colaboração técnica; • Certificações em: PL-400 (Developer), MB-200/210/230 ou PL-600 (Architect) To apply: https://weworkremotely.com/remote-jobs/cashme-desenvolvedor-dynamics-365-ce-100-remota

[requirements]
CRM, Cross-Browser Development, MySQL, Computer Vision, NoSQL, PostgreeSQL, CRM Systems, Cross-Selling, CRM Integration, and APIs

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
Dynamics 365 CE Developer [100% Remote]

[company_profile]
CashMe

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cashme.com.br Dynamics 365 CRM Developer - 100% remote! We are looking for a Dynamics 365 CRM Developer to work in a 100% remote model. The objective is to design and implement scalable, high-performance solutions in the Microsoft ecosystem, supporting the expansion of CashMe's financial products. We are looking for a solid and proactive technical profile, with mastery in C# and APIs, capable of proposing efficient architectures and guaranteeing the quality of deliveries in a remote collaboration environment. As a Dynamics 365 CRM Developer, you will focus on: • Developing technology solutions to enable CashMe's exponential growth, with multiple business products, from loan simulation to contract signing; • Work with Dynamics 365 CRM (Sales, Marketing, Customer Service with Omnichannel), Power Platform (Power Apps Model Driven and Canvas, Dataverse, Power Automate), carrying out development, administration, configuration, customization and unit testing activities; • Propose solution patterns and share technical knowledge; • Evaluate impacts, mapping risks and opportunities for product improvement; • Work with agile SCRUM methodology, participating in refinements, plannings, dailies, and retro/reviews. You will have SM, PO, PM, QA, UX and other devs. It is important that you have: • Complete higher education in technology areas; • Experience with Microsoft Dynamics CRM, Power Apps Model Driven, plug-ins, workflows, customizations, Actions and Custom APIs, Power Automate and SDK; • Experience with data modeling decisions in Dataverse; • Experience with systems development using C# (.NET), JavaScript/TypeScript and integrations via REST/SOAP and OData (Web API); • Experience with tools

support: XrmToolBox, Power Pane, Level Up and CLI tools (PAC CLI); • Experience with source code management using GIT; • Ability to create technical documentation. • Proactive and Autonomous Profile: Results-oriented stance, with initiative to identify technical debts, propose refactorings and anticipate integration impacts. You stand out even more if you have: • Experience in Power Apps Canvas, Power Fx; • Experience in PCF (PowerApps Component Framework); • Knowledge in Cloud Aws, Azure; • Knowledge of SQL Server; • Experience with Marketing, Customer Service modules with Omnichannel and Copilot Studio; • Advanced English for technical collaboration; • Certifications in: PL-400 (Developer), MB-200/210/230 or PL-600 (Architect) To apply: https://weworkremotely.com/remote-jobs/cashme-desenvolvedor-dynamics-365-ce-100-remota

[requirements]
CRM, Cross-Browser Development, MySQL, Computer Vision, NoSQL, PostgreeSQL, CRM Systems, Cross-Selling, CRM Integration, and APIs

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #15 | Operations Manager (Germany)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/ey-operations-manager-germany
- apply_url: https://weworkremotely.com/remote-jobs/ey-operations-manager-germany

,field,original,translated,changed
0,title,Operations Manager (Germany),Operations Manager (Germany),False
1,company_profile,EY,EY,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: Wrocław/Katowice - 2 days office/3 days remote URL: http://ey.com Operations Manager (Germany) Location: Wrocław/Katowice - 2 days office/3 days remote Let us int...,Headquarters: Wrocław/Katowice - 2 days office/3 days remote URL: http://ey.com Operations Manager (Germany) Location: Wrocław/Katowice - 2 days office/3 days remote Let us int...,False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Operations Manager (Germany)

[company_profile]
EY

[location]
Anywhere in the World

[description]
Headquarters: Wrocław/Katowice - 2 days office/3 days remote URL: http://ey.com Operations Manager (Germany) Location: Wrocław/Katowice - 2 days office/3 days remote Let us introduce you the job offer by EY GDS Poland – a member of the global integrated service delivery center network by EY. The opportunity The Operation Manager (Germany) will actively establish and maintain positive relationships with functional leaders of the Germany team ensuring their functional priorities, issues & concerns are addressed timely. This role requires functional hands-on approach to achieving best-in-class delivery experience between GDS and EY Germany by fostering collaboration across various departments & teams. Your key responsibilities Operation management: Collaborate with cross-functional teams across geographies, ensuring effective relationship. Drive operational excellence, standardization, and scalability across engagements. Monitor KPIs, SLAs, and client satisfaction metrics across branches. Address operational issues raised by the Germany and GDS Enablement Services functional leaders. Supporting AI initiatives by coordinating details for their function. Mentor and coach team members, fostering a high-performance culture. Relationship & Stakeholder management Actively establish and maintain positive relationships with existing functional leaders and POC’s across Germany and GDS and help by addressing their concerns. Serve as the key point of contact for any issues that arise, ensuring timely and effective resolution Establishing a cadence with function leaders and / or deputies to get an appreciation of each function and its competencies. Understanding the priorities of each function and help towards alignment of Germany and GDS team priorities Approach potential partners and directors in Germany to cultivate fruitful relationships. Collaboration: Conduct workshops, meetings, and sessions to enhance integration between GDS and EY Germany Enable the 2 in a box model to yield standardization and automation of processes Have an understanding across functions to help solution operational and delivery issues if any Collaborate across departments such as DPS, Talent, Service Excellence, and GDS Finance to meet the needs of Germany stakeholders. Support Solutions for GDS: Provide high-quality support in solutioning and identifying new opportunities to enhance GDS and Germany integration. Transformational initiatives Monitor, track, guide and manage key transformational initiatives for enhancing collaboration between Germany and GDS Skills and attributes for success At least 10 years of experience in relationship management for larger delivery functions, with a proven track record in relationship building and maintenance. Excellent analytical skills with the ability to analyse stakeholder behaviour and comprehend business information. Strong interpersonal skills to build and maintain positive relationships with Germany stakeholders, demonstrating empathy and effectively managing conflicts. Proficient in executive presentations to detail mitigation plans addressing stakeholders’ concerns. Fluent in English; knowledge of the German language is advantageous. Understanding of GDS locations and Enablement services functions. Customer service-oriented and a collaborative team player. Preferred Skills and Qualifications: Bachelor’s degree Proven experience in customer-facing roles such as customer service, sales, business development, or solutioning. Strong problem-solving and negotiation skills. Excellent written and verbal communication skills. Strong organizational and planning abilities. Willingness to travel for client meetings and conferences as required What we offer EY Global Delivery Services (GDS) is a dynamic and truly global delivery network. We work across nine locations – Argentina, Hungary, India, the Philippines, Poland, Sri Lanka, Mexico, Spain and the United Kingdom – and with teams from all EY service lines, geographies and sectors, playing a vital role in the delivery of the EY growth strategy. From accountants to coders to advisory consultants, we offer a wide variety of fulfilling career opportunities that span all business disciplines. In GDS, you will collaborate with EY teams on exciting projects and work with well-known brands from across the globe. We’ll introduce you to an ever-expanding ecosystem of people, learning, skills and insights that will stay with you throughout your career. Continuous learning : You’ll develop the mindset and skills to navigate whatever comes next. Success as defined by you : We’ll provide the tools and flexibility, so you can make a meaningful impact, your way. Transformative leadership : We’ll give you the insights, coaching and confidence to be the leader the world needs. Diverse and inclusive culture: You’ll be embraced for who you are and empowered to use your voice to help others find theirs. About EY EY | Building a better working world EY exists to build a better working world, helping to create long-term value for clients, people and society and build trust in the capital markets. Enabled by data and technology, diverse EY teams in over 150 countries provide trust through assurance and help clients grow, transform and operate. Working across assurance, consulting, law, strategy, tax and transactions, EY teams ask better questions to find new answers for the complex issues facing our world today. If you can demonstrate that you meet the criteria above, please contact us as soon as possible. The exceptional EY experience. It’s yours to build. In compliance with the requirements of the Whistleblower Protection Act, our company has established the Procedure for reporting breaches of law and undertaking appropriate follow-up actions . Any misconduct should be reported through the EY Ethics Hotline. To apply: https://weworkremotely.com/remote-jobs/ey-operations-manager-germany

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
Operations Manager (Germany)

[company_profile]
EY

[location]
Anywhere in the World

[description]
Headquarters: Wrocław/Katowice - 2 days office/3 days remote URL: http://ey.com Operations Manager (Germany) Location: Wrocław/Katowice - 2 days office/3 days remote Let us introduce you the job offer by EY GDS Poland – a member of the global integrated service delivery center network by EY. The opportunity The Operation Manager (Germany) will actively establish and maintain positive relationships with functional leaders of the Germany team ensuring their functional priorities, issues & concerns are addressed timely. This role requires functional hands-on approach to achieving best-in-class delivery experience between GDS and EY Germany by fostering collaboration across various departments & teams. Your key responsibilities Operation management: Collaborate with cross-functional teams across geographies, ensuring effective relationship. Drive operational excellence, standardization, and scalability across engagements. Monitor KPIs, SLAs, and client satisfaction metrics across branches. Address operational issues raised by the Germany and GDS Enablement Services functional leaders. Supporting AI initiatives by coordinating details for their function. Mentor and coach team members, fostering a high-performance culture. Relationship & Stakeholder management Actively establish and maintain positive relationships with existing functional leaders and POC’s across Germany and GDS and help by addressing their concerns. Serve as the key point of contact for any issues that arise, ensuring timely and effective resolution Establishing a cadence with function leaders and / or deputies to get an appreciation of each function and its competencies. Understanding the priorities of each function and help towards alignment of Germany and GDS team priorities Approach potential partners and directors in Germany to cultivate fruitful relationships. Collaboration: Conduct workshops, meetings, and sessions to enhance integration between GDS and EY Germany Enable the 2 in a box model to yield standardization and automation of processes Have an understanding across functions to help solution operational and delivery issues if any Collaborate across departments such as DPS, Talent, Service Excellence, and GDS Finance to meet the needs of Germany stakeholders. Support Solutions for GDS: Provide high-quality support in solutioning and identifying new opportunities to enhance GDS and Germany integration. Transformational initiatives Monitor, track, guide and manage key transformational initiatives for enhancing collaboration between Germany and GDS Skills and attributes for success At least 10 years of experience in relationship management for larger delivery functions, with a proven track record in relationship building and maintenance. Excellent analytical skills with the ability to analyse stakeholder behaviour and comprehend business information. Strong interpersonal skills to build and maintain positive relationships with Germany stakeholders, demonstrating empathy and effectively managing conflicts. Proficient in executive presentations to detail mitigation plans addressing stakeholders’ concerns. Fluent in English; knowledge of the German language is advantageous. Understanding of GDS locations and Enablement services functions. Customer service-oriented and a collaborative team player. Preferred Skills and Qualifications: Bachelor’s degree Proven experience in customer-facing roles such as customer service, sales, business development, or solutioning. Strong problem-solving and negotiation skills. Excellent written and verbal communication skills. Strong organizational and planning abilities. Willingness to travel for client meetings and conferences as required What we offer EY Global Delivery Services (GDS) is a dynamic and truly global delivery network. We work across nine locations – Argentina, Hungary, India, the Philippines, Poland, Sri Lanka, Mexico, Spain and the United Kingdom – and with teams from all EY service lines, geographies and sectors, playing a vital role in the delivery of the EY growth strategy. From accountants to coders to advisory consultants, we offer a wide variety of fulfilling career opportunities that span all business disciplines. In GDS, you will collaborate with EY teams on exciting projects and work with well-known brands from across the globe. We’ll introduce you to an ever-expanding ecosystem of people, learning, skills and insights that will stay with you throughout your career. Continuous learning : You’ll develop the mindset and skills to navigate whatever comes next. Success as defined by you : We’ll provide the tools and flexibility, so you can make a meaningful impact, your way. Transformative leadership : We’ll give you the insights, coaching and confidence to be the leader the world needs. Diverse and inclusive culture: You’ll be embraced for who you are and empowered to use your voice to help others find theirs. About EY EY | Building a better working world EY exists to build a better working world, helping to create long-term value for clients, people and society and build trust in the capital markets. Enabled by data and technology, diverse EY teams in over 150 countries provide trust through assurance and help clients grow, transform and operate. Working across assurance, consulting, law, strategy, tax and transactions, EY teams ask better questions to find new answers for the complex issues facing our world today. If you can demonstrate that you meet the criteria above, please contact us as soon as possible. The exceptional EY experience. It’s yours to build. In compliance with the requirements of the Whistleblower Protection Act, our company has established the Procedure for reporting breaches of law and undertaking appropriate follow-up actions . Any misconduct should be reported through the EY Ethics Hotline. To apply: https://weworkremotely.com/remote-jobs/ey-operations-manager-germany

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #16 | Senior Manager, Finance Strategy & Planning
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/cohesity-senior-manager-finance-strategy-planning
- apply_url: https://weworkremotely.com/remote-jobs/cohesity-senior-manager-finance-strategy-planning

,field,original,translated,changed
0,title,"Senior Manager, Finance Strategy & Planning","Senior Manager, Finance Strategy & Planning",False
1,company_profile,Cohesity,Cohesity,False
2,location,Washington,Washington,False
3,department,,,False
4,description,"Headquarters: Seattle Metro Area - Washington - USA (Remote) URL: http://cohesity.com Interested candidates based outside of the designated areas are welcome to apply, provided...","Headquarters: Seattle Metro Area - Washington - USA (Remote) URL: http://cohesity.com Interested candidates based outside of the designated areas are welcome to apply, provided...",False
5,requirements,"Adobe Creative Suite, Analytics, Accounting, Architect, Architecture, Blog Writing, Analytics Tools, Data Visualization, Editing, and Audio Editing","Adobe Creative Suite, Analytics, Accounting, Architect, Architecture, Blog Writing, Analytics Tools, Data Visualization, Editing, and Audio Editing",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Manager, Finance Strategy & Planning

[company_profile]
Cohesity

[location]
Washington

[description]
Headquarters: Seattle Metro Area - Washington - USA (Remote) URL: http://cohesity.com Interested candidates based outside of the designated areas are welcome to apply, provided they have the indefinite right to work in the job location. Cohesity is a leader in AI-powered data security and management. Aided by an extensive ecosystem of partners, Cohesity makes it easy to secure, protect, manage, and get value from data — across the data center, edge, and cloud. Cohesity helps organizations defend against cybersecurity threats with comprehensive data security and management capabilities, including immutable backup snapshots, AI-based threat detection, monitoring for malicious behavior, and rapid recovery at scale. We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design. Join us on our mission to shape the future of our industry. We’re looking for a forward-thinking finance leader with an analytical mind who thrives in the fast-paced environment of a scaling technology company. The ideal candidate possesses robust finance acumen, a strong mastery of SaaS business models, and an AI-first mindset. As a core pillar of our GTM Finance team, this role sits at the intersection of strategy, modeling, and execution. You will partner closely with the Office of the CFO and the Office of the CRO to solve complex business problems ranging from strategic planning and business modeling to the cross-functional design and execution of GTM initiatives. You will be responsible for operationalizing AI-native tools and automation , driving high-impact analysis and executive decision-making as a trusted strategic advisor. This position reports to the Finance Director, Sales Strategy & Planning . HOW YOU’LL SPEND YOUR TIME HERE: Strategic Initiative Leadership & Decision Velocity: Mobilize and lead cross-functional teams to dissect complex, business-critical problems. You will structure data-driven hypotheses, orchestrate deep analytical review , and deliver recommendations that actively shape GTM strategy, resource prioritization, and investment decisions. Topline Management & Architecture: Lead the short-range forecasting process for Bookings, Billings, and Revenue. Beyond tracking, you will build and use predictive modeling to identify growth levers and provide early-warning signals across key metrics. Executive & Board-Level Reporting: Lead the creation of high-impact reporting and financial narratives for executive and board-level consumption. By leveraging AI-native analytics, you will increase reporting velocity and visibility to GTM trends, performance metrics, and strategic risks . Integrated Planning: Lead quarterly and annual planning cycles for the sales organization, translating corporate growth targets into departmental financial impacts and quotas. Strategic Business Partnership: Act as the primary finance lead for multiple VPs across the GTM organization. Provide data-driven recommendations on resource allocation, sales productivity, and investment ROI. Cross-Functional Collaboration: Build and maintain strong relationships with Corporate Finance, Sales Operations, Accounting, etc. to ensure data integrity, streamline GTM workflows, and align departmental goals with the long-range financial plan. WE’D LOVE TO TALK TO YOU IF YOU HAVE MANY OF THE FOLLOWING: Topline Expertise: Deep experience managing SaaS or high-growth metrics (Bookings, Billings, ARR/Revenue) and a strong understanding of how sales cycles impact financial statements. Strategic Mindset: A curiosity to look beyond the "what" of the numbers to explain the "why," with the initiative to proactively solve complex business problems, using AI-native tools to provide faster, more accurate analysis . Communication Mastery: The ability to distill complex financial data into clear, concise narratives for VPs and non-financial leaders. Agility: A track record of thriving in fast-paced environments, with a proven ability to manage and lead high-priority projects and influence cross-functional stakeholders. Advanced Modeling: Expert-level Excel skills combined with a 'future-of-finance' toolkit. You are comfortable using AI assistants to write scripts, automate repetitive reporting workstreams, and build models that are scalable and resilient . Demonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision making. YOUR EXPERIENCE: Bachelor’s degree in Finance , Accounting, Economics, or a related field; MBA or equivalent experience is a plus. Minimum of 5 + years of relevant experience in FP&A, Sales Finance, or Strategic Finance, preferably within a fast-paced technology or SaaS company. Strong proficiency with financial systems (e.g., Adaptive Insights, NetSuite, Salesforce, and Tableau ) and a proven ability to operationalize AI-native tools ( e.g. Claude , ChatGPT, Cu rsor ) #LI-VM1 Disclosure Pursuant to Applicable State Equal Pay Transparency Laws - This position has a starting pay range as listed below. Actual salary depends upon many factors, including a candidate’s skills, qualifications and experience, location, and salary expectations, and therefore a starting salary at the low end, high end, or even above the stated range may be offered. This position may also be eligible for bonus compensation, commission (if in a sales function), and/or equity grants. Additionally, full-time employees are eligible to participate in our comprehensive benefits framework, including health and wellness benefits, vacation, paid holidays and refresh days, 401(k) retirement plan, life and disability insurance coverages, and other benefits the Company may offer from time to time. Pay Range : $145,440.00-$181,800.00 The compensation noted above is based on an annualized hourly rate assuming normal full-time employment. Data Privacy Notice for Job Candidates: For information on personal data processing, please see our . Equal Employment Opportunity Employer (EEOE) Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law. If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance. In-Office Expectations Cohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing. Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location. To apply: https://weworkremotely.com/remote-jobs/cohesity-senior-manager-finance-strategy-planning

[requirements]
Adobe Creative Suite, Analytics, Accounting, Architect, Architecture, Blog Writing, Analytics Tools, Data Visualization, Editing, and Audio Editing

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
Senior Manager, Finance Strategy & Planning

[company_profile]
Cohesity

[location]
Washington

[description]
Headquarters: Seattle Metro Area - Washington - USA (Remote) URL: http://cohesity.com Interested candidates based outside of the designated areas are welcome to apply, provided they have the indefinite right to work in the job location. Cohesity is a leader in AI-powered data security and management. Aided by an extensive ecosystem of partners, Cohesity makes it easy to secure, protect, manage, and get value from data — across the data center, edge, and cloud. Cohesity helps organizations defend against cybersecurity threats with comprehensive data security and management capabilities, including immutable backup snapshots, AI-based threat detection, monitoring for malicious behavior, and rapid recovery at scale. We’ve been named a Leader by multiple analyst firms and have been globally recognized for Innovation, Product Strength, and Simplicity in Design. Join us on our mission to shape the future of our industry. We’re looking for a forward-thinking finance leader with an analytical mind who thrives in the fast-paced environment of a scaling technology company. The ideal candidate possesses robust finance acumen, a strong mastery of SaaS business models, and an AI-first mindset. As a core pillar of our GTM Finance team, this role sits at the intersection of strategy, modeling, and execution. You will partner closely with the Office of the CFO and the Office of the CRO to solve complex business problems ranging from strategic planning and business modeling to the cross-functional design and execution of GTM initiatives. You will be responsible for operationalizing AI-native tools and automation , driving high-impact analysis and executive decision-making as a trusted strategic advisor. This position reports to the Finance Director, Sales Strategy & Planning . HOW YOU’LL SPEND YOUR TIME HERE: Strategic Initiative Leadership & Decision Velocity: Mobilize and lead cross-functional teams to dissect complex, business-critical problems. You will structure data-driven hypotheses, orchestrate deep analytical review , and deliver recommendations that actively shape GTM strategy, resource prioritization, and investment decisions. Topline Management & Architecture: Lead the short-range forecasting process for Bookings, Billings, and Revenue. Beyond tracking, you will build and use predictive modeling to identify growth levers and provide early-warning signals across key metrics. Executive & Board-Level Reporting: Lead the creation of high-impact reporting and financial narratives for executive and board-level consumption. By leveraging AI-native analytics, you will increase reporting velocity and visibility to GTM trends, performance metrics, and strategic risks . Integrated Planning: Lead quarterly and annual planning cycles for the sales organization, translating corporate growth targets into departmental financial impacts and quotas. Strategic Business Partnership: Act as the primary finance lead for multiple VPs across the GTM organization. Provide data-driven recommendations on resource allocation, sales productivity, and investment ROI. Cross-Functional Collaboration: Build and maintain strong relationships with Corporate Finance, Sales Operations, Accounting, etc. to ensure data integrity, streamline GTM workflows, and align departmental goals with the long-range financial plan. WE’D LOVE TO TALK TO YOU IF YOU HAVE MANY OF THE FOLLOWING: Topline Expertise: Deep experience managing SaaS or high-growth metrics (Bookings, Billings, ARR/Revenue) and a strong understanding of how sales cycles impact financial statements. Strategic Mindset: A curiosity to look beyond the "what" of the numbers to explain the "why," with the initiative to proactively solve complex business problems, using AI-native tools to provide faster, more accurate analysis . Communication Mastery: The ability to distill complex financial data into clear, concise narratives for VPs and non-financial leaders. Agility: A track record of thriving in fast-paced environments, with a proven ability to manage and lead high-priority projects and influence cross-functional stakeholders. Advanced Modeling: Expert-level Excel skills combined with a 'future-of-finance' toolkit. You are comfortable using AI assistants to write scripts, automate repetitive reporting workstreams, and build models that are scalable and resilient . Demonstrated ability to leverage AI tools to enhance productivity, streamline workflows, and support decision making. YOUR EXPERIENCE: Bachelor’s degree in Finance , Accounting, Economics, or a related field; MBA or equivalent experience is a plus. Minimum of 5 + years of relevant experience in FP&A, Sales Finance, or Strategic Finance, preferably within a fast-paced technology or SaaS company. Strong proficiency with financial systems (e.g., Adaptive Insights, NetSuite, Salesforce, and Tableau ) and a proven ability to operationalize AI-native tools ( e.g. Claude , ChatGPT, Cu rsor ) #LI-VM1 Disclosure Pursuant to Applicable State Equal Pay Transparency Laws - This position has a starting pay range as listed below. Actual salary depends upon many factors, including a candidate’s skills, qualifications and experience, location, and salary expectations, and therefore a starting salary at the low end, high end, or even above the stated range may be offered. This position may also be eligible for bonus compensation, commission (if in a sales function), and/or equity grants. Additionally, full-time employees are eligible to participate in our comprehensive benefits framework, including health and wellness benefits, vacation, paid holidays and refresh days, 401(k) retirement plan, life and disability insurance coverages, and other benefits the Company may offer from time to time. Pay Range : $145,440.00-$181,800.00 The compensation noted above is based on an annualized hourly rate assuming normal full-time employment. Data Privacy Notice for Job Candidates: For information on personal data processing, please see our . Equal Employment Opportunity Employer (EEOE) Cohesity is an Equal Employment Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, creed, religion, sex, sexual orientation, national origin or nationality, ancestry, age, disability, gender identity or expression, marital status, veteran status or any other category protected by law. If you are an individual with a disability and require a reasonable accommodation to complete any part of the application process, or are limited in the ability or unable to access or use this online application process and need an alternative method for applying, you may contact us at 1-855-9COHESITY or recruiting@cohesity.com for assistance. In-Office Expectations Cohesity employees who are within a reasonable commute (e.g. within a forty-five (45) minute average travel time) work out of our core offices 2-3 days a week of their choosing. Interested candidates based outside of the designated areas are welcome to apply, provided they have the right to work in the job location. To apply: https://weworkremotely.com/remote-jobs/cohesity-senior-manager-finance-strategy-planning

[requirements]
Adobe Creative Suite, Analytics, Accounting, Architect, Architecture, Blog Writing, Analytics Tools, Data Visualization, Editing, and Audio Editing

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #17 | Senior Fullstack Engineer — Produtos Financeiros (Miniapps)
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.85)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/rock-encantech-senior-fullstack-engineer-produtos-financeiros-miniapps
- apply_url: https://weworkremotely.com/remote-jobs/rock-encantech-senior-fullstack-engineer-produtos-financeiros-miniapps

,field,original,translated,changed
0,title,Senior Fullstack Engineer — Produtos Financeiros (Miniapps),Senior Fullstack Engineer — Financial Products (Miniapps),True
1,company_profile,Rock Encantech,Rock Encantech,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://rockencantech.com.br Construa experiências financeiras digitais de ponta a ponta A Akropoli está desenvolvendo produtos financeiros integrados à jo...,Headquarters: BR URL: http://rockencantech.com.br Build end-to-end digital financial experiences Akropoli is developing financial products integrated into the retail consumer j...,True
5,requirements,Cross-Browser Development and Cross-Selling,Cross-Browser Development and Cross-Selling,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Fullstack Engineer — Produtos Financeiros (Miniapps)

[company_profile]
Rock Encantech

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://rockencantech.com.br Construa experiências financeiras digitais de ponta a ponta A Akropoli está desenvolvendo produtos financeiros integrados à jornada de consumo do varejo. Como parte do ecossistema da Rock Encantech, temos acesso a um conjunto único de dados que permite criar experiências financeiras altamente contextualizadas. Estamos buscando um Senior Fullstack Engineer para construir miniapps financeiros modernos — atuando tanto na experiência do usuário quanto na lógica de backend e integração com serviços financeiros . O problema que estamos resolvendo Criar experiências financeiras digitais simples, rápidas e confiáveis dentro da jornada de consumo. Isso significa permitir que usuários acessem serviços como crédito, pagamentos e inteligência financeira diretamente no momento da compra , com baixa fricção e alta performance. O que você fará Desenvolver aplicações fullstack (frontend + backend) para produtos financeiros Construir miniapps integrados a apps, marketplaces e superapps Desenvolver e evoluir APIs que suportam as jornadas financeiras Trabalhar próximo aos times de produto, design e dados Garantir qualidade, performance e escalabilidade das soluções Participar de decisões arquiteturais com foco em simplicidade e velocidade Stack e ambiente tecnológico Trabalhamos com um stack moderno e orientado a produto: React ou Flutter (frontend) Node.js / APIs REST (backend) JavaScript / TypeScript arquitetura baseada em microserviços integração com serviços externos (Open Finance, pagamentos, crédito) design systems modernos O perfil que buscamos Experiência sólida como Fullstack Engineer Forte domínio de JavaScript ou TypeScript Experiência com desenvolvimento de APIs Experiência com aplicações digitais escaláveis Capacidade de atuar com autonomia e visão de produto Mentalidade pragmática (foco em entregar valor rápido) Diferenciais Experiência em fintechs ou produtos financeiros Experiência com miniapps, superapps ou marketplaces Experiência com integrações de pagamentos ou crédito Experiência com arquitetura orientada a eventos Por que essa oportunidade é única Construir produtos financeiros baseados em dados reais de consumo Atuar de ponta a ponta, com alto nível de autonomia Trabalhar em problemas reais de crédito, pagamentos e comportamento financeiro Participar de uma plataforma em crescimento dentro do ecossistema da Rock Encantech To apply: https://weworkremotely.com/remote-jobs/rock-encantech-senior-fullstack-engineer-produtos-financeiros-miniapps

[requirements]
Cross-Browser Development and Cross-Selling

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
Senior Fullstack Engineer — Financial Products (Miniapps)

[company_profile]
Rock Encantech

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://rockencantech.com.br Build end-to-end digital financial experiences Akropoli is developing financial products integrated into the retail consumer journey. As part of the Rock Encantech ecosystem, we have access to a unique set of data that allows us to create highly contextualized financial experiences. We are looking for a Senior Fullstack Engineer to build modern financial mini-apps — working on both user experience and backend logic and integration with financial services. The problem we are solving Create simple, fast and reliable digital financial experiences within the consumer journey. This means allowing users to access services such as credit, payments and financial intelligence directly at the time of purchase, with low friction and high performance. What you will do Develop fullstack applications (frontend + backend) for financial products Build miniapps integrated with apps, marketplaces and superapps Develop and evolve APIs that support financial journeys Work closely with product, design and data teams Ensure quality, performance and scalability of solutions Participate in architectural decisions with a focus on simplicity and speed Stack and technological environment We work with a modern, product-oriented stack: React or Flutter (frontend) Node.js / APIs REST (backend) JavaScript / TypeScript architecture based on microservices integration with external services (Open Finance, payments, credit) modern design systems The profile we are looking for Solid experience as a Fullstack Engineer Strong command of JavaScript or TypeScript Experience with API development Experience with scalable digital applications Ability to

act with autonomy and product vision Pragmatic mentality (focus on delivering quick value) Differentiators Experience in fintechs or financial products Experience with miniapps, superapps or marketplaces Experience with payment or credit integrations Experience with event-driven architecture Why this opportunity is unique Build financial products based on real consumer data Act end-to-end, with a high level of autonomy Work on real credit, payments and financial behavior problems Participate in a growing platform within the Rock Encantech ecosystem To apply: https://weworkremotely.com/remote-jobs/rock-encantech-senior-fullstack-engineer-produtos-financieiros-miniapps

[requirements]
Cross-Browser Development and Cross-Selling

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #18 | Pessoa Desenvolvedora Backend Sênior
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/cora-pessoa-desenvolvedora-backend-senior
- apply_url: https://weworkremotely.com/remote-jobs/cora-pessoa-desenvolvedora-backend-senior

,field,original,translated,changed
0,title,Pessoa Desenvolvedora Backend Sênior,Senior Backend Developer Person,True
1,company_profile,Cora,Cora,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: BR URL: http://cora.com.br Vem trabalhar com a gente. Vem ser Cora! Sobre a Cora Das 21 milhões de empresas do Brasil, 93% são pequenos e médios negócios e, apesa...","Headquarters: BR URL: http://cora.com.br Come work with us. Come be Cora! About Cora Of the 21 million companies in Brazil, 93% are small and medium-sized businesses and, despi...",True
5,requirements,"Cross-Browser Development, Paid Social Media Advertising, DevOps, Bug Tracking, Social Media Management, Cross-Selling, Social Media Ads, KPI Tracking, Social Media Content, an...","Cross-Browser Development, Paid Social Media Advertising, DevOps, Bug Tracking, Social Media Management, Cross-Selling, Social Media Ads, KPI Tracking, Social Media Content, an...",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Management and Finance,Management and Finance,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Pessoa Desenvolvedora Backend Sênior

[company_profile]
Cora

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cora.com.br Vem trabalhar com a gente. Vem ser Cora! Sobre a Cora Das 21 milhões de empresas do Brasil, 93% são pequenos e médios negócios e, apesar de serem responsáveis por ⅓ do PIB do país e 60% dos empregos, as pequenas e médias empresas (PMEs) não são o foco da maioria das instituições financeiras. Isso muda com a Cora, banco digital criado exclusivamente para apoiar PMES. Com 5 anos de existência, já somamos mais de 1 milhão de clientes e 300 pessoas trabalhando de forma remota em vários lugares do Brasil. Dia a dia como Pessoa Desenvolvedora Backend Sênior na Cora Definir junto com o time de desenvolvimento e produto as melhores formas de construir soluções que se aprimorem a cada dia; Prezar pela qualidade do que vai ser desenvolvido; Entender a fundo o comportamento do cliente que vai usar a ferramenta desenvolvida. Quem estamos buscando Nosso desafio - e seu também, caso decida se aplicar - é construir sistemas manuteníveis, escaláveis, observáveis, resilientes e seguros. Manter e evoluir nossas aplicações e também construir produtos e aplicações novas. Aqui você terá incentivo para: Aprender novas tecnologias e ferramentas; Opinar e participar sobre construção de soluções desde sua arquitetura até sua implementação e operação; Fazer avaliação técnica na priorização de tarefas; Adquirir experiência com sistemas distribuídos, comunicação assíncrona (mensageria), alta disponibilidade e troubleshooting em produção; Escrever código com fluência e manutenibilidade; Ter proximidade com a área de dados e demais áreas que o produto se relacione. Ter facilidade para criar aplicações, arquiteturas, ferramentas e soluções para resolver os mais diversos problemas. O que esperamos de você: Uma pessoa comunicativa que agrega valor ao time e expõe a sua opinião, ideias e questionamentos; Experiência prévia como Back-End; Conhecimento em Java e Kotlin; Conhecimentos básicos em ferramentas de infraestrutura; Conhecimento em banco de dados; Padrões de arquitetura e Design Patterns; Experiência com API RESTful; Conhecimento básico de comunicação assíncrona entre serviços; Capacidade de produzir código limpo e de fácil manutenção; Testes unitários e automatizados; Experiência com o Git; Conhecimento em desenvolvimento utilizando micro serviços; Diferenciais: Conhecimento em Go; Conhecimento em Python; Conhecimento sobre ferramentas de IA em fluxos de produto; Cultura da Cora Potencializamos o espírito empreendedor e valorizamos quem empreende e vive a nossa Cultura no dia a dia. Precisamos de energia e inconformismo para resolver problemas dos nossos clientes, construindo (muitas vezes do zero) produtos e soluções financeiras simples e acessíveis para ajudar pessoas empreendedoras a tomar decisões informadas de negócio. Buscamos pessoas inconformadas e excelentes no que fazem (levantamos a barra), que trabalhem de forma autônoma e resolutiva (fazemos acontecer), colaborativa (trabalhamos juntos) e empática (pensamos nas pessoas). O que oferecemos Um ambiente dinâmico, com oportunidades de aprender construindo todos os dias, trabalhando de forma colaborativa e gerando alto direto para donos e donas de pequenos e médios negócios. Para te apoiar financeiramente: Remuneração competitiva Participação nos Lucros e Resultados (PLR) Benefícios Flexíveis no cartão Flash A partir de 1 ano de Cora, todas as pessoas podem adquirir Ações Para apoiar a sua saúde e bem-estar: Plano de Saúde Sulamerica com inclusão de dependentes Plano Odontológico Bradesco Apoio e suporte 24h da Pipo Saúde Parceria com Gympass Parceria com Zenklub Seguro de vida Zurich Licença parental estendida (180 dias para gestante e 90 dias para não gestante) Auxílio-creche para pais e mães com filhos até 6 anos. Auxílio financeiro para pais e mães com filhos com deficiência. Modelo de trabalho flexível: Trabalho 100% remoto Day Off de aniversário 5 Day Offs por ano para emendar feriados ou combinar uma folga Auxílio Home Office mensal Banco de horas semestral e flexibilidade nos horários de entrada e saída desde que dentro do horário comercial (08h-20h) Equipamentos para trabalhar em casa (monitor extra, cadeira, escrivaninha, fone de ouvido e apoio para pé) Convênio com a plataforma de Coworkings Woba Oportunidade de desenvolvimento: Auxílio Aprendizagem de R$ 3.000 por ano para cursos, livros, eventos, graduação, pós graduação, entre outros; Para profissionais em início de carreira, o benefício é de R$ 4.000. Informações Adicionais Política de Privacidade: Fazemos algumas perguntas já nesse primeiro momento pensando em agilizar o seu processo. Se quiser saber mais sobre como usamos os dados, pode conferir nossa Política de Privacidade aqui . Para saber mais sobre a Cora: visite nosso site e nosso LinkedIn. To apply: https://weworkremotely.com/remote-jobs/cora-pessoa-desenvolvedora-backend-senior

[requirements]
Cross-Browser Development, Paid Social Media Advertising, DevOps, Bug Tracking, Social Media Management, Cross-Selling, Social Media Ads, KPI Tracking, Social Media Content, and Inventory Tracking

[employment_type]
Full-Time

[industry]
Management and Finance

**Translated Full Posting Text**

[title]
Senior Backend Developer Person

[company_profile]
Cora

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cora.com.br Come work with us. Come be Cora! About Cora Of the 21 million companies in Brazil, 93% are small and medium-sized businesses and, despite being responsible for ⅓ of the country's GDP and 60% of jobs, small and medium-sized companies (SMEs) are not the focus of most financial institutions. This changes with Cora, a digital bank created exclusively to support SMES. With 5 years of existence, we already have more than 1 million customers and 300 people working remotely in various places in Brazil. Day to day as a Senior Backend Developer at Cora Define together with the development and product team the best ways to build solutions that improve every day; Value the quality of what will be developed; Understand in depth the behavior of the customer who will use the developed tool. Who we are looking for Our challenge - and yours too, if you decide to apply yourself - is to build maintainable, scalable, observable, resilient and secure systems. Maintain and evolve our applications and also build new products and applications. Here you will be encouraged to: Learn new technologies and tools; Give your opinion and participate in the construction of solutions from their architecture to their implementation and operation; Perform technical assessment in prioritizing tasks; Gain experience with distributed systems, asynchronous communication (messaging), high availability and troubleshooting in production; Write code fluently and maintainably; Be close to the data area and other areas that the product relates to. Be able to create applications, architectures, tools and solutions to solve the most diverse problems. What we expect from you: A communicative person who adds value to the team and

expresses your opinion, ideas and questions; Previous experience as Back-End; Knowledge of Java and Kotlin; Basic knowledge of infrastructure tools; Database knowledge; Architecture patterns and Design Patterns; Experience with RESTful API; Basic knowledge of asynchronous communication between services; Ability to produce clean and maintainable code; Unit and automated tests; Experience with Git; Knowledge in development using microservices; Differentiators: Knowledge of Go; Knowledge of Python; Knowledge of AI tools in product flows; Cora Culture We enhance the entrepreneurial spirit and value those who undertake and live our Culture on a daily basis. We need energy and non-conformity to solve our customers' problems, building (often from scratch) simple and accessible financial products and solutions to help entrepreneurs make informed business decisions. We are looking for non-conformist people who are excellent at what they do (we raise the bar), who work autonomously and resolutely (we make it happen), collaborative (we work together) and empathetic (we think about people). What we offer A dynamic environment, with opportunities to learn by building every day, working collaboratively and generating direct income for owners of small and medium-sized businesses. To support you financially: Competitive remuneration Profit Sharing (PLR) Flexible Benefits on the Flash card From 1 year of Cora, everyone can acquire Shares To support their health and well-being: Sulamerica Health Plan with inclusion of dependents Bradesco Dental Plan Support and 24-hour support from Pipo Saúde Partnership with Gympass Partnership with

Zenklub Zurich life insurance Extended parental leave (180 days for pregnant women and 90 days for non-pregnant women) Childcare allowance for fathers and mothers with children up to 6 years old. Financial assistance for fathers and mothers with children with disabilities. Flexible working model: 100% remote work Birthday Day Off 5 Day Offs per year to amend holidays or arrange a day off Monthly Home Office Allowance Semiannual hours bank and flexibility in arrival and departure times as long as they are within business hours (08h-20h) Equipment for working from home (extra monitor, chair, desk, headset and footrest) Agreement with the Woba Coworking platform Development opportunity: Assistance Learning of R$3,000 per year for courses, books, events, undergraduate, postgraduate, among others; For professionals at the beginning of their careers, the benefit is R$4,000. Additional Information Privacy Policy: We ask a few questions at the outset to speed up your process. If you want to know more about how we use data, you can check our Privacy Policy here. To learn more about Cora: visit our website and our LinkedIn. To apply: https://weworkremotely.com/remote-jobs/cora-pessoa-desenvolvedora-backend-senior

[requirements]
Cross-Browser Development, Paid Social Media Advertising, DevOps, Bug Tracking, Social Media Management, Cross-Selling, Social Media Ads, KPI Tracking, Social Media Content, and Inventory Tracking

[employment_type]
Full-Time

[industry]
Management and Finance

---

### #19 | Data Labeling Specialist — Remote Contract Work ($18-$22 per hour)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/workada-data-labeling-specialist-remote-contract-work-18-22-per-hour
- apply_url: https://weworkremotely.com/remote-jobs/workada-data-labeling-specialist-remote-contract-work-18-22-per-hour

,field,original,translated,changed
0,title,Data Labeling Specialist — Remote Contract Work ($18-$22 per hour),Data Labeling Specialist — Remote Contract Work ($18-$22 per hour),False
1,company_profile,Workada,Workada,False
2,location,"Anywhere in the World, California, 🇺🇸 United States of America","Anywhere in the World, California, 🇺🇸 United States of America",False
3,department,,,False
4,description,"Headquarters: San Francisco URL: http://workada.co Who We Are Workada creates high-quality labeled data for advanced technology systems. Our team reviews, organizes, categorize...","Headquarters: San Francisco URL: http://workada.co Who We Are Workada creates high-quality labeled data for advanced technology systems. Our team reviews, organizes, categorize...",False
5,requirements,"Digital Marketing, Visual Hierarchy, Data Visualization, Data Entry, Data Extraction, and Data Annotation","Digital Marketing, Visual Hierarchy, Data Visualization, Data Entry, Data Extraction, and Data Annotation",False
6,benefits,,,False
7,employment_type,Contract,Contract,False
8,required_experience,,,False
9,required_education,,,False
10,industry,All Other Remote,All Other Remote,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Data Labeling Specialist — Remote Contract Work ($18-$22 per hour)

[company_profile]
Workada

[location]
Anywhere in the World, California, 🇺🇸 United States of America

[description]
Headquarters: San Francisco URL: http://workada.co Who We Are Workada creates high-quality labeled data for advanced technology systems. Our team reviews, organizes, categorizes, evaluates, and quality-checks digital content so those systems can better understand information and perform real-world tasks. We believe careful data work matters. Every reviewed item, categorized example, and quality-checked task helps improve how technology interprets information, follows instructions, and responds in practical settings. About You We're hiring detail-oriented individuals who are comfortable working on a computer and interested in careful, focused digital work. We're especially interested in: People who can carefully review written information, images, documents, or other digital content Strong readers and writers with good judgment People who can follow detailed instructions consistently Individuals who are comfortable using web-based tools and online platforms People who take quality seriously and can spot mistakes or inconsistencies Those who enjoy focused, independent work while contributing to a larger project Strong character matters — we value integrity, reliability, curiosity, and a commitment to high-quality work Qualifications Comfortable using a computer for extended periods Reliable internet connection Strong attention to detail Ability to follow written guidelines and project instructions Clear written communication skills Basic familiarity with spreadsheets, online forms, or web-based work tools Ability to work independently and meet deadlines Prior experience in data labeling, annotation, quality review, research, writing, customer support, operations, or administrative work is helpful but not required Compensation Compensation is $18- $22 an hour and a max of 40 hours a week. A Place to Do Meaningful Work Data labeling may sound simple, but it plays an important role in improving the technology people use every day. At Workada, your work helps create the examples and feedback that make advanced systems more accurate, consistent, and useful. We're looking for people who care about accuracy, consistency, and careful judgment. Whether you're reviewing text, categorizing information, evaluating responses, or checking data quality, your work helps improve the way technology performs. To apply: https://weworkremotely.com/remote-jobs/workada-data-labeling-specialist-remote-contract-work-18-22-per-hour

[requirements]
Digital Marketing, Visual Hierarchy, Data Visualization, Data Entry, Data Extraction, and Data Annotation

[employment_type]
Contract

[industry]
All Other Remote

**Translated Full Posting Text**

[title]
Data Labeling Specialist — Remote Contract Work ($18-$22 per hour)

[company_profile]
Workada

[location]
Anywhere in the World, California, 🇺🇸 United States of America

[description]
Headquarters: San Francisco URL: http://workada.co Who We Are Workada creates high-quality labeled data for advanced technology systems. Our team reviews, organizes, categorizes, evaluates, and quality-checks digital content so those systems can better understand information and perform real-world tasks. We believe careful data work matters. Every reviewed item, categorized example, and quality-checked task helps improve how technology interprets information, follows instructions, and responds in practical settings. About You We're hiring detail-oriented individuals who are comfortable working on a computer and interested in careful, focused digital work. We're especially interested in: People who can carefully review written information, images, documents, or other digital content Strong readers and writers with good judgment People who can follow detailed instructions consistently Individuals who are comfortable using web-based tools and online platforms People who take quality seriously and can spot mistakes or inconsistencies Those who enjoy focused, independent work while contributing to a larger project Strong character matters — we value integrity, reliability, curiosity, and a commitment to high-quality work Qualifications Comfortable using a computer for extended periods Reliable internet connection Strong attention to detail Ability to follow written guidelines and project instructions Clear written communication skills Basic familiarity with spreadsheets, online forms, or web-based work tools Ability to work independently and meet deadlines Prior experience in data labeling, annotation, quality review, research, writing, customer support, operations, or administrative work is helpful but not required Compensation Compensation is $18- $22 an hour and a max of 40 hours a week. A Place to Do Meaningful Work Data labeling may sound simple, but it plays an important role in improving the technology people use every day. At Workada, your work helps create the examples and feedback that make advanced systems more accurate, consistent, and useful. We're looking for people who care about accuracy, consistency, and careful judgment. Whether you're reviewing text, categorizing information, evaluating responses, or checking data quality, your work helps improve the way technology performs. To apply: https://weworkremotely.com/remote-jobs/workada-data-labeling-specialist-remote-contract-work-18-22-per-hour

[requirements]
Digital Marketing, Visual Hierarchy, Data Visualization, Data Entry, Data Extraction, and Data Annotation

[employment_type]
Contract

[industry]
All Other Remote

---

### #20 | Profissional Web Designer Sênior
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1
- apply_url: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1

,field,original,translated,changed
0,title,Profissional Web Designer Sênior,Professional Senior Web Designer,True
1,company_profile,Radix,Radix,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://radixeng.com.br A primeira coisa que você precisa saber é que aqui você não vai cair na rotina. A Radix desenvolve soluções para empresas de difere...,Headquarters: BR URL: http://radixeng.com.br The first thing you need to know is that here you won't fall into a routine. Radix develops solutions for companies from different ...,True
5,requirements,,,False
6,benefits,,,False
7,employment_type,,,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Front-End Programming,Front End Programming,True
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Profissional Web Designer Sênior

[company_profile]
Radix

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://radixeng.com.br A primeira coisa que você precisa saber é que aqui você não vai cair na rotina. A Radix desenvolve soluções para empresas de diferentes setores e indústrias. Cada projeto tem suas tecnologias, soluções e prazos e você terá oportunidade de atuar e experimentar diferentes desafios. Além da nossa atuação pelo Brasil, com escritório no Rio de janeiro, São Paulo e Belo Horizonte, temos também filiais nos Estados Unidos, fazendo com que a Radix se consolide cada vez mais como uma empresa global . Quer fazer parte dessa história e transformar ideias e sonhos em realidade? Como Web Designer você vai: Responsabilidades: Executar atividades de design em projetos variados, garantindo qualidade e aderência aos prazos e objetivos acordados; Criar interfaces e experiências inovadoras, incorporando soluções de Inteligência Artificial (AI) e Generative AI (GenAI) para otimização de fluxos, personalização de conteúdo e automação de interações; Manter-se atualizado quanto às metodologias e ferramentas de UX/UI e AI/GenAI, promovendo inovação nos projetos; Realizar pesquisas com usuários, desenvolver personas, mapear jornadas do usuário e construir protótipos de baixa e alta fidelidade; Testar e validar experiências com usuários, coletando feedbacks e refinando interações suportadas por AI/GenAI; Colaborar com equipes de Produto, Engajamento e Comercial, integrando insights de AI/GenAI para melhorar a experiência do usuário; Contribuir para a excelência da equipe de Design, promovendo mentorias, revisões e treinamentos; Desenvolver interfaces funcionais utilizando frameworks fornecidos pelo cliente ou plataformas de desenvolvimento de mercado, incorporando componentes de AI/GenAI quando aplicável. Pré-Requisitos: Inglês avançado para conversação; Experiência sólida com UX/UI, incluindo prototipagem para web e aplicativos (desktop, tablet, mobile); Conhecimento em Design Thinking e metodologias centradas no usuário; Experiência prática ou interesse em AI e GenAI aplicado a interfaces e experiências digitais; Ter portfólio robusto, demonstrando habilidades em design de interface e experiência do usuário; Ter proficiência em Figma e Adobe XD. Desejável: Conhecimentos básicos em CSS e HTML; Familiaridade com metodologias ágeis (Scrum, Kanban); Experiência em ferramentas de colaboração (Miro, InVision); Experiência na integração de AI/GenAI em fluxos de UX, automação e personalização de interfaces. Benefícios: Assistência Médica Nacional (para o titular e dependentes, com quarto privativo) Assistência odontológica nacional (para o titular e dependentes) Vale refeição / alimentação flexível Auxílio home office Day off (no mês do aniversário) Wellhub (antigo Gympass) Licença Maternidade (6 meses) e Paternidade (20 dias) estendidas Auxílio creche para filhos de até 3 anos (por filho) Apoio em saúde mental com a Wellz Clube de Vantagens com descontos em diversos parceiros Convênio com instituições de ensino e cursos de idioma Desenvolvimento Profissional (Universidade Corporativa) Parceria com empresa de coworkings no Brasil Programa de Qualidade de Vida e Bem-Estar Médico consultor para acompanhamento de radixers Planos de incentivos A Radix está sempre no topo das Melhores Empresas para se trabalhar porque: Temos profissionais comprometidos, dedicados, curiosos e inovadores. O espírito de equipe é a nossa maior força. Trabalhamos de forma cooperativa e sabemos que estamos juntos, remando na mesma direção. Temos um ambiente diverso, que valoriza equidade e inclusão. Nossa jornada de trabalho é flexível e em quase todos os projetos é possível trabalhar de qualquer lugar do Brasil. Valorizamos o bem-estar e o cuidado com as nossas pessoas, com programas de apoio à saúde mental, psiquiatra e médico consultor disponíveis. Curtiu? #VemPraRadix Código da vaga: 9fbb To apply: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1

[industry]
Front-End Programming

**Translated Full Posting Text**

[title]
Professional Senior Web Designer

[company_profile]
Radix

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://radixeng.com.br The first thing you need to know is that here you won't fall into a routine. Radix develops solutions for companies from different sectors and industries. Each project has its technologies, solutions and deadlines and you will have the opportunity to act and experience different challenges. In addition to our operations in Brazil, with offices in Rio de Janeiro, São Paulo and Belo Horizonte, we also have branches in the United States, making Radix increasingly consolidated as a global company. Do you want to be part of this story and turn ideas and dreams into reality? As a Web Designer you will: Responsibilities: Carry out design activities on various projects, ensuring quality and adherence to agreed deadlines and objectives; Create innovative interfaces and experiences, incorporating Artificial Intelligence (AI) and Generative AI (GenAI) solutions to optimize flows, personalize content and automate interactions; Keep up to date with UX/UI and AI/GenAI methodologies and tools, promoting innovation in projects; Conduct user research, develop personas, map user journeys and build low and high fidelity prototypes; Test and validate user experiences, collecting feedback and refining interactions supported by AI/GenAI; Collaborate with Product, Engagement and Commercial teams, integrating AI/GenAI insights to improve user experience; Contribute to the excellence of the Design team, promoting mentoring, reviews and training; Develop functional interfaces using customer-supplied frameworks or market development platforms, incorporating AI/GenAI components when applicable. Prerequisites: Advanced English for

conversation; Solid experience with UX/UI, including prototyping for web and applications (desktop, tablet, mobile); Knowledge of Design Thinking and user-centered methodologies; Practical experience or interest in AI and GenAI applied to digital interfaces and experiences; Have a robust portfolio, demonstrating skills in interface design and user experience; Have proficiency in Figma and Adobe XD. Desirable: Basic knowledge of CSS and HTML; Familiarity with agile methodologies (Scrum, Kanban); Experience in collaboration tools (Miro, InVision); Experience in integrating AI/GenAI into UX flows, automation and interface customization. Benefits: National Medical Assistance (for the holder and dependents, with a private room) National dental assistance (for the holder and dependents) Flexible meal/food voucher Home office assistance Day off (in the month of the birthday) Wellhub (formerly Gympass) Maternity (6 months) and Paternity (20 days) leave extended Daycare allowance for children up to 3 years old (per child) Mental health support with Wellz Advantages Club with discounts from several partners Agreement with educational institutions and language courses Professional Development (Corporate University) Partnership with coworking company in Brazil Quality of Life and Wellbeing Program Consultant doctor to monitor radixers Incentive plans Radix is always at the top of the Best Companies to work for because: We have committed, dedicated, curious and innovative professionals. Team spirit is our greatest strength. We work cooperatively and know that we are together, rowing in the same direction. We have a diverse environment, which values ​​equity and inclusion. Our working hours are flexible and

In almost all projects it is possible to work from anywhere in Brazil. We value the well-being and care of our people, with mental health support programs, psychiatrists and consultant doctors available. Did you like it? #VemPraRadix Job code: 9fbb To apply: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1

[industry]
Front End Programming

---

### #21 | Profissional Web Designer Sênior
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1
- apply_url: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1

,field,original,translated,changed
0,title,Profissional Web Designer Sênior,Professional Senior Web Designer,True
1,company_profile,Radix,Radix,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://radixeng.com.br A primeira coisa que você precisa saber é que aqui você não vai cair na rotina. A Radix desenvolve soluções para empresas de difere...,Headquarters: BR URL: http://radixeng.com.br The first thing you need to know is that here you won't fall into a routine. Radix develops solutions for companies from different ...,True
5,requirements,"Cross-Browser Development, Graphic Design, and Cross-Selling","Cross-Browser Development, Graphic Design, and Cross-Selling",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Front-End Programming,Front End Programming,True
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Profissional Web Designer Sênior

[company_profile]
Radix

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://radixeng.com.br A primeira coisa que você precisa saber é que aqui você não vai cair na rotina. A Radix desenvolve soluções para empresas de diferentes setores e indústrias. Cada projeto tem suas tecnologias, soluções e prazos e você terá oportunidade de atuar e experimentar diferentes desafios. Além da nossa atuação pelo Brasil, com escritório no Rio de janeiro, São Paulo e Belo Horizonte, temos também filiais nos Estados Unidos, fazendo com que a Radix se consolide cada vez mais como uma empresa global . Quer fazer parte dessa história e transformar ideias e sonhos em realidade? Como Web Designer você vai: Responsabilidades: Executar atividades de design em projetos variados, garantindo qualidade e aderência aos prazos e objetivos acordados; Criar interfaces e experiências inovadoras, incorporando soluções de Inteligência Artificial (AI) e Generative AI (GenAI) para otimização de fluxos, personalização de conteúdo e automação de interações; Manter-se atualizado quanto às metodologias e ferramentas de UX/UI e AI/GenAI, promovendo inovação nos projetos; Realizar pesquisas com usuários, desenvolver personas, mapear jornadas do usuário e construir protótipos de baixa e alta fidelidade; Testar e validar experiências com usuários, coletando feedbacks e refinando interações suportadas por AI/GenAI; Colaborar com equipes de Produto, Engajamento e Comercial, integrando insights de AI/GenAI para melhorar a experiência do usuário; Contribuir para a excelência da equipe de Design, promovendo mentorias, revisões e treinamentos; Desenvolver interfaces funcionais utilizando frameworks fornecidos pelo cliente ou plataformas de desenvolvimento de mercado, incorporando componentes de AI/GenAI quando aplicável. Pré-Requisitos: Inglês avançado para conversação; Experiência sólida com UX/UI, incluindo prototipagem para web e aplicativos (desktop, tablet, mobile); Conhecimento em Design Thinking e metodologias centradas no usuário; Experiência prática ou interesse em AI e GenAI aplicado a interfaces e experiências digitais; Ter portfólio robusto, demonstrando habilidades em design de interface e experiência do usuário; Ter proficiência em Figma e Adobe XD. Desejável: Conhecimentos básicos em CSS e HTML; Familiaridade com metodologias ágeis (Scrum, Kanban); Experiência em ferramentas de colaboração (Miro, InVision); Experiência na integração de AI/GenAI em fluxos de UX, automação e personalização de interfaces. Benefícios: Assistência Médica Nacional (para o titular e dependentes, com quarto privativo) Assistência odontológica nacional (para o titular e dependentes) Vale refeição / alimentação flexível Auxílio home office Day off (no mês do aniversário) Wellhub (antigo Gympass) Licença Maternidade (6 meses) e Paternidade (20 dias) estendidas Auxílio creche para filhos de até 3 anos (por filho) Apoio em saúde mental com a Wellz Clube de Vantagens com descontos em diversos parceiros Convênio com instituições de ensino e cursos de idioma Desenvolvimento Profissional (Universidade Corporativa) Parceria com empresa de coworkings no Brasil Programa de Qualidade de Vida e Bem-Estar Médico consultor para acompanhamento de radixers Planos de incentivos A Radix está sempre no topo das Melhores Empresas para se trabalhar porque: Temos profissionais comprometidos, dedicados, curiosos e inovadores. O espírito de equipe é a nossa maior força. Trabalhamos de forma cooperativa e sabemos que estamos juntos, remando na mesma direção. Temos um ambiente diverso, que valoriza equidade e inclusão. Nossa jornada de trabalho é flexível e em quase todos os projetos é possível trabalhar de qualquer lugar do Brasil. Valorizamos o bem-estar e o cuidado com as nossas pessoas, com programas de apoio à saúde mental, psiquiatra e médico consultor disponíveis. Curtiu? #VemPraRadix Código da vaga: 88ab To apply: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1

[requirements]
Cross-Browser Development, Graphic Design, and Cross-Selling

[employment_type]
Full-Time

[industry]
Front-End Programming

**Translated Full Posting Text**

[title]
Professional Senior Web Designer

[company_profile]
Radix

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://radixeng.com.br The first thing you need to know is that here you won't fall into a routine. Radix develops solutions for companies from different sectors and industries. Each project has its technologies, solutions and deadlines and you will have the opportunity to act and experience different challenges. In addition to our operations in Brazil, with offices in Rio de Janeiro, São Paulo and Belo Horizonte, we also have branches in the United States, making Radix increasingly consolidated as a global company. Do you want to be part of this story and turn ideas and dreams into reality? As a Web Designer you will: Responsibilities: Carry out design activities on various projects, ensuring quality and adherence to agreed deadlines and objectives; Create innovative interfaces and experiences, incorporating Artificial Intelligence (AI) and Generative AI (GenAI) solutions to optimize flows, personalize content and automate interactions; Keep up to date with UX/UI and AI/GenAI methodologies and tools, promoting innovation in projects; Conduct user research, develop personas, map user journeys and build low and high fidelity prototypes; Test and validate user experiences, collecting feedback and refining interactions supported by AI/GenAI; Collaborate with Product, Engagement and Commercial teams, integrating AI/GenAI insights to improve user experience; Contribute to the excellence of the Design team, promoting mentoring, reviews and training; Develop functional interfaces using customer-supplied frameworks or market development platforms, incorporating AI/GenAI components when applicable. Prerequisites: Advanced English for

conversation; Solid experience with UX/UI, including prototyping for web and applications (desktop, tablet, mobile); Knowledge of Design Thinking and user-centered methodologies; Practical experience or interest in AI and GenAI applied to digital interfaces and experiences; Have a robust portfolio, demonstrating skills in interface design and user experience; Have proficiency in Figma and Adobe XD. Desirable: Basic knowledge of CSS and HTML; Familiarity with agile methodologies (Scrum, Kanban); Experience in collaboration tools (Miro, InVision); Experience in integrating AI/GenAI into UX flows, automation and interface customization. Benefits: National Medical Assistance (for the holder and dependents, with a private room) National dental assistance (for the holder and dependents) Flexible meal/food voucher Home office assistance Day off (in the month of the birthday) Wellhub (formerly Gympass) Maternity (6 months) and Paternity (20 days) leave extended Daycare allowance for children up to 3 years old (per child) Mental health support with Wellz Advantages Club with discounts from several partners Agreement with educational institutions and language courses Professional Development (Corporate University) Partnership with coworking company in Brazil Quality of Life and Wellbeing Program Consultant doctor to monitor radixers Incentive plans Radix is always at the top of the Best Companies to work for because: We have committed, dedicated, curious and innovative professionals. Team spirit is our greatest strength. We work cooperatively and know that we are together, rowing in the same direction. We have a diverse environment, which values ​​equity and inclusion. Our working hours are flexible and

In almost all projects it is possible to work from anywhere in Brazil. We value the well-being and care of our people, with mental health support programs, psychiatrists and consultant doctors available. Did you like it? #VemPraRadix Job code: 88ab To apply: https://weworkremotely.com/remote-jobs/radix-profissional-web-designer-senior-1

[requirements]
Cross-Browser Development, Graphic Design, and Cross-Selling

[employment_type]
Full-Time

[industry]
Front End Programming

---

### #22 | Senior Product Manager - Remote - 13.5-18.3k CLT
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/vinta-senior-product-manager-remote-13-5-18-3k-clt
- apply_url: https://weworkremotely.com/remote-jobs/vinta-senior-product-manager-remote-13-5-18-3k-clt

,field,original,translated,changed
0,title,Senior Product Manager - Remote - 13.5-18.3k CLT,Senior Product Manager - Remote - 13.5-18.3k CLT,False
1,company_profile,Vinta,Vinta,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: BR URL: http://vinta.com.br Quem somos A Vinta é uma consultoria de produtos digitais para clientes internacionais em diversos setores há mais de uma década, com ...","Headquarters: BR URL: http://vinta.com.br Who we are Vinta has been a digital product consultancy for international clients in various sectors for over a decade, with a technic...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Front-End Programming,Front End Programming,True
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Product Manager - Remote - 13.5-18.3k CLT

[company_profile]
Vinta

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://vinta.com.br Quem somos A Vinta é uma consultoria de produtos digitais para clientes internacionais em diversos setores há mais de uma década, com um time técnico que constrói excelência num ambiente de melhoramento colaborativo e saudável. Trabalhamos viabilizando tecnicamente a visão de produtos digitais com as melhores práticas de software, trazendo qualidade, escalabilidade e eficiência, e estabelecendo relações de longo prazo com nossos clientes e profissionais. Nosso diferencial são os times que possuem cultura forte, numa interface próxima com os clientes. Esse trabalho só é possível em um ambiente altamente colaborativo que trabalha numa aplicação de ponta-a-ponta, com espaços de desenvolvimento e crescimento, segurança e flexibilidade. Somos 100% remotos e async first. A comunicação assíncrona é central em nosso dia-a-dia, nos favorecendo horas de trabalho focado sem interrupções. Transformar reuniões em reports assíncronos nos ajuda a promover qualidade de vida e equilíbrio entre vida pessoal e profissional de verdade! Para conhecer mais, veja o nosso site . Temos também muita colaboração pra comunidade de código aberto em nosso Github , e palestras disponíveis em nosso canal do Youtube . Dá uma olhada também em nosso Glassdoor ! Seu trabalho na Vinta O mercado de healthcare nos Estados Unidos é grande, e repleto de soluções tecnológicas burocráticas, pesadas e datadas que não conversam com as necessidades de seus usuários finais - médicas, enfermeiras, equipes interdisciplinares, hospitais e operadoras de saúde. A Vinta tem obtido sucesso nesse mercado se posicionando como uma facilitadora da inovação nessa área, simplificando a construção de produtos de saúde que falem diretamente com o que o mercado precisa. Você construirá a visão, estratégia e a execução do nosso principal produto proprietário: o Vinta Building Blocks, um conjunto de funcionalidades e componentes para construção de produtos healthtech, onde você atuará como Product Owner. Seu objetivo é conhecer o ecossistema de saúde dos EUA a fundo (seus EHR’s, possibilidades de AI e seus agentes, e Design Systems), transformando componentes isolados em experiências unificadas que garantam um time-to-market acelerado para novos projetos healthtech, habilitando o time técnico de devs e design para a geração de valor. Você também viabilizará e acompanhará esse projeto para que seja tecnicamente viável, considerando riscos, oportunidades e recursos, fornecendo soluções para construir e acelerar o produto e nosso time, atendendo os objetivos, visões e preocupações de nossos stakeholders internos, CPO e CTO. Com esse domínio de mercado, você também auxiliará o Expansion com discovery contínuo e outras ações que convertam leads e expandem contas atuais, demonstrando tecnicamente como nossos building blocks resolvem os problemas de negócio dos clientes, gerando provas sociais em demos que mostram como nossa consultoria healthtech é exatamente o que eles precisam pra os produtos digitais de saúde deles. Pessoas gestoras de time na Vinta também paralelizam atividades em outros projetos. Apesar desse ser o escopo inicial de seu trabalho, esperamos que após algum tempo assentada nessa posição, que você também ganhe contexto de outros projetos e atue neles com outro time. Experiência que buscamos: Prática com discovery contínuo: Baseando soluções em dores reais de leads, clientes e pesquisa de mercado, para impulsionar a adesão a nossos produtos e conversão de nossas propostas para o ecossistema de saúde dos EUA. Independência estratégica: Autonomia para guiar a estratégia, roadmap e rotina desses Building Blocks, questionando C-levels e time técnico com base em dados e visão de produto. Capacidade de inovação: Desenhando e coordenando a UX/UI dos componentes modulares de nosso produto junto devs e designers, experimentando e construindo esse produto para que seja AI-native Velocidade e Pragmatismo: Foco em time-to-market, priorizando prototipar, testar e iterar em ciclos curtos, focando em escopos estratégicos e remover bloqueios de time, produto e stakeholders. Direcionamento de time: Esperamos que você lidere sua equipe de desenvolvimento e design, agindo estrategicamente para garantir objetivos claros e que habilite a produtividade da equipe numa cultura colaborativa, garantindo feedback contínuo e orientação para o crescimento da equipe. Paralelizando times: Nossa expectativa é que após esteja assentada nessa primeira cadeira, você seja capaz de também direcionar outros times técnicos em outros projetos, negociando escopos e acompanhando entregas entregas do time e satisfação de clientes. Competência comunicacional: Fluente em inglês para atuar amparando Expansion e projetos, vendendo nossa visão de produto e técnica de forma persuasiva. É diferencial se você: Tiver entendimento do ecossistema de saúde digital (EHRs, workflows clínicos, Medplum/FHIR); Tiver vivência montando produtos AI-native; Nossos benefícios: Salário de R$ 13.500 a R$ 18.300 no regime CLT, reajustado anualmente; O Vinta Beyond Program remunera, de forma variável e anual, o equivalente a até dois salários e meio, com metas com base em sua performance e desenvolvimento da Vinta; Vinta +Home: Use R$ 500 mensais, de maneira totalmente flexível, para deixar sua experiência de home-office mais confortável. Equidade de licença parental: 4 meses de licença paternidade para filhos adotivos e biológicos, para todos os tipos de família; Cartão Flash: R$ 1600 em benefícios mensais em cartão bandeira Visa, a ser usado em múltiplos estabelecimentos: restaurantes, iFood e Uber Eats, supermercados, postos de gasolina, etc.; SulAmérica saúde e odontológico nacional, com direito a parto e quarto, totalmente pago pela Vinta e sem abatimento na folha. A inclusão dos dois primeiros dependentes também é coberta pelo benefício; Auxílio-creche: R$ 347 reais mensais até 6 anos, 11 meses e 29 dias da criança. Compra de cursos, livros e material técnico para seu desenvolvimento profissional; Wellhub (antigo Gympass): acesso a diversas modalidades de atividades físicas e a uma ampla rede de academias e estúdios parceiros no país, para fazer quando e onde quiser. Além disso, você terá acesso a aulas individuais ou em grupo, e também a aplicativos de atividades físicas, bem-estar emocional, hábitos saudáveis e mais; Ingresso e bônus de até R$1500,00 adicional ao aprovar palestras em conferências nacionais alinhadas à estratégia da Vinta. Passagem e estadia também coberto em caso evento presenciais To apply: https://weworkremotely.com/remote-jobs/vinta-senior-product-manager-remote-13-5-18-3k-clt

[employment_type]
Full-Time

[industry]
Front-End Programming

**Translated Full Posting Text**

[title]
Senior Product Manager - Remote - 13.5-18.3k CLT

[company_profile]
Vinta

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://vinta.com.br Who we are Vinta has been a digital product consultancy for international clients in various sectors for over a decade, with a technical team that builds excellence in an environment of collaborative and healthy improvement. We work to technically enable the vision of digital products with the best software practices, bringing quality, scalability and efficiency, and establishing long-term relationships with our clients and professionals. Our difference is the teams that have a strong culture, in a close interface with customers. This work is only possible in a highly collaborative environment that works on an end-to-end application, with spaces for development and growth, security and flexibility. We are 100% remote and async first. Asynchronous communication is central to our daily lives, giving us hours of focused work without interruptions. Turning meetings into asynchronous reports helps us promote quality of life and real work-life balance! To find out more, see our website. We also have a lot of collaboration for the open source community on our Github, and lectures available on our YouTube channel. Also take a look at our Glassdoor! Your work at Vinta The healthcare market in the United States is large, and full of bureaucratic, cumbersome and dated technological solutions that do not meet the needs of their end users - doctors, nurses, interdisciplinary teams, hospitals and healthcare providers. Vinta has been successful in this market by positioning itself as a facilitator of innovation in this area, simplifying the construction of health products that speak directly to what the market needs. You will build the

vision, strategy and execution of our main proprietary product: Vinta Building Blocks, a set of functionalities and components for building healthtech products, where you will act as Product Owner. Its objective is to understand the US healthcare ecosystem in depth (its EHR's, AI possibilities and its agents, and Design Systems), transforming isolated components into unified experiences that guarantee an accelerated time-to-market for new healthtech projects, enabling the technical dev and design team to generate value. You will also facilitate and monitor this project so that it is technically viable, considering risks, opportunities and resources, providing solutions to build and accelerate the product and our team, meeting the objectives, visions and concerns of our internal stakeholders, CPO and CTO. With this market dominance, you will also assist Expansion with continuous discovery and other actions that convert leads and expand current accounts, technically demonstrating how our building blocks solve customers' business problems, generating social proof in demos that show how our healthtech consultancy is exactly what they need for their digital health products. Team managers at Vinta also parallel activities in other projects. Although this is the initial scope of your work, we hope that after some time in this position, you will also gain context from other projects and work on them with another team. Experience we seek: Practice with continuous discovery: Basing solutions on real pain from leads, customers and market research, to drive adoption of our products and conversion of our proposals for the US healthcare ecosystem. Strategic independence:

Autonomy to guide the strategy, roadmap and routine of these Building Blocks, questioning C-levels and technical teams based on data and product vision. Capacity for innovation: Designing and coordinating the UX/UI of the modular components of our product together with devs and designers, experimenting and building this product so that it is AI-native Speed ​​and Pragmatism: Focus on time-to-market, prioritizing prototyping, testing and iterating in short cycles, focusing on strategic scopes and removing team, product and stakeholder blockages. Team leadership: We expect you to lead your development and design team, acting strategically to ensure clear objectives and enable team productivity in a collaborative culture, ensuring continuous feedback and guidance for team growth. Parallelizing teams: Our expectation is that after you are seated in this first chair, you will also be able to direct other technical teams in other projects, negotiating scopes and monitoring team deliveries and customer satisfaction. Communication skills: Fluent in English to work supporting Expansion and projects, selling our product and technical vision in a persuasive way. It makes a difference if you: Have an understanding of the digital health ecosystem (EHRs, clinical workflows, Medplum/FHIR); Have experience assembling AI-native products; Our benefits: Salary from R$13,500 to R$18,300 under the CLT regime, adjusted annually; The Vinta Beyond Program pays, on a variable and annual basis, the equivalent of up to two and a half salaries, with goals based on your performance and development at Vinta; Vinta +Home: Use R$500 per month, in a completely flexible way, to make your home office experience more comfortable. License equity

parental: 4 months of paternity leave for adopted and biological children, for all types of families; Flash Card: R$1600 in monthly benefits on a Visa card, to be used in multiple establishments: restaurants, iFood and Uber Eats, supermarkets, gas stations, etc.; SulAmérica national health and dental care, with the right to childbirth and room, fully paid by Vinta and without deduction from the payroll. The inclusion of the first two dependents is also covered by the benefit; Daycare allowance: R$347 monthly for up to 6 years, 11 months and 29 days of age. Purchase of courses, books and technical material for your professional development; Wellhub (formerly Gympass): access to various types of physical activity and a wide network of partner gyms and studios in the country, to do whenever and wherever you want. In addition, you will have access to individual or group classes, as well as apps for physical activities, emotional well-being, healthy habits and more; Ticket and bonus of up to R$1500.00 additional when approving lectures at national conferences aligned with Vinta's strategy. Travel and accommodation also covered in case of in-person events To apply: https://weworkremotely.com/remote-jobs/vinta-senior-product-manager-remote-13-5-18-3k-clt

[employment_type]
Full-Time

[industry]
Front End Programming

---

### #23 | Staff Software Engineer - AI Website Builder - US (Remote)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/luxury-presence-staff-software-engineer-ai-website-builder-us-remote
- apply_url: https://weworkremotely.com/remote-jobs/luxury-presence-staff-software-engineer-ai-website-builder-us-remote

,field,original,translated,changed
0,title,Staff Software Engineer - AI Website Builder - US (Remote),Staff Software Engineer - AI Website Builder - US (Remote),False
1,company_profile,Luxury Presence,Luxury Presence,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: United States URL: http://luxurypresence.com Luxury Presence is building the AI growth platform for real estate. Backed by Bessemer Venture Partners and other top...,Headquarters: United States URL: http://luxurypresence.com Luxury Presence is building the AI growth platform for real estate. Backed by Bessemer Venture Partners and other top...,False
5,requirements,"Cross-Browser Development, Database, Infrastructure Orchestration, Computer Vision, and Cross-Selling","Cross-Browser Development, Database, Infrastructure Orchestration, Computer Vision, and Cross-Selling",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Front-End Programming,Front-End Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Staff Software Engineer - AI Website Builder - US (Remote)

[company_profile]
Luxury Presence

[location]
Anywhere in the World

[description]
Headquarters: United States URL: http://luxurypresence.com Luxury Presence is building the AI growth platform for real estate. Backed by Bessemer Venture Partners and other top investors, we're a Series C company on track to hit $100M in annual recurring revenue in the next six months. More than 90,000 real estate professionals, including over 30% of the WSJ Real Trends top 100 agents in the United States, use us to run and grow their business. The Role As a Staff Software Engineer , you will be a key contributor on a cross-functional team, building the foundation of our AI-first platform. You’ll take ownership of major features and services, drive meaningful improvements to our architecture, and collaborate closely with product, design, and AI teams to deliver high-impact outcomes for our customers. What You’ll Do Contribute to key architectural decisions and support a large scale re-imagining of our Site Generation and Site Builder Experience Design and build cloud-native APIs, services, and front-end experiences used across our platform to support building Websites Collaborate with cross-functional teams to deliver AI-powered workflows to Site Building experiences Write clean, testable, scalable code across the stack What We’re Looking For Passion for building in an AI-augmented environment Familiarity with modern AI tools; experience developing AI-driven solutions is a plus (Claude Code is a must) 5+ years of professional experience in full-stack engineering (leaning backend), ideally having supported a product from MVP to scale in rapid iterations Strong skills in JavaScript/TypeScript, Node.js , and React Experience with scalable microservice architecture (AWS preferred) Solid command of GraphQL, event-driven systems (Kafka/SQS), and distributed databases Track record of delivering high-quality features in rapid prototyping environments and integrating with feedback quickly While you will have Product and Design partners, we value strong communicators and collaborators; able to work with limited product and design guidance, and operate independently in chasing well defined outcomes Customer-first mindset with the ability to empathize with internal and external stakeholder needs Tech Stack Frontend: React, Tailwind, Apollo, SingleSPA Backend: Node.js, TypeScript (microservices), Python ETLs AI: LangChain, LangFuse, OpenRouter, Mastra, Claude Code Data: PostgreSQL, DynamoDB, Elasticsearch Infrastructure: AWS, Kubernetes, Lambda Messaging: Kafka, SQS $200,000 - $250,000 a year Join us in shaping the future of real estate The real estate industry is in the midst of a seismic shift, and the future belongs to those who break new ground. As one of the fastest-growing companies in the proptech and marketing sectors, Luxury Presence challenges the status quo of what technology can do for real estate agents, leaders, and brokerages. We're a team of agile and tenacious innovators working collaboratively to drive the industry forward. Together, we build game-changing products that empower modern real estate entrepreneurs to dominate their markets. From award-winning web design to agile SEO solutions to cutting-edge AI tools, we deliver tech that anticipates market shifts and keeps our clients ahead of their competition. Founded in 2016 by Stanford Business School alum Malte Kramer, Luxury Presence has grown to a global team ranked on the Inc. 5000 fastest-growing companies list three years in a row. We're backed by world-class investors, including Bessemer Venture Partners, NextEquity Partners, Toba Capital, and Switch Ventures, and have raised $89 million to date. More than 18,000 real estate businesses rely on our platform, including 30% of the Wall Street Journal RealTrends top agents and teams. Additionally, many of the industry's most powerful brokerages rely on Luxury Presence as a trusted business partner. Every year since 2020, Luxury Presence has ranked on BuiltIn's Best Place to Work lists. HousingWire named our founder and CEO a 2024 Tech Trendsetter, we've received several Tech100 Awards, and we just scored an Inman Innovation Award for Best AI-Powered Platform. Luxury Presence is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, or national origin. We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/luxury-presence-staff-software-engineer-ai-website-builder-us-remote

[requirements]
Cross-Browser Development, Database, Infrastructure Orchestration, Computer Vision, and Cross-Selling

[employment_type]
Full-Time

[industry]
Front-End Programming

**Translated Full Posting Text**

[title]
Staff Software Engineer - AI Website Builder - US (Remote)

[company_profile]
Luxury Presence

[location]
Anywhere in the World

[description]
Headquarters: United States URL: http://luxurypresence.com Luxury Presence is building the AI growth platform for real estate. Backed by Bessemer Venture Partners and other top investors, we're a Series C company on track to hit $100M in annual recurring revenue in the next six months. More than 90,000 real estate professionals, including over 30% of the WSJ Real Trends top 100 agents in the United States, use us to run and grow their business. The Role As a Staff Software Engineer , you will be a key contributor on a cross-functional team, building the foundation of our AI-first platform. You’ll take ownership of major features and services, drive meaningful improvements to our architecture, and collaborate closely with product, design, and AI teams to deliver high-impact outcomes for our customers. What You’ll Do Contribute to key architectural decisions and support a large scale re-imagining of our Site Generation and Site Builder Experience Design and build cloud-native APIs, services, and front-end experiences used across our platform to support building Websites Collaborate with cross-functional teams to deliver AI-powered workflows to Site Building experiences Write clean, testable, scalable code across the stack What We’re Looking For Passion for building in an AI-augmented environment Familiarity with modern AI tools; experience developing AI-driven solutions is a plus (Claude Code is a must) 5+ years of professional experience in full-stack engineering (leaning backend), ideally having supported a product from MVP to scale in rapid iterations Strong skills in JavaScript/TypeScript, Node.js , and React Experience with scalable microservice architecture (AWS preferred) Solid command of GraphQL, event-driven systems (Kafka/SQS), and distributed databases Track record of delivering high-quality features in rapid prototyping environments and integrating with feedback quickly While you will have Product and Design partners, we value strong communicators and collaborators; able to work with limited product and design guidance, and operate independently in chasing well defined outcomes Customer-first mindset with the ability to empathize with internal and external stakeholder needs Tech Stack Frontend: React, Tailwind, Apollo, SingleSPA Backend: Node.js, TypeScript (microservices), Python ETLs AI: LangChain, LangFuse, OpenRouter, Mastra, Claude Code Data: PostgreSQL, DynamoDB, Elasticsearch Infrastructure: AWS, Kubernetes, Lambda Messaging: Kafka, SQS $200,000 - $250,000 a year Join us in shaping the future of real estate The real estate industry is in the midst of a seismic shift, and the future belongs to those who break new ground. As one of the fastest-growing companies in the proptech and marketing sectors, Luxury Presence challenges the status quo of what technology can do for real estate agents, leaders, and brokerages. We're a team of agile and tenacious innovators working collaboratively to drive the industry forward. Together, we build game-changing products that empower modern real estate entrepreneurs to dominate their markets. From award-winning web design to agile SEO solutions to cutting-edge AI tools, we deliver tech that anticipates market shifts and keeps our clients ahead of their competition. Founded in 2016 by Stanford Business School alum Malte Kramer, Luxury Presence has grown to a global team ranked on the Inc. 5000 fastest-growing companies list three years in a row. We're backed by world-class investors, including Bessemer Venture Partners, NextEquity Partners, Toba Capital, and Switch Ventures, and have raised $89 million to date. More than 18,000 real estate businesses rely on our platform, including 30% of the Wall Street Journal RealTrends top agents and teams. Additionally, many of the industry's most powerful brokerages rely on Luxury Presence as a trusted business partner. Every year since 2020, Luxury Presence has ranked on BuiltIn's Best Place to Work lists. HousingWire named our founder and CEO a 2024 Tech Trendsetter, we've received several Tech100 Awards, and we just scored an Inman Innovation Award for Best AI-Powered Platform. Luxury Presence is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, or national origin. We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/luxury-presence-staff-software-engineer-ai-website-builder-us-remote

[requirements]
Cross-Browser Development, Database, Infrastructure Orchestration, Computer Vision, and Cross-Selling

[employment_type]
Full-Time

[industry]
Front-End Programming

---

### #24 | [Cubos DevOps] Pessoa Engenheira de DevOps Pleno
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/cubos-tecnologia-cubos-devops-pessoa-engenheira-de-devops-pleno
- apply_url: https://weworkremotely.com/remote-jobs/cubos-tecnologia-cubos-devops-pessoa-engenheira-de-devops-pleno

,field,original,translated,changed
0,title,[Cubos DevOps] Pessoa Engenheira de DevOps Pleno,[DevOps Cubes] Full DevOps Engineer,True
1,company_profile,Cubos Tecnologia,Cubes Technology,True
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://cubos.io Sobre a Cubos DevOps: Somos especialistas em gestão de infraestrutura e automação de processos de Cloud para atender às necessidades dos n...,Headquarters: BR URL: http://cubos.io About Cubos DevOps: We are specialists in infrastructure management and automation of Cloud processes to meet the needs of our customers a...,True
5,requirements,"Adobe Photoshop, Cross-Browser Development, Database, Estimating and Cost Forecasting, Computer Vision, InfoSec, DevOps, Cross-Selling, Deal Closure, and Composition","Adobe Photoshop, Cross-Browser Development, Database, Estimating and Cost Forecasting, Computer Vision, InfoSec, DevOps, Cross-Selling, Deal Closure, and Composition",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,DevOps and Sysadmin,DevOps and Sysadmin,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
[Cubos DevOps] Pessoa Engenheira de DevOps Pleno

[company_profile]
Cubos Tecnologia

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cubos.io Sobre a Cubos DevOps: Somos especialistas em gestão de infraestrutura e automação de processos de Cloud para atender às necessidades dos nossos clientes para mantê-los competitivos. Nosso foco é fornecer produtos e serviços que impulsionam a transformação digital e promovem o sucesso de nossos clientes. Operando em um ambiente dinâmico e colaborativo e tendo o comprometimento com a excelência em todas as áreas do nosso negócio, desde o desenvolvimento de produtos até o suporte ao cliente. Sobre a vaga: Responsabilidades: Escrever scripts e automações em tecnologias variadas; Escrever módulos Terraform para provisionamento de recursos em infra; Implantar soluções de monitoramento (disponibilidade, performance e segurança); Agir proativamente em identificar, remediar e corrigir problemas. Requisitos e Qualificações: Ler e escrever em inglês confortavelmente; Experiência prévia gerenciando aplicações na AWS ou GCP; Conhecer os princípios de DevOps e de GitOps; Conhecimento em orquestração de containers com Kubernetes; Habilidades em programação em JavaScript (é preferível em JS, mas outras linguagens também são aceitáveis); Domínio de gerenciamento de infraestrutura com Terraform; Entender sobre administração de sistemas Linux; Domínio na criação e configuração de pipelines utilizando GitHub Actions ou GitLab CI. Diferenciais: Conhecer o funcionamento de bancos de dados relacionais (como por exemplo PostgreSQL, MySQL, etc) para analisar métricas e aplicar otimizações; Expertise na gestão de ferramentas de GitOps, incluindo ArgoCD ou FluxCD; Conhecimento aprofundado em Prometheus e Grafana. Proficiência na configuração de pipelines para aplicações móveis em iOS e Android; Possuir certificação na área. To apply: https://weworkremotely.com/remote-jobs/cubos-tecnologia-cubos-devops-pessoa-engenheira-de-devops-pleno

[requirements]
Adobe Photoshop, Cross-Browser Development, Database, Estimating and Cost Forecasting, Computer Vision, InfoSec, DevOps, Cross-Selling, Deal Closure, and Composition

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

**Translated Full Posting Text**

[title]
[DevOps Cubes] Full DevOps Engineer

[company_profile]
Cubes Technology

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cubos.io About Cubos DevOps: We are specialists in infrastructure management and automation of Cloud processes to meet the needs of our customers and keep them competitive. Our focus is to provide products and services that drive digital transformation and promote our customers' success. Operating in a dynamic and collaborative environment and committed to excellence in all areas of our business, from product development to customer support. About the position: Responsibilities: Writing scripts and automations in various technologies; Write Terraform modules for provisioning infrastructure resources; Implement monitoring solutions (availability, performance and security); Act proactively in identifying, remediating and correcting problems. Requirements and Qualifications: Read and write English comfortably; Previous experience managing applications on AWS or GCP; Know the principles of DevOps and GitOps; Knowledge of container orchestration with Kubernetes; JavaScript programming skills (JS is preferred, but other languages ​​are also acceptable); Infrastructure management domain with Terraform; Understand Linux systems administration; Proficiency in creating and configuring pipelines using GitHub Actions or GitLab CI. Differentiators: Know how relational databases work (such as PostgreSQL, MySQL, etc.) to analyze metrics and apply optimizations; Expertise in managing GitOps tools, including ArgoCD or FluxCD; In-depth knowledge of Prometheus and Grafana. Proficiency in configuring pipelines for mobile applications on iOS and Android; Have certification in the area. To apply:

https://weworkremotely.com/remote-jobs/cubos-tecnologia-cubos-devops-pessoa-engenheira-de-devops-pleno

[requirements]
Adobe Photoshop, Cross-Browser Development, Database, Estimating and Cost Forecasting, Computer Vision, InfoSec, DevOps, Cross-Selling, Deal Closure, and Composition

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

---

### #25 | Profissional IaC| DevOps
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/radix-profissional-iac-devops
- apply_url: https://weworkremotely.com/remote-jobs/radix-profissional-iac-devops

,field,original,translated,changed
0,title,Profissional IaC| DevOps,IaC Professional | DevOps,True
1,company_profile,Radix,Radix,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: BR URL: http://radixeng.com.br A primeira coisa que você precisa saber é que aqui você não vai cair na rotina. A Radix desenvolve soluções para empresas de difere...,Headquarters: BR URL: http://radixeng.com.br The first thing you need to know is that here you won't fall into a routine. Radix develops solutions for companies from different ...,True
5,requirements,"Cross-Browser Development, Version Control, Computer Vision, DevOps, and Cross-Selling","Cross-Browser Development, Version Control, Computer Vision, DevOps, and Cross-Selling",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,DevOps and Sysadmin,DevOps and Sysadmin,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Profissional IaC| DevOps

[company_profile]
Radix

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://radixeng.com.br A primeira coisa que você precisa saber é que aqui você não vai cair na rotina. A Radix desenvolve soluções para empresas de diferentes setores e indústrias. Cada projeto tem suas tecnologias, soluções e prazos e você terá oportunidade de atuar e experimentar diferentes desafios. Além da nossa atuação pelo Brasil, com escritório no Rio de janeiro, São Paulo e Belo Horizonte, temos também filiais nos Estados Unidos, fazendo com que a Radix se consolide cada vez mais como uma empresa global . Quer fazer parte dessa história e transformar ideias e sonhos em realidade? Como profissional de IaC / Devops vocÊ vai: Atuar na automação, provisionamento e gestão de infraestrutura em nuvem Azure utilizando práticas modernas de Infrastructure as Code (IaC), garantindo ambientes padronizados, seguros e escaláveis para suportar o ciclo de vida dos projetos de desenvolvimento. Responsabilidades Principais Provisionamento de Infraestrutura Azure Projetar, implementar e manter recursos de infraestrutura no Azure (VNets, AKS, App Services, Storage Accounts, Key Vault, Azure SQL, ACR, entre outros) de forma automatizada e rastreável via código. Infrastructure as Code com Terraform e Terragrunt Desenvolver e manter módulos Terraform reutilizáveis para provisionamento de recursos Azure. Utilizar Terragrunt para orquestrar ambientes múltiplos (dev, staging, prod), gerenciar dependências entre módulos e garantir DRY (Don't Repeat Yourself) na estrutura de IaC. Criação e Gestão de Pipelines CI/CD Construir e manter pipelines de integração e entrega contínua utilizando Azure DevOps (Pipelines YAML) e/ou GitHub Actions, cobrindo builds, testes, provisionamento de infraestrutura (pipeline de IaC) e deploy de aplicações. Gestão de Estado e Boas Práticas de IaC Configurar e gerenciar remote state do Terraform (Azure Storage Account + Blob Container), implementar locking de estado, versionamento de módulos e separação por workspaces/ambientes. Segurança e Governança Aplicar práticas de segurança em infraestrutura: uso de Azure Key Vault para gestão de secrets, definição de políticas IAM (RBAC), Azure Policy, e garantia de conformidade nos recursos provisionados. Monitoramento e Observabilidade Configurar recursos de monitoramento via código (Azure Monitor, Log Analytics Workspace, Application Insights), garantindo visibilidade sobre a saúde da infraestrutura e aplicações. Documentação e Padronização Manter documentação técnica atualizada, padrões de nomenclatura de recursos, tagging strategy e guias de uso dos módulos de IaC para as equipes de desenvolvimento. Benefícios: Assistência Médica Nacional (para o titular e dependentes, com quarto privativo) Assistência odontológica nacional (para o titular e dependentes) Vale refeição / alimentação flexível Auxílio home office Day off (no mês do aniversário) Wellhub (antigo Gympass) Licença Maternidade (6 meses) e Paternidade (20 dias) estendidas Auxílio creche para filhos de até 3 anos (por filho) Apoio em saúde mental com a Wellz Clube de Vantagens com descontos em diversos parceiros Convênio com instituições de ensino e cursos de idioma Desenvolvimento Profissional (Universidade Corporativa) Parceria com empresa de coworkings no Brasil Programa de Qualidade de Vida e Bem-Estar Médico consultor para acompanhamento de radixers Planos de incentivos A Radix está sempre no topo das Melhores Empresas para se trabalhar porque: Temos profissionais comprometidos, dedicados, curiosos e inovadores. O espírito de equipe é a nossa maior força. Trabalhamos de forma cooperativa e sabemos que estamos juntos, remando na mesma direção. Temos um ambiente diverso, que valoriza equidade e inclusão. Nossa jornada de trabalho é flexível e em quase todos os projetos é possível trabalhar de qualquer lugar do Brasil. Valorizamos o bem-estar e o cuidado com as nossas pessoas, com programas de apoio à saúde mental, psiquiatra e médico consultor disponíveis. Curtiu? #VemPraRadix Código da vaga: 2b73 To apply: https://weworkremotely.com/remote-jobs/radix-profissional-iac-devops

[requirements]
Cross-Browser Development, Version Control, Computer Vision, DevOps, and Cross-Selling

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

**Translated Full Posting Text**

[title]
IaC Professional | DevOps

[company_profile]
Radix

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://radixeng.com.br The first thing you need to know is that here you won't fall into a routine. Radix develops solutions for companies from different sectors and industries. Each project has its technologies, solutions and deadlines and you will have the opportunity to act and experience different challenges. In addition to our operations in Brazil, with offices in Rio de Janeiro, São Paulo and Belo Horizonte, we also have branches in the United States, making Radix increasingly consolidated as a global company. Do you want to be part of this story and turn ideas and dreams into reality? As an IaC / Devops professional you will: Work in the automation, provisioning and management of infrastructure in the Azure cloud using modern Infrastructure as Code (IaC) practices, ensuring standardized, secure and scalable environments to support the life cycle of development projects. Main Responsibilities Azure Infrastructure Provisioning Design, implement and maintain infrastructure resources in Azure (VNets, AKS, App Services, Storage Accounts, Key Vault, Azure SQL, ACR, among others) in an automated and traceable manner via code. Infrastructure as Code with Terraform and Terragrunt Develop and maintain reusable Terraform modules for provisioning Azure resources. Use Terragrunt to orchestrate multiple environments (dev, staging, prod), manage dependencies between modules and guarantee DRY (Don't Repeat Yourself) in the IaC structure. Creation and Management of CI/CD Pipelines Build and maintain integration and continuous delivery pipelines using Azure DevOps (YAML Pipelines) and/or GitHub Actions, covering builds, tests, infrastructure provisioning (IaC pipeline) and application deployment. State Management and Goods

IaC Practices Configure and manage remote state of Terraform (Azure Storage Account + Blob Container), implement state locking, module versioning and separation by workspaces/environments. Security and Governance Apply security practices to infrastructure: use of Azure Key Vault to manage secrets, define IAM policies (RBAC), Azure Policy, and ensure compliance in provisioned resources. Monitoring and Observability Configure monitoring resources via code (Azure Monitor, Log Analytics Workspace, Application Insights), ensuring visibility into the health of infrastructure and applications. Documentation and Standardization Maintain up-to-date technical documentation, resource naming standards, tagging strategies and guides for using IaC modules for development teams. Benefits: National Medical Assistance (for the holder and dependents, with a private room) National dental assistance (for the holder and dependents) Flexible meal/food voucher Home office assistance Day off (in the month of the birthday) Wellhub (formerly Gympass) Maternity (6 months) and Paternity (20 days) leave extended Daycare allowance for children up to 3 years old (per child) Mental health support with Wellz Advantages Club with discounts from several partners Agreement with educational institutions and language courses Professional Development (Corporate University) Partnership with coworking company in Brazil Quality of Life and Wellbeing Program Consultant doctor to monitor radixers Incentive plans Radix is always at the top of the Best Companies to work for because: We have committed, dedicated, curious and innovative professionals. Team spirit is our greatest strength. We work cooperatively

and we know that we are together, rowing in the same direction. We have a diverse environment, which values ​​equity and inclusion. Our working hours are flexible and in almost all projects it is possible to work from anywhere in Brazil. We value the well-being and care of our people, with mental health support programs, psychiatrists and consultant doctors available. Did you like it? #VemPraRadix Job code: 2b73 To apply: https://weworkremotely.com/remote-jobs/radix-profissional-iac-devops

[requirements]
Cross-Browser Development, Version Control, Computer Vision, DevOps, and Cross-Selling

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

---

### #26 | [Banco de Talentos] Product Manager Pleno
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-pleno
- apply_url: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-pleno

,field,original,translated,changed
0,title,[Banco de Talentos] Product Manager Pleno,[Talent Bank] Full Product Manager,True
1,company_profile,Cubos Tecnologia,Cubes Technology,True
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: BR URL: http://cubos.io Sobre a Cubos: Existimos para transformar a realidade ao nosso redor por meio de tecnologia. Somos um hub de conhecimento e inovação, cria...","Headquarters: BR URL: http://cubos.io About Cubos: We exist to transform the reality around us through technology. We are a knowledge and innovation hub, we create our own digi...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,DevOps and Sysadmin,DevOps and Sysadmin,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
[Banco de Talentos] Product Manager Pleno

[company_profile]
Cubos Tecnologia

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cubos.io Sobre a Cubos: Existimos para transformar a realidade ao nosso redor por meio de tecnologia. Somos um hub de conhecimento e inovação, criamos nossas próprias empresas digitais e apoiamos empresas na tomada de decisão, desenvolvimento e resolução de desafios técnicos complexos. Nós acreditamos que podemos mudar o mundo, e: Não temos medo de cair 😎 Cuidamos e respeitamos as pessoas 💕 Buscamos sair do padrão 🚀 Fazemos entregas fodas 🎁 Focamos nos usuários 🔍 Somos um hub de conhecimento 🧠 Sobre a vaga: A vaga é para o nosso Banco de Talentos de Product Manager, ou seja, surgindo uma vaga efetiva, olharemos primeiramente para o Banco de Talentos e chamaremos as pessoas que estejam pré-aprovadas. Ao se cadastrar para essa vaga, você passará pelo nosso processo seletivo e se tornará uma pessoa apta para as oportunidades que possam surgir a qualquer momento. Com o Banco de Talentos, não há prazos entre as etapas, mas à medida que você avança, torna-se mais propenso a ser contatado e chamado para entrevistas, além de ficar pré-aprovado para fazer parte do nosso time. Responsabilidades: Participar e colaborar na definição dos KR's e seus KPI's Realizar UX research; Analisar dados quantitativos e qualitativos; Priorizar problemas e funcionalidades; Elaboração e gerenciamento do backlog do produto. Operacionalizar o mapeamento a fundo das oportunidades/problemas e seus impactos, utilizando-se de fatos e dados. Planeja e acorda com o time técnico a execução das iniciativas priorizadas na Squad. Requisitos e Qualificações: Conhecimento sobre o processo de Discovery e suas metodologias; Conhecer técnicas de UX research. Experiência como UX, PM, PO ou ter background de Consultoria; Capacidade analítica para identificar problemas e levantar hipóteses; Saber conduzir reuniões com clientes e stakeholders; Perfil empreendedor para identificar oportunidades no mercado. Diferenciais: Experiência como Product Manager; Experiência com Teste A/B; Experiência com gestão de projetos; Realizar análise de dados das pesquisas Product delivery e relacionamento com desenvolvedores. To apply: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-pleno

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

**Translated Full Posting Text**

[title]
[Talent Bank] Full Product Manager

[company_profile]
Cubes Technology

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cubos.io About Cubos: We exist to transform the reality around us through technology. We are a knowledge and innovation hub, we create our own digital companies and support companies in decision-making, development and solving complex technical challenges. We believe that we can change the world, and: We are not afraid of falling 😎 We care and respect people 💕 We seek to break out of the norm 🚀 We make amazing deliveries 🎁 We focus on users 🔍 We are a knowledge hub 🧠 About the vacancy: The vacancy is for our Product Manager Talent Bank, that is, if an effective vacancy arises, we will first look at the Talent Bank and call the people who are pre-approved. When registering for this vacancy, you will go through our selection process and become a person suitable for opportunities that may arise at any time. With the Talent Bank, there are no deadlines between stages, but as you progress, you become more likely to be contacted and called for interviews, in addition to being pre-approved to be part of our team. Responsibilities: Participate and collaborate in the definition of KR's and their KPI's Carry out UX research; Analyze quantitative and qualitative data; Prioritize problems and features; Preparation and management of the product backlog. Operationalize the in-depth mapping of opportunities/problems and their impacts, using facts and data. Plans and agrees with the technical team the execution of the initiatives prioritized at Squad. Requirements and Qualifications: Knowledge of the Discovery process and its methodologies; Know UX research techniques. Experience as UX, PM, PO or have a Consulting background; Analytical ability to identify problems and raise

hypotheses; Know how to conduct meetings with clients and stakeholders; Entrepreneurial profile to identify opportunities in the market. Differentiators: Experience as a Product Manager; Experience with A/B Testing; Experience with project management; Perform data analysis from Product delivery surveys and relationships with developers. To apply: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-pleno

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

---

### #27 | [BANCO DE TALENTOS] Product Manager Jr.
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-jr
- apply_url: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-jr

,field,original,translated,changed
0,title,[BANCO DE TALENTOS] Product Manager Jr.,[TALENT BANK] Product Manager Jr.,True
1,company_profile,Cubos Tecnologia,Cubes Technology,True
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: BR URL: http://cubos.io Sobre a Cubos: Existimos para transformar a realidade ao nosso redor por meio de tecnologia. Somos um hub de conhecimento e inovação, cria...","Headquarters: BR URL: http://cubos.io About Cubos: We exist to transform the reality around us through technology. We are a knowledge and innovation hub, we create our own digi...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,DevOps and Sysadmin,DevOps and Sysadmin,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
[BANCO DE TALENTOS] Product Manager Jr.

[company_profile]
Cubos Tecnologia

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cubos.io Sobre a Cubos: Existimos para transformar a realidade ao nosso redor por meio de tecnologia. Somos um hub de conhecimento e inovação, criamos nossas próprias empresas digitais e apoiamos empresas na tomada de decisão, desenvolvimento e resolução de desafios técnicos complexos. Nós acreditamos que podemos mudar o mundo, mas também acreditamos que: Não temos medo de cair 😎 Cuidamos e respeitamos as pessoas 💕 Buscamos sair do padrão 🚀 Fazemos entregas fodas 🎁 Focamos nos usuários 🔍 Somos um hub de conhecimento 🧠 Sobre a vaga: Responsabilidades: Apoio ao PM e ao time em atividades operacionais; Criação e acompanhamento de task; Pesquisas e captura de informações; Refinamento de escopo. Requisitos: Conhecimento de Frameworks iniciais de produto; Entendimento das metodologias ágeis; Comunicação clara e objetiva; Facilidade em trabalho em equipe. To apply: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-jr

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

**Translated Full Posting Text**

[title]
[TALENT BANK] Product Manager Jr.

[company_profile]
Cubes Technology

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://cubos.io About Cubos: We exist to transform the reality around us through technology. We are a knowledge and innovation hub, we create our own digital companies and support companies in decision-making, development and solving complex technical challenges. We believe that we can change the world, but we also believe that: We are not afraid of falling 😎 We care and respect people 💕 We seek to break out of the norm 🚀 We make amazing deliveries 🎁 We focus on users 🔍 We are a knowledge hub 🧠 About the position: Responsibilities: Supporting the PM and the team in operational activities; Task creation and monitoring; Research and information capture; Scope refinement. Requirements: Knowledge of initial product Frameworks; Understanding of agile methodologies; Clear and objective communication; Ease of teamwork. To apply: https://weworkremotely.com/remote-jobs/cubos-tecnologia-banco-de-talentos-product-manager-jr

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

---

### #28 | DevOps Engineer
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/alice-devops-engineer
- apply_url: https://weworkremotely.com/remote-jobs/alice-devops-engineer

,field,original,translated,changed
0,title,DevOps Engineer,DevOps Engineer,False
1,company_profile,Alice,Alice,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: BR URL: http://alice.com.br Por que isso não é “só mais um trabalho” Na Alice, a gente não oferece um lugar para assistir da arquibancada — você vai entrar na are...","Headquarters: BR URL: http://alice.com.br Why this isn't “just another job” At Alice, we don't offer a place to watch from the stands — you'll enter the arena of one of Latin A...",True
5,requirements,"Containers, Cross-Browser Development, Infrastructure Orchestration, Monitoring and Analytics, Computer Vision, DevOps, Kubernetes, Network Monitoring, Performance Monitoring, ...","Containers, Cross-Browser Development, Infrastructure Orchestration, Monitoring and Analytics, Computer Vision, DevOps, Kubernetes, Network Monitoring, Performance Monitoring, ...",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,DevOps and Sysadmin,DevOps and Sysadmin,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
DevOps Engineer

[company_profile]
Alice

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://alice.com.br Por que isso não é “só mais um trabalho” Na Alice, a gente não oferece um lugar para assistir da arquibancada — você vai entrar na arena de uma das jornadas de crescimento mais ousadas da América Latina em tecnologia e saúde. Como Software Engineer, você vai construir tecnologia de ponta com impacto direto em melhorar a vida das pessoas. Se você tem fome de gerar resultados, aprender rápido e fazer parte da empresa mais inovadora da América Latina , continue lendo. Atenção: Na Alice, a Engenharia opera 100% no modelo de Agentic Development. Se você não tem experiência e entusiasmo em atuar como orquestrador de agentes de AI, esta vaga não é para você. Sobre a Alice Nossa missão é tornar o mundo mais saudável. Para chegar lá, estamos construindo algo raro: uma experiência de saúde em que as pessoas realmente confiam, se engajam e até amam. Somos um plano de saúde para empresas movido por tecnologia — unindo cuidado e seguro de saúde — e entregamos resultados superiores de saúde com menor custo para mais de 90 mil membros (e crescendo). Site Institucional: https://alice.com.br/ Blog institucional: https://alice.com.br/blog/ Blog Tech: https://alice.com.br/tech/ Sobre a posição DevOps Engineer na Alice é a pessoa que vai além de manter a infraestrutura no ar! Nessa posição, esperamos que você atue em diversas dimensões cruciais para a nossa missão de tornar o mundo mais saudável. Plataforma e Infraestrutura: Construir e evoluir nossa plataforma em AWS e Kubernetes, com soluções sustentáveis e escaláveis; Desenhar e manter Infrastructure as Code (Terraform, Helm) com versionamento, revisão e testes; Decompor mudanças de plataforma em tarefas que fazem sentido para agentes — ordem, dependências, paralelismo, nível de autonomia; Colaborar com decisões de arquitetura cross squads; Manter nossas ADRs, documentações, rules e skills atualizados. Confiabilidade, Entrega e Operação: Construir e evoluir nossos pipelines de CI/CD e estratégias de release (canary, blue/green, rollback) via agentes; Trabalhar spec-first em todo o ciclo — planejar, codar, debugar, testar, documentar, revisar diffs e iterar; Ser responsável pelo ciclo de vida da plataforma (deploy, métricas, alarmes, SLOs) e pelos guardrails que mantêm a qualidade (testes de infra, linting, policy checks, security scans); Usar agentes também em operação, investigando incidentes via MCPs (Datadog, logs, traces, GitHub); Participar do on-call, evoluindo runbooks e automações que reduzem ruído e MTTR; Garantir alto desempenho, alta disponibilidade e segurança dos sistemas. Liderança Técnica: Contribuir com os desafios de plataforma e de todo o time de tecnologia, compartilhando ideias, soluções, módulos de IaC, arquiteturas, skills, subagents, rules e workflows reutilizáveis; Evoluir os arquivos de contexto do seu domínio para elevar a qualidade do que os agentes produzem em mudanças de infraestrutura; Publicar e manter skills no nosso marketplace interno; Aprimorar a experiência de desenvolvimento na Alice (tooling de plataforma, ambientes efêmeros, deploys self-service, observabilidade) e mentorar colegas no mindset de orquestrador. Produto / Negócio: Trabalhar junto com pessoas Engenheiras de Software, Designers e Product Managers para entender as dores dos usuários e dos times internos, criando as melhores soluções de plataforma; Ajudar o time a decidir onde cabe automação agentic e onde queremos judgement humano, especialmente em mudanças críticas de produção e em fluxos com cuidado, dados clínicos e decisões regulatórias; Colaborar para o fortalecimento de cultura do time, participando ativamente dos ritos e processos da squad. Sobre o time de Engenharia na Alice Fazer parte da equipe de Engenharia da Alice significa ter a responsabilidade e o privilégio de trabalhar para tornar o mundo mais saudável. Nossa missão é enorme e buscamos pessoas alinhadas com nosso propósito e com alta competência e resiliência para transformar o sistema de saúde no Brasil. É um desafio gigante, mas muito gratificante, e que traz inúmeras oportunidades de crescimento. Somos um time colaborativo e que busca excelência técnica, sem perder de vista o real objetivo de cada uma das linhas que escrevemos. Você vai trabalhar junto às áreas de negócios e produtos, com muitas iniciativas já amadurecidas e outras tantas para tirar do zero. Focamos em qualidade e em decisões diligentes. Ao mesmo tempo que buscamos evoluir todos os dias e nos reinventar, somos um time que foca em decisões consistentes, racionais e bem documentadas. Somos remotos. Se preferir trabalhar no escritório (como algumas pessoas do nosso time), nosso endereço é na Avenida Rebouças, 3535. Outros times da Alice trabalham de forma híbrida (produto, design, negócios, operações). O que te faz uma pessoa candidata forte Fundamentos de plataforma e infraestrutura Experiência sólida operando infraestrutura em AWS (VPC, IAM, EC2, EKS/ECS, RDS, S3, networking, custos); Proficiência com Kubernetes em produção (deployments, autoscaling, networking, RBAC, observabilidade, troubleshooting); Experiência sólida com Infrastructure as Code (Terraform, Helm) — modularização, versionamento, testes e revisão de mudanças; Experiência com pipelines de CI/CD (GitHub Actions, Jenkins ou equivalente) e estratégias de release (blue/green, canary, rollback, feature flags); Vivência com sistemas distribuídos / micro-serviços e suas armadilhas operacionais; Forte prática com observabilidade e monitoramento (Datadog, Prometheus, logs, traces, definição de SLIs/SLOs e alarmes); Experiência com as melhores práticas de segurança e privacidade de dados (gestão de secrets, least privilege, hardening, varreduras de vulnerabilidade, conformidade); Capacidade de codar quando necessário (Python, Go, Bash ou similar) para construir tooling de plataforma e automações; Experiência sólida como liderança de projetos técnicos de plataforma (migrações, padronizações cross squad, ferramentas internas, decisões arquiteturais); Agentic development Capacidade de adaptar sua forma de trabalho continuamente para extrair o máximo de benefício dos melhores modelos / harnesses / frameworks de AI. Uso regular de ferramenta agentic em modo agente, não apenas autocomplete (Claude Code, Cursor, Augment Code, Codex ou equivalente); Spec-driven development em todo o ciclo: planeja antes de gerar, revisa diffs, usa testes como verificação, e aplica o mesmo rigor em debugging, documentação e investigação de incidentes; Context engineering: configura e mantém CLAUDE.md, AGENTS.md, .cursorrules e equivalentes; sabe dividir tarefas em codebases grandes; Failure literacy: conhece modos de falha (hallucination, context rot, loops, sycophancy) e ajusta o processo a partir deles; Multiplicação: já criou skill, subagent, rule, template de prompt ou workflow que o time adotou; Guardrails e autonomia: decide o que delega ao agente e o que exige revisão humana; Diferenciais: orquestrar múltiplas instâncias/worktrees em paralelo; operar long-running agents; escrever evals para skills, prompts e workflows (medir qualidade de output e detectar regressão); avaliar ferramentas criticamente (custo, qualidade, segurança, privacidade); liderar adoção de agentic development em um time ou organização. Mentalidade Forte senso de comprometimento e foco no resultado; Apaixonada por tecnologia e por saúde; Entusiasmo genuíno por agentic development, com vontade de empurrar a fronteira do que é possível hoje. Remuneração Fazemos o nosso melhor para compensar de forma competitiva. Sempre fazemos nossa melhor oferta. Não negociamos (isso é bom para você). To apply: https://weworkremotely.com/remote-jobs/alice-devops-engineer

[requirements]
Containers, Cross-Browser Development, Infrastructure Orchestration, Monitoring and Analytics, Computer Vision, DevOps, Kubernetes, Network Monitoring, Performance Monitoring, and Cross-Selling

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

**Translated Full Posting Text**

[title]
DevOps Engineer

[company_profile]
Alice

[location]
Anywhere in the World

[description]
Headquarters: BR URL: http://alice.com.br Why this isn't “just another job” At Alice, we don't offer a place to watch from the stands — you'll enter the arena of one of Latin America's most daring growth journeys in technology and healthcare. As a Software Engineer, you will build cutting-edge technology with a direct impact on improving people's lives. If you are hungry to generate results, learn quickly and be part of the most innovative company in Latin America, keep reading. Attention: At Alice, Engineering operates 100% on the Agentic Development model. If you don't have experience and enthusiasm for working as an AI agent orchestrator, this role is not for you. About Alice Our mission is to make the world healthier. To get there, we're building something rare: a healthcare experience that people truly trust, engage in, and even love. We're a technology-powered business health plan—bringing together care and health insurance—delivering superior health outcomes at a lower cost to more than 90,000 members (and growing). Institutional Website: https://alice.com.br/ Institutional Blog: https://alice.com.br/blog/ Tech Blog: https://alice.com.br/tech/ About the position DevOps Engineer at Alice is the person who goes beyond keeping the infrastructure up and running! In this role, we expect you to act in several crucial dimensions to our mission to make the world healthier. Platform and Infrastructure: Build and evolve our platform on AWS and Kubernetes, with sustainable and scalable solutions; Design and maintain Infrastructure as Code (Terraform, Helm) with versioning, review and testing; Decompose platform changes into tasks that make sense for agents — order, dependencies, parallelism, level of autonomy;

Collaborate with cross squad architecture decisions; Keep our ADRs, documentation, rules and skills updated. Reliability, Delivery and Operation: Build and evolve our CI/CD pipelines and release strategies (canary, blue/green, rollback) via agents; Work spec-first throughout the cycle — plan, code, debug, test, document, review diffs and iterate; Be responsible for the platform's life cycle (deployment, metrics, alarms, SLOs) and the guardrails that maintain quality (infra tests, linting, policy checks, security scans); Use agents also in operation, investigating incidents via MCPs (Datadog, logs, traces, GitHub); Participate in on-call, evolving runbooks and automations that reduce noise and MTTR; Ensure high performance, high availability and security of systems. Technical Leadership: Contribute to the challenges of the platform and the entire technology team, sharing ideas, solutions, IaC modules, architectures, skills, subagents, rules and reusable workflows; Evolve your domain's context files to increase the quality of what agents produce in infrastructure changes; Publish and maintain skills in our internal marketplace; Improve the development experience at Alice (platform tooling, ephemeral environments, self-service deployments, observability) and mentor colleagues in the orchestrator mindset. Product / Business: Work together with Software Engineers, Designers and Product Managers to understand the pain points of users and internal teams, creating the best platform solutions; Help the team decide where agentic automation fits and where we want human judgment, especially in critical production changes and in flows of care, clinical data and regulatory decisions; Collaborate

to strengthen the team's culture, actively participating in the squad's rites and processes. About the Engineering team at Alice Being part of the Engineering team at Alice means having the responsibility and privilege of working to make the world healthier. Our mission is enormous and we are looking for people aligned with our purpose and with high competence and resilience to transform the healthcare system in Brazil. It is a huge challenge, but very rewarding, and brings countless opportunities for growth. We are a collaborative team that seeks technical excellence, without losing sight of the real objective of each of the lines we write. You will work closely with the business and product areas, with many initiatives already mature and many others to take from scratch. We focus on quality and diligent decisions. While we seek to evolve every day and reinvent ourselves, we are a team that focuses on consistent, rational and well-documented decisions. We are remote. If you prefer to work in the office (like some people on our team), our address is at Avenida Rebouças, 3535. Other Alice teams work in a hybrid way (product, design, business, operations). What makes you a strong candidate Platform and infrastructure fundamentals Solid experience operating infrastructure in AWS (VPC, IAM, EC2, EKS/ECS, RDS, S3, networking, costs); Proficiency with Kubernetes in production (deployments, autoscaling, networking, RBAC, observability, troubleshooting); Solid experience with Infrastructure as Code (Terraform, Helm) — modularization, versioning, testing and review of changes; Experience with CI/CD pipelines (GitHub Actions, Jenkins or equivalent) and release strategies (blue/green, canary, rollback, feature flags);

Experience with distributed systems / micro-services and their operational pitfalls; Strong practice with observability and monitoring (Datadog, Prometheus, logs, traces, definition of SLIs/SLOs and alarms); Experience with best data security and privacy practices (secrets management, least privilege, hardening, vulnerability scans, compliance); Ability to code when necessary (Python, Go, Bash or similar) to build platform tooling and automations; Solid experience leading technical platform projects (migrations, cross squad standardizations, internal tools, architectural decisions); Agentic development Ability to adapt your way of working continuously to extract the maximum benefit from the best AI models / harnesses / frameworks. Regular use of an agentic tool in agent mode, not just autocomplete (Claude Code, Cursor, Augment Code, Codex or equivalent); Spec-driven development throughout the cycle: plan before generating, review diffs, use tests as verification, and apply the same rigor to debugging, documentation and incident investigation; Context engineering: configures and maintains CLAUDE.md, AGENTS.md, .cursorrules and equivalents; knows how to divide tasks into large codebases; Failure literacy: knows failure modes (hallucination, context rot, loops, sycophancy) and adjusts the process based on them; Multiplication: already created skill, subagent, rule, prompt template or workflow that the team adopted; Guardrails and autonomy: decide what to delegate to the agent and what requires human review; Differentiators: orchestrate multiple instances/worktrees in parallel; operate long-running agents; write evals for skills, prompts and workflows (measure output quality and detect regression); evaluate tools

critically (cost, quality, security, privacy); lead adoption of agentic development in a team or organization. Mentality Strong sense of commitment and focus on results; Passionate about technology and health; Genuine enthusiasm for agentic development, with a desire to push the frontier of what is possible today. Compensation We do our best to compensate competitively. We always make our best offer. We don't negotiate (that's good for you). To apply: https://weworkremotely.com/remote-jobs/alice-devops-engineer

[requirements]
Containers, Cross-Browser Development, Infrastructure Orchestration, Monitoring and Analytics, Computer Vision, DevOps, Kubernetes, Network Monitoring, Performance Monitoring, and Cross-Selling

[employment_type]
Full-Time

[industry]
DevOps and Sysadmin

---

### #29 | Creative Performance Designer
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/nabu-global-fze-creative-performance-designer
- apply_url: https://weworkremotely.com/remote-jobs/nabu-global-fze-creative-performance-designer

,field,original,translated,changed
0,title,Creative Performance Designer,Creative Performance Designer,False
1,company_profile,Nabu Global FZE,Nabu Global FZE,False
2,location,"Anywhere in the World, Sharjah","Anywhere in the World, Sharjah",False
3,department,,,False
4,description,"Headquarters: Dubai, UAE URL: http://nabuglobal.com We are looking for a creative, results-driven designer who understands that great design is not just about aesthetics — it’s...","Headquarters: Dubai, UAE URL: http://nabuglobal.com We are looking for a creative, results-driven designer who understands that great design is not just about aesthetics — it’s...",False
5,requirements,"Adobe Creative Suite, Canva, Video Editing (Final Cut Pro, Adobe Premiere), and AI Chatbots","Adobe Creative Suite, Canva, Video Editing (Final Cut Pro, Adobe Premiere), and AI Chatbots",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Design,Design,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Creative Performance Designer

[company_profile]
Nabu Global FZE

[location]
Anywhere in the World, Sharjah

[description]
Headquarters: Dubai, UAE URL: http://nabuglobal.com We are looking for a creative, results-driven designer who understands that great design is not just about aesthetics — it’s about performance. This role is ideal for someone who combines design skills, AI tools, and marketing thinking to create visuals that capture attention and drive conversions. What You’ll Do Design high-performing creatives for digital campaigns (ads, landing pages, social media) Work primarily in Canva for speed and execution , while also using Adobe tools (Photoshop, Illustrator) when needed Use AI tools to create images, videos, and visual concepts Collaborate with the marketing team to develop conversion-focused visual strategies Continuously test and optimize creatives based on performance data Stay up to date with design trends, AI tools, and new technologies Bring ideas, concepts, and improvements — not just execute tasks What We’re Looking For Experience with Adobe tools (Photoshop, Illustrator) (Even if you mainly use Canva — Adobe knowledge is important) Strong experience using Canva for fast content production Experience with AI tools for image and video creation (e.g. Midjourney, DALL·E, Runway, Pika, VEO etc.) Experience in creating AI short-form videos and avatars is a big advantage Understanding of digital marketing and visual communication Basic knowledge of HTML & CSS (big plus) Strong creative thinking and attention to detail Someone who follows trends and enjoys working with new technologies Fast learner who adapts quickly to changes Proactive mindset — brings ideas and solutions Focused on results and performance , not just design ⚡ What Makes You a Great Fit You understand that design = conversion You move fast and execute efficiently You are curious about AI and actively use it in your workflow You think like a marketer, not just a designer Bonus Points Experience creating performance ads (Meta, Google, native ads) Experience with video creation/editing (AI or traditional tools) Experience working with landing pages and funnels Why Join Us Work at the intersection of design, AI, and performance marketing Freedom to experiment with tools and creative ideas Fast-paced, results-driven environment Your work directly impacts business growth How to Apply Please send: Your portfolio (required) Examples of AI-generated visuals and videos A short note on how you use AI in your creative process To apply: https://weworkremotely.com/remote-jobs/nabu-global-fze-creative-performance-designer

[requirements]
Adobe Creative Suite, Canva, Video Editing (Final Cut Pro, Adobe Premiere), and AI Chatbots

[employment_type]
Full-Time

[industry]
Design

**Translated Full Posting Text**

[title]
Creative Performance Designer

[company_profile]
Nabu Global FZE

[location]
Anywhere in the World, Sharjah

[description]
Headquarters: Dubai, UAE URL: http://nabuglobal.com We are looking for a creative, results-driven designer who understands that great design is not just about aesthetics — it’s about performance. This role is ideal for someone who combines design skills, AI tools, and marketing thinking to create visuals that capture attention and drive conversions. What You’ll Do Design high-performing creatives for digital campaigns (ads, landing pages, social media) Work primarily in Canva for speed and execution , while also using Adobe tools (Photoshop, Illustrator) when needed Use AI tools to create images, videos, and visual concepts Collaborate with the marketing team to develop conversion-focused visual strategies Continuously test and optimize creatives based on performance data Stay up to date with design trends, AI tools, and new technologies Bring ideas, concepts, and improvements — not just execute tasks What We’re Looking For Experience with Adobe tools (Photoshop, Illustrator) (Even if you mainly use Canva — Adobe knowledge is important) Strong experience using Canva for fast content production Experience with AI tools for image and video creation (e.g. Midjourney, DALL·E, Runway, Pika, VEO etc.) Experience in creating AI short-form videos and avatars is a big advantage Understanding of digital marketing and visual communication Basic knowledge of HTML & CSS (big plus) Strong creative thinking and attention to detail Someone who follows trends and enjoys working with new technologies Fast learner who adapts quickly to changes Proactive mindset — brings ideas and solutions Focused on results and performance , not just design ⚡ What Makes You a Great Fit You understand that design = conversion You move fast and execute efficiently You are curious about AI and actively use it in your workflow You think like a marketer, not just a designer Bonus Points Experience creating performance ads (Meta, Google, native ads) Experience with video creation/editing (AI or traditional tools) Experience working with landing pages and funnels Why Join Us Work at the intersection of design, AI, and performance marketing Freedom to experiment with tools and creative ideas Fast-paced, results-driven environment Your work directly impacts business growth How to Apply Please send: Your portfolio (required) Examples of AI-generated visuals and videos A short note on how you use AI in your creative process To apply: https://weworkremotely.com/remote-jobs/nabu-global-fze-creative-performance-designer

[requirements]
Adobe Creative Suite, Canva, Video Editing (Final Cut Pro, Adobe Premiere), and AI Chatbots

[employment_type]
Full-Time

[industry]
Design

---

### #30 | Lead Manager for Real Estate Investment Company
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/campos-property-solutions-lead-manager-for-real-estate-investment-company
- apply_url: https://weworkremotely.com/remote-jobs/campos-property-solutions-lead-manager-for-real-estate-investment-company

,field,original,translated,changed
0,title,Lead Manager for Real Estate Investment Company,Lead Manager for Real Estate Investment Company,False
1,company_profile,Campos Property Solutions,Campos Property Solutions,False
2,location,"Anywhere in the World, South Carolina","Anywhere in the World, South Carolina",False
3,department,,,False
4,description,Headquarters: South Carolina URL: https://www.campospropertysolutions.com/ What You'll Be Doing: - Managing our lead database in REISift (keeping it clean and organized) - Over...,Headquarters: South Carolina URL: https://www.campospropertysolutions.com/ What You'll Be Doing: - Managing our lead database in REISift (keeping it clean and organized) - Over...,False
5,requirements,"Operations Management, Sales, Client Relationship Management, and Team Management","Operations Management, Sales, Client Relationship Management, and Team Management",False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Sales and Marketing,Sales and Marketing,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Lead Manager for Real Estate Investment Company

[company_profile]
Campos Property Solutions

[location]
Anywhere in the World, South Carolina

[description]
Headquarters: South Carolina URL: https://www.campospropertysolutions.com/ What You'll Be Doing: - Managing our lead database in REISift (keeping it clean and organized) - Overseeing and supporting our cold calling team (currently 2 callers) - Making outbound calls to follow up on warm leads and dig deeper into promising records - Assigning leads/records to the right callers ("sniping") - Tracking KPIs daily and reporting weekly - Following up on old leads to bring them back to life Requirements: - Excellent spoken and written English (this role is phone-heavy) - Leadership experience — you'll be managing a small team - Highly organized, detail-oriented, and proactive - Reliable internet, headset, and quiet work environment - Long-term commitment Pay: $8 USD per hour Full Time (40 Hours) Regular bonuses Opportunity for a pay increase once established in the role Please send in a voice note or an introduction video recording. with your application. Applications that don't include one will not be taken into consideration To apply: https://weworkremotely.com/remote-jobs/campos-property-solutions-lead-manager-for-real-estate-investment-company

[requirements]
Operations Management, Sales, Client Relationship Management, and Team Management

[employment_type]
Full-Time

[industry]
Sales and Marketing

**Translated Full Posting Text**

[title]
Lead Manager for Real Estate Investment Company

[company_profile]
Campos Property Solutions

[location]
Anywhere in the World, South Carolina

[description]
Headquarters: South Carolina URL: https://www.campospropertysolutions.com/ What You'll Be Doing: - Managing our lead database in REISift (keeping it clean and organized) - Overseeing and supporting our cold calling team (currently 2 callers) - Making outbound calls to follow up on warm leads and dig deeper into promising records - Assigning leads/records to the right callers ("sniping") - Tracking KPIs daily and reporting weekly - Following up on old leads to bring them back to life Requirements: - Excellent spoken and written English (this role is phone-heavy) - Leadership experience — you'll be managing a small team - Highly organized, detail-oriented, and proactive - Reliable internet, headset, and quiet work environment - Long-term commitment Pay: $8 USD per hour Full Time (40 Hours) Regular bonuses Opportunity for a pay increase once established in the role Please send in a voice note or an introduction video recording. with your application. Applications that don't include one will not be taken into consideration To apply: https://weworkremotely.com/remote-jobs/campos-property-solutions-lead-manager-for-real-estate-investment-company

[requirements]
Operations Management, Sales, Client Relationship Management, and Team Management

[employment_type]
Full-Time

[industry]
Sales and Marketing

---

### #31 | Staff Product Engineer
- source: we_work_remotely_rss
- detected_language: pt (confidence=0.75)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/lawnstarter-staff-product-engineer
- apply_url: https://weworkremotely.com/remote-jobs/lawnstarter-staff-product-engineer

,field,original,translated,changed
0,title,Staff Product Engineer,Staff Product Engineer,False
1,company_profile,LawnStarter,LawnStarter,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: São Paulo, Brazil URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and outdoor services, with...","Headquarters: São Paulo, Brazil URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and outdoor services, with...",True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,All Other Remote,All Other Remote,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Staff Product Engineer

[company_profile]
LawnStarter

[location]
Anywhere in the World

[description]
Headquarters: São Paulo, Brazil URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and outdoor services, with over $100M in annual bookings. We're expanding beyond lawn care to become the one-stop shop for all home services — operating across three brands (LawnStarter, Lawn Love, Home Gnome) on a single shared platform. About Engineering at LawnStarter We're restructuring engineering around initiative teams : a Product Engineer paired with a PM and a designer, with an Engineering Manager who covers a couple of initiatives and supports your growth. The engineer leads AI agents like a team, ships the work, and is accountable — with the rest of the triangle — for whether the initiative moves its metric. We're betting that 1-2 strong engineers running AI agents can outship the labor-team model that defined the last decade of software. That bet only works if the engineers we hire are wired for ownership and can ship to a marketplace with real customers and pros on both sides. The Role You're the engineering anchor of one initiative at a time. The initiative is a team effort — an iron triangle of you, your PM, and your designer — and you have key participation across the full lifecycle: shaping the problem, deciding the technical approach, leading the AI agents that implement most of the code, shipping to production, and answering for the outcome alongside the rest of the triangle. You're accountable for the outcome — not for the volume of code merged. If an agent can ship it safely, your job is to make sure the agent does it right and the metric moves. If the initiative needs hand-written code in a sensitive area, you write it yourself. What makes this role different: You lead AI agents, not humans. Claude Code, Cursor, Codex, and our internal agent stack are your team. You own the quality, safety, and velocity of what they produce. You own an outcome, not a ticket queue. Problem-framing through production through the metric review 2-4 weeks after launch. You partner horizontally with PM and design. No tech lead above you. No architect approval. No ticket grooming committee. The bar is staff, not senior. You make the call when the call needs to be made. If you're waiting to be told, this isn't the role. What You'll Own The technical approach — architecture, data model, integration choices, rollout plan, observability, and rollback strategy for your initiative. You make the call, document it, and revisit it if the data says you were wrong. Agent-led implementation quality — the prompts, guardrails, evals, tests, and review loop that let agents ship safe, correct, production-ready code on your initiative. Most lines will be agent-authored. You're accountable for them. Cross-functional partnership — daily working contact with your PM (scope, tradeoffs) and your designer (UX decisions, in-tool prototyping with agents), and weekly check-ins with your EM (initiative health, blockers, growth). The initiative outcome — the specific metric the initiative was set up to move. In partnership with your PM, you present results 2-4 weeks post-launch and share the "did it work" answer. A high bar for what ships under your name — production correctness, security posture, performance, observability, and the experience for customers and pros. Agents accelerate you; they don't lower the bar. Problems to Solve Leading AI agents at staff-level quality Most of the code on your initiative will be authored by AI agents. The work is making agents ship as if a senior engineer wrote it: prompts that encode our codebase conventions, evals that catch hallucinations before merge, tests that exercise the edges, observability that catches the regression in production before a customer reports it. How do you build the agent workflow that lets one engineer ship what used to take a team? Owning an outcome without a tech lead You don't have a tech lead to approve your design or an architect to escalate to. You have an EM who covers a couple of initiatives and peers on adjacent ones. How do you make calls fast, document them clearly, and stay accountable to the outcome — without slowing down for hierarchy that no longer exists? Shipping outcomes, not features The initiative will be measured by a metric — a conversion rate, a retention curve, a pro-funnel KPI, a unit economics shift. You're accountable for the number, not the feature. How do you scope to actually move it, decide what to not build, and have the discipline to follow up 2-4 weeks after launch even when the next initiative is calling? What Success Looks Like (Year 1) Initiative outcomes hit — You've shipped 3-4 initiatives end-to-end, and at least two clearly moved the metric they were set up to move (with the post-launch review to prove it). Agent workflow that travels — The prompts, evals, and review loop you built for your initiative are adopted by at least one other engineer on an adjacent initiative. Cycle time — Median time from problem-framing to first production rollout on your initiatives is meaningfully shorter than the pre-restructure baseline. Zero "agent-shipped that" incidents — No customer- or pro-facing regression traceable to agent-authored code that you missed in review. Visible leverage — Other engineers point to artifacts you left behind — runbooks, evals, agent workflows, post-launch write-ups — as references they use. Who You Are AI-native. Claude Code, Cursor, Codex, or equivalent are how you ship — daily, on production work. You have opinions about prompts, evals, agent loops, MCP servers, and review workflows, and you know when to let the agent run vs. write it yourself. This is unlikely to be a good fit if you describe AI coding as "something you're exploring" or prefer to write everything by hand. Already operating at lead level. You may currently be titled Senior, Staff, Lead, or Principal — but in practice you've been the person making the call, shipping the hard thing, and answering for whether it worked. This is unlikely to be a good fit if you've always had a tech lead breaking down the work for you. Outcome-driven, not output-driven. You measure your week in "did the metric move" and "did the experience get better," not in tickets closed. You read the post-launch dashboard and you own the answer. This is unlikely to be a good fit if you take pride in volume of code shipped or feel uncomfortable being measured on a number you don't fully control. A strong horizontal partner. You hold your own with a strong PM and a strong designer. You bring engineering judgment to product calls and product judgment to engineering calls. This is unlikely to be a good fit if you hide behind "that's product's decision" or default to RICE-scoring tickets handed down to you. Decisive and documented. Architecture decisions, data-model choices, rollout plans — you write them down, get fast input, and move. This is unlikely to be a good fit if you wait for consensus on questions that have a clear right answer, or if you make calls and never write them down. Raises the floor, not just the ceiling. Your impact compounds beyond your own initiative because you leave artifacts — agent workflows, evals, runbooks, post-launch reviews. This is unlikely to be a good fit if you're a lone wolf who ships brilliantly but leaves nothing reusable behind. Cares about customers and pros. This is a real-world marketplace with real people on both sides. This is unlikely to be a good fit if you're chasing pure engineering elegance over business and customer outcomes. This Role Is NOT A tech lead in an old-style team. No 4-5 engineers reporting up to you on technical direction. The team is you + PM + designer + EM, with AI agents doing most of the implementation. A management role today. People management is the EM's job in this role. That said, the path can grow into management for those who want it — it's an open door, not a closed one. A platform-only or architecture-only role. You're a Product Engineer. You ship features that move metrics, end-to-end. Platform work happens inside the initiative when it's needed for the outcome. A "let AI do everything" role. Agents handle implementation grunt work. You handle judgment, design, safety, and accountability. The bar is higher than the old senior bar, not lower. A research role. This is shipping to a marketplace with $100M+ in bookings. Customers and pros are using what you ship inside the same week. Tech You'll Touch AI agents — Claude Code, Cursor, Codex, internal agent stack, MCP servers, evals tooling Backend — PHP/Laravel Frontend — TypeScript/React/React Native (customer & pro apps, web and mobile) Data — Redshift, dbt, Segment, Airflow Infra — AWS, Datadog, Sentry, GitHub Actions Documentation & process — Brain (Claude Code skills + docs repo), Confluence, Jira You don't need every box checked. You need deep skill in at least one of our stacks plus credible production experience with AI coding agents. Benefits Competitive salary of USD $80,000-$100,000 annual base Work from anywhere High ownership and autonomy Fast-moving team that loves to build, learn, and grow To apply: https://weworkremotely.com/remote-jobs/lawnstarter-staff-product-engineer

[employment_type]
Full-Time

[industry]
All Other Remote

**Translated Full Posting Text**

[title]
Staff Product Engineer

[company_profile]
LawnStarter

[location]
Anywhere in the World

[description]
Headquarters: São Paulo, Brazil URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and outdoor services, with over $100M in annual bookings. We're expanding beyond lawn care to become the one-stop shop for all home services — operating across three brands (LawnStarter, Lawn Love, Home Gnome) on a single shared platform. About Engineering at LawnStarter We're restructuring engineering around initiative teams: a Product Engineer paired with a PM and a designer, with an Engineering Manager who covers a couple of initiatives and supports your growth. The engineer leads AI agents like a team, ships the work, and is accountable — with the rest of the triangle — for whether the initiative moves its metric. We're betting that 1-2 strong engineers running AI agents can outship the labor-team model that defined the last decade of software. That bet only works if the engineers we hire are wired for ownership and can ship to a marketplace with real customers and professionals on both sides. The Role You're the engineering anchor of one initiative at a time. The initiative is a team effort — an iron triangle of you, your PM, and your designer — and you have key participation across the full lifecycle: shaping the problem, deciding the technical approach, leading the AI ​​agents that implement most of the code, shipping to production, and responding for the outcome alongside the rest of the triangle. You're accountable for the outcome — not for the volume of code merged. If an agent can ship it safely, your job is to make sure the agent does it right and the metric moves. If the initiative needs hand-written code in a sensitive area, you write it yourself. What makes this role different: You lead AI agents, not humans. Claude

Code, Cursor, Codex, and our internal agent stack are your team. You own the quality, safety, and velocity of what they produce. You own an outcome, not a ticket queue. Problem-framing through production through the metric review 2-4 weeks after launch. You partner horizontally with PM and design. No tech lead above you. No architect approval. No ticket grooming committee. The bar is staff, not senior. You make the call when the call needs to be made. If you're waiting to be told, this isn't the role. What You'll Own The technical approach — architecture, data model, integration choices, rollout plan, observability, and rollback strategy for your initiative. You make the call, document it, and revisit it if the data says you were wrong. Agent-led implementation quality — the prompts, guardrails, evals, tests, and review loop that let agents ship safe, correct, production-ready code on your initiative. Most lines will be agent-authored. You're accountable for them. Cross-functional partnership — daily working contact with your PM (scope, tradeoffs) and your designer (UX decisions, in-tool prototyping with agents), and weekly check-ins with your EM (initiative health, blockers, growth). The initiative outcome — the specific metric the initiative was set up to move. In partnership with your PM, you present results 2-4 weeks post-launch and share the "did it work" answer. A high bar for what ships under your name — production correctness, security posture, performance, observability, and the experience for customers and professionals. Agents accelerate you; they don't lower the bar. Problems to Solve Leading AI agents at staff-level quality Most of the code on your initiative will be authored by AI agents. The work is making agents ship as if a senior engineer wrote it: prompts

that encodes our codebase conventions, evals that catch hallucinations before merge, tests that exercise the edges, observability that catches the regression in production before a customer reports it. How do you build the agent workflow that lets one engineer ship what is used to take a team? Owning an outcome without a tech lead You don't have a tech lead to approve your design or an architect to escalate to. You have an EM who covers a couple of initiatives and peers on adjacent ones. How do you make calls fast, document them clearly, and stay accountable to the outcome — without slowing down for hierarchy that no longer exists? Shipping outcomes, not features The initiative will be measured by a metric — a conversion rate, a retention curve, a pro-funnel KPI, a unit economics shift. You're accountable for the number, not the feature. How do you scope to actually move it, decide what not to build, and have the discipline to follow up 2-4 weeks after launch even when the next initiative is calling? What Success Looks Like (Year 1) Initiative outcomes hit — You've shipped 3-4 end-to-end initiatives, and at least two clearly moved the metric they were set up to move (with the post-launch review to prove it). Agent workflow that travels — The prompts, evals, and review loop you built for your initiative are adopted by at least one other engineer on an adjacent initiative. Cycle time — Median time from problem-framing to first production rollout on your initiatives is significantly shorter than the pre-restructure baseline. Zero "agent-shipped that" incidents — No customer- or pro-facing regression traceable to agent-authored code that you missed in review. Visible leverage — Other engineers point to artifacts you left behind — runbooks, evals, agent workflows, post-launch

write-ups — the references they use. Who You Are AI-native. Claude Code, Cursor, Codex, or equivalent are how you ship — daily, on production work. You have opinions about prompts, evals, agent loops, MCP servers, and review workflows, and you know when to let the agent run vs. write it yourself. This is unlikely to be a good fit if you describe AI coding as "something you're exploring" or prefer to write everything by hand. Already operating at lead level. You may currently be titled Senior, Staff, Lead, or Principal — but in practice you've been the person making the call, shipping the hard thing, and answering for whether it worked. This is unlikely to be a good fit if you've always had a tech lead breaking down the work for you. Outcome-driven, not output-driven. You measure your week in "did the metric move" and "did the experience get better," not in closed tickets. You read the post-launch dashboard and you own the answer. This is unlikely to be a good fit if you take pride in volume of code shipped or feel uncomfortable being measured on a number you don't fully control. A strong horizontal partner. You hold your own with a strong PM and a strong designer. You bring engineering judgment to product calls and product judgment to engineering calls. This is unlikely to be a good fit if you hide behind "that's product's decision" or default to RICE-scoring tickets handed down to you. Decisive and documented. Architecture decisions, data-model choices, rollout plans — you write them down, get fast input, and move. This is unlikely to be a good fit if you wait for consensus on questions that have a clear right answer, or if you make calls and never write them down. Raises the floor, not just the ceiling. Your impact compounds beyond your own initiative because you

leave artifacts — agent workflows, evals, runbooks, post-launch reviews. This is unlikely to be a good fit if you're a lone wolf who ships brilliantly but leaves nothing reusable behind. Cares about customers and pros. This is a real-world marketplace with real people on both sides. This is unlikely to be a good fit if you're chasing pure engineering elegance over business and customer outcomes. This Role Is NOT A tech lead in an old-style team. No 4-5 engineers reporting up to you on technical direction. The team is you + PM + designer + EM, with AI agents doing most of the implementation. A management role today. People management is the EM's job in this role. That said, the path can grow into management for those who want it — it's an open door, not a closed one. A platform-only or architecture-only role. You're a Product Engineer. You ship features that move metrics, end-to-end. Platform work happens inside the initiative when it's needed for the outcome. A "let AI do everything" role. Agents handle implementation grunt work. You handle judgment, design, safety, and accountability. The bar is higher than the old senior bar, not lower. A research role. This is shipping to a marketplace with $100M+ in bookings. Customers and pros are using what you ship within the same week. Tech You'll Touch AI agents — Claude Code, Cursor, Codex, internal agent stack, MCP servers, evals tooling Backend — PHP/Laravel Frontend — TypeScript/React/React Native (customer & pro apps, web and mobile) Data — Redshift, dbt, Segment, Airflow Infra — AWS, Datadog, Sentry, GitHub Actions Documentation & process — Brain (Claude Code skills + docs repo), Confluence, Jira You don't need every box checked. You need deep skill in at least one of our stacks plus credible production experience with

AI coding agents. Benefits Competitive salary of USD $80,000-$100,000 annual base Work from anywhere High ownership and autonomy Fast-moving team that loves to build, learn, and grow To apply: https://weworkremotely.com/remote-jobs/lawnstarter-staff-product-engineer

[employment_type]
Full-Time

[industry]
All Other Remote

---

### #32 | Senior Webflow Designer
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/lawnstarter-senior-webflow-designer
- apply_url: https://weworkremotely.com/remote-jobs/lawnstarter-senior-webflow-designer

,field,original,translated,changed
0,title,Senior Webflow Designer,Senior Webflow Designer,False
1,company_profile,LawnStarter,LawnStarter,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: United States URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and related services, with ove...","Headquarters: United States URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and related services, with ove...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,All Other Remote,All Other Remote,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Webflow Designer

[company_profile]
LawnStarter

[location]
Anywhere in the World

[description]
Headquarters: United States URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and related services, with over $100M in annual bookings. We're expanding beyond lawn care to become the one-stop shop for all home services. About Growth at LawnStarter Our Growth team drives customer acquisition and conversion across four brands — LawnStarter, Lawn Love, Home Gnome, and ProBase. The marketing sites are central to that work: thousands of organic SEO pages, landing pages, and core site experiences that need to move as fast as the team iterating on them. Today, making changes to our marketing sites requires engineering support. That bottleneck slows down testing, kills momentum, and means conversion opportunities sit on the table. We're moving to Webflow as the source of truth for our marketing sites, and we need someone to own that transition and everything that follows. The Role You'll report to the Director of Design but sit on the Growth team day-to-day, working alongside the entire Growth team including the Technical Growth Manager, the CRO Specialist, data analysts, SEO, Paid, and content. Your job is to make our marketing sites fast to change, beautiful, on-brand, and optimized for conversion — without needing an engineer every time something needs to move. You'll start with Home Gnome, building it right from the ground up in Webflow. From there, you'll bring LawnStarter, Lawn Love, and ProBase into a componentized Webflow design system. This is a chance to define how all four brands show up on the web. The three Growth team roles you'll work with most closely The Designer, Technical Growth Manager, and CRO Specialist are three peers on the Growth team — one tight unit, not three separate orgs. The work runs as a constant collaboration, with the design loop iterating on every test result: You (Senior Webflow Designer) — design the foundation: page templates, page architecture, the component library and design system, interactions and animations, and the UX/UI standards (usability, accessibility, conversion best practices) every page is held to. The system you build needs to be robust and flexible enough that the Technical Growth Manager and CRO Specialist can spin up new pages from it without coming back to design every time. You step in when there's a new template, a new pattern, a major test-driven iteration, or a brand-new flow. Technical Growth Manager — takes your templates, page architecture, and components and makes them production-ready: CMS architecture, programmatic page infrastructure, production page builds, structured data, analytics implementation, and the same-day test rollout SLA. Once the foundation is in place, they spin up new pages directly from the system — that's how the team moves fast. CRO Specialist — owns the conversion testing roadmap, test design, hypotheses, and reads results. They can also spin up test pages from your templates and components when speed matters. You and the CRO Specialist work tightly together: they bring the conversion lens, you bring the design and UX lens, and you iterate on templates, page architecture, and components based on what the data shows. The whole model only works through close collaboration. The system isn't handed off and forgotten — it evolves as the three of you ship, test, and learn together. What makes this role different: You design AND build in Webflow : This isn't a Figma-to-handoff role. You design the page templates, page architecture, components, and UX/UI standards that define the marketing sites, and you build them directly in Webflow. Design happens in Webflow, not Figma. Embedded with Growth, not siloed in Design : You sit with the people running experiments, analyzing conversion data, and optimizing funnels. Design decisions here are measured in conversion rates, not likes. Multi-brand site ownership : You design the marketing site experience across four brands — each with its own identity, sharing a foundation you build and maintain. AI-native by default : Claude Code and Claude are core to how you work, not novelty add-ons. What You'll Own The marketing site design and foundation across four brands : Page templates, page architecture (section flow, hierarchy, layout patterns), navigation, key flows, hero patterns, conversion patterns. The system you design needs to be flexible and robust enough that the Technical Growth Manager and CRO Specialist can spin up new pages directly from it — without coming back to design for every page. Visual design and brand execution at a high bar : This is core to the role. The marketing sites need to look modern, polished, and unmistakably on-brand for each of the four brands — and they need to hold up against the best marketing sites on the web. You're the quality bar for typography, spacing, hierarchy, color, imagery, composition, and all the details that separate good from great. Strong visual design and disciplined brand execution are non-negotiable. Webflow design system and component library : Build and maintain the system across all four brands — components, design tokens, page templates, shared interaction patterns. The system is the source of truth for how every brand looks, behaves, and is built, and the foundation the Technical Growth Manager and CRO Specialist build new pages from. UX/UI, usability, and accessibility : You bring the discipline. Every component, template, and page reflects current best practices for usability, conversion, and WCAG accessibility. This isn't a checklist run at the end — it's how you design from the start. Interactions and motion : A core part of the role, not a finishing touch. You design and build purposeful interactions and animations — micro-interactions, scroll behavior, loading states, motion-driven storytelling — that elevate the brands and make pages feel premium. You use Webflow's native tools where they fit and write custom CSS or JS when they don't. Test-ready designs and variants : Partner closely with the CRO Specialist. You design the templates, components, and variants that power tests so they can be spun up and iterated quickly. The CRO Specialist defines hypotheses and reads results; together you iterate on the templates and components based on what wins. The Technical Growth Manager rolls winners out. Production handoff and QA : Hand off completed templates and built components to the Technical Growth Manager, who wires them into the CMS, builds production pages, and ships at scale. You stay involved through QA so production matches design intent — and you iterate on the system based on what the team learns shipping it. Problems to Solve Our marketing sites depend on engineering for every change Today, even simple updates require a developer. That means the Growth team can't iterate at the speed they need to. New pages wait in a queue. You're the design half of the unblock: a Webflow design system the Technical Growth Manager can build with, so marketing site changes happen fast without engineering involvement. Our marketing sites aren't designed at the level we need Functional, but not designed. There are no shared page templates, no Webflow component library, no design tokens, no consistent UX/UI patterns, no interaction language. You build the foundation: a designed site, page templates, a component library, and the UX/UI standards (usability, accessibility, conversion best practices) that everything is held to. The Technical Growth Manager makes it production-ready; you make it worth shipping. Thousands of SEO pages need to look modern, feel premium, and convert We have over a thousand organic SEO pages across our brands. These pages drive significant traffic and revenue, but they need to look modern, feel polished, be accessible, and maintain brand and UX consistency at scale. You design the page templates, the components, and the UX patterns; the Technical Growth Manager wires them into the CMS and ships them at scale. Together you make the SEO portfolio look like a real brand, not a content farm. Four brands need to look distinct but share a foundation Home Gnome, LawnStarter, Lawn Love, and ProBase each have their own visual identity. But the underlying design system — components, tokens, interaction patterns — should be shared where it makes sense. What Success Looks Like (Year 1) Home Gnome fully designed and live in Webflow — page templates, components, interactions, and UX/UI standards that meet a high bar for visual design, brand execution, usability, and accessibility, with the Technical Growth Manager scaling it across pages without engineering A complete Webflow design system the team can self-serve from — components, design tokens, page templates, and UX/UI standards solid enough that the Technical Growth Manager and CRO Specialist can spin up new pages directly from the system without coming back to design every time Test-ready designs and variants ready to iterate fast — when the CRO Specialist needs a hero variant, a new template, or a CTA test, the components are ready to test or you ship the new design quickly and iterate based on results SEO templates designed for scale — page templates that set the visual, UX, and accessibility bar across thousands of programmatic pages the Technical Growth Manager wires into the CMS Interactions and motion that make the brands feel premium — purposeful animation across the design system, not bolted-on after launch WCAG-compliant by default — accessibility is a baseline, not a project A working iteration loop with the CRO Specialist — test results consistently flow back into your templates and components Site design migration underway for LawnStarter and Lawn Love The Technical Growth Manager and CRO Specialist consider you essential — they can't imagine shipping or testing without you Requirements Who You Are A top-tier visual and brand designer. Strong visual design and disciplined brand execution are at the core of this role, not a side requirement. Your work is modern, polished, and unmistakably on-brand. You hold up against the best marketing sites on the web. You care deeply about typography, spacing, hierarchy, color, imagery, composition, and the details that separate good from great. You can execute within established brand guidelines while pushing the visual quality forward, and you can hold the line across four distinct brands without letting any of them drift. This is unlikely to be a good fit if visual design or brand discipline is secondary to your other skills, or if you rely heavily on templates without elevating them. A Webflow expert. You've built and maintained complex, multi-page Webflow sites with real architectural rigor — not just pretty one-pagers. You understand component architecture, design systems, dynamic content, advanced interactions, and how to keep a large site clean and performant. You can structure a page so it works at scale, not just for one hero shot. This is unlikely to be a good fit if you've only used Webflow for small projects or treat it as a visual tool rather than a design and build platform. UX/UI disciplined. You bring real expertise in usability, accessibility (WCAG), and conversion best practices — and you apply it to every component, template, and page. You can articulate why a layout works (or doesn't) for the user, not just how it looks. You design for clarity, scannability, and performance, and you treat accessibility as a baseline, not a finishing touch. This is unlikely to be a good fit if you can't speak to UX principles beyond aesthetics or treat usability and accessibility as someone else's job. Collaborative by default. This role only works through tight collaboration with the Technical Growth Manager (on production handoff and feasibility) and the CRO Specialist (on test design and iteration). You give and take feedback well, you're comfortable handing off work and staying involved through QA, and you treat test results as input rather than judgment. This is unlikely to be a good fit if you prefer to work alone or get defensive when data contradicts your design choices. Growth-team fluent. You've worked alongside CMOs, SEO teams, paid teams, content teams, CRO specialists, data analysts, and engineers before. You understand conversion funnels, A/B testing, and how to support experiments and iterate quickly. You make decisions based on data, not just aesthetics. This is unlikely to be a good fit if you've only worked in brand or product design teams and aren't familiar with the pace and priorities of growth. Self-directed and fast. You take a brief, run with it, and ship. You don't need someone managing your queue or reviewing every decision. When there's a new template to design, a new pattern to add to the system, or a test result that points to an iteration, you turn it around quickly without sacrificing quality. This is unlikely to be a good fit if you need detailed direction for each project or prefer a slower, more deliberate pace. AI-native. You use Claude Code and Claude as core parts of your workflow — generating component code, exploring design directions, drafting interaction logic, and accelerating everything from naming to layout iteration. You treat AI as a design and build partner, not a novelty. This is unlikely to be a good fit if you're skeptical of AI tools or insist on building everything from scratch. Technically capable beyond Webflow native. Webflow's native tools won't cover everything — especially the interactions, animations, and complex components you'll build. You can write custom CSS and JavaScript when Webflow falls short, and you can read enough code to debug a third-party embed or extend an existing component. The Technical Growth Manager owns tracking and integrations; you own the code that makes the design system feel alive. This is unlikely to be a good fit if you strictly avoid code or rely on others to handle anything beyond drag-and-drop. This Role Is NOT A Figma-to-Webflow production role : The design system for growth and marketing lives in Webflow. You're not translating someone else's mockups — you're designing and building directly. The production builder for SEO and CMS pages : The Technical Growth Manager owns CMS architecture, programmatic page infrastructure, and the production builds for thousands of SEO URLs. You design the templates and components; the Technical Growth Manager wires them into production. The owner of test rollouts : The Technical Growth Manager owns running tests live and the same-day rollout SLA. Your job is upstream — shipping the variants and components that make tests possible. A brand design role : You'll maintain brand consistency, but you're not creating brand identities. A role with a clean starting point : The current marketing sites need significant work. You're inheriting complexity and building toward simplicity — not maintaining something that already works well. A solo design role : You'll collaborate regularly with the Director of Design and the brand/product design team on component development and brand standards. Day-to-day, your closest partners are the Technical Growth Manager and CRO Specialist on the Growth team. Benefits Base salary : $110K - $140K. 401k Healthcare : Medical, dental, and vision Fully remote Unlimited PTO : We focus on results. Take what you need. LawnStarter provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, sex, national origin, age, disability, or genetics. We comply with applicable state and local laws governing nondiscrimination in employment. To apply: https://weworkremotely.com/remote-jobs/lawnstarter-senior-webflow-designer

[employment_type]
Full-Time

[industry]
All Other Remote

**Translated Full Posting Text**

[title]
Senior Webflow Designer

[company_profile]
LawnStarter

[location]
Anywhere in the World

[description]
Headquarters: United States URL: http://lawnstarter.com About LawnStarter LawnStarter is the nation's leading on-demand marketplace for lawn care and related services, with over $100M in annual bookings. We're expanding beyond lawn care to become the one-stop shop for all home services. About Growth at LawnStarter Our Growth team drives customer acquisition and conversion across four brands — LawnStarter, Lawn Love, Home Gnome, and ProBase. The marketing sites are central to that work: thousands of organic SEO pages, landing pages, and core site experiences that need to move as fast as the team iterating on them. Today, making changes to our marketing sites requires engineering support. That bottleneck slows down testing, kills momentum, and means conversion opportunities sit on the table. We're moving to Webflow as the source of truth for our marketing sites, and we need someone to own that transition and everything that follows. The Role You'll report to the Director of Design but sit on the Growth team day-to-day, working alongside the entire Growth team including the Technical Growth Manager, the CRO Specialist, data analysts, SEO, Paid, and content. Your job is to make our marketing sites fast to change, beautiful, on-brand, and optimized for conversion — without needing an engineer every time something needs to move. You'll start with Home Gnome, building it right from the ground up in Webflow. From there, you'll bring LawnStarter, Lawn Love, and ProBase into a componentized Webflow design system. This is a chance to define how all four brands show up on the web. The three Growth team roles you'll work with most closely The Designer, Technical Growth Manager, and CRO Specialist are three peers on the Growth team — one tight unit, not three separate orgs. The work runs as a constant collaboration, with the design loop iterating on every test result: You (Senior Webflow Designer) — design the foundation: page templates, page architecture, the component library and design system, interactions and animations, and the UX/UI standards (usability, accessibility, conversion best practices) every page is held to. The system you build needs to be robust and flexible enough that the Technical Growth Manager and CRO Specialist can spin up new pages from it without coming back to design every time. You step in when there's a new template, a new pattern, a major test-driven iteration, or a brand-new flow. Technical Growth Manager — takes your templates, page architecture, and components and makes them production-ready: CMS architecture, programmatic page infrastructure, production page builds, structured data, analytics implementation, and the same-day test rollout SLA. Once the foundation is in place, they spin up new pages directly from the system — that's how the team moves fast. CRO Specialist — owns the conversion testing roadmap, test design, hypotheses, and reads results. They can also spin up test pages from your templates and components when speed matters. You and the CRO Specialist work tightly together: they bring the conversion lens, you bring the design and UX lens, and you iterate on templates, page architecture, and components based on what the data shows. The whole model only works through close collaboration. The system isn't handed off and forgotten — it evolves as the three of you ship, test, and learn together. What makes this role different: You design AND build in Webflow : This isn't a Figma-to-handoff role. You design the page templates, page architecture, components, and UX/UI standards that define the marketing sites, and you build them directly in Webflow. Design happens in Webflow, not Figma. Embedded with Growth, not siloed in Design : You sit with the people running experiments, analyzing conversion data, and optimizing funnels. Design decisions here are measured in conversion rates, not likes. Multi-brand site ownership : You design the marketing site experience across four brands — each with its own identity, sharing a foundation you build and maintain. AI-native by default : Claude Code and Claude are core to how you work, not novelty add-ons. What You'll Own The marketing site design and foundation across four brands : Page templates, page architecture (section flow, hierarchy, layout patterns), navigation, key flows, hero patterns, conversion patterns. The system you design needs to be flexible and robust enough that the Technical Growth Manager and CRO Specialist can spin up new pages directly from it — without coming back to design for every page. Visual design and brand execution at a high bar : This is core to the role. The marketing sites need to look modern, polished, and unmistakably on-brand for each of the four brands — and they need to hold up against the best marketing sites on the web. You're the quality bar for typography, spacing, hierarchy, color, imagery, composition, and all the details that separate good from great. Strong visual design and disciplined brand execution are non-negotiable. Webflow design system and component library : Build and maintain the system across all four brands — components, design tokens, page templates, shared interaction patterns. The system is the source of truth for how every brand looks, behaves, and is built, and the foundation the Technical Growth Manager and CRO Specialist build new pages from. UX/UI, usability, and accessibility : You bring the discipline. Every component, template, and page reflects current best practices for usability, conversion, and WCAG accessibility. This isn't a checklist run at the end — it's how you design from the start. Interactions and motion : A core part of the role, not a finishing touch. You design and build purposeful interactions and animations — micro-interactions, scroll behavior, loading states, motion-driven storytelling — that elevate the brands and make pages feel premium. You use Webflow's native tools where they fit and write custom CSS or JS when they don't. Test-ready designs and variants : Partner closely with the CRO Specialist. You design the templates, components, and variants that power tests so they can be spun up and iterated quickly. The CRO Specialist defines hypotheses and reads results; together you iterate on the templates and components based on what wins. The Technical Growth Manager rolls winners out. Production handoff and QA : Hand off completed templates and built components to the Technical Growth Manager, who wires them into the CMS, builds production pages, and ships at scale. You stay involved through QA so production matches design intent — and you iterate on the system based on what the team learns shipping it. Problems to Solve Our marketing sites depend on engineering for every change Today, even simple updates require a developer. That means the Growth team can't iterate at the speed they need to. New pages wait in a queue. You're the design half of the unblock: a Webflow design system the Technical Growth Manager can build with, so marketing site changes happen fast without engineering involvement. Our marketing sites aren't designed at the level we need Functional, but not designed. There are no shared page templates, no Webflow component library, no design tokens, no consistent UX/UI patterns, no interaction language. You build the foundation: a designed site, page templates, a component library, and the UX/UI standards (usability, accessibility, conversion best practices) that everything is held to. The Technical Growth Manager makes it production-ready; you make it worth shipping. Thousands of SEO pages need to look modern, feel premium, and convert We have over a thousand organic SEO pages across our brands. These pages drive significant traffic and revenue, but they need to look modern, feel polished, be accessible, and maintain brand and UX consistency at scale. You design the page templates, the components, and the UX patterns; the Technical Growth Manager wires them into the CMS and ships them at scale. Together you make the SEO portfolio look like a real brand, not a content farm. Four brands need to look distinct but share a foundation Home Gnome, LawnStarter, Lawn Love, and ProBase each have their own visual identity. But the underlying design system — components, tokens, interaction patterns — should be shared where it makes sense. What Success Looks Like (Year 1) Home Gnome fully designed and live in Webflow — page templates, components, interactions, and UX/UI standards that meet a high bar for visual design, brand execution, usability, and accessibility, with the Technical Growth Manager scaling it across pages without engineering A complete Webflow design system the team can self-serve from — components, design tokens, page templates, and UX/UI standards solid enough that the Technical Growth Manager and CRO Specialist can spin up new pages directly from the system without coming back to design every time Test-ready designs and variants ready to iterate fast — when the CRO Specialist needs a hero variant, a new template, or a CTA test, the components are ready to test or you ship the new design quickly and iterate based on results SEO templates designed for scale — page templates that set the visual, UX, and accessibility bar across thousands of programmatic pages the Technical Growth Manager wires into the CMS Interactions and motion that make the brands feel premium — purposeful animation across the design system, not bolted-on after launch WCAG-compliant by default — accessibility is a baseline, not a project A working iteration loop with the CRO Specialist — test results consistently flow back into your templates and components Site design migration underway for LawnStarter and Lawn Love The Technical Growth Manager and CRO Specialist consider you essential — they can't imagine shipping or testing without you Requirements Who You Are A top-tier visual and brand designer. Strong visual design and disciplined brand execution are at the core of this role, not a side requirement. Your work is modern, polished, and unmistakably on-brand. You hold up against the best marketing sites on the web. You care deeply about typography, spacing, hierarchy, color, imagery, composition, and the details that separate good from great. You can execute within established brand guidelines while pushing the visual quality forward, and you can hold the line across four distinct brands without letting any of them drift. This is unlikely to be a good fit if visual design or brand discipline is secondary to your other skills, or if you rely heavily on templates without elevating them. A Webflow expert. You've built and maintained complex, multi-page Webflow sites with real architectural rigor — not just pretty one-pagers. You understand component architecture, design systems, dynamic content, advanced interactions, and how to keep a large site clean and performant. You can structure a page so it works at scale, not just for one hero shot. This is unlikely to be a good fit if you've only used Webflow for small projects or treat it as a visual tool rather than a design and build platform. UX/UI disciplined. You bring real expertise in usability, accessibility (WCAG), and conversion best practices — and you apply it to every component, template, and page. You can articulate why a layout works (or doesn't) for the user, not just how it looks. You design for clarity, scannability, and performance, and you treat accessibility as a baseline, not a finishing touch. This is unlikely to be a good fit if you can't speak to UX principles beyond aesthetics or treat usability and accessibility as someone else's job. Collaborative by default. This role only works through tight collaboration with the Technical Growth Manager (on production handoff and feasibility) and the CRO Specialist (on test design and iteration). You give and take feedback well, you're comfortable handing off work and staying involved through QA, and you treat test results as input rather than judgment. This is unlikely to be a good fit if you prefer to work alone or get defensive when data contradicts your design choices. Growth-team fluent. You've worked alongside CMOs, SEO teams, paid teams, content teams, CRO specialists, data analysts, and engineers before. You understand conversion funnels, A/B testing, and how to support experiments and iterate quickly. You make decisions based on data, not just aesthetics. This is unlikely to be a good fit if you've only worked in brand or product design teams and aren't familiar with the pace and priorities of growth. Self-directed and fast. You take a brief, run with it, and ship. You don't need someone managing your queue or reviewing every decision. When there's a new template to design, a new pattern to add to the system, or a test result that points to an iteration, you turn it around quickly without sacrificing quality. This is unlikely to be a good fit if you need detailed direction for each project or prefer a slower, more deliberate pace. AI-native. You use Claude Code and Claude as core parts of your workflow — generating component code, exploring design directions, drafting interaction logic, and accelerating everything from naming to layout iteration. You treat AI as a design and build partner, not a novelty. This is unlikely to be a good fit if you're skeptical of AI tools or insist on building everything from scratch. Technically capable beyond Webflow native. Webflow's native tools won't cover everything — especially the interactions, animations, and complex components you'll build. You can write custom CSS and JavaScript when Webflow falls short, and you can read enough code to debug a third-party embed or extend an existing component. The Technical Growth Manager owns tracking and integrations; you own the code that makes the design system feel alive. This is unlikely to be a good fit if you strictly avoid code or rely on others to handle anything beyond drag-and-drop. This Role Is NOT A Figma-to-Webflow production role : The design system for growth and marketing lives in Webflow. You're not translating someone else's mockups — you're designing and building directly. The production builder for SEO and CMS pages : The Technical Growth Manager owns CMS architecture, programmatic page infrastructure, and the production builds for thousands of SEO URLs. You design the templates and components; the Technical Growth Manager wires them into production. The owner of test rollouts : The Technical Growth Manager owns running tests live and the same-day rollout SLA. Your job is upstream — shipping the variants and components that make tests possible. A brand design role : You'll maintain brand consistency, but you're not creating brand identities. A role with a clean starting point : The current marketing sites need significant work. You're inheriting complexity and building toward simplicity — not maintaining something that already works well. A solo design role : You'll collaborate regularly with the Director of Design and the brand/product design team on component development and brand standards. Day-to-day, your closest partners are the Technical Growth Manager and CRO Specialist on the Growth team. Benefits Base salary : $110K - $140K. 401k Healthcare : Medical, dental, and vision Fully remote Unlimited PTO : We focus on results. Take what you need. LawnStarter provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, sex, national origin, age, disability, or genetics. We comply with applicable state and local laws governing nondiscrimination in employment. To apply: https://weworkremotely.com/remote-jobs/lawnstarter-senior-webflow-designer

[employment_type]
Full-Time

[industry]
All Other Remote

---

### #33 | Full-Stack Developer — .NET + React + Azure — Remote (US)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/shiftforce-llc-full-stack-developer-net-react-azure-remote-us
- apply_url: https://weworkremotely.com/remote-jobs/shiftforce-llc-full-stack-developer-net-react-azure-remote-us

,field,original,translated,changed
0,title,Full-Stack Developer — .NET + React + Azure — Remote (US),Full-Stack Developer — .NET + React + Azure — Remote (US),False
1,company_profile,ShiftForce LLC,ShiftForce LLC,False
2,location,"Anywhere in the World, Missouri","Anywhere in the World, Missouri",False
3,department,,,False
4,description,"Headquarters: Kansas City URL: https://www.shiftforce.com **About us** ShiftForce is scheduling and operations software for restaurants. We've been around a while, we're profit...","Headquarters: Kansas City URL: https://www.shiftforce.com **About us** ShiftForce is scheduling and operations software for restaurants. We've been around a while, we're profit...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Full-Stack Developer — .NET + React + Azure — Remote (US)

[company_profile]
ShiftForce LLC

[location]
Anywhere in the World, Missouri

[description]
Headquarters: Kansas City URL: https://www.shiftforce.com **About us** ShiftForce is scheduling and operations software for restaurants. We've been around a while, we're profitable, and we ship real features to real users every week. Small team — there are no layers of management between you and the work, which means real ownership and real impact, but also means everyone pitches in on whatever needs doing. **The role** We need a full-stack developer who works like an owner. You'll pick up problems from the backlog, ask the questions you need answered, then build and ship the solution. We're not looking for someone who needs every decision made for them — but we're also not looking for someone who treats every ticket as an excuse to rewrite a subsystem. A typical week might be shipping a couple of features, fixing a few bugs, debugging a weird Azure Function timeout, reviewing a teammate's PR, and pushing back on a product idea that doesn't make sense. Some weeks lean more toward infra and ops — a broken pipeline, a slow query. Because we're small, you'll wear many hats. You should be comfortable solving technical problems that aren't strictly "writing code," and you shouldn't expect a dedicated DevOps or DBA team to hand you a clean environment. **Stack** - Backend: C# / .NET Core 10, some legacy .NET Framework (being migrated) - Frontend: React, Next.js, TypeScript, CSS - Mobile: React Native / Expo - Data: SQL Server, PostgreSQL — real queries, real indexes, real execution plans - Infra: Azure Functions, App Service, DevOps pipelines, Key Vault **You're a fit if you** - Have 3+ years shipping production code on a similar stack - Solve problems instead of escalating them — you read the logs, write a repro, check the docs - Build what was asked for, not what you wish was asked for - Are comfortable wearing many hats: code, infra, debugging, customer issues, whatever the week needs - Use AI coding tools (Cursor, Claude, Copilot) as part of your daily workflow — not as a novelty - Communicate clearly in writing (most of our communication is async) **Logistics** - 100% remote, US-based - Full-time - Slight preference for candidates in Las Vegas or Kansas City — not a requirement **How to apply** Email justinb@shiftforce.com with a short note describing a hard bug you debugged recently — what was broken, how you found it, how you fixed it. That's the application. Resume optional. To apply: https://weworkremotely.com/remote-jobs/shiftforce-llc-full-stack-developer-net-react-azure-remote-us

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Full-Stack Developer — .NET + React + Azure — Remote (US)

[company_profile]
ShiftForce LLC

[location]
Anywhere in the World, Missouri

[description]
Headquarters: Kansas City URL: https://www.shiftforce.com **About us** ShiftForce is scheduling and operations software for restaurants. We've been around a while, we're profitable, and we ship real features to real users every week. Small team — there are no layers of management between you and the work, which means real ownership and real impact, but also means everyone pitches in on whatever needs doing. **The role** We need a full-stack developer who works like an owner. You'll pick up problems from the backlog, ask the questions you need answered, then build and ship the solution. We're not looking for someone who needs every decision made for them — but we're also not looking for someone who treats every ticket as an excuse to rewrite a subsystem. A typical week might be shipping a couple of features, fixing a few bugs, debugging a weird Azure Function timeout, reviewing a teammate's PR, and pushing back on a product idea that doesn't make sense. Some weeks lean more toward infra and ops — a broken pipeline, a slow query. Because we're small, you'll wear many hats. You should be comfortable solving technical problems that aren't strictly "writing code," and you shouldn't expect a dedicated DevOps or DBA team to hand you a clean environment. **Stack** - Backend: C# / .NET Core 10, some legacy .NET Framework (being migrated) - Frontend: React, Next.js, TypeScript, CSS - Mobile: React Native / Expo - Data: SQL Server, PostgreSQL — real queries, real indexes, real execution plans - Infra: Azure Functions, App Service, DevOps pipelines, Key Vault **You're a fit if you** - Have 3+ years shipping production code on a similar stack - Solve problems instead of escalating them — you read the logs, write a repro, check the docs - Build what was asked for, not what you wish was asked for - Are comfortable wearing many hats: code, infra, debugging, customer issues, whatever the week needs - Use AI coding tools (Cursor, Claude, Copilot) as part of your daily workflow — not as a novelty - Communicate clearly in writing (most of our communication is async) **Logistics** - 100% remote, US-based - Full-time - Slight preference for candidates in Las Vegas or Kansas City — not a requirement **How to apply** Email justinb@shiftforce.com with a short note describing a hard bug you debugged recently — what was broken, how you found it, how you fixed it. That's the application. Resume optional. To apply: https://weworkremotely.com/remote-jobs/shiftforce-llc-full-stack-developer-net-react-azure-remote-us

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #34 | Jr Appointment Setter
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/orchard-brokerage-jr-appointment-setter
- apply_url: https://weworkremotely.com/remote-jobs/orchard-brokerage-jr-appointment-setter

,field,original,translated,changed
0,title,Jr Appointment Setter,Jr Appointment Setter,False
1,company_profile,Orchard Brokerage,Orchard Brokerage,False
2,location,"Anywhere in the World, Texas","Anywhere in the World, Texas",False
3,department,,,False
4,description,"Headquarters: New York, New York URL: https://orchard.com/ Quick read before you apply. This job is simple. You call people. You find out if they have a house. You find out if ...","Headquarters: New York, New York URL: https://orchard.com/ Quick read before you apply. This job is simple. You call people. You find out if they have a house. You find out if ...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Contract,Contract,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Sales and Marketing,Sales and Marketing,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Jr Appointment Setter

[company_profile]
Orchard Brokerage

[location]
Anywhere in the World, Texas

[description]
Headquarters: New York, New York URL: https://orchard.com/ Quick read before you apply. This job is simple. You call people. You find out if they have a house. You find out if they want to sell it. That's it. If they say yes, you book the appointment with our closer. Then you move on to the next one. What You Don't Do You don't pitch. You don't sell. You don't talk about price or commission. That's not your job. Your job is to find people who want to talk. What A Day Looks Like You dial for 4 hours. You talk to about 30 people. Out of those, 3-5 will raise their hand. Out of those, 1 will end up on our closer's calendar. That's a good day. You log the call. One line. Move on. The Pay $4-5/hr base. Paid Twice a month. Bonuses on top: $5 every time our closer gets on the phone with someone you passed over Bumps to $8 per call once you hit your weekly quota $5 every time our closer books the appointment $25 every time we get the listing $2,500 cash when 12 deals close from your work — plus all your bonuses double for the next year The top people on our team make way more than their base. The math works if you consistently do the reps. The Schedule 20 hours a week. Part-time. Fully remote. You pick your hours. Just be on during US business hours (8am-7pm, CST US time zone). Who We Want You're comfortable on the phone Rejection doesn't bother you You follow a script. You don't freelance. You're organized. You can track 50 calls a day without losing your place. Your English is strong enough that people trust you on the phone You want to get paid for results Who We Don't Want People who want to "sell" People who think a script is beneath them People who go quiet after 3 "no"s in a row How to Apply Send us two things: 1. Your resume. 2. A audio recording of you reading this script out loud. This is the actual script you'd run on the job. It's called the Expired Script and we use it when we call homeowners whose listing just came off the market without selling. Read your lines like you'd say them on a real phone call. Skip the "[Prospect:]" lines — those are just there so you know what you're responding to. You: Hi, is this Bob? [Prospect:] Yeah, who is this. You: Bob, this is [your name]. Look, I'll be upfront, I'm with a Realtor, and before you hang up, I was hoping to ask you something really quick, would that be ok? [Prospect:] ...okay, what is it? You: I appreciate that. I saw the home on Oak Street came off the market a few weeks back. Do you still want to get it sold? [Prospect:] Yeah, we do. You: Listen, you've got to talk to Ry. He's awesome. He just sold four homes exactly like yours. Would there be any downside to taking a 5 minute call with him? I've got him open Tuesday at 2 or Wednesday at 10 — which works better? Read it like you'd say it on a real call. Energy matters. We're listening for tone, pace, and confidence. Send both to: [ryan.colston@orchard.com] If your audio sounds right and your resume fits, we'll set up a call. If not, we'll let you know. To apply: https://weworkremotely.com/remote-jobs/orchard-brokerage-jr-appointment-setter

[employment_type]
Contract

[industry]
Sales and Marketing

**Translated Full Posting Text**

[title]
Jr Appointment Setter

[company_profile]
Orchard Brokerage

[location]
Anywhere in the World, Texas

[description]
Headquarters: New York, New York URL: https://orchard.com/ Quick read before you apply. This job is simple. You call people. You find out if they have a house. You find out if they want to sell it. That's it. If they say yes, you book the appointment with our closer. Then you move on to the next one. What You Don't Do You don't pitch. You don't sell. You don't talk about price or commission. That's not your job. Your job is to find people who want to talk. What A Day Looks Like You dial for 4 hours. You talk to about 30 people. Out of those, 3-5 will raise their hand. Out of those, 1 will end up on our closer's calendar. That's a good day. You log the call. One line. Move on. The Pay $4-5/hr base. Paid Twice a month. Bonuses on top: $5 every time our closer gets on the phone with someone you passed over Bumps to $8 per call once you hit your weekly quota $5 every time our closer books the appointment $25 every time we get the listing $2,500 cash when 12 deals close from your work — plus all your bonuses double for the next year The top people on our team make way more than their base. The math works if you consistently do the reps. The Schedule 20 hours a week. Part-time. Fully remote. You pick your hours. Just be on during US business hours (8am-7pm, CST US time zone). Who We Want You're comfortable on the phone Rejection doesn't bother you You follow a script. You don't freelance. You're organized. You can track 50 calls a day without losing your place. Your English is strong enough that people trust you on the phone You want to get paid for results Who We Don't Want People who want to "sell" People who think a script is beneath them People who go quiet after 3 "no"s in a row How to Apply Send us two things: 1. Your resume. 2. A audio recording of you reading this script out loud. This is the actual script you'd run on the job. It's called the Expired Script and we use it when we call homeowners whose listing just came off the market without selling. Read your lines like you'd say them on a real phone call. Skip the "[Prospect:]" lines — those are just there so you know what you're responding to. You: Hi, is this Bob? [Prospect:] Yeah, who is this. You: Bob, this is [your name]. Look, I'll be upfront, I'm with a Realtor, and before you hang up, I was hoping to ask you something really quick, would that be ok? [Prospect:] ...okay, what is it? You: I appreciate that. I saw the home on Oak Street came off the market a few weeks back. Do you still want to get it sold? [Prospect:] Yeah, we do. You: Listen, you've got to talk to Ry. He's awesome. He just sold four homes exactly like yours. Would there be any downside to taking a 5 minute call with him? I've got him open Tuesday at 2 or Wednesday at 10 — which works better? Read it like you'd say it on a real call. Energy matters. We're listening for tone, pace, and confidence. Send both to: [ryan.colston@orchard.com] If your audio sounds right and your resume fits, we'll set up a call. If not, we'll let you know. To apply: https://weworkremotely.com/remote-jobs/orchard-brokerage-jr-appointment-setter

[employment_type]
Contract

[industry]
Sales and Marketing

---

### #35 | Entry-Level Account Manager
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/nogigiddy-entry-level-account-manager-4
- apply_url: https://weworkremotely.com/remote-jobs/nogigiddy-entry-level-account-manager-4

,field,original,translated,changed
0,title,Entry-Level Account Manager,Entry-Level Account Manager,False
1,company_profile,NoGigiddy,NoGigiddy,False
2,location,"Anywhere in the World, Georgia","Anywhere in the World, Georgia",False
3,department,,,False
4,description,"Headquarters: Atlanta, Georgia URL: https://www.nogigiddy.com/ NoGigiddy is seeking a proactive and customer-focused Entry-Level Account Manager to join our remote team. In thi...","Headquarters: Atlanta, Georgia URL: https://www.nogigiddy.com/ NoGigiddy is seeking a proactive and customer-focused Entry-Level Account Manager to join our remote team. In thi...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Contract,Contract,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Customer Support,Customer Support,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Entry-Level Account Manager

[company_profile]
NoGigiddy

[location]
Anywhere in the World, Georgia

[description]
Headquarters: Atlanta, Georgia URL: https://www.nogigiddy.com/ NoGigiddy is seeking a proactive and customer-focused Entry-Level Account Manager to join our remote team. In this role, you will build and maintain relationships with our clients, ensuring their needs are met and providing exceptional service. This position is perfect for someone eager to start their career in account management and customer service. No college degree is required, but strong communication skills and a passion for helping clients are essential. Key Responsibilities: Client Relationship Management: Build and maintain strong relationships with clients, understanding their needs and ensuring their satisfaction. Communication: Act as the main point of contact for clients, addressing their inquiries, concerns, and requests promptly and effectively. Account Coordination: Assist in coordinating client accounts, including setting up new accounts, managing renewals, and ensuring all client information is up to date. Problem Solving: Identify and resolve client issues proactively, ensuring a positive client experience. Reporting: Prepare and deliver regular reports on account performance, client feedback, and service improvements. Collaboration: Work closely with internal teams, including sales, marketing, and customer support, to ensure client needs are met. Client Onboarding: Assist in onboarding new clients, providing them with the necessary resources and information to get started. Feedback Collection: Gather and relay client feedback to improve our services and client experience. Skills and Qualifications: Communication Skills: Exceptional verbal and written communication skills. Customer Service Skills: Strong ability to understand and meet client needs. Organizational Skills: Ability to manage multiple tasks and prioritize effectively. Interpersonal Skills: Strong ability to build and maintain relationships with clients and team members. Problem-Solving: Ability to address and resolve client issues effectively. Time Management: Strong ability to manage time and meet deadlines. Technical Skills: Basic proficiency with Microsoft Office Suite (Word, Excel, Outlook) and CRM software. Preferred Experience: Experience in customer service, sales, or a related field is a plus but not required. Familiarity with CRM software and account management tools is a plus. Previous experience with gig economy platforms or staffing apps is a plus. Education: High school diploma or equivalent. Relevant certifications or coursework in customer service, sales, or account management are beneficial but not required. Working Conditions: Remote Work: The role is remote, allowing for flexibility in work location. Collaboration: Regular virtual meetings and communications with the sales and support teams. Tools: Use of various communication and collaboration tools, such as email, video conferencing, and CRM software. Salary Range: $20 to $27 per hour, depending on experience and qualifications. If you are organized, detail-oriented, and passionate about providing excellent service to clients, we’d love to hear from you! Apply now to join NoGigiddy and make a difference in the gig economy. To apply: https://weworkremotely.com/remote-jobs/nogigiddy-entry-level-account-manager-4

[employment_type]
Contract

[industry]
Customer Support

**Translated Full Posting Text**

[title]
Entry-Level Account Manager

[company_profile]
NoGigiddy

[location]
Anywhere in the World, Georgia

[description]
Headquarters: Atlanta, Georgia URL: https://www.nogigiddy.com/ NoGigiddy is seeking a proactive and customer-focused Entry-Level Account Manager to join our remote team. In this role, you will build and maintain relationships with our clients, ensuring their needs are met and providing exceptional service. This position is perfect for someone eager to start their career in account management and customer service. No college degree is required, but strong communication skills and a passion for helping clients are essential. Key Responsibilities: Client Relationship Management: Build and maintain strong relationships with clients, understanding their needs and ensuring their satisfaction. Communication: Act as the main point of contact for clients, addressing their inquiries, concerns, and requests promptly and effectively. Account Coordination: Assist in coordinating client accounts, including setting up new accounts, managing renewals, and ensuring all client information is up to date. Problem Solving: Identify and resolve client issues proactively, ensuring a positive client experience. Reporting: Prepare and deliver regular reports on account performance, client feedback, and service improvements. Collaboration: Work closely with internal teams, including sales, marketing, and customer support, to ensure client needs are met. Client Onboarding: Assist in onboarding new clients, providing them with the necessary resources and information to get started. Feedback Collection: Gather and relay client feedback to improve our services and client experience. Skills and Qualifications: Communication Skills: Exceptional verbal and written communication skills. Customer Service Skills: Strong ability to understand and meet client needs. Organizational Skills: Ability to manage multiple tasks and prioritize effectively. Interpersonal Skills: Strong ability to build and maintain relationships with clients and team members. Problem-Solving: Ability to address and resolve client issues effectively. Time Management: Strong ability to manage time and meet deadlines. Technical Skills: Basic proficiency with Microsoft Office Suite (Word, Excel, Outlook) and CRM software. Preferred Experience: Experience in customer service, sales, or a related field is a plus but not required. Familiarity with CRM software and account management tools is a plus. Previous experience with gig economy platforms or staffing apps is a plus. Education: High school diploma or equivalent. Relevant certifications or coursework in customer service, sales, or account management are beneficial but not required. Working Conditions: Remote Work: The role is remote, allowing for flexibility in work location. Collaboration: Regular virtual meetings and communications with the sales and support teams. Tools: Use of various communication and collaboration tools, such as email, video conferencing, and CRM software. Salary Range: $20 to $27 per hour, depending on experience and qualifications. If you are organized, detail-oriented, and passionate about providing excellent service to clients, we’d love to hear from you! Apply now to join NoGigiddy and make a difference in the gig economy. To apply: https://weworkremotely.com/remote-jobs/nogigiddy-entry-level-account-manager-4

[employment_type]
Contract

[industry]
Customer Support

---

### #36 | Cold Caller / VertriebsmitarbeiterIn (Freelance Basis)
- source: we_work_remotely_rss
- detected_language: de (confidence=0.95)
- detector: latin-keyword-heuristic
- translation_applied: True
- translation_provider: deep-translator-google
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/lotaro-cold-caller-vertriebsmitarbeiterin-freelance-basis
- apply_url: https://weworkremotely.com/remote-jobs/lotaro-cold-caller-vertriebsmitarbeiterin-freelance-basis

,field,original,translated,changed
0,title,Cold Caller / VertriebsmitarbeiterIn (Freelance Basis),Cold caller / sales representative (freelance basis),True
1,company_profile,LOTARO,LOTARO,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: Germany Munich Du bist Vollblut-Verkäufer und würdest gerne in einem der schnellst wachsenden Remote-Ed-Tech Unternehmen im deutschsprachigen Raum arbeiten? Mit u...,Headquarters: Germany Munich Are you a thoroughbred salesperson and would like to work in one of the fastest growing remote ed-tech companies in German-speaking countries? With...,True
5,requirements,,,False
6,benefits,,,False
7,employment_type,Contract,Contract,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Sales and Marketing,Sales and Marketing,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Cold Caller / VertriebsmitarbeiterIn (Freelance Basis)

[company_profile]
LOTARO

[location]
Anywhere in the World

[description]
Headquarters: Germany Munich Du bist Vollblut-Verkäufer und würdest gerne in einem der schnellst wachsenden Remote-Ed-Tech Unternehmen im deutschsprachigen Raum arbeiten? Mit unserem Unternehmen LOTARO haben wir aktuell ein Remote-Team aus +15 High-Performern. Konkret suchen wir nach Verstärkung in unserem Setting Team. Warum du unbedingt Teil von Heartbeat werden solltest? Extremer Produktfokus → du verkaufst ein echt gutes Produkt! Starkes Wachstum durch interne Weiterbildungen Einkommen selbst in der Hand haben Gute Aufstiegsmöglichkeiten bei starker Performance (Setter/Closer) Aufstrebendes Unternehmen mit großer Vision Flexible Arbeitsplatzgestaltung durch Remote-Kultur Aufgaben 1. Qualifizierung von Leads 2. Telefonische Vereinbarung von Sales Calls Qualifikation Was du dafür mitbringen musst: Erfahrung im Sales Bereich (B2B) Kommunikative Persönlichkeit Guten Umgang mit Menschen Volle Verfügbarkeit den Willen Vollgas zu geben Berufserfahrung: Vertrieb (B2B): 1 Jahr (notwendig) Sprache: Deutsch (Erforderlich) Benefits Leistungen: Betriebliche Weiterbildung Flexible Arbeitszeiten 100% remote – arbeite von überall Unsere Vision? Wir bauen das beste Livetrainingsangebot für Unternehmen im deutschsprachigen Markt auf! Aktuell haben wir zu viele hungrige Interessenten und brauchen dringend High-Performer, die sich unsere Mission anschließen wollen. Wenn du also hungrig auf mehr bist und massiv wachsen möchtest - bewirb dich noch heute bei uns. Art der Stelle: Freelance To apply: https://weworkremotely.com/remote-jobs/lotaro-cold-caller-vertriebsmitarbeiterin-freelance-basis

[employment_type]
Contract

[industry]
Sales and Marketing

**Translated Full Posting Text**

[title]
Cold caller / sales representative (freelance basis)

[company_profile]
LOTARO

[location]
Anywhere in the World

[description]
Headquarters: Germany Munich Are you a thoroughbred salesperson and would like to work in one of the fastest growing remote ed-tech companies in German-speaking countries? With our company LOTARO we currently have a remote team of +15 high performers. Specifically, we are looking for reinforcements in our setting team. Why you should definitely become part of Heartbeat? Extreme product focus → you sell a really good product! Strong growth through internal training Having your income in your own hands Good opportunities for advancement with strong performance (setter/closer) Up-and-coming company with a great vision Flexible workplace design through remote culture Tasks 1. Qualification of leads 2. Telephone arrangement of sales calls Qualifications What you need to bring with you: Experience in the sales area (B2B) Communicative personality Good dealings with people Full availability The will to go full throttle Professional experience: Sales (B2B): 1 year (necessary) Language: German (Required) Benefits: Company training Flexible working hours 100% remote – work from anywhere Our vision? We are building the best live training offering for companies in the German-speaking market! We currently have too many hungry prospects and urgently need high performers who want to join our mission. So if you are hungry for more and want to grow massively - apply to us today. Type of position: Freelance To apply: https://weworkremotely.com/remote-jobs/lotaro-cold-caller-vertriebsarbeiterin-freelance-basis

[employment_type]
Contract

[industry]
Sales and Marketing

---

### #37 | Senior Software Engineer II
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/nomad-senior-software-engineer-ii
- apply_url: https://weworkremotely.com/remote-jobs/nomad-senior-software-engineer-ii

,field,original,translated,changed
0,title,Senior Software Engineer II,Senior Software Engineer II,False
1,company_profile,Nomad,Nomad,False
2,location,"Anywhere in the World, Colorado, 🇺🇲 United States Minor Outlying Islands and 🇺🇸 United States of America","Anywhere in the World, Colorado, 🇺🇲 United States Minor Outlying Islands and 🇺🇸 United States of America",False
3,department,,,False
4,description,Headquarters: Denver CO URL: https://nomadlease.com About Nomad Nomad is unlocking economic opportunity for everyone in the long-term rental community. We offer property owners...,Headquarters: Denver CO URL: https://nomadlease.com About Nomad Nomad is unlocking economic opportunity for everyone in the long-term rental community. We offer property owners...,False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Software Engineer II

[company_profile]
Nomad

[location]
Anywhere in the World, Colorado, 🇺🇲 United States Minor Outlying Islands and 🇺🇸 United States of America

[description]
Headquarters: Denver CO URL: https://nomadlease.com About Nomad Nomad is unlocking economic opportunity for everyone in the long-term rental community. We offer property owners guaranteed rent and peace of mind, while delivering a better rental experience for residents. Backed by leading investors, we're transforming a massive, fragmented market with technology that makes renting better for everyone involved. About the Team Nomad's Engineering team builds the platform that powers guaranteed rent, owner dashboards, resident experiences, and the operational tools that make our business run. We're a small, senior team that ships fast and owns our outcomes. You'll work alongside product, design, and ops to solve real problems in a massive, underserved market. We're entering a new phase of growth. This is a high-leverage moment to join. About the Role We're hiring a Senior Software Engineer to take on meaningful ownership of our platform and deliver features that directly impact the business. You'll work across the stack, make real technical decisions, and ship end-to-end. This is a role for someone who's moved past needing close direction. You see what needs to be done, you build it well, and you make the people around you better in the process. In this role, you will: Build and ship features across our Rails backend and Typescript+React frontend Play a crucial role in bringing solid engineering principles into multiple legacy codebases Own your work end-to-end; from technical design through implementation, testing, and deployment Collaborate directly with product and design to refine requirements and deliver solutions that move business metrics Write clean, well-tested code and contribute to improving our engineering standards Participate in code reviews and provide constructive feedback that raises the quality bar Identify and address technical debt, bugs, and performance issues proactively Contribute to architectural discussions and help the team make sound technical decisions Who you are An experienced product engineer with strong systems thinking abilities; you should be comfortable asking questions and improving the ideas that shape product iteration as well as executing on product vision Significant professional software engineering experience, with strong experience in Typescript+React, Ruby+Rails, and RDBMS (we use Postgre) You have experience with modern testing philosophies and can actively improve test suites that are slow, nondeterministic, or need updated practices Bonus: You have experience automating workflows, using Playwright, Slack bots, and other tooling You've shipped meaningful features or systems and can point to work you owned and delivered Solid technical fundamentals; you write clean code, think about edge cases, and care about quality You introduce and discuss modern tooling and libraries that solve recurring problems in the codebase You are relentless in pushing for simplified patterns in the code and you have examples of systems you've simplified. You have built out tooling (CI/Editor) to enforce improved coding practices across a codebase and improve developer experience. You have experience with writing component and e2e-level visual browser tests and know when to use each. Comfortable working across the stack; you're not precious about frontend vs. backend Strong collaborator who communicates clearly with both technical and non-technical teammates Self-directed: You take initiative, manage your own work, and don't wait to be told what's next Experience in a startup or high-growth environment preferred You’re comfortable using AI coding tools when they speed up implementation, debugging, or test writing, but you don’t rely on them to replace engineering judgment. Interview process Quick meeting with recruiter to discuss role and company Hiring manager interview (up to) 3 hour technical assessment where you'll work on a real problem that a Nomad engineer would own, building a feature. Discuss technical assessment with engineering and product Founder interview Where you'll be Remote within the continental United States. Denver-based candidates are preferred and are encouraged to work hybrid from our downtown office. At Nomad, we are committed to offering competitive compensation that reflects the value each team member brings to our mission. Salary ranges for this role are determined based on factors such as experience, skills, location, and role expectations. Final offers may vary from the posted range, ensuring fair and equitable consideration for every candidate. Our Values Nomads Build Community: We foster genuine relationships and act as dependable stewards of our community. One Percent Better Every Day: We are always learning, taking small, deliberate actions to continuously improve. Mission Before Ourselves: We're a championship team driven to make our customers' lives better. Act From Ownership: We roll up our sleeves, solve problems proactively, and take responsibility for our work. Dream Without Boundaries: We challenge the status quo and strive to achieve the extraordinary. Benefits at Nomad We believe in supporting our team with benefits that enhance your life, both inside and outside of work. Medical, Dental & Vision Insurance Plans: Comprehensive coverage to keep you and your family healthy. Team Bonding Outings and Volunteer Days: Opportunities to connect and give back to the community. Dog-Friendly Office: Because we know pets are family too! ️ 11 Paid Company Holidays: Including a dedicated Mental Health Day. Company Equity: Become a part owner of Nomad and share in our success. ☂️ Short-Term & Long-Term Disability: Supporting you when life throws curveballs. MacBook: Plus, an equipment budget to set you up for success. ⏰ Sick, Parental, and Generous Paid Time Off: Work-life balance matters to us. Nomadic Anniversary Rewards: Celebrate milestones with rewards ranging from paid yearly events to a 4-week sabbatical. Discounted Employee Brokerage Rates: Helping you buy or sell a home with ease. Equal Opportunity Employer Nomad Labs Inc. provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws. This policy applies to all terms and conditions of employment, including recruiting, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation and training. To apply: https://weworkremotely.com/remote-jobs/nomad-senior-software-engineer-ii

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Senior Software Engineer II

[company_profile]
Nomad

[location]
Anywhere in the World, Colorado, 🇺🇲 United States Minor Outlying Islands and 🇺🇸 United States of America

[description]
Headquarters: Denver CO URL: https://nomadlease.com About Nomad Nomad is unlocking economic opportunity for everyone in the long-term rental community. We offer property owners guaranteed rent and peace of mind, while delivering a better rental experience for residents. Backed by leading investors, we're transforming a massive, fragmented market with technology that makes renting better for everyone involved. About the Team Nomad's Engineering team builds the platform that powers guaranteed rent, owner dashboards, resident experiences, and the operational tools that make our business run. We're a small, senior team that ships fast and owns our outcomes. You'll work alongside product, design, and ops to solve real problems in a massive, underserved market. We're entering a new phase of growth. This is a high-leverage moment to join. About the Role We're hiring a Senior Software Engineer to take on meaningful ownership of our platform and deliver features that directly impact the business. You'll work across the stack, make real technical decisions, and ship end-to-end. This is a role for someone who's moved past needing close direction. You see what needs to be done, you build it well, and you make the people around you better in the process. In this role, you will: Build and ship features across our Rails backend and Typescript+React frontend Play a crucial role in bringing solid engineering principles into multiple legacy codebases Own your work end-to-end; from technical design through implementation, testing, and deployment Collaborate directly with product and design to refine requirements and deliver solutions that move business metrics Write clean, well-tested code and contribute to improving our engineering standards Participate in code reviews and provide constructive feedback that raises the quality bar Identify and address technical debt, bugs, and performance issues proactively Contribute to architectural discussions and help the team make sound technical decisions Who you are An experienced product engineer with strong systems thinking abilities; you should be comfortable asking questions and improving the ideas that shape product iteration as well as executing on product vision Significant professional software engineering experience, with strong experience in Typescript+React, Ruby+Rails, and RDBMS (we use Postgre) You have experience with modern testing philosophies and can actively improve test suites that are slow, nondeterministic, or need updated practices Bonus: You have experience automating workflows, using Playwright, Slack bots, and other tooling You've shipped meaningful features or systems and can point to work you owned and delivered Solid technical fundamentals; you write clean code, think about edge cases, and care about quality You introduce and discuss modern tooling and libraries that solve recurring problems in the codebase You are relentless in pushing for simplified patterns in the code and you have examples of systems you've simplified. You have built out tooling (CI/Editor) to enforce improved coding practices across a codebase and improve developer experience. You have experience with writing component and e2e-level visual browser tests and know when to use each. Comfortable working across the stack; you're not precious about frontend vs. backend Strong collaborator who communicates clearly with both technical and non-technical teammates Self-directed: You take initiative, manage your own work, and don't wait to be told what's next Experience in a startup or high-growth environment preferred You’re comfortable using AI coding tools when they speed up implementation, debugging, or test writing, but you don’t rely on them to replace engineering judgment. Interview process Quick meeting with recruiter to discuss role and company Hiring manager interview (up to) 3 hour technical assessment where you'll work on a real problem that a Nomad engineer would own, building a feature. Discuss technical assessment with engineering and product Founder interview Where you'll be Remote within the continental United States. Denver-based candidates are preferred and are encouraged to work hybrid from our downtown office. At Nomad, we are committed to offering competitive compensation that reflects the value each team member brings to our mission. Salary ranges for this role are determined based on factors such as experience, skills, location, and role expectations. Final offers may vary from the posted range, ensuring fair and equitable consideration for every candidate. Our Values Nomads Build Community: We foster genuine relationships and act as dependable stewards of our community. One Percent Better Every Day: We are always learning, taking small, deliberate actions to continuously improve. Mission Before Ourselves: We're a championship team driven to make our customers' lives better. Act From Ownership: We roll up our sleeves, solve problems proactively, and take responsibility for our work. Dream Without Boundaries: We challenge the status quo and strive to achieve the extraordinary. Benefits at Nomad We believe in supporting our team with benefits that enhance your life, both inside and outside of work. Medical, Dental & Vision Insurance Plans: Comprehensive coverage to keep you and your family healthy. Team Bonding Outings and Volunteer Days: Opportunities to connect and give back to the community. Dog-Friendly Office: Because we know pets are family too! ️ 11 Paid Company Holidays: Including a dedicated Mental Health Day. Company Equity: Become a part owner of Nomad and share in our success. ☂️ Short-Term & Long-Term Disability: Supporting you when life throws curveballs. MacBook: Plus, an equipment budget to set you up for success. ⏰ Sick, Parental, and Generous Paid Time Off: Work-life balance matters to us. Nomadic Anniversary Rewards: Celebrate milestones with rewards ranging from paid yearly events to a 4-week sabbatical. Discounted Employee Brokerage Rates: Helping you buy or sell a home with ease. Equal Opportunity Employer Nomad Labs Inc. provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws. This policy applies to all terms and conditions of employment, including recruiting, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation and training. To apply: https://weworkremotely.com/remote-jobs/nomad-senior-software-engineer-ii

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #38 | Senior Ruby on Rails Developer
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/onthegosystems-senior-ruby-on-rails-developer-2
- apply_url: https://weworkremotely.com/remote-jobs/onthegosystems-senior-ruby-on-rails-developer-2

,field,original,translated,changed
0,title,Senior Ruby on Rails Developer,Senior Ruby on Rails Developer,False
1,company_profile,OnTheGoSystems,OnTheGoSystems,False
2,location,"Anywhere in the World, Nevada","Anywhere in the World, Nevada",False
3,department,,,False
4,description,"Headquarters: Remote URL: http://onthegosystems.com We’re looking for a Senior Ruby on Rails developer with a curious, hands-on mindset who enjoys building reliable systems, ow...","Headquarters: Remote URL: http://onthegosystems.com We’re looking for a Senior Ruby on Rails developer with a curious, hands-on mindset who enjoys building reliable systems, ow...",False
5,requirements,Ruby on Rails and Artificial Intelligence (AI),Ruby on Rails and Artificial Intelligence (AI),False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Back-End Programming,Back-End Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Ruby on Rails Developer

[company_profile]
OnTheGoSystems

[location]
Anywhere in the World, Nevada

[description]
Headquarters: Remote URL: http://onthegosystems.com We’re looking for a Senior Ruby on Rails developer with a curious, hands-on mindset who enjoys building reliable systems, owning meaningful features, solving complex problems, and using AI tools to improve development workflows, product quality, and user experience. What you’ll be working on: Building and maintaining Ruby on Rails systems used at scaleOwning features from implementation to production Writing and maintaining automated tests (unit, integration, E2E) Investigating production issues, debugging complex problems, and helping design practical solutions Improving performance, reliability, and maintainability What we’re looking for: To succeed in this role, you’ll have: 4+ years of professional experience with Ruby on Rails Experience building and running production systems Strong backend skills, including databases, performance, and API design Solid experience writing and maintaining automated tests (including E2E) Curiousity about AI technologies and use AI-powered tools to improve productivity, debugging, testing, research, or development workflows. Nice to have: Experience with React CI/CD, background jobs, or AWS experience Why Join OTGS ? Stable & self-funded: Founded in 2007, profitable, and independent. Industry leaders: Creators of WPML , the #1 multilingual plugin for WordPress, used on 1.5M+ sites Fully remote, async-friendly: Work from anywhere within EMEA hours Engineering-driven culture: Ownership, autonomy, testing, and thoughtful problem-solving Fair compensation and great benefits: Designed to support your well-being both inside and outside of work. You’ll enjoy this role if you: Take pride in ownership and accountability Care about testing and long-term code quality Are motivated by solving problems in complex systems Enjoy collaborative environments where kind and experienced people learn, investigate issues, and solve problems. Want to make a lasting impact on a product used by thousands of real customers? We would love to hear from you. To apply: https://weworkremotely.com/remote-jobs/onthegosystems-senior-ruby-on-rails-developer-2

[requirements]
Ruby on Rails and Artificial Intelligence (AI)

[employment_type]
Full-Time

[industry]
Back-End Programming

**Translated Full Posting Text**

[title]
Senior Ruby on Rails Developer

[company_profile]
OnTheGoSystems

[location]
Anywhere in the World, Nevada

[description]
Headquarters: Remote URL: http://onthegosystems.com We’re looking for a Senior Ruby on Rails developer with a curious, hands-on mindset who enjoys building reliable systems, owning meaningful features, solving complex problems, and using AI tools to improve development workflows, product quality, and user experience. What you’ll be working on: Building and maintaining Ruby on Rails systems used at scaleOwning features from implementation to production Writing and maintaining automated tests (unit, integration, E2E) Investigating production issues, debugging complex problems, and helping design practical solutions Improving performance, reliability, and maintainability What we’re looking for: To succeed in this role, you’ll have: 4+ years of professional experience with Ruby on Rails Experience building and running production systems Strong backend skills, including databases, performance, and API design Solid experience writing and maintaining automated tests (including E2E) Curiousity about AI technologies and use AI-powered tools to improve productivity, debugging, testing, research, or development workflows. Nice to have: Experience with React CI/CD, background jobs, or AWS experience Why Join OTGS ? Stable & self-funded: Founded in 2007, profitable, and independent. Industry leaders: Creators of WPML , the #1 multilingual plugin for WordPress, used on 1.5M+ sites Fully remote, async-friendly: Work from anywhere within EMEA hours Engineering-driven culture: Ownership, autonomy, testing, and thoughtful problem-solving Fair compensation and great benefits: Designed to support your well-being both inside and outside of work. You’ll enjoy this role if you: Take pride in ownership and accountability Care about testing and long-term code quality Are motivated by solving problems in complex systems Enjoy collaborative environments where kind and experienced people learn, investigate issues, and solve problems. Want to make a lasting impact on a product used by thousands of real customers? We would love to hear from you. To apply: https://weworkremotely.com/remote-jobs/onthegosystems-senior-ruby-on-rails-developer-2

[requirements]
Ruby on Rails and Artificial Intelligence (AI)

[employment_type]
Full-Time

[industry]
Back-End Programming

---

### #39 | Lead Product Designer
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/blink-health-lead-product-designer
- apply_url: https://weworkremotely.com/remote-jobs/blink-health-lead-product-designer

,field,original,translated,changed
0,title,Lead Product Designer,Lead Product Designer,False
1,company_profile,Blink Health,Blink Health,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: United States Company Overview: Blink Health is the fastest growing healthcare technology company that builds products to make prescriptions accessible and afford...,Headquarters: United States Company Overview: Blink Health is the fastest growing healthcare technology company that builds products to make prescriptions accessible and afford...,False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Design,Design,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Lead Product Designer

[company_profile]
Blink Health

[location]
Anywhere in the World

[description]
Headquarters: United States Company Overview: Blink Health is the fastest growing healthcare technology company that builds products to make prescriptions accessible and affordable to everybody. Our two primary products – BlinkRx and Quick Save – remove traditional roadblocks within the current prescription supply chain, resulting in better access to critical medications and improved health outcomes for patients. BlinkRx is the world’s first pharma-to-patient cloud that offers a digital concierge service for patients who are prescribed branded medications. Patients benefit from transparent low prices, free home delivery, and world-class support on this first-of-its-kind centralized platform. With BlinkRx, never again will a patient show up at the pharmacy only to discover that they can’t afford their medication, their doctor needs to fill out a form for them, or the pharmacy doesn’t have the medication in stock. We are a highly collaborative team of builders and operators who invent new ways of working in an industry that historically has resisted innovation. Join us! As Lead Product Designer at BlinkRx, you will support the day-to-day design needs of a cross-functional product team and drive alignment across multiple product areas. You’ll partner closely with stakeholders, product managers, engineers, and other product designers to help define and execute on BlinkRx’s overall product vision and strategy. You’ll be a vocal advocate for all segments of users and customers and consistently deliver intuitive, well-crafted user experiences for BlinkRx products. Responsibilities: Craft a modern, engaging user experience that solves both user and business needs. Organize and facilitate collaborative work sessions and design thinking exercises that span multiple teams or departments. Utilize user research insights and data analysis to inform design decisions, as well as identify where additional data and research are needed. Propose and concept new product opportunities that are additive to product strategy and provide value to all patient and user segments. Define interaction patterns, user flows, and complex information architecture models that support the end-to-end user journey through our products. Generate low, medium, and high-fidelity wireframes, mockups, and prototypes for products and user interfaces. Conduct a basic level of generative and evaluative user research including moderation of user sessions, synthesizing feedback, and sharing insights for broader team consumption and action. Document all product design work, including detailed UI specifications, UX decision making and supporting rationale, and user interview insights. Identify and develop toolkits and processes that empower team members and scale the design team. Requirements: 7+ years of product design experience in a similar role or product organization BA/BS degree in Design, HCI, or equivalent practical experience Problem-solving skills in complex software applications and platforms. Excellent storytelling and communication skills, both written and verbal Demonstrated proficiency in Figma and the Adobe Creative Cloud Suite A blended skill set of visual design, information architecture, interaction design, various prototyping methods, and basic user research skills Proven track record of collaborating successfully with a cross-functional product and engineering teams to launch products Experience leading a style guide or design system initiative and driving organization-wide usage and adoption Ability to exhibit strong judgement and decision making skills A comprehensive portfolio of product design case studies that showcase early concepts and iterations, supporting user research, performance metrics, and design processes used throughout the duration of each project. Why Join Us: It is rare to have a company that both deeply impacts its customers and is able to provide its services across a massive population. At Blink, we have a huge impact on people when they are most vulnerable: at the intersection of their healthcare and finances. We are also the fastest growing healthcare company in the country and are driving that impact across millions of new patients every year. Our business model not only helps people, but drives economics that allow us to build a generational company. We are a relentlessly learning, constantly curious, and aggressively collaborative cross-functional team dedicated to inventing new ways to improve the lives of our customers. We are an equal opportunity employer and value diversity of all kinds. We do not discriminate on the basis of race, religion, color, national origin, gender, sexual orientation, age, marital status, veteran status, or disability status. To apply: https://weworkremotely.com/remote-jobs/blink-health-lead-product-designer

[employment_type]
Full-Time

[industry]
Design

**Translated Full Posting Text**

[title]
Lead Product Designer

[company_profile]
Blink Health

[location]
Anywhere in the World

[description]
Headquarters: United States Company Overview: Blink Health is the fastest growing healthcare technology company that builds products to make prescriptions accessible and affordable to everybody. Our two primary products – BlinkRx and Quick Save – remove traditional roadblocks within the current prescription supply chain, resulting in better access to critical medications and improved health outcomes for patients. BlinkRx is the world’s first pharma-to-patient cloud that offers a digital concierge service for patients who are prescribed branded medications. Patients benefit from transparent low prices, free home delivery, and world-class support on this first-of-its-kind centralized platform. With BlinkRx, never again will a patient show up at the pharmacy only to discover that they can’t afford their medication, their doctor needs to fill out a form for them, or the pharmacy doesn’t have the medication in stock. We are a highly collaborative team of builders and operators who invent new ways of working in an industry that historically has resisted innovation. Join us! As Lead Product Designer at BlinkRx, you will support the day-to-day design needs of a cross-functional product team and drive alignment across multiple product areas. You’ll partner closely with stakeholders, product managers, engineers, and other product designers to help define and execute on BlinkRx’s overall product vision and strategy. You’ll be a vocal advocate for all segments of users and customers and consistently deliver intuitive, well-crafted user experiences for BlinkRx products. Responsibilities: Craft a modern, engaging user experience that solves both user and business needs. Organize and facilitate collaborative work sessions and design thinking exercises that span multiple teams or departments. Utilize user research insights and data analysis to inform design decisions, as well as identify where additional data and research are needed. Propose and concept new product opportunities that are additive to product strategy and provide value to all patient and user segments. Define interaction patterns, user flows, and complex information architecture models that support the end-to-end user journey through our products. Generate low, medium, and high-fidelity wireframes, mockups, and prototypes for products and user interfaces. Conduct a basic level of generative and evaluative user research including moderation of user sessions, synthesizing feedback, and sharing insights for broader team consumption and action. Document all product design work, including detailed UI specifications, UX decision making and supporting rationale, and user interview insights. Identify and develop toolkits and processes that empower team members and scale the design team. Requirements: 7+ years of product design experience in a similar role or product organization BA/BS degree in Design, HCI, or equivalent practical experience Problem-solving skills in complex software applications and platforms. Excellent storytelling and communication skills, both written and verbal Demonstrated proficiency in Figma and the Adobe Creative Cloud Suite A blended skill set of visual design, information architecture, interaction design, various prototyping methods, and basic user research skills Proven track record of collaborating successfully with a cross-functional product and engineering teams to launch products Experience leading a style guide or design system initiative and driving organization-wide usage and adoption Ability to exhibit strong judgement and decision making skills A comprehensive portfolio of product design case studies that showcase early concepts and iterations, supporting user research, performance metrics, and design processes used throughout the duration of each project. Why Join Us: It is rare to have a company that both deeply impacts its customers and is able to provide its services across a massive population. At Blink, we have a huge impact on people when they are most vulnerable: at the intersection of their healthcare and finances. We are also the fastest growing healthcare company in the country and are driving that impact across millions of new patients every year. Our business model not only helps people, but drives economics that allow us to build a generational company. We are a relentlessly learning, constantly curious, and aggressively collaborative cross-functional team dedicated to inventing new ways to improve the lives of our customers. We are an equal opportunity employer and value diversity of all kinds. We do not discriminate on the basis of race, religion, color, national origin, gender, sexual orientation, age, marital status, veteran status, or disability status. To apply: https://weworkremotely.com/remote-jobs/blink-health-lead-product-designer

[employment_type]
Full-Time

[industry]
Design

---

### #40 | Senior Product Marketing Manager
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/nivoda-senior-product-marketing-manager
- apply_url: https://weworkremotely.com/remote-jobs/nivoda-senior-product-marketing-manager

,field,original,translated,changed
0,title,Senior Product Marketing Manager,Senior Product Marketing Manager,False
1,company_profile,Nivoda,Nivoda,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: US Location: Remote About Nivoda At Nivoda, we’re reimagining how the world buys and sells jewellery. Our global marketplace connects retailers and suppliers acro...","Headquarters: US Location: Remote About Nivoda At Nivoda, we’re reimagining how the world buys and sells jewellery. Our global marketplace connects retailers and suppliers acro...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Sales and Marketing,Sales and Marketing,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Product Marketing Manager

[company_profile]
Nivoda

[location]
Anywhere in the World

[description]
Headquarters: US Location: Remote About Nivoda At Nivoda, we’re reimagining how the world buys and sells jewellery. Our global marketplace connects retailers and suppliers across diamonds, gemstones, and finished jewellery - already powering over $300M in annual transactions and scaling fast toward our billion-dollar vision. We’re bringing tech, data, and automation to an $350B industry that’s barely scratched the surface of digital transformation. The result? Explosive growth, massive opportunity, powered by a team that makes it happen. We are growing fast and building the team that powers the next phase of the business. About the Role We’re looking for a Sr. Product Marketing Manager to drive one clear outcome: grow retailer revenue across every jewelry category - engagement rings, wedding bands, fashion jewellery, fine jewelry, gemstones, and all future categories. Your primary goal is to make jewellery cross-sell simple, obvious, and profitable for every retailer. You will own the positioning, messaging, sales enablement, education, and category launch plans that get retailers to buy more than loose diamonds. You will turn each jewellery category into a revenue engine for both retailers and Nivoda. This is a highly commercial, hands-on role at the centre of Product, Sales, and Category Management. Everything you produce will impact new customer purchases, cross-sell rates, ARPU, and retention. What You’ll Do Own category messaging & positioning : Clearly explain each jewellery category, including margins, customer use cases, and where it fits in a retailer’s business. Build the retailer story for engagement rings, wedding bands, fashion, fine, gemstone lines, and custom manufacturing. Build the cross-sell engine : Design the full experience that moves retailers from loose stones into complete jewelry. Create bundles, companion sets, attach strategies, and decision tools that make category expansion natural and profitable. Partner with sales enablement for jewellery adoption : Partner with Sales Enablement to provide AEs and AMs with battlecards, scripts, demo flows, objection handling, comparison sheets, and playbooks that help them land and expand by category. Lead category launches & activation : Own launch plans for new jewellery categories. Partner with Category Management on pricing, assortment, and positioning. Build campaigns, training, and education that drive first-time and repeat purchases. Drive ARPU growth & share of wallet : Build programs, guides, calculators, and content that help retailers expand their assortment and monthly spend. Collaborate with Sales to identify the next category each retailer should adopt. Produce high-value retailer education : Create content for Nivoda University: how to sell engagement rings, design a wedding band upsell, add fashion to their website, or build a gemstone story. Use a data-driven approach : Running structured experiments, testing assumptions, and using insights to shape category adoption and cross-sell performance. Clarify Nivoda’s automated workflows: Turn advanced, AI-powered features into simple, intuitive steps retailers can follow. Make the entire journey from design to manufacturing effortless, and show how Nivoda’s automation helps retailers produce more jewellery with less manual work and fewer operational bottlenecks. What You Bring 6+ years in product marketing, category marketing, or a similar commercial role in SaaS, marketplace, or retail-adjacent environments. Ability to translate complex products into simple narratives that drive revenue. A strong commercial mindset - you understand how retailers make money and how to influence their buying behaviour. A data-driven mindset - comfortable designing experiments, analysing results, and iterating quickly based on what the data shows. Experience producing clear, concise positioning, messaging, and sales enablement assets. Confidence working cross-functionally with Product, Sales, and Category teams. Ability to build from scratch, iterate quickly, and ship with speed and precision. Excellent written communication and structured thinking. Marketplace or jewellery experience is a nice-to-have, but clarity, ownership, and commercial judgement matter most. What Success Looks Like Growth in new customer purchases across jewellery categories. Cross-sell rate increases across engagement rings, wedding bands, fashion, fine jewellery, and gemstones. ARPU uplift per retailer and expansion into additional categories. Increased share of wallet across existing retailers. Strong jewellery activation immediately after onboarding. High adoption of your materials across the Sales and Account Management teams. Growth in monthly transactions across all jewellery categories. Retention improves for multi-category retailers compared to single-category users. Why Join Us Build from the ground up - own the product marketing engine for jewellery at Nivoda. Work directly with Product, Category Management, Sales, and leadership to shape revenue outcomes. See your work translated directly into retailer behaviour and measurable revenue impact. Join a team that values clarity, speed, experimentation, and commercial thinking. Help transform how thousands of retailers buy and sell jewelry worldwide. To apply: https://weworkremotely.com/remote-jobs/nivoda-senior-product-marketing-manager

[employment_type]
Full-Time

[industry]
Sales and Marketing

**Translated Full Posting Text**

[title]
Senior Product Marketing Manager

[company_profile]
Nivoda

[location]
Anywhere in the World

[description]
Headquarters: US Location: Remote About Nivoda At Nivoda, we’re reimagining how the world buys and sells jewellery. Our global marketplace connects retailers and suppliers across diamonds, gemstones, and finished jewellery - already powering over $300M in annual transactions and scaling fast toward our billion-dollar vision. We’re bringing tech, data, and automation to an $350B industry that’s barely scratched the surface of digital transformation. The result? Explosive growth, massive opportunity, powered by a team that makes it happen. We are growing fast and building the team that powers the next phase of the business. About the Role We’re looking for a Sr. Product Marketing Manager to drive one clear outcome: grow retailer revenue across every jewelry category - engagement rings, wedding bands, fashion jewellery, fine jewelry, gemstones, and all future categories. Your primary goal is to make jewellery cross-sell simple, obvious, and profitable for every retailer. You will own the positioning, messaging, sales enablement, education, and category launch plans that get retailers to buy more than loose diamonds. You will turn each jewellery category into a revenue engine for both retailers and Nivoda. This is a highly commercial, hands-on role at the centre of Product, Sales, and Category Management. Everything you produce will impact new customer purchases, cross-sell rates, ARPU, and retention. What You’ll Do Own category messaging & positioning : Clearly explain each jewellery category, including margins, customer use cases, and where it fits in a retailer’s business. Build the retailer story for engagement rings, wedding bands, fashion, fine, gemstone lines, and custom manufacturing. Build the cross-sell engine : Design the full experience that moves retailers from loose stones into complete jewelry. Create bundles, companion sets, attach strategies, and decision tools that make category expansion natural and profitable. Partner with sales enablement for jewellery adoption : Partner with Sales Enablement to provide AEs and AMs with battlecards, scripts, demo flows, objection handling, comparison sheets, and playbooks that help them land and expand by category. Lead category launches & activation : Own launch plans for new jewellery categories. Partner with Category Management on pricing, assortment, and positioning. Build campaigns, training, and education that drive first-time and repeat purchases. Drive ARPU growth & share of wallet : Build programs, guides, calculators, and content that help retailers expand their assortment and monthly spend. Collaborate with Sales to identify the next category each retailer should adopt. Produce high-value retailer education : Create content for Nivoda University: how to sell engagement rings, design a wedding band upsell, add fashion to their website, or build a gemstone story. Use a data-driven approach : Running structured experiments, testing assumptions, and using insights to shape category adoption and cross-sell performance. Clarify Nivoda’s automated workflows: Turn advanced, AI-powered features into simple, intuitive steps retailers can follow. Make the entire journey from design to manufacturing effortless, and show how Nivoda’s automation helps retailers produce more jewellery with less manual work and fewer operational bottlenecks. What You Bring 6+ years in product marketing, category marketing, or a similar commercial role in SaaS, marketplace, or retail-adjacent environments. Ability to translate complex products into simple narratives that drive revenue. A strong commercial mindset - you understand how retailers make money and how to influence their buying behaviour. A data-driven mindset - comfortable designing experiments, analysing results, and iterating quickly based on what the data shows. Experience producing clear, concise positioning, messaging, and sales enablement assets. Confidence working cross-functionally with Product, Sales, and Category teams. Ability to build from scratch, iterate quickly, and ship with speed and precision. Excellent written communication and structured thinking. Marketplace or jewellery experience is a nice-to-have, but clarity, ownership, and commercial judgement matter most. What Success Looks Like Growth in new customer purchases across jewellery categories. Cross-sell rate increases across engagement rings, wedding bands, fashion, fine jewellery, and gemstones. ARPU uplift per retailer and expansion into additional categories. Increased share of wallet across existing retailers. Strong jewellery activation immediately after onboarding. High adoption of your materials across the Sales and Account Management teams. Growth in monthly transactions across all jewellery categories. Retention improves for multi-category retailers compared to single-category users. Why Join Us Build from the ground up - own the product marketing engine for jewellery at Nivoda. Work directly with Product, Category Management, Sales, and leadership to shape revenue outcomes. See your work translated directly into retailer behaviour and measurable revenue impact. Join a team that values clarity, speed, experimentation, and commercial thinking. Help transform how thousands of retailers buy and sell jewelry worldwide. To apply: https://weworkremotely.com/remote-jobs/nivoda-senior-product-marketing-manager

[employment_type]
Full-Time

[industry]
Sales and Marketing

---

### #41 | DevOps Engineer
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/createit-s-c-borkowski-bartosz-fredrych-aleksander-devops-engineer
- apply_url: https://weworkremotely.com/remote-jobs/createit-s-c-borkowski-bartosz-fredrych-aleksander-devops-engineer

,field,original,translated,changed
0,title,DevOps Engineer,DevOps Engineer,False
1,company_profile,"createIT s.c. Borkowski Bartosz, Fredrych Aleksander","createIT s.c. Borkowski Bartosz, Fredrych Aleksander",False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Warsaw, 14, Poland Job description DevOps Engineer for one of our long-term clients Job requirements AWS Stack (SQS/SQS/Api Gateway/RDS/Mongo/DynamoDb etc.) Kuber...","Headquarters: Warsaw, 14, Poland Job description DevOps Engineer for one of our long-term clients Job requirements AWS Stack (SQS/SQS/Api Gateway/RDS/Mongo/DynamoDb etc.) Kuber...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
DevOps Engineer

[company_profile]
createIT s.c. Borkowski Bartosz, Fredrych Aleksander

[location]
Anywhere in the World

[description]
Headquarters: Warsaw, 14, Poland Job description DevOps Engineer for one of our long-term clients Job requirements AWS Stack (SQS/SQS/Api Gateway/RDS/Mongo/DynamoDb etc.) Kubernetes Node.js/React deployments CI/CD English min. B2 All done! Your application has been successfully submitted! Other jobs To apply: https://weworkremotely.com/remote-jobs/createit-s-c-borkowski-bartosz-fredrych-aleksander-devops-engineer

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
DevOps Engineer

[company_profile]
createIT s.c. Borkowski Bartosz, Fredrych Aleksander

[location]
Anywhere in the World

[description]
Headquarters: Warsaw, 14, Poland Job description DevOps Engineer for one of our long-term clients Job requirements AWS Stack (SQS/SQS/Api Gateway/RDS/Mongo/DynamoDb etc.) Kubernetes Node.js/React deployments CI/CD English min. B2 All done! Your application has been successfully submitted! Other jobs To apply: https://weworkremotely.com/remote-jobs/createit-s-c-borkowski-bartosz-fredrych-aleksander-devops-engineer

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #42 | Product Marketing Manager
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/bazaarvoice-product-marketing-manager
- apply_url: https://weworkremotely.com/remote-jobs/bazaarvoice-product-marketing-manager

,field,original,translated,changed
0,title,Product Marketing Manager,Product Marketing Manager,False
1,company_profile,Bazaarvoice,Bazaarvoice,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Remote, United States About Bazaarvoice At Bazaarvoice, we create smart shopping experiences. Through our expansive global network, product-passionate community &...","Headquarters: Remote, United States About Bazaarvoice At Bazaarvoice, we create smart shopping experiences. Through our expansive global network, product-passionate community &...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Full-Stack Programming,Full-Stack Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Product Marketing Manager

[company_profile]
Bazaarvoice

[location]
Anywhere in the World

[description]
Headquarters: Remote, United States About Bazaarvoice At Bazaarvoice, we create smart shopping experiences. Through our expansive global network, product-passionate community & enterprise technology, we connect thousands of brands and retailers with billions of consumers. Our solutions enable brands to connect with consumers and collect valuable user-generated content, at an unprecedented scale. This content achieves global reach by leveraging our extensive and ever-expanding retail, social & search syndication network. And we make it easy for brands & retailers to gain valuable business insights from real-time consumer feedback with intuitive tools and dashboards. The result is smarter shopping: loyal customers, increased sales, and improved products. The problem we are trying to solve : Brands and retailers struggle to make real connections with consumers. It's a challenge to deliver trustworthy and inspiring content in the moments that matter most during the discovery and purchase cycle. The result? Time and money spent on content that doesn't attract new consumers, convert them, or earn their long-term loyalty. Our brand promise : closing the gap between brands and consumers. Founded in 2005, Bazaarvoice is headquartered in Austin, Texas with offices in North America, Europe, Asia and Australia. It’s official: Bazaarvoice is a Great Place to Work in the US , Australia , India , Lithuania, France, Germany and the UK ! We’re seeking a strategic, results-driven Product Marketing Manager to join the team driving the evolution of Bazaarvoice’s flagship product: Ratings & Reviews. As AI transforms how consumers shop, trust is the ultimate currency. You will help define the next era of shopping, where ratings and reviews are powering AI-driven shopping experiences. You’ll play a central role in shaping product messaging and positioning, influencing roadmap strategy, enabling Sales and Client Success, and driving adoption and growth for the market leading solution. You’ll thrive in this role if you’re a builder—someone who loves translating complex capabilities into clear business value, aligning cross-functional teams, and turning market insights into powerful GTM strategies. What You'll Do: Define and execute GTM strategy for Bazaarvoice Ratings & Reviews releases, including launch positioning, messaging, internal and external enablement/comms, and ongoing adoption motions across different business sizes, personas, industries and geographies. Build compelling narratives that clearly differentiate Bazaarvoice as the premium offering in the ratings and reviews space. Lead product launches and feature releases with cross-functional partners across Product, Sales, CS, and Enablement, delivering key assets, messaging, and training. Create competitive positioning and de-positioning with research-backed insights and strategic clarity; guide internal teams on how to win. Collaborate with Sales, Client Success, and Enablement teams to equip the field with the tools they need to confidently sell, support, and upsell our Ratings & Reviews offering. Gather market intelligence and voice of the customer to inform roadmap prioritization and guide product-market fit. Create clear, compelling sales and marketing collateral, from one-sheets and web copy to playbooks and pitch decks. Serve as a strategic partner to Product Management, influencing roadmap decisions with market context and go-to-market requirements. What You'll Need: 3-5 years of product marketing or relevant experience in B2B SaaS, ideally in e-commerce, martech or adtech. Proven experience owning GTM strategy, leading successful product launches, and working cross-functionally. Exceptional messaging and positioning skills; you are able to turn features into compelling stories that resonate with marketing and e-commerce leaders. Understanding of modern consumer behavior, especially in the e-commerce industry. Strategic thinker with a bias for action. You know how to prioritize for highest impact, and are not afraid of experimenting and making mistakes. Excellent written and verbal communication. Familiarity with our tools is ideal, but not required: Google Suite, Asana, Gemini, Confluence, Crayon, Pendo. Understanding of and/or experience with our top industries is desired: Retail, Apparel & Fashion, Consumer Electronics, Health & Beauty, Food & Bev, Home & Garden. $108,347.27 - $162,520.90 a year At Bazaarvoice, we carefully consider multiple factors when determining compensation. Since we believe the transparency and integrity builds trust, we want to share that we expect the base salary for this position to be in the range listed above and is based on Bazaarvoice's good faith belief at the time of posting. Actual compensation may vary based on factors such as geographic location, work experience, market conditions, education/training, and skill level. While this is a good faith estimate of the expected base pay range, Bazaarvoice reserves the right to pay outside this range if these assumptions and understandings are modified as we progress through the interview process. Your recruiter can share more about the salary range and total compensation package during the hiring process. If this compensation is somewhere close to your desired range, we encourage you to apply! Why join Bazaarvoice? Customer is key We see our own success through our customers’ outcomes. We approach every situation with a customer first mindset. Transparency & Integrity Builds Trust We believe in the power of authentic feedback because it’s in our DNA. We do the right thing when faced with hard choices. Transparency and trust accelerate our collective performance. Passionate Pursuit of Performance Our energy is contagious, because we hire for passion, drive & curiosity. We love what we do, and because we’re laser focused on our mission. Innovation over Imitation We seek to innovate as we are not content with the status quo. We embrace agility and experimentation as an advantage. Stronger Together We bring our whole selves to the mission and find value in diverse perspectives. We champion what’s best for Bazaarvoice before individuals or teams. As a stronger company we build a stronger community. Commitment to diversity and inclusion Bazaarvoice provides equal employment opportunities (EEO) to all team members and applicants according to their experience, talent, and qualifications for the job without regard to race, color, national origin, religion, age, disability, sex (including pregnancy, gender stereotyping, and marital status), sexual orientation, gender identity, genetic information, military/veteran status, or any other category protected by federal, state, or local law in every location in which the company has facilities. Bazaarvoice believes that diversity and an inclusive company culture are key drivers of creativity, innovation and performance. Furthermore, a diverse workforce and the maintenance of an atmosphere that welcomes versatile perspectives will enhance our ability to fulfill our vision of creating the world’s smartest network of consumers, brands, and retailers. The successful candidate will be required to complete a background check. We will provide additional information and obtain your written consent before proceeding. We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/bazaarvoice-product-marketing-manager

[employment_type]
Full-Time

[industry]
Full-Stack Programming

**Translated Full Posting Text**

[title]
Product Marketing Manager

[company_profile]
Bazaarvoice

[location]
Anywhere in the World

[description]
Headquarters: Remote, United States About Bazaarvoice At Bazaarvoice, we create smart shopping experiences. Through our expansive global network, product-passionate community & enterprise technology, we connect thousands of brands and retailers with billions of consumers. Our solutions enable brands to connect with consumers and collect valuable user-generated content, at an unprecedented scale. This content achieves global reach by leveraging our extensive and ever-expanding retail, social & search syndication network. And we make it easy for brands & retailers to gain valuable business insights from real-time consumer feedback with intuitive tools and dashboards. The result is smarter shopping: loyal customers, increased sales, and improved products. The problem we are trying to solve : Brands and retailers struggle to make real connections with consumers. It's a challenge to deliver trustworthy and inspiring content in the moments that matter most during the discovery and purchase cycle. The result? Time and money spent on content that doesn't attract new consumers, convert them, or earn their long-term loyalty. Our brand promise : closing the gap between brands and consumers. Founded in 2005, Bazaarvoice is headquartered in Austin, Texas with offices in North America, Europe, Asia and Australia. It’s official: Bazaarvoice is a Great Place to Work in the US , Australia , India , Lithuania, France, Germany and the UK ! We’re seeking a strategic, results-driven Product Marketing Manager to join the team driving the evolution of Bazaarvoice’s flagship product: Ratings & Reviews. As AI transforms how consumers shop, trust is the ultimate currency. You will help define the next era of shopping, where ratings and reviews are powering AI-driven shopping experiences. You’ll play a central role in shaping product messaging and positioning, influencing roadmap strategy, enabling Sales and Client Success, and driving adoption and growth for the market leading solution. You’ll thrive in this role if you’re a builder—someone who loves translating complex capabilities into clear business value, aligning cross-functional teams, and turning market insights into powerful GTM strategies. What You'll Do: Define and execute GTM strategy for Bazaarvoice Ratings & Reviews releases, including launch positioning, messaging, internal and external enablement/comms, and ongoing adoption motions across different business sizes, personas, industries and geographies. Build compelling narratives that clearly differentiate Bazaarvoice as the premium offering in the ratings and reviews space. Lead product launches and feature releases with cross-functional partners across Product, Sales, CS, and Enablement, delivering key assets, messaging, and training. Create competitive positioning and de-positioning with research-backed insights and strategic clarity; guide internal teams on how to win. Collaborate with Sales, Client Success, and Enablement teams to equip the field with the tools they need to confidently sell, support, and upsell our Ratings & Reviews offering. Gather market intelligence and voice of the customer to inform roadmap prioritization and guide product-market fit. Create clear, compelling sales and marketing collateral, from one-sheets and web copy to playbooks and pitch decks. Serve as a strategic partner to Product Management, influencing roadmap decisions with market context and go-to-market requirements. What You'll Need: 3-5 years of product marketing or relevant experience in B2B SaaS, ideally in e-commerce, martech or adtech. Proven experience owning GTM strategy, leading successful product launches, and working cross-functionally. Exceptional messaging and positioning skills; you are able to turn features into compelling stories that resonate with marketing and e-commerce leaders. Understanding of modern consumer behavior, especially in the e-commerce industry. Strategic thinker with a bias for action. You know how to prioritize for highest impact, and are not afraid of experimenting and making mistakes. Excellent written and verbal communication. Familiarity with our tools is ideal, but not required: Google Suite, Asana, Gemini, Confluence, Crayon, Pendo. Understanding of and/or experience with our top industries is desired: Retail, Apparel & Fashion, Consumer Electronics, Health & Beauty, Food & Bev, Home & Garden. $108,347.27 - $162,520.90 a year At Bazaarvoice, we carefully consider multiple factors when determining compensation. Since we believe the transparency and integrity builds trust, we want to share that we expect the base salary for this position to be in the range listed above and is based on Bazaarvoice's good faith belief at the time of posting. Actual compensation may vary based on factors such as geographic location, work experience, market conditions, education/training, and skill level. While this is a good faith estimate of the expected base pay range, Bazaarvoice reserves the right to pay outside this range if these assumptions and understandings are modified as we progress through the interview process. Your recruiter can share more about the salary range and total compensation package during the hiring process. If this compensation is somewhere close to your desired range, we encourage you to apply! Why join Bazaarvoice? Customer is key We see our own success through our customers’ outcomes. We approach every situation with a customer first mindset. Transparency & Integrity Builds Trust We believe in the power of authentic feedback because it’s in our DNA. We do the right thing when faced with hard choices. Transparency and trust accelerate our collective performance. Passionate Pursuit of Performance Our energy is contagious, because we hire for passion, drive & curiosity. We love what we do, and because we’re laser focused on our mission. Innovation over Imitation We seek to innovate as we are not content with the status quo. We embrace agility and experimentation as an advantage. Stronger Together We bring our whole selves to the mission and find value in diverse perspectives. We champion what’s best for Bazaarvoice before individuals or teams. As a stronger company we build a stronger community. Commitment to diversity and inclusion Bazaarvoice provides equal employment opportunities (EEO) to all team members and applicants according to their experience, talent, and qualifications for the job without regard to race, color, national origin, religion, age, disability, sex (including pregnancy, gender stereotyping, and marital status), sexual orientation, gender identity, genetic information, military/veteran status, or any other category protected by federal, state, or local law in every location in which the company has facilities. Bazaarvoice believes that diversity and an inclusive company culture are key drivers of creativity, innovation and performance. Furthermore, a diverse workforce and the maintenance of an atmosphere that welcomes versatile perspectives will enhance our ability to fulfill our vision of creating the world’s smartest network of consumers, brands, and retailers. The successful candidate will be required to complete a background check. We will provide additional information and obtain your written consent before proceeding. We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/bazaarvoice-product-marketing-manager

[employment_type]
Full-Time

[industry]
Full-Stack Programming

---

### #43 | Senior QLab Support Specialist (half time)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time-1
- apply_url: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time-1

,field,original,translated,changed
0,title,Senior QLab Support Specialist (half time),Senior QLab Support Specialist (half time),False
1,company_profile,Figure 53,Figure 53,False
2,location,"Anywhere in the World, Maryland, 🇺🇸 United States of America","Anywhere in the World, Maryland, 🇺🇸 United States of America",False
3,department,,,False
4,description,"Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a can...","Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a can...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Customer Support,Customer Support,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior QLab Support Specialist (half time)

[company_profile]
Figure 53

[location]
Anywhere in the World, Maryland, 🇺🇸 United States of America

[description]
Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a candidate with both high-level technical expertise in QLab and the ability to provide clear, generous, and friendly support to our customers. Our flagship product, QLab, is used to control audio, video, and lighting for live performance. (But you, our future teammate, already know that!) All customer support for our products is conducted via email. We are looking for an additional team member to help answer any licensing and technical QLab questions our customers send us. This position requires 20 hours of work a week, and includes benefits such as a generous paid vacation policy, health insurance, profit sharing after one year, and a SIMPLE IRA with matching contributions. We are a fully remote company. You must be based in the US, with a slight preference for those based in Maryland, New York, California, or Wisconsin. Much of our success stems from taking care of our customers with exceptional support and responsiveness. We feel grateful for our customers, and we try to keep the principles of patience, gratitude, respect, and expertise driving our interactions with them. Our support team is devoted to problem-solving in a kind and generous spirit. We provide deep technical knowledge, and also bring a curiosity, dedication, and genuine compassion for customers to our work. We often work as a team to solve difficult issues. While experience with sound is absolutely a plus, we are specifically looking for a candidate with experience in one or more of the following areas: Lighting Stage Management Video Broadcasting Product licensing Required Skills The successful applicant will have all of the following skills: Superb writing skills. Experience with QLab at a moderate or expert level. (At least a year or two of actual hands-on experience with QLab.) Compassion, empathy, and an ability to convey a friendly and supportive tone via email. Patience and a pleasant demeanor, with customers and with teammates. A willingness to learn, adaptability, attention to detail, and problem solving skills. First-hand familiarity with the process of producing theater — you understand the environment our customers work in and the strains and stresses of that environment. You understand terms like standby, upstage, spike, and strike. You’ve experienced a technical rehearsal. You have (at least) run sound, lights, or video for a show at some point. Basic macOS administration skills. Willingness to ask questions and self direct learning in areas where you are not already an expert. Willingness to learn Figure 53’s complex licensing system and ultimately provide support to customers about that system. Ability to manage your own calendar, and timeliness. Ability to maintain focus while working independently and remotely. Ability to bring renewed energy for repetitive work. Bonus Point Skills While no one person will be an expert in all of these things, any of the following skills would impress us: Professional (or high-level) experience as a technician, designer, director, or stage manager. Extensive customer service experience, particularly with a written component. You’ve done technical work for theater in multiple departments. You’ve used MIDI or OSC to control a show. You’ve dabbled in AppleScript, or written AppleScripts to control QLab. If your background is in audio, familiarity with any of the following: Meyer, d&b, L-Acoustics, or QSC loudspeakers or processing hardware DiGiCo, Yamaha, Allen & Heath, or Behringer mixing consoles RME, Motu, Universal Audio, or Focusrite audio interfaces Dante/AVB If your background is in video, familiarity with any of the following: Blackmagic hardware a solid grasp on the concepts of resolution and frame rate the uses of and differences between VGA, DVI, HDMI, and SDI network video systems, such as NDI live video systems, live camera feeds, camera switching projectors made by either Panasonic, Barco, or Christie LED Video walls and controllers knowledge of what baluns are and how to use them Matrox/Datapath multi-heads If your background is in lighting, familiarity with any of the following: ETC Express or EOS-family consoles Programming lighting effects or other complex sequences. reading a lighting plot Pre-visualisation software like Vectorworks, WYSIWYG, or Capture Art-Net protocol USB-DMX devices If you are a stage manager, experience with the following: Running many shows on QLab A working knowledge of QLab programming Troubleshooting various technical issues in a rehearsal environment We build our schedule collaboratively as a team. While it is not a requirement, availability and willingness to work mornings (starting at 9am) in the Eastern Time Zone is a plus, as is a willingness to occasionally work holidays & weekends. Availability during periods which are typically busy for professional theatre: September-early November, February-March Familiarity and experience with Github Salary and Benefits All full- and half-time employees at Figure 53 are paid based on the same annual salary. (Our CEO makes 1.5x the base salary). The base salary is $76,000 for half-time (20 hrs/week) employment. After 1 year at Figure 53, you’ll receive quarterly profit sharing which is divided based on the length of time you’ve been at the company. Profit sharing is often a significant portion of our compensation. 25 paid vacation days, unlimited unpaid vacation days (with notice and permission), and paid federal holidays plus the week between Christmas and New Years off. SIMPLE IRA retirement plan with employer contribution matching Free health insurance for you, your spouse, and your dependents, including an HRA for out-of-pocket spending. Vision and dental insurance are included because teeth and eyes are also part of your body. Fully remote work. Figure 53 is committed to building a culturally diverse staff and strongly encourages applications from people of color, women, LGBTQ+, those living with disabilities, or a member of any group that is traditionally excluded from work in the tech sector. The position is open immediately. We are accepting applications through Friday, June 5th. To get a sense of our company culture and HR policies, we encourage you to take a look at our handbook . How to Apply Please email jobs@figure53.com to apply. Attach PDFs of your resume and a cover letter that demonstrates your relevant experience and interest in the job. If you have any example QLab workspaces you’ve created we’d love to see those too. To apply: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time-1

[employment_type]
Full-Time

[industry]
Customer Support

**Translated Full Posting Text**

[title]
Senior QLab Support Specialist (half time)

[company_profile]
Figure 53

[location]
Anywhere in the World, Maryland, 🇺🇸 United States of America

[description]
Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a candidate with both high-level technical expertise in QLab and the ability to provide clear, generous, and friendly support to our customers. Our flagship product, QLab, is used to control audio, video, and lighting for live performance. (But you, our future teammate, already know that!) All customer support for our products is conducted via email. We are looking for an additional team member to help answer any licensing and technical QLab questions our customers send us. This position requires 20 hours of work a week, and includes benefits such as a generous paid vacation policy, health insurance, profit sharing after one year, and a SIMPLE IRA with matching contributions. We are a fully remote company. You must be based in the US, with a slight preference for those based in Maryland, New York, California, or Wisconsin. Much of our success stems from taking care of our customers with exceptional support and responsiveness. We feel grateful for our customers, and we try to keep the principles of patience, gratitude, respect, and expertise driving our interactions with them. Our support team is devoted to problem-solving in a kind and generous spirit. We provide deep technical knowledge, and also bring a curiosity, dedication, and genuine compassion for customers to our work. We often work as a team to solve difficult issues. While experience with sound is absolutely a plus, we are specifically looking for a candidate with experience in one or more of the following areas: Lighting Stage Management Video Broadcasting Product licensing Required Skills The successful applicant will have all of the following skills: Superb writing skills. Experience with QLab at a moderate or expert level. (At least a year or two of actual hands-on experience with QLab.) Compassion, empathy, and an ability to convey a friendly and supportive tone via email. Patience and a pleasant demeanor, with customers and with teammates. A willingness to learn, adaptability, attention to detail, and problem solving skills. First-hand familiarity with the process of producing theater — you understand the environment our customers work in and the strains and stresses of that environment. You understand terms like standby, upstage, spike, and strike. You’ve experienced a technical rehearsal. You have (at least) run sound, lights, or video for a show at some point. Basic macOS administration skills. Willingness to ask questions and self direct learning in areas where you are not already an expert. Willingness to learn Figure 53’s complex licensing system and ultimately provide support to customers about that system. Ability to manage your own calendar, and timeliness. Ability to maintain focus while working independently and remotely. Ability to bring renewed energy for repetitive work. Bonus Point Skills While no one person will be an expert in all of these things, any of the following skills would impress us: Professional (or high-level) experience as a technician, designer, director, or stage manager. Extensive customer service experience, particularly with a written component. You’ve done technical work for theater in multiple departments. You’ve used MIDI or OSC to control a show. You’ve dabbled in AppleScript, or written AppleScripts to control QLab. If your background is in audio, familiarity with any of the following: Meyer, d&b, L-Acoustics, or QSC loudspeakers or processing hardware DiGiCo, Yamaha, Allen & Heath, or Behringer mixing consoles RME, Motu, Universal Audio, or Focusrite audio interfaces Dante/AVB If your background is in video, familiarity with any of the following: Blackmagic hardware a solid grasp on the concepts of resolution and frame rate the uses of and differences between VGA, DVI, HDMI, and SDI network video systems, such as NDI live video systems, live camera feeds, camera switching projectors made by either Panasonic, Barco, or Christie LED Video walls and controllers knowledge of what baluns are and how to use them Matrox/Datapath multi-heads If your background is in lighting, familiarity with any of the following: ETC Express or EOS-family consoles Programming lighting effects or other complex sequences. reading a lighting plot Pre-visualisation software like Vectorworks, WYSIWYG, or Capture Art-Net protocol USB-DMX devices If you are a stage manager, experience with the following: Running many shows on QLab A working knowledge of QLab programming Troubleshooting various technical issues in a rehearsal environment We build our schedule collaboratively as a team. While it is not a requirement, availability and willingness to work mornings (starting at 9am) in the Eastern Time Zone is a plus, as is a willingness to occasionally work holidays & weekends. Availability during periods which are typically busy for professional theatre: September-early November, February-March Familiarity and experience with Github Salary and Benefits All full- and half-time employees at Figure 53 are paid based on the same annual salary. (Our CEO makes 1.5x the base salary). The base salary is $76,000 for half-time (20 hrs/week) employment. After 1 year at Figure 53, you’ll receive quarterly profit sharing which is divided based on the length of time you’ve been at the company. Profit sharing is often a significant portion of our compensation. 25 paid vacation days, unlimited unpaid vacation days (with notice and permission), and paid federal holidays plus the week between Christmas and New Years off. SIMPLE IRA retirement plan with employer contribution matching Free health insurance for you, your spouse, and your dependents, including an HRA for out-of-pocket spending. Vision and dental insurance are included because teeth and eyes are also part of your body. Fully remote work. Figure 53 is committed to building a culturally diverse staff and strongly encourages applications from people of color, women, LGBTQ+, those living with disabilities, or a member of any group that is traditionally excluded from work in the tech sector. The position is open immediately. We are accepting applications through Friday, June 5th. To get a sense of our company culture and HR policies, we encourage you to take a look at our handbook . How to Apply Please email jobs@figure53.com to apply. Attach PDFs of your resume and a cover letter that demonstrates your relevant experience and interest in the job. If you have any example QLab workspaces you’ve created we’d love to see those too. To apply: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time-1

[employment_type]
Full-Time

[industry]
Customer Support

---

### #44 | Senior QLab Support Specialist (half time)
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time
- apply_url: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time

,field,original,translated,changed
0,title,Senior QLab Support Specialist (half time),Senior QLab Support Specialist (half time),False
1,company_profile,Figure 53,Figure 53,False
2,location,"Anywhere in the World, Maryland, 🇺🇸 United States of America","Anywhere in the World, Maryland, 🇺🇸 United States of America",False
3,department,,,False
4,description,"Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a can...","Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a can...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Customer Support,Customer Support,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior QLab Support Specialist (half time)

[company_profile]
Figure 53

[location]
Anywhere in the World, Maryland, 🇺🇸 United States of America

[description]
Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a candidate with both high-level technical expertise in QLab and the ability to provide clear, generous, and friendly support to our customers. Our flagship product, QLab, is used to control audio, video, and lighting for live performance. (But you, our future teammate, already know that!) All customer support for our products is conducted via email. We are looking for an additional team member to help answer any licensing and technical QLab questions our customers send us. This position requires 20 hours of work a week, and includes benefits such as a generous paid vacation policy, health insurance, profit sharing after one year, and a SIMPLE IRA with matching contributions. We are a fully remote company. You must be based in the US, with a slight preference for those based in Maryland, New York, California, or Wisconsin. Much of our success stems from taking care of our customers with exceptional support and responsiveness. We feel grateful for our customers, and we try to keep the principles of patience, gratitude, respect, and expertise driving our interactions with them. Our support team is devoted to problem-solving in a kind and generous spirit. We provide deep technical knowledge, and also bring a curiosity, dedication, and genuine compassion for customers to our work. We often work as a team to solve difficult issues. While experience with sound is absolutely a plus, we are specifically looking for a candidate with experience in one or more of the following areas: Lighting Stage Management Video Broadcasting Product licensing Required Skills The successful applicant will have all of the following skills: Superb writing skills. Experience with QLab at a moderate or expert level. (At least a year or two of actual hands-on experience with QLab.) Compassion, empathy, and an ability to convey a friendly and supportive tone via email. Patience and a pleasant demeanor, with customers and with teammates. A willingness to learn, adaptability, attention to detail, and problem solving skills. First-hand familiarity with the process of producing theater — you understand the environment our customers work in and the strains and stresses of that environment. You understand terms like standby, upstage, spike, and strike. You’ve experienced a technical rehearsal. You have (at least) run sound, lights, or video for a show at some point. Basic macOS administration skills. Willingness to ask questions and self direct learning in areas where you are not already an expert. Willingness to learn Figure 53’s complex licensing system and ultimately provide support to customers about that system. Ability to manage your own calendar, and timeliness. Ability to maintain focus while working independently and remotely. Ability to bring renewed energy for repetitive work. Bonus Point Skills While no one person will be an expert in all of these things, any of the following skills would impress us: Professional (or high-level) experience as a technician, designer, director, or stage manager. Extensive customer service experience, particularly with a written component. You’ve done technical work for theater in multiple departments. You’ve used MIDI or OSC to control a show. You’ve dabbled in AppleScript, or written AppleScripts to control QLab. If your background is in audio, familiarity with any of the following: Meyer, d&b, L-Acoustics, or QSC loudspeakers or processing hardware DiGiCo, Yamaha, Allen & Heath, or Behringer mixing consoles RME, Motu, Universal Audio, or Focusrite audio interfaces Dante/AVB If your background is in video, familiarity with any of the following: Blackmagic hardware a solid grasp on the concepts of resolution and frame rate the uses of and differences between VGA, DVI, HDMI, and SDI network video systems, such as NDI live video systems, live camera feeds, camera switching projectors made by either Panasonic, Barco, or Christie LED Video walls and controllers knowledge of what baluns are and how to use them Matrox/Datapath multi-heads If your background is in lighting, familiarity with any of the following: ETC Express or EOS-family consoles Programming lighting effects or other complex sequences. reading a lighting plot Pre-visualisation software like Vectorworks, WYSIWYG, or Capture Art-Net protocol USB-DMX devices If you are a stage manager, experience with the following: Running many shows on QLab A working knowledge of QLab programming Troubleshooting various technical issues in a rehearsal environment We build our schedule collaboratively as a team. While it is not a requirement, availability and willingness to work mornings (starting at 9am) in the Eastern Time Zone is a plus, as is a willingness to occasionally work holidays & weekends. Availability during periods which are typically busy for professional theatre: September-early November, February-March Familiarity and experience with Github Salary and Benefits All full- and half-time employees at Figure 53 are paid based on the same annual salary. (Our CEO makes 1.5x the base salary). The base salary is $76,000 for half-time (20 hrs/week) employment. After 1 year at Figure 53, you’ll receive quarterly profit sharing which is divided based on the length of time you’ve been at the company. Profit sharing is often a significant portion of our compensation. 25 paid vacation days, unlimited unpaid vacation days (with notice and permission), and paid federal holidays plus the week between Christmas and New Years off. SIMPLE IRA retirement plan with employer contribution matching Free health insurance for you, your spouse, and your dependents, including an HRA for out-of-pocket spending. Vision and dental insurance are included because teeth and eyes are also part of your body. Fully remote work. Figure 53 is committed to building a culturally diverse staff and strongly encourages applications from people of color, women, LGBTQ+, those living with disabilities, or a member of any group that is traditionally excluded from work in the tech sector. The position is open immediately. We are accepting applications through Friday, June 5th. To get a sense of our company culture and HR policies, we encourage you to take a look at our handbook . How to Apply Please email jobs@figure53.com to apply. Attach PDFs of your resume and a cover letter that demonstrates your relevant experience and interest in the job. If you have any example QLab workspaces you’ve created we’d love to see those too. To apply: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time

[employment_type]
Full-Time

[industry]
Customer Support

**Translated Full Posting Text**

[title]
Senior QLab Support Specialist (half time)

[company_profile]
Figure 53

[location]
Anywhere in the World, Maryland, 🇺🇸 United States of America

[description]
Headquarters: Baltimore, MD URL: https://qlab.app/ Figure 53, a Baltimore-based software company, is hiring a part-time Senior QLab Support Specialist. We are looking for a candidate with both high-level technical expertise in QLab and the ability to provide clear, generous, and friendly support to our customers. Our flagship product, QLab, is used to control audio, video, and lighting for live performance. (But you, our future teammate, already know that!) All customer support for our products is conducted via email. We are looking for an additional team member to help answer any licensing and technical QLab questions our customers send us. This position requires 20 hours of work a week, and includes benefits such as a generous paid vacation policy, health insurance, profit sharing after one year, and a SIMPLE IRA with matching contributions. We are a fully remote company. You must be based in the US, with a slight preference for those based in Maryland, New York, California, or Wisconsin. Much of our success stems from taking care of our customers with exceptional support and responsiveness. We feel grateful for our customers, and we try to keep the principles of patience, gratitude, respect, and expertise driving our interactions with them. Our support team is devoted to problem-solving in a kind and generous spirit. We provide deep technical knowledge, and also bring a curiosity, dedication, and genuine compassion for customers to our work. We often work as a team to solve difficult issues. While experience with sound is absolutely a plus, we are specifically looking for a candidate with experience in one or more of the following areas: Lighting Stage Management Video Broadcasting Product licensing Required Skills The successful applicant will have all of the following skills: Superb writing skills. Experience with QLab at a moderate or expert level. (At least a year or two of actual hands-on experience with QLab.) Compassion, empathy, and an ability to convey a friendly and supportive tone via email. Patience and a pleasant demeanor, with customers and with teammates. A willingness to learn, adaptability, attention to detail, and problem solving skills. First-hand familiarity with the process of producing theater — you understand the environment our customers work in and the strains and stresses of that environment. You understand terms like standby, upstage, spike, and strike. You’ve experienced a technical rehearsal. You have (at least) run sound, lights, or video for a show at some point. Basic macOS administration skills. Willingness to ask questions and self direct learning in areas where you are not already an expert. Willingness to learn Figure 53’s complex licensing system and ultimately provide support to customers about that system. Ability to manage your own calendar, and timeliness. Ability to maintain focus while working independently and remotely. Ability to bring renewed energy for repetitive work. Bonus Point Skills While no one person will be an expert in all of these things, any of the following skills would impress us: Professional (or high-level) experience as a technician, designer, director, or stage manager. Extensive customer service experience, particularly with a written component. You’ve done technical work for theater in multiple departments. You’ve used MIDI or OSC to control a show. You’ve dabbled in AppleScript, or written AppleScripts to control QLab. If your background is in audio, familiarity with any of the following: Meyer, d&b, L-Acoustics, or QSC loudspeakers or processing hardware DiGiCo, Yamaha, Allen & Heath, or Behringer mixing consoles RME, Motu, Universal Audio, or Focusrite audio interfaces Dante/AVB If your background is in video, familiarity with any of the following: Blackmagic hardware a solid grasp on the concepts of resolution and frame rate the uses of and differences between VGA, DVI, HDMI, and SDI network video systems, such as NDI live video systems, live camera feeds, camera switching projectors made by either Panasonic, Barco, or Christie LED Video walls and controllers knowledge of what baluns are and how to use them Matrox/Datapath multi-heads If your background is in lighting, familiarity with any of the following: ETC Express or EOS-family consoles Programming lighting effects or other complex sequences. reading a lighting plot Pre-visualisation software like Vectorworks, WYSIWYG, or Capture Art-Net protocol USB-DMX devices If you are a stage manager, experience with the following: Running many shows on QLab A working knowledge of QLab programming Troubleshooting various technical issues in a rehearsal environment We build our schedule collaboratively as a team. While it is not a requirement, availability and willingness to work mornings (starting at 9am) in the Eastern Time Zone is a plus, as is a willingness to occasionally work holidays & weekends. Availability during periods which are typically busy for professional theatre: September-early November, February-March Familiarity and experience with Github Salary and Benefits All full- and half-time employees at Figure 53 are paid based on the same annual salary. (Our CEO makes 1.5x the base salary). The base salary is $76,000 for half-time (20 hrs/week) employment. After 1 year at Figure 53, you’ll receive quarterly profit sharing which is divided based on the length of time you’ve been at the company. Profit sharing is often a significant portion of our compensation. 25 paid vacation days, unlimited unpaid vacation days (with notice and permission), and paid federal holidays plus the week between Christmas and New Years off. SIMPLE IRA retirement plan with employer contribution matching Free health insurance for you, your spouse, and your dependents, including an HRA for out-of-pocket spending. Vision and dental insurance are included because teeth and eyes are also part of your body. Fully remote work. Figure 53 is committed to building a culturally diverse staff and strongly encourages applications from people of color, women, LGBTQ+, those living with disabilities, or a member of any group that is traditionally excluded from work in the tech sector. The position is open immediately. We are accepting applications through Friday, June 5th. To get a sense of our company culture and HR policies, we encourage you to take a look at our handbook . How to Apply Please email jobs@figure53.com to apply. Attach PDFs of your resume and a cover letter that demonstrates your relevant experience and interest in the job. If you have any example QLab workspaces you’ve created we’d love to see those too. To apply: https://weworkremotely.com/remote-jobs/figure-53-senior-qlab-support-specialist-half-time

[employment_type]
Full-Time

[industry]
Customer Support

---

### #45 | Casino Management & Operations
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/fairgambling-casino-management-operations
- apply_url: https://weworkremotely.com/remote-jobs/fairgambling-casino-management-operations

,field,original,translated,changed
0,title,Casino Management & Operations,Casino Management & Operations,False
1,company_profile,FairGambling,FairGambling,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,Headquarters: URL: https://fairgambling.com Casino Management & Operations About us – FairGambling We're a fast-growing platform in the online gaming space. Not a casino oursel...,Headquarters: URL: https://fairgambling.com Casino Management & Operations About us – FairGambling We're a fast-growing platform in the online gaming space. Not a casino oursel...,False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Customer Support,Customer Support,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Casino Management & Operations

[company_profile]
FairGambling

[location]
Anywhere in the World

[description]
Headquarters: URL: https://fairgambling.com Casino Management & Operations About us – FairGambling We're a fast-growing platform in the online gaming space. Not a casino ourselves, but the layer on top of it: we review, compare, and analyze operators across the industry, with transparency as the whole point. A lot of what we cover happens onchain, so we don't take operator numbers at face value – we verify them. Player reviews are checked against real on-platform activity, not just star ratings. The goal is simple: give players the honest picture the industry usually doesn't. The role This is a broad, hands-on role for people who really know the iGaming industry. The title is intentionally open: we have multiple areas to cover and we'd rather meet strong industry people first and place them where they fit best. Junior and ambitious people are very welcome – we're happy to grow the right person into it. What you'll do: Coordinate casino-related content and reviews, working closely with writers and researchers Own our operator database – keep it accurate, current, and well-organized Handle ongoing operations, updates, and escalations Manage affiliate relationships with casino operators Drive day-to-day ops and process improvements, coordinate publishing schedules, keep the team moving Cover user support: handle inquiries, help users navigate disputes with casinos, answer questions about our reviews, and improve support processes What we're looking for: Solid background in iGaming – this is the part that matters most Deep understanding of wagering, bonuses, and what separates good operators from bad actors Coordination and ops mindset – you keep things moving and don't let them slip Strong communication; comfortable working independently Real industry experience prioritized over a perfect title match – juniors welcome To apply, please include: Your background in the iGaming industry and where you've worked One operator problem or dispute you'd know how to handle, and how Your availability and what part of this role fits you best To apply: https://weworkremotely.com/remote-jobs/fairgambling-casino-management-operations

[employment_type]
Full-Time

[industry]
Customer Support

**Translated Full Posting Text**

[title]
Casino Management & Operations

[company_profile]
FairGambling

[location]
Anywhere in the World

[description]
Headquarters: URL: https://fairgambling.com Casino Management & Operations About us – FairGambling We're a fast-growing platform in the online gaming space. Not a casino ourselves, but the layer on top of it: we review, compare, and analyze operators across the industry, with transparency as the whole point. A lot of what we cover happens onchain, so we don't take operator numbers at face value – we verify them. Player reviews are checked against real on-platform activity, not just star ratings. The goal is simple: give players the honest picture the industry usually doesn't. The role This is a broad, hands-on role for people who really know the iGaming industry. The title is intentionally open: we have multiple areas to cover and we'd rather meet strong industry people first and place them where they fit best. Junior and ambitious people are very welcome – we're happy to grow the right person into it. What you'll do: Coordinate casino-related content and reviews, working closely with writers and researchers Own our operator database – keep it accurate, current, and well-organized Handle ongoing operations, updates, and escalations Manage affiliate relationships with casino operators Drive day-to-day ops and process improvements, coordinate publishing schedules, keep the team moving Cover user support: handle inquiries, help users navigate disputes with casinos, answer questions about our reviews, and improve support processes What we're looking for: Solid background in iGaming – this is the part that matters most Deep understanding of wagering, bonuses, and what separates good operators from bad actors Coordination and ops mindset – you keep things moving and don't let them slip Strong communication; comfortable working independently Real industry experience prioritized over a perfect title match – juniors welcome To apply, please include: Your background in the iGaming industry and where you've worked One operator problem or dispute you'd know how to handle, and how Your availability and what part of this role fits you best To apply: https://weworkremotely.com/remote-jobs/fairgambling-casino-management-operations

[employment_type]
Full-Time

[industry]
Customer Support

---

### #46 | Blockchain Engineer & Researcher
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/fairgambling-blockchain-engineer-researcher
- apply_url: https://weworkremotely.com/remote-jobs/fairgambling-blockchain-engineer-researcher

,field,original,translated,changed
0,title,Blockchain Engineer & Researcher,Blockchain Engineer & Researcher,False
1,company_profile,FairGambling,FairGambling,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: URL: https://fairgambling.com Blockchain Engineer / Analyst (Remote, Full-time or Contract) About us – FairGambling We're a fast-growing platform in the online ga...","Headquarters: URL: https://fairgambling.com Blockchain Engineer / Analyst (Remote, Full-time or Contract) About us – FairGambling We're a fast-growing platform in the online ga...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Back-End Programming,Back-End Programming,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Blockchain Engineer & Researcher

[company_profile]
FairGambling

[location]
Anywhere in the World

[description]
Headquarters: URL: https://fairgambling.com Blockchain Engineer / Analyst (Remote, Full-time or Contract) About us – FairGambling We're a fast-growing platform in the online gaming space. Not a casino ourselves, but the layer on top of it: we review, compare, and analyze operators across the industry, with transparency as the whole point. A lot of what we cover happens onchain, so we don't take operator numbers at face value – we verify them. Player reviews are checked against real on-platform activity, not just star ratings. The goal is simple: give players the honest picture the industry usually doesn't. The role A lot of what we verify lives onchain. We're hiring someone who's comfortable there – building tooling, tracking transactions across chains, and following contracts to surface what operators don't say themselves. What you'll do: Build and maintain trackers, dashboards, and scripts Monitor multiple chains, track transactions, and follow contracts onchain Investigate transaction flows and surface insights for the research and content team Follow trails through data – the work is genuinely investigative What we're looking for: Experience with trackers, dashboards, and scripts; smart contracts and transaction flows a strong plus Multi-chain experience ideally (EVM, Solana, BSC, TRON, etc.) Hands-on with blockchain explorers and analytics tools Background in a crypto product (exchange, DeFi) is a big plus Investigative mindset – you enjoy digging through data and following trails To apply, please include: Onchain tools, trackers, or investigations you've worked on (links / addresses welcome) Your favorite analytics tool and something you've built or found with it Your availability and preferred setup (full-time or contract) To apply: https://weworkremotely.com/remote-jobs/fairgambling-blockchain-engineer-researcher

[employment_type]
Full-Time

[industry]
Back-End Programming

**Translated Full Posting Text**

[title]
Blockchain Engineer & Researcher

[company_profile]
FairGambling

[location]
Anywhere in the World

[description]
Headquarters: URL: https://fairgambling.com Blockchain Engineer / Analyst (Remote, Full-time or Contract) About us – FairGambling We're a fast-growing platform in the online gaming space. Not a casino ourselves, but the layer on top of it: we review, compare, and analyze operators across the industry, with transparency as the whole point. A lot of what we cover happens onchain, so we don't take operator numbers at face value – we verify them. Player reviews are checked against real on-platform activity, not just star ratings. The goal is simple: give players the honest picture the industry usually doesn't. The role A lot of what we verify lives onchain. We're hiring someone who's comfortable there – building tooling, tracking transactions across chains, and following contracts to surface what operators don't say themselves. What you'll do: Build and maintain trackers, dashboards, and scripts Monitor multiple chains, track transactions, and follow contracts onchain Investigate transaction flows and surface insights for the research and content team Follow trails through data – the work is genuinely investigative What we're looking for: Experience with trackers, dashboards, and scripts; smart contracts and transaction flows a strong plus Multi-chain experience ideally (EVM, Solana, BSC, TRON, etc.) Hands-on with blockchain explorers and analytics tools Background in a crypto product (exchange, DeFi) is a big plus Investigative mindset – you enjoy digging through data and following trails To apply, please include: Onchain tools, trackers, or investigations you've worked on (links / addresses welcome) Your favorite analytics tool and something you've built or found with it Your availability and preferred setup (full-time or contract) To apply: https://weworkremotely.com/remote-jobs/fairgambling-blockchain-engineer-researcher

[employment_type]
Full-Time

[industry]
Back-End Programming

---

### #47 | Senior Product Manager
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/hint-health-senior-product-manager
- apply_url: https://weworkremotely.com/remote-jobs/hint-health-senior-product-manager

,field,original,translated,changed
0,title,Senior Product Manager,Senior Product Manager,False
1,company_profile,Hint Health,Hint Health,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: USA, Canada, Costa Rica, Uruguay - Remote About Hint Health Hint Health is the leading digital health company dedicated to supporting the growth and success of th...","Headquarters: USA, Canada, Costa Rica, Uruguay - Remote About Hint Health Hint Health is the leading digital health company dedicated to supporting the growth and success of th...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Product,Product,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Product Manager

[company_profile]
Hint Health

[location]
Anywhere in the World

[description]
Headquarters: USA, Canada, Costa Rica, Uruguay - Remote About Hint Health Hint Health is the leading digital health company dedicated to supporting the growth and success of the Direct Primary Care (DPC) movement. With a mission to power direct care and make it the new standard, the HintOS platform supports thousands of clinics and networks across the nation providing care for over a million members. Hint also produces Hint Summit, the leading DPC innovation conference and supports Hint Connect, a curated national network of independent DPC clinics. Founded in 2013, the company is headquartered in San Francisco, CA. To learn more visit www.hint.com/company . Hint Health is seeking a Senior Product Manager to join us in our mission to make great healthcare accessible and affordable. Reporting to our Director of Product, you’ll play a pivotal role in building software that empowers healthcare providers to scale direct care models nationwide. You’ll partner closely with Hint’s community of forward-thinking providers to reimagine how healthcare is delivered – from the first patient enrollment to ongoing care – driving better experiences, better outcomes, and lower costs. In this role, you’ll serve as the product owner responsible for a major portion of the Core side of Hint’s platform. Hint Core is the operating system for Direct Primary Care (DPC): it powers the essential business backbone that makes membership-based care models run smoothly, including enrollment, membership management, billing and payments infrastructure, and day-to-day operational workflows. Thousands of DPC practices rely on Hint Core to keep their businesses running so providers can automate away the admin work and stay focused on delivering excellent care. About the Team Our mission on this team is simple: help DPC clinicians practice at the top of their license by automating the boring stuff. Providers don’t want to wrestle with billing, complex payment processing, or administrative overhead – they want to care for patients. At the same time, they’re entrepreneurs pioneering new models of care and need technology that gives them confidence, business resilience, and the ability to grow. As the Senior Product Manager on Core, you’ll steward critical product areas that ensure DPC practices can run effectively and sustainably. This role involves evolving a mature, widely-used platform – balancing incremental improvements with thoughtful system modernization and long-term scalability. Your decisions will shape the infrastructure and user experience that keeps thousands of practices humming and enables clinics across the country to deliver more personalized, relationship-centered care. Key Responsibilities: Be the owner of the product vision for your product zone, continually refining it based on customer insights and rallying the team around it Define the product priorities and short, medium, and long-term roadmap Lead the team to deliver the roadmap through agile sprint cycles, breaking down the product roadmap into executable stories and requirements with partners in Engineering and Design Use data and insights, including product analytics, market research, user research, and business needs, to inform product work and prioritization Define success metrics and consistently measure the impact of the team’s work Build strong cross-functional relationships, founded on clear communication, to take new products and features to market in a way that maximizes their success Build bridges and feedback loops directly with Hint customers, from engagement with Hint’s user community to lean user research and design activities Mentor and support broader product team and improve on product best practices at Hint This role might be for you if… You excel in established product environments. You thrive working with legacy products, balancing reliability and maintenance with pushing forward continuous innovation and meaningful product evolution. Cutting through ambiguity is your superpower. You can get to the root of a problem and create a compelling vision and actionable plans that align your team and stakeholders. You have a technical PM background. You bring strong technical fluency, with experience shaping products that involve APIs, system integrations, backend workflows, and complex data flows. You get energy from both discovery and delivery in regulated domains. You’re comfortable exploring new problem spaces and shepherding complex initiatives, like payments, billing, or financial workflows – from concept through build, release, and adoption, ideally within health or fintech contexts What you bring.... At least 5 years of Product Management experience in a consumer or B2B software company, with a track record of shipping impactful products across the end-to-end product lifecycle Technical PM background or strong technical fluency. You’re comfortable digging into APIs, system integrations, backend workflows, and data infrastructure A balance of strategic and executional strengths – you can zoom out to define long-term vision and priorities, then zoom in to drive sprint-level details with an eagle eye for detail Entrepreneurial and creative attitude when problem solving Excellent communication and storytelling abilities – you quickly build trust with customers, partners, and cross-functional teams, and can translate complex concepts into clear narratives Adept at making small and large trade-off decisions based on product and company priorities Strong product sense and business judgment, grounding all product decisions in data, user feedback, and measurable impact Curiosity, openness, and experimental mindset toward using AI to accelerate product development, improve workflows, or enhance the user experience Nice to haves: Healthcare or fintech experience Mix of web and mobile UX experience. Experience shaping companion mobile experiences to a primarily web based product Life at Hint Our team is inquisitive, kind, open, and smart. We share glimpses of our lives—introducing our kids and pets—and host virtual hangouts to stay connected. Our employee Slack channels include spaces for women, caregivers, and our Diversity & Inclusion Committee. We also have regular cadences for company all-hands updates and team learning sessions so all Hinters can stay connected to how their work is changing the landscape of healthcare. Hint has taken the Parity Pledge and is committed to racial and gender parity. Furthermore, those historically underrepresented in tech—including people of color, immigrants, members of the LGBTQ+ community, people with disabilities and veterans—are encouraged to apply. We look for the best candidate for the job based on demonstrable skills, and do not screen for educational background, age, or markers of socioeconomic status. Benefits At Hint we support our teams to be their best by taking care of them and providing attractive benefits. * Competitive compensation of base salary & stock options * 401k plan * Progressive paid parental leave for both parents * Comprehensive medical, dental & vision + DPC membership or HSA stipend * Remote-first workplace, home office stipend, & optional in-person meet-ups * Flexible working hours, flexible vacation, & paid national holidays As Hint Health is a remote company, we use e-verify for all US employees to complete an I9. More about this can be found here and here . We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/hint-health-senior-product-manager

[employment_type]
Full-Time

[industry]
Product

**Translated Full Posting Text**

[title]
Senior Product Manager

[company_profile]
Hint Health

[location]
Anywhere in the World

[description]
Headquarters: USA, Canada, Costa Rica, Uruguay - Remote About Hint Health Hint Health is the leading digital health company dedicated to supporting the growth and success of the Direct Primary Care (DPC) movement. With a mission to power direct care and make it the new standard, the HintOS platform supports thousands of clinics and networks across the nation providing care for over a million members. Hint also produces Hint Summit, the leading DPC innovation conference and supports Hint Connect, a curated national network of independent DPC clinics. Founded in 2013, the company is headquartered in San Francisco, CA. To learn more visit www.hint.com/company . Hint Health is seeking a Senior Product Manager to join us in our mission to make great healthcare accessible and affordable. Reporting to our Director of Product, you’ll play a pivotal role in building software that empowers healthcare providers to scale direct care models nationwide. You’ll partner closely with Hint’s community of forward-thinking providers to reimagine how healthcare is delivered – from the first patient enrollment to ongoing care – driving better experiences, better outcomes, and lower costs. In this role, you’ll serve as the product owner responsible for a major portion of the Core side of Hint’s platform. Hint Core is the operating system for Direct Primary Care (DPC): it powers the essential business backbone that makes membership-based care models run smoothly, including enrollment, membership management, billing and payments infrastructure, and day-to-day operational workflows. Thousands of DPC practices rely on Hint Core to keep their businesses running so providers can automate away the admin work and stay focused on delivering excellent care. About the Team Our mission on this team is simple: help DPC clinicians practice at the top of their license by automating the boring stuff. Providers don’t want to wrestle with billing, complex payment processing, or administrative overhead – they want to care for patients. At the same time, they’re entrepreneurs pioneering new models of care and need technology that gives them confidence, business resilience, and the ability to grow. As the Senior Product Manager on Core, you’ll steward critical product areas that ensure DPC practices can run effectively and sustainably. This role involves evolving a mature, widely-used platform – balancing incremental improvements with thoughtful system modernization and long-term scalability. Your decisions will shape the infrastructure and user experience that keeps thousands of practices humming and enables clinics across the country to deliver more personalized, relationship-centered care. Key Responsibilities: Be the owner of the product vision for your product zone, continually refining it based on customer insights and rallying the team around it Define the product priorities and short, medium, and long-term roadmap Lead the team to deliver the roadmap through agile sprint cycles, breaking down the product roadmap into executable stories and requirements with partners in Engineering and Design Use data and insights, including product analytics, market research, user research, and business needs, to inform product work and prioritization Define success metrics and consistently measure the impact of the team’s work Build strong cross-functional relationships, founded on clear communication, to take new products and features to market in a way that maximizes their success Build bridges and feedback loops directly with Hint customers, from engagement with Hint’s user community to lean user research and design activities Mentor and support broader product team and improve on product best practices at Hint This role might be for you if… You excel in established product environments. You thrive working with legacy products, balancing reliability and maintenance with pushing forward continuous innovation and meaningful product evolution. Cutting through ambiguity is your superpower. You can get to the root of a problem and create a compelling vision and actionable plans that align your team and stakeholders. You have a technical PM background. You bring strong technical fluency, with experience shaping products that involve APIs, system integrations, backend workflows, and complex data flows. You get energy from both discovery and delivery in regulated domains. You’re comfortable exploring new problem spaces and shepherding complex initiatives, like payments, billing, or financial workflows – from concept through build, release, and adoption, ideally within health or fintech contexts What you bring.... At least 5 years of Product Management experience in a consumer or B2B software company, with a track record of shipping impactful products across the end-to-end product lifecycle Technical PM background or strong technical fluency. You’re comfortable digging into APIs, system integrations, backend workflows, and data infrastructure A balance of strategic and executional strengths – you can zoom out to define long-term vision and priorities, then zoom in to drive sprint-level details with an eagle eye for detail Entrepreneurial and creative attitude when problem solving Excellent communication and storytelling abilities – you quickly build trust with customers, partners, and cross-functional teams, and can translate complex concepts into clear narratives Adept at making small and large trade-off decisions based on product and company priorities Strong product sense and business judgment, grounding all product decisions in data, user feedback, and measurable impact Curiosity, openness, and experimental mindset toward using AI to accelerate product development, improve workflows, or enhance the user experience Nice to haves: Healthcare or fintech experience Mix of web and mobile UX experience. Experience shaping companion mobile experiences to a primarily web based product Life at Hint Our team is inquisitive, kind, open, and smart. We share glimpses of our lives—introducing our kids and pets—and host virtual hangouts to stay connected. Our employee Slack channels include spaces for women, caregivers, and our Diversity & Inclusion Committee. We also have regular cadences for company all-hands updates and team learning sessions so all Hinters can stay connected to how their work is changing the landscape of healthcare. Hint has taken the Parity Pledge and is committed to racial and gender parity. Furthermore, those historically underrepresented in tech—including people of color, immigrants, members of the LGBTQ+ community, people with disabilities and veterans—are encouraged to apply. We look for the best candidate for the job based on demonstrable skills, and do not screen for educational background, age, or markers of socioeconomic status. Benefits At Hint we support our teams to be their best by taking care of them and providing attractive benefits. * Competitive compensation of base salary & stock options * 401k plan * Progressive paid parental leave for both parents * Comprehensive medical, dental & vision + DPC membership or HSA stipend * Remote-first workplace, home office stipend, & optional in-person meet-ups * Flexible working hours, flexible vacation, & paid national holidays As Hint Health is a remote company, we use e-verify for all US employees to complete an I9. More about this can be found here and here . We may use artificial intelligence (AI) tools to support parts of the hiring process, such as reviewing applications, analyzing resumes, or assessing responses. These tools assist our recruitment team but do not replace human judgment. Final hiring decisions are ultimately made by humans. If you would like more information about how your data is processed, please contact us. To apply: https://weworkremotely.com/remote-jobs/hint-health-senior-product-manager

[employment_type]
Full-Time

[industry]
Product

---

### #48 | Turfgrass Horticulturalist Agronomist - Product Innovation & Support - REMOTE
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/custom-simple-solutions-turfgrass-horticulturalist-agronomist-product-innovation-support-remote
- apply_url: https://weworkremotely.com/remote-jobs/custom-simple-solutions-turfgrass-horticulturalist-agronomist-product-innovation-support-remote

,field,original,translated,changed
0,title,Turfgrass Horticulturalist Agronomist - Product Innovation & Support - REMOTE,Turfgrass Horticulturalist Agronomist - Product Innovation & Support - REMOTE,False
1,company_profile,Custom Simple Solutions,Custom Simple Solutions,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: Tampa, Florida, United States Position Overview This role requires a digitally savvy, flexible Agronomist to join a dynamic team. This fully remote role is centra...","Headquarters: Tampa, Florida, United States Position Overview This role requires a digitally savvy, flexible Agronomist to join a dynamic team. This fully remote role is centra...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Customer Support,Customer Support,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Turfgrass Horticulturalist Agronomist - Product Innovation & Support - REMOTE

[company_profile]
Custom Simple Solutions

[location]
Anywhere in the World

[description]
Headquarters: Tampa, Florida, United States Position Overview This role requires a digitally savvy, flexible Agronomist to join a dynamic team. This fully remote role is central to ensuring product quality , driving turf research , and delivering exceptional customer service to our nationwide client base. The ideal candidate will blend technical expertise in Turfgrass and soil science with a passion for leveraging digital tools to support a modern client base. Key Responsibilities Product Claims and Quality Assurance Work with state regulators to clarify and potentially challenge product labeling requirements Maintain research and keep diligent records to help with customer interactions, claims, and product performance Monitor and test fertilizer product quality to help with claims, marketing, and responsiveness to customer feedback Assist with and provide turf expertise to Investigate and resolve product complaints, documenting findings and recommending corrective actions Turfgrass Research & Innovation Design, coordinate, and analyze remote field trials to evaluate fertilizer effectiveness across diverse environments Collect, interpret, and report on turfgrass data using digital tools and software, particularly office applications (Excel, Google Sheets) and reporting Stay current on industry research and integrate innovative practices into product development and customer recommendations Develop and implement testing procedures and protocols for new and existing products Work with State Regulatory bodies to clarify product labeling and compliance for new or substantially revised products Customer Service & Technical Support Sweep product marketing verbiage to make sure claims and quality are accurately reflected Serve as a primary point of contact for customer inquiries, offering science-based recommendations for fertilizer use, turf nutrition, and soil health. Provide virtual training, educational materials, and technical support to customers and internal teams Communicate research findings and product benefits through digital presentations, webinars, podcasts, and written reports Required Skills & Qualifications Masters degree or higher in Turfgrass, Agronomy, Horticulture, Crop Science, Soil Science, or related field Minimum 3 years’ experience in agronomy, agricultural research, or technical support (turfgrass and fertilizer industry preferred) Proficiency with digital business tools, data management software, and remote communication platforms Strong analytical skills and ability to interpret datasets related to turf management, soil conditions, and product performance Excellent written and verbal communication skills for technical and customer-facing audiences Self-motivated, flexible, and capable of working independently in a fully remote environment Demonstrated customer service orientation and problem-solving abilities Preferred Qualifications Turf specialization or equivalent experience with turf. Experience supporting retail fertilizer product sales and customer education. Prior experience with remote or distributed teams. This role has a unique opportunity to shape the future of digital-first, growing retail fertilizer business. Required Skills & Qualifications Masters degree or higher in Turfgrass, Agronomy, Horticulture, Crop Science, Soil Science, or related field Minimum 3 years’ experience in agronomy, agricultural research, or technical support (turfgrass and fertilizer industry preferred) Proficiency with digital business tools, data management software, and remote communication platforms Strong analytical skills and ability to interpret datasets related to turf management, soil conditions, and product performance Excellent written and verbal communication skills for technical and customer-facing audiences Self-motivated, flexible, and capable of working independently in a fully remote environment Demonstrated customer service orientation and problem-solving abilities Benefits - Paid Time Off - Paid Holidays To apply: https://weworkremotely.com/remote-jobs/custom-simple-solutions-turfgrass-horticulturalist-agronomist-product-innovation-support-remote

[employment_type]
Full-Time

[industry]
Customer Support

**Translated Full Posting Text**

[title]
Turfgrass Horticulturalist Agronomist - Product Innovation & Support - REMOTE

[company_profile]
Custom Simple Solutions

[location]
Anywhere in the World

[description]
Headquarters: Tampa, Florida, United States Position Overview This role requires a digitally savvy, flexible Agronomist to join a dynamic team. This fully remote role is central to ensuring product quality , driving turf research , and delivering exceptional customer service to our nationwide client base. The ideal candidate will blend technical expertise in Turfgrass and soil science with a passion for leveraging digital tools to support a modern client base. Key Responsibilities Product Claims and Quality Assurance Work with state regulators to clarify and potentially challenge product labeling requirements Maintain research and keep diligent records to help with customer interactions, claims, and product performance Monitor and test fertilizer product quality to help with claims, marketing, and responsiveness to customer feedback Assist with and provide turf expertise to Investigate and resolve product complaints, documenting findings and recommending corrective actions Turfgrass Research & Innovation Design, coordinate, and analyze remote field trials to evaluate fertilizer effectiveness across diverse environments Collect, interpret, and report on turfgrass data using digital tools and software, particularly office applications (Excel, Google Sheets) and reporting Stay current on industry research and integrate innovative practices into product development and customer recommendations Develop and implement testing procedures and protocols for new and existing products Work with State Regulatory bodies to clarify product labeling and compliance for new or substantially revised products Customer Service & Technical Support Sweep product marketing verbiage to make sure claims and quality are accurately reflected Serve as a primary point of contact for customer inquiries, offering science-based recommendations for fertilizer use, turf nutrition, and soil health. Provide virtual training, educational materials, and technical support to customers and internal teams Communicate research findings and product benefits through digital presentations, webinars, podcasts, and written reports Required Skills & Qualifications Masters degree or higher in Turfgrass, Agronomy, Horticulture, Crop Science, Soil Science, or related field Minimum 3 years’ experience in agronomy, agricultural research, or technical support (turfgrass and fertilizer industry preferred) Proficiency with digital business tools, data management software, and remote communication platforms Strong analytical skills and ability to interpret datasets related to turf management, soil conditions, and product performance Excellent written and verbal communication skills for technical and customer-facing audiences Self-motivated, flexible, and capable of working independently in a fully remote environment Demonstrated customer service orientation and problem-solving abilities Preferred Qualifications Turf specialization or equivalent experience with turf. Experience supporting retail fertilizer product sales and customer education. Prior experience with remote or distributed teams. This role has a unique opportunity to shape the future of digital-first, growing retail fertilizer business. Required Skills & Qualifications Masters degree or higher in Turfgrass, Agronomy, Horticulture, Crop Science, Soil Science, or related field Minimum 3 years’ experience in agronomy, agricultural research, or technical support (turfgrass and fertilizer industry preferred) Proficiency with digital business tools, data management software, and remote communication platforms Strong analytical skills and ability to interpret datasets related to turf management, soil conditions, and product performance Excellent written and verbal communication skills for technical and customer-facing audiences Self-motivated, flexible, and capable of working independently in a fully remote environment Demonstrated customer service orientation and problem-solving abilities Benefits - Paid Time Off - Paid Holidays To apply: https://weworkremotely.com/remote-jobs/custom-simple-solutions-turfgrass-horticulturalist-agronomist-product-innovation-support-remote

[employment_type]
Full-Time

[industry]
Customer Support

---

### #49 | Director, Graphic Design
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/olive-june-director-graphic-design
- apply_url: https://weworkremotely.com/remote-jobs/olive-june-director-graphic-design

,field,original,translated,changed
0,title,"Director, Graphic Design","Director, Graphic Design",False
1,company_profile,Olive June,Olive June,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: United States Title: Director, Graphic Design (Product/Packaging/Visual Merchandising) To Apply: Submit resume and design portfolio About Olive & June: In 2013, O...","Headquarters: United States Title: Director, Graphic Design (Product/Packaging/Visual Merchandising) To Apply: Submit resume and design portfolio About Olive & June: In 2013, O...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Design,Design,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Director, Graphic Design

[company_profile]
Olive June

[location]
Anywhere in the World

[description]
Headquarters: United States Title: Director, Graphic Design (Product/Packaging/Visual Merchandising) To Apply: Submit resume and design portfolio About Olive & June: In 2013, Olive & June opened its first salon in Beverly Hills and elevated the salon experience, giving women personalized attention and luxury service at an approachable price. Now, founder Sarah Gibson Tuttle is on a mission to bring beautiful nails to everyone with an ever-growing line of nail care must-haves that are changing the at-home manicure game. With best in class investors and huge press coverage on their mani kit launch, if you are looking for a hyper growth DTC startup with meaningful momentum, Olive & June may be for you. About the Role Olive & June is looking for a new Graphic Designer to join the design team. You will be responsible for the execution of elevated brand creative that translates business and marketing objectives into designs that are on-brand, beautiful, and clear to the consumer. This role will be remote. Roles & Responsibilities Full-time, remote position Collaborate with the creative, product, retail, and marketing team members to design compelling assets across all channels including but not limited to: visual merchandising displays, product packaging, print assets, press-on nail designs, event collateral, marketing mailers, and occasionally email, web, and social assets. Ensure on time and accurate delivery of all projects. Demonstrate flexibility, organizational skills and the ability to multitask. Maintain high brand standards and quality assurance across all work, so that it is cohesive, consistent, inspired, original, and on brand. Qualifications Minimum 3+ years of graphic design experience in-house, at an agency, or freelance Maintain a flexible mindset Strong collaboration within creative team as well as cross-functional Must be proficient on Adobe Creative Suite including InDesign, Illustrator, and Photoshop (3D rendering / mockup softwares are a bonus!) Strong technical skills (comping and presentation prep) Strong 3D rendering skills that can be applied to visual merchandise and product packaging projects Strong typography, layout, hierarchy, branding skills Ability to work on multiple projects at the same time in a fast paced environment Positive attitude Detail oriented and organized BFA/BA in Graphic/Product Design Experience working in project management software such as Asana, Monday, Workfront or similar Experience working in Figma or similar visualization platform A love for the beauty industry! To apply: https://weworkremotely.com/remote-jobs/olive-june-director-graphic-design

[employment_type]
Full-Time

[industry]
Design

**Translated Full Posting Text**

[title]
Director, Graphic Design

[company_profile]
Olive June

[location]
Anywhere in the World

[description]
Headquarters: United States Title: Director, Graphic Design (Product/Packaging/Visual Merchandising) To Apply: Submit resume and design portfolio About Olive & June: In 2013, Olive & June opened its first salon in Beverly Hills and elevated the salon experience, giving women personalized attention and luxury service at an approachable price. Now, founder Sarah Gibson Tuttle is on a mission to bring beautiful nails to everyone with an ever-growing line of nail care must-haves that are changing the at-home manicure game. With best in class investors and huge press coverage on their mani kit launch, if you are looking for a hyper growth DTC startup with meaningful momentum, Olive & June may be for you. About the Role Olive & June is looking for a new Graphic Designer to join the design team. You will be responsible for the execution of elevated brand creative that translates business and marketing objectives into designs that are on-brand, beautiful, and clear to the consumer. This role will be remote. Roles & Responsibilities Full-time, remote position Collaborate with the creative, product, retail, and marketing team members to design compelling assets across all channels including but not limited to: visual merchandising displays, product packaging, print assets, press-on nail designs, event collateral, marketing mailers, and occasionally email, web, and social assets. Ensure on time and accurate delivery of all projects. Demonstrate flexibility, organizational skills and the ability to multitask. Maintain high brand standards and quality assurance across all work, so that it is cohesive, consistent, inspired, original, and on brand. Qualifications Minimum 3+ years of graphic design experience in-house, at an agency, or freelance Maintain a flexible mindset Strong collaboration within creative team as well as cross-functional Must be proficient on Adobe Creative Suite including InDesign, Illustrator, and Photoshop (3D rendering / mockup softwares are a bonus!) Strong technical skills (comping and presentation prep) Strong 3D rendering skills that can be applied to visual merchandise and product packaging projects Strong typography, layout, hierarchy, branding skills Ability to work on multiple projects at the same time in a fast paced environment Positive attitude Detail oriented and organized BFA/BA in Graphic/Product Design Experience working in project management software such as Asana, Monday, Workfront or similar Experience working in Figma or similar visualization platform A love for the beauty industry! To apply: https://weworkremotely.com/remote-jobs/olive-june-director-graphic-design

[employment_type]
Full-Time

[industry]
Design

---

### #50 | Senior Product Manager
- source: we_work_remotely_rss
- detected_language: en (confidence=0.55)
- detector: latin-keyword-heuristic
- translation_applied: False
- translation_provider: none
- translation_error: None
- job_url: https://weworkremotely.com/remote-jobs/biggerpockets-senior-product-manager
- apply_url: https://weworkremotely.com/remote-jobs/biggerpockets-senior-product-manager

,field,original,translated,changed
0,title,Senior Product Manager,Senior Product Manager,False
1,company_profile,Biggerpockets,Biggerpockets,False
2,location,Anywhere in the World,Anywhere in the World,False
3,department,,,False
4,description,"Headquarters: United States Senior Product Manager – Marketplace About Us BiggerPockets is the leading real estate investing community and podcast. Since 2004, we’ve helped mil...","Headquarters: United States Senior Product Manager – Marketplace About Us BiggerPockets is the leading real estate investing community and podcast. Since 2004, we’ve helped mil...",False
5,requirements,,,False
6,benefits,,,False
7,employment_type,Full-Time,Full-Time,False
8,required_experience,,,False
9,required_education,,,False
10,industry,Product,Product,False
11,function,,,False
12,salary_range,,,False

**Original Full Posting Text**

[title]
Senior Product Manager

[company_profile]
Biggerpockets

[location]
Anywhere in the World

[description]
Headquarters: United States Senior Product Manager – Marketplace About Us BiggerPockets is the leading real estate investing community and podcast. Since 2004, we’ve helped millions of people take steps toward financial freedom through education, tools, and a vibrant member-driven community. With over 3 million members, BiggerPockets is the go-to platform for real estate investors at every stage of their journey. We’re building the next generation of products that power learning, investing, and community—and we’re looking for a seasoned product leader to help shape the foundation of our platform. About the Role We’re looking for a Senior Product Manager, Marketplace to own and evolve key marketplace experiences at BiggerPockets. This role will focus on building scalable, trusted, and high-performing marketplace products that create value for both sides of the network - investors and partners. You'll work closely with engineering, design, data, and business stakeholders to define strategy, drive execution, and improve marketplace health across acquisition, engagement, conversation, and retention. This is a hands-on role for a strong product operator who thrives in complex, cross-functional environments and enjoys balancing user needs with business outcomes. What You’ll Do Own the product strategy and roadmap for key marketplace surfaces and experiences, from discovery through conversion and retention. Deeply understand marketplace dynamics, including supply and demand balance, liquidity, trust, incentives, and monetization. Partner with engineering and design to deliver high-quality, user-centered solutions with a strong bias toward execution. Work closely with business and marketplace stakeholders to align product decisions with revenue, growth, and partner success goals. Define and track success metrics, using data and experimentation to inform prioritization and measure impact. Identify opportunities to improve marketplace efficiency, transparency, and value for all participants. Lead cross-functional initiatives involving engineering, design, analytics, marketing, and operations. Communicate product direction, tradeoffs, and outcomes clearly to stakeholders at all levels. What We’re Looking For Proven experience building or scaling marketplace, platform, or multi-sided products. Strong intuition for marketplace mechanics, incentives, and tradeoffs. Ability to translate ambiguous problems into clear product direction and shipped outcomes. Strong prioritization skills and comfort making decisions with incomplete information. Experience partnering closely with engineering, design, and business teams. Ability to influence without authority and align diverse stakeholders. Customer & Business Focus Deep empathy for users and a clear understanding of how product decisions drive business results. Comfort owning revenue-adjacent surfaces and metrics. Experience using qualitative insights and quantitative data to guide product decisions. Familiarity with experimentation and analytics tools. Education & Experience Knowledge of real estate investing is a plus, but not required. 6–10 years of product management experience, with at least 2+ years owning significant product areas end-to-end. Experience in marketplaces, SaaS platforms, fintech, or community-driven products strongly preferred. Familiarity with modern product development practices (Agile, continuous delivery, discovery-driven development). Experience with analytics and experimentation tools (e.g., Amplitude, Tableau, A/B testing platforms). Benefits include: Medical, dental, and vision coverage Flexible paid time off Office snacks & beverages Career development budget 401k package Paid parental leave 12 company-paid holidays per year Community service & volunteer opportunities Amazing team & fun culture with lots of team events Learn more about real estate investing Compensation Base Salary Range: $190,000 – $220,000 per year This role is also eligible for an annual bonus based on individual and company performance. Compensation is based on a variety of factors including experience, skills, and location, and is compliant with applicable pay transparency laws, including Colorado’s Equal Pay for Equal Work Act. BiggerPockets is proud to be an EOE/Veterans/Disabled/LGBTQ+ employer. We celebrate, support, and encourage being different for the benefit of our team members and community. We do not discriminate on the basis of race, color, religion, age, sex, gender identity, sexual orientation, national origin, political affiliation, marital status, non-disqualifying physical or mental disability, genetic information, membership in an employee organization, retaliation, parental status, veteran status or other non-merit factor. We celebrate diversity and are committed to creating an inclusive environment for all team members. All employment offers are decided on the basis of qualifications, merit, and business need. Please note this job description is not designed to cover or contain a comprehensive listing of activities, duties, or responsibilities that are required of the employee for this job. Duties, responsibilities and activities may change at any time with or without notice. To apply: https://weworkremotely.com/remote-jobs/biggerpockets-senior-product-manager

[employment_type]
Full-Time

[industry]
Product

**Translated Full Posting Text**

[title]
Senior Product Manager

[company_profile]
Biggerpockets

[location]
Anywhere in the World

[description]
Headquarters: United States Senior Product Manager – Marketplace About Us BiggerPockets is the leading real estate investing community and podcast. Since 2004, we’ve helped millions of people take steps toward financial freedom through education, tools, and a vibrant member-driven community. With over 3 million members, BiggerPockets is the go-to platform for real estate investors at every stage of their journey. We’re building the next generation of products that power learning, investing, and community—and we’re looking for a seasoned product leader to help shape the foundation of our platform. About the Role We’re looking for a Senior Product Manager, Marketplace to own and evolve key marketplace experiences at BiggerPockets. This role will focus on building scalable, trusted, and high-performing marketplace products that create value for both sides of the network - investors and partners. You'll work closely with engineering, design, data, and business stakeholders to define strategy, drive execution, and improve marketplace health across acquisition, engagement, conversation, and retention. This is a hands-on role for a strong product operator who thrives in complex, cross-functional environments and enjoys balancing user needs with business outcomes. What You’ll Do Own the product strategy and roadmap for key marketplace surfaces and experiences, from discovery through conversion and retention. Deeply understand marketplace dynamics, including supply and demand balance, liquidity, trust, incentives, and monetization. Partner with engineering and design to deliver high-quality, user-centered solutions with a strong bias toward execution. Work closely with business and marketplace stakeholders to align product decisions with revenue, growth, and partner success goals. Define and track success metrics, using data and experimentation to inform prioritization and measure impact. Identify opportunities to improve marketplace efficiency, transparency, and value for all participants. Lead cross-functional initiatives involving engineering, design, analytics, marketing, and operations. Communicate product direction, tradeoffs, and outcomes clearly to stakeholders at all levels. What We’re Looking For Proven experience building or scaling marketplace, platform, or multi-sided products. Strong intuition for marketplace mechanics, incentives, and tradeoffs. Ability to translate ambiguous problems into clear product direction and shipped outcomes. Strong prioritization skills and comfort making decisions with incomplete information. Experience partnering closely with engineering, design, and business teams. Ability to influence without authority and align diverse stakeholders. Customer & Business Focus Deep empathy for users and a clear understanding of how product decisions drive business results. Comfort owning revenue-adjacent surfaces and metrics. Experience using qualitative insights and quantitative data to guide product decisions. Familiarity with experimentation and analytics tools. Education & Experience Knowledge of real estate investing is a plus, but not required. 6–10 years of product management experience, with at least 2+ years owning significant product areas end-to-end. Experience in marketplaces, SaaS platforms, fintech, or community-driven products strongly preferred. Familiarity with modern product development practices (Agile, continuous delivery, discovery-driven development). Experience with analytics and experimentation tools (e.g., Amplitude, Tableau, A/B testing platforms). Benefits include: Medical, dental, and vision coverage Flexible paid time off Office snacks & beverages Career development budget 401k package Paid parental leave 12 company-paid holidays per year Community service & volunteer opportunities Amazing team & fun culture with lots of team events Learn more about real estate investing Compensation Base Salary Range: $190,000 – $220,000 per year This role is also eligible for an annual bonus based on individual and company performance. Compensation is based on a variety of factors including experience, skills, and location, and is compliant with applicable pay transparency laws, including Colorado’s Equal Pay for Equal Work Act. BiggerPockets is proud to be an EOE/Veterans/Disabled/LGBTQ+ employer. We celebrate, support, and encourage being different for the benefit of our team members and community. We do not discriminate on the basis of race, color, religion, age, sex, gender identity, sexual orientation, national origin, political affiliation, marital status, non-disqualifying physical or mental disability, genetic information, membership in an employee organization, retaliation, parental status, veteran status or other non-merit factor. We celebrate diversity and are committed to creating an inclusive environment for all team members. All employment offers are decided on the basis of qualifications, merit, and business need. Please note this job description is not designed to cover or contain a comprehensive listing of activities, duties, or responsibilities that are required of the employee for this job. Duties, responsibilities and activities may change at any time with or without notice. To apply: https://weworkremotely.com/remote-jobs/biggerpockets-senior-product-manager

[employment_type]
Full-Time

[industry]
Product

---

In [ ]:
# Optional quick filters for failures or non-English jobs
non_english = debug_summary_df[debug_summary_df['detected_language'].fillna('unknown') != 'en']
translation_errors = debug_summary_df[debug_summary_df['translation_error'].notna()]

print('Non-English rows:', len(non_english))
display(non_english[['row_id', 'title', 'detected_language', 'language_confidence', 'translation_applied', 'translation_error']])

print('Rows with translation errors:', len(translation_errors))
display(translation_errors[['row_id', 'title', 'detected_language', 'translation_error', 'job_url']])

Non-English rows: 17

    row_id                                                             title detected_language  language_confidence  translation_applied translation_error
5        6          Senior DevOps Engineer - Migraciones CI/CD (Remoto 100%)                es                 0.95                 True              None
6        7                                               Product Owner (m/f)                it                 0.95                 True              None
7        8  Product Owner Zendesk Customer Service (m/w/d) // remote möglich                de                 0.85                 True              None
11      12                       [Banco de Talentos] Pessoas com deficiência                pt                 0.95                 True              None
13      14                       Desenvolvedor Dynamics 365 CE [100% Remota]                pt                 0.95                 True              None
16      17       Senior Fullstack Engineer — Produtos Financeiros (Miniapps)                pt                 0.85                 True              None
17      18                              Pessoa Desenvolvedora Backend Sênior                pt                 0.95                 True              None
19      20                                  Profissional Web Designer Sênior                pt                 0.95                 True              None
20      21                                  Profissional Web Designer Sênior                pt                 0.95                 True              None
21      22                  Senior Product Manager - Remote - 13.5-18.3k CLT                pt                 0.95                 True              None
23      24                  [Cubos DevOps] Pessoa Engenheira de DevOps Pleno                pt                 0.95                 True              None
24      25                                          Profissional IaC| DevOps                pt                 0.95                 True              None
25      26                         [Banco de Talentos] Product Manager Pleno                pt                 0.95                 True              None
26      27                           [BANCO DE TALENTOS] Product Manager Jr.                pt                 0.95                 True              None
27      28                                                   DevOps Engineer                pt                 0.95                 True              None
30      31                                            Staff Product Engineer                pt                 0.75                 True              None
35      36            Cold Caller / VertriebsmitarbeiterIn (Freelance Basis)                de                 0.95                 True              None

Rows with translation errors: 0

Empty DataFrame
Columns: [row_id, title, detected_language, translation_error, job_url]
Index: []